# Matriz canônica DIR T2 — definição dos conceitos (fonte de verdade para o build).
# Localizações: "p." = página do PDF (não a numeração impressa). Slides = slide físico.
A31 = "8 Aula 3.1.pptx"
A41 = "9 Aula 4.1.pptx"
A42 = "10 Aula 4.2.pptx"
CPM = "Codigo Penal Militar.pdf (STM, 2ª ed., 2017)"
CPPM = "Código de Processo Penal Militar.pdf (STM)"
CF = "Constituição Federal.pdf (STF, 2024, até EC 132/2023)"
EM = "Lei 6880.pdf (Planalto, texto compilado)"
PERFIL = "perfil-cobranca.json (P1 2022 SP, P1 2023, P1 2024, SOPA T1 2024)"

T = True
F = False

# presenca: (rapido, pra-safar, completo); examinavel
# Cada tupla: id, modulo, assunto, deps, fontes, prioridade_evidencia, examinavel, presenca, vulnerabilidades
C = [
  # ── 00
  ("DIRT2-ESCOPO", "00-mapa-e-metodo", "Recorte oficial da T2: Cap. 3 inteiro, Aula 4.1 inteira, Aula 4.2 só slides 1–7", [],
   [f"{A31}, slides 1–75", f"{A41}, slides 1–42", f"{A42}, slides 1–7 (slide 8 em diante — excluído)", "MANIFESTO_FONTES_DIR.md §4 (transcrição da mensagem do professor)"],
   ["Delimitação transcrita da mensagem do professor"], T, (T,T,T),
   ["estudar os slides posteriores ao 7 da Aula 4.2 por estarem no mesmo deck", "tratar slides 8+ da Aula 4.2 como matéria"]),
  ("DIRT2-METODO", "00-mapa-e-metodo", "Cadeia de resolução: fatos → questão jurídica → norma → aplicação → exceção → conclusão", [],
   [PERFIL, "DIR P1 2022 SOLUÇÃO PADRÃO.pdf, p. 6–7 (espelho com tese do STF aplicada)", "T1 DIREITO 2024 SOPA.pdf, p. 6–7 (casos penais militares)"],
   ["Padrão de correção por fundamentação observado nas provas"], F, (T,T,T),
   ["responder por palavra-chave", "citar artigo sem aplicar aos fatos"]),
  # ── 01
  ("DIRT2-DP-CONCEITO", "01-principios-e-lei-no-tempo-e-espaco", "Conceito de Direito Penal: poder punitivo exclusivo do Estado", [],
   [f"{A31}, slide 4"], ["Slide conceitual de abertura"], T, (T,T,T), ["confundir ramo público com privado"]),
  ("DIRT2-PRINC-LEGALIDADE", "01-principios-e-lei-no-tempo-e-espaco", "Princípio da legalidade (reserva legal e anterioridade)", ["DIRT2-DP-CONCEITO"],
   [f"{A31}, slide 5", f"{CF}, art. 5º, XXXIX, p. 17", f"{CPM}, art. 1º, p. 16"], ["Princípio listado em slide e cobrado em P1 (reserva legal)"], T, (T,T,T),
   ["aceitar crime criado por regulamento", "confundir legalidade com irretroatividade"]),
  ("DIRT2-PRINC-IRRETRO", "01-principios-e-lei-no-tempo-e-espaco", "Irretroatividade da lei penal e retroatividade benéfica (abolitio e lex mitior)", ["DIRT2-PRINC-LEGALIDADE"],
   [f"{A31}, slide 5", f"{CF}, art. 5º, XL, p. 17", f"{CPM}, art. 2º e §§ 1º–2º, p. 16"], ["Slide 5; alvo típico de contrafactual temporal"], T, (T,T,T),
   ["supor que a coisa julgada impede a retroatividade benéfica", "manter efeitos civis como se também cessassem"]),
  ("DIRT2-PRINC-GARANTIAS", "01-principios-e-lei-no-tempo-e-espaco", "Presunção de inocência, pessoalidade, individualização e penas vedadas", ["DIRT2-PRINC-LEGALIDADE"],
   [f"{A31}, slide 5", f"{CF}, art. 5º, XLV–XLVII, p. 17; XLVIII e LVII, p. 18"], ["SOPA T1 2024 q. 16 cobra penas vedadas (p. 5)"], T, (T,T,T),
   ["esquecer a exceção da pena de morte em guerra declarada", "estender pena a sucessores"]),
  ("DIRT2-TEMPO-CRIME", "01-principios-e-lei-no-tempo-e-espaco", "Tempo do crime: teoria da atividade (CPM art. 5º) e menoridade na conduta", ["DIRT2-PRINC-IRRETRO"],
   [f"{A31}, slide 6", f"{CPM}, art. 5º, p. 17", f"{CF}, art. 228, p. 202"], ["Exemplo do professor (17 anos e 11 meses)"], T, (T,T,T),
   ["usar a data do resultado para aferir imputabilidade", "confundir tempo (atividade) com lugar (ubiquidade)"]),
  ("DIRT2-LUGAR-CRIME", "01-principios-e-lei-no-tempo-e-espaco", "Lugar do crime: ubiquidade nos comissivos e atividade nos omissivos (CPM art. 6º)", ["DIRT2-TEMPO-CRIME"],
   [f"{A31}, slides 7–9", f"{CPM}, art. 6º, p. 17"], ["Três slides dedicados; teoria mista é pegadinha natural"], T, (T,T,T),
   ["aplicar ubiquidade ao crime omissivo", "aplicar atividade ao lugar do crime comissivo"]),
  ("DIRT2-TERRITORIALIDADE", "01-principios-e-lei-no-tempo-e-espaco", "Territorialidade e extraterritorialidade da lei penal militar; navios e aeronaves", ["DIRT2-LUGAR-CRIME"],
   [f"{A31}, slides 10–12", f"{CPM}, art. 7º e §§ 1º–3º, p. 17–18"], ["Três slides; alta aderência ao ambiente naval"], T, (T,T,T),
   ["exigir propriedade pública do navio", "aplicar §2º sem lugar sujeito à administração militar e sem ataque às instituições militares"]),
  # ── 02
  ("DIRT2-ELEMENTOS-CRIME", "02-fato-tipico-dolo-culpa-preterdolo", "Conceito analítico: fato típico, antijurídico e culpável", [],
   [f"{A31}, slides 13–14 (slide 14 é imagem não recuperada)", f"{A31}, slides 38–40 (exercícios de estratificação)"], ["Exercícios resolvidos do próprio professor"], T, (T,T,T),
   ["pular a tipicidade e ir direto à excludente", "tratar ausência de culpabilidade como ausência de fato típico"]),
  ("DIRT2-FATO-TIPICO", "02-fato-tipico-dolo-culpa-preterdolo", "Elementos do fato típico: conduta voluntária, tipicidade, nexo causal e resultado", ["DIRT2-ELEMENTOS-CRIME"],
   [f"{A31}, slide 15", f"{CPM}, art. 29 e §§ 1º–2º, p. 24–25"], ["Slide 15; art. 29 dá o suporte normativo"], T, (T,T,T),
   ["ignorar a omissão relevante do garantidor", "atribuir resultado produzido por causa superveniente independente"]),
  ("DIRT2-DOLO", "02-fato-tipico-dolo-culpa-preterdolo", "Dolo direto e indireto (alternativo e eventual) — CPM art. 33, I", ["DIRT2-FATO-TIPICO"],
   [f"{A31}, slides 16–17", f"{CPM}, art. 33, I, p. 26"], ["Distinção dolo eventual × culpa consciente é distrator declarado no prompt de autoria"], T, (T,T,T),
   ["confundir dolo eventual com culpa consciente", "exigir que o agente queira o resultado para haver dolo"]),
  ("DIRT2-CULPA", "02-fato-tipico-dolo-culpa-preterdolo", "Crime culposo: elementos, imprudência, negligência, imperícia e excepcionalidade", ["DIRT2-FATO-TIPICO"],
   [f"{A31}, slides 16, 18–22", f"{CPM}, art. 33, II e parágrafo único, p. 26"], ["Cinco slides; exemplos do professor"], T, (T,T,T),
   ["punir culposamente sem previsão legal", "trocar negligência (passiva) por imprudência (ativa)"]),
  ("DIRT2-PRETERDOLO", "02-fato-tipico-dolo-culpa-preterdolo", "Crime preterdoloso: dolo no antecedente e culpa no consequente", ["DIRT2-DOLO", "DIRT2-CULPA"],
   [f"{A31}, slide 23", f"{CPM}, art. 34, p. 26", f"{CPM}, art. 209, § 3º, p. 94"], ["Exemplo do professor (tiro nos pés)"], T, (T,T,T),
   ["imputar resultado agravador sem ao menos culpa", "classificar como homicídio doloso"]),
  # ── 03
  ("DIRT2-EXCL-ILICITUDE", "03-ilicitude-culpabilidade-e-excludentes", "Excludentes de ilicitude do CPM art. 42 (estado de necessidade, legítima defesa, estrito cumprimento, exercício regular)", ["DIRT2-ELEMENTOS-CRIME"],
   [f"{A31}, slides 24–26 (slide 24 é imagem não recuperada)", f"{CPM}, arts. 42–44, p. 29"], ["SOPA T1 2024 q. 19 correlaciona excludentes e características (p. 7)"], T, (T,T,T),
   ["trocar perigo atual (necessidade) por agressão injusta (legítima defesa)", "chamar de ‘isento de pena’ o que é exclusão do crime"]),
  ("DIRT2-EXCL-COMANDANTE", "03-ilicitude-culpabilidade-e-excludentes", "Excludente especial do comandante de navio, aeronave ou praça de guerra (art. 42, parágrafo único)", ["DIRT2-EXCL-ILICITUDE"],
   [f"{A31}, slide 27", f"{CPM}, art. 42, parágrafo único, p. 29"], ["Dispositivo exclusivamente militar e naval"], T, (T,T,T),
   ["estender a qualquer superior ou a situação sem iminência de perigo", "omitir as finalidades legais"]),
  ("DIRT2-EXCESSO", "03-ilicitude-culpabilidade-e-excludentes", "Excesso culposo, escusável e doloso nas excludentes (arts. 45–46)", ["DIRT2-EXCL-ILICITUDE"],
   [f"{CPM}, arts. 45–46, p. 30"], ["Adjacência normativa do art. 42 — não aparece nos slides"], F, (F,F,T),
   ["supor que qualquer excesso anula toda a excludente"]),
  ("DIRT2-IMPUTABILIDADE", "03-ilicitude-culpabilidade-e-excludentes", "Culpabilidade e imputabilidade: doença mental e embriaguez fortuita (arts. 48–49)", ["DIRT2-ELEMENTOS-CRIME"],
   [f"{A31}, slides 28–31 (slides 28–29 são imagens não recuperadas)", f"{CPM}, arts. 48–49, p. 30–31"], ["Quatro slides"], T, (T,T,T),
   ["aplicar isenção à embriaguez voluntária", "confundir redução (incompleta) com isenção (completa)"]),
  ("DIRT2-ERRO-DIREITO", "03-ilicitude-culpabilidade-e-excludentes", "Potencial conhecimento da ilicitude e erro de direito (LINDB art. 3º; CPM art. 35)", ["DIRT2-IMPUTABILIDADE"],
   [f"{A31}, slides 32–35 (slides 33–34 são imagens não recuperadas)", f"{CPM}, art. 35, p. 26"], ["Quatro slides"], T, (T,T,T),
   ["tratar erro de direito como isenção de pena", "aplicar o art. 35 a crime que atenta contra o dever militar"]),
  ("DIRT2-INEXIGIBILIDADE", "03-ilicitude-culpabilidade-e-excludentes", "Inexigibilidade de conduta diversa: coação irresistível e obediência hierárquica (arts. 38 e 40)", ["DIRT2-IMPUTABILIDADE"],
   [f"{A31}, slides 36–37 e 40", f"{CPM}, arts. 38, 40 e 41, p. 28–29"], ["Obediência hierárquica é tema central no ambiente militar"], T, (T,T,T),
   ["cumprir ordem manifestamente criminosa e alegar obediência", "invocar coação moral em crime contra o dever militar"]),
  ("DIRT2-ESTADO-NEC-EXCULPANTE", "03-ilicitude-culpabilidade-e-excludentes", "Estado de necessidade exculpante (art. 39) × justificante (art. 43)", ["DIRT2-EXCL-ILICITUDE", "DIRT2-INEXIGIBILIDADE"],
   [f"{CPM}, art. 39, p. 28; art. 43, p. 29"], ["Adjacência normativa — não aparece nos slides"], F, (F,F,T),
   ["tratar todo estado de necessidade como excludente de ilicitude"]),
  # ── 04
  ("DIRT2-ITER", "04-iter-criminis-tentativa-e-desistencia", "Iter criminis: cogitação, preparação, execução e consumação", [],
   [f"{A31}, slides 41–43", f"{CPM}, art. 30, I, p. 25"], ["Exemplo detalhado do professor"], T, (T,T,T),
   ["punir atos preparatórios como tentativa", "fixar início da execução na compra da arma"]),
  ("DIRT2-TENTATIVA", "04-iter-criminis-tentativa-e-desistencia", "Tentativa: circunstâncias alheias e pena (1/3 a 2/3; exceção de excepcional gravidade)", ["DIRT2-ITER"],
   [f"{A31}, slide 44", f"{CPM}, art. 30, II e parágrafo único, p. 25"], ["SOPA T1 2024 q. 18 (tentativa × lesão, p. 6)"], T, (T,T,T),
   ["ignorar a exceção do parágrafo único", "classificar como tentativa a interrupção voluntária"]),
  ("DIRT2-DESIST-ARREP", "04-iter-criminis-tentativa-e-desistencia", "Desistência voluntária e arrependimento eficaz (art. 31)", ["DIRT2-TENTATIVA"],
   [f"{A31}, slide 45", f"{CPM}, art. 31, p. 25"], ["Distinção expressa no slide"], T, (T,T,T),
   ["confundir voluntariedade com espontaneidade", "punir pela tentativa quem desistiu"]),
  ("DIRT2-CRIME-IMPOSSIVEL", "04-iter-criminis-tentativa-e-desistencia", "Crime impossível: ineficácia absoluta do meio ou impropriedade absoluta do objeto (art. 32)", ["DIRT2-TENTATIVA"],
   [f"{A31}, slide 46", f"{CPM}, art. 32, p. 26"], ["SOPA T1 2024 q. 18 usa distrator de crime impossível (p. 6)"], T, (T,T,T),
   ["tratar ineficácia relativa (dose insuficiente) como absoluta"]),
  # ── 05
  ("DIRT2-CONCURSO-MONISTA", "05-concurso-de-agentes", "Concurso de agentes e teorias; CPM adota a monista (art. 53, caput)", [],
   [f"{A31}, slides 47–49 e 53", f"{CPM}, art. 53, caput, p. 32"], ["Três slides"], T, (T,T,T),
   ["atribuir crimes distintos a cada concorrente no mesmo fato", "confundir monista com pluralista"]),
  ("DIRT2-AUTORIA-PARTICIPACAO", "05-concurso-de-agentes", "Autor × partícipe e atenuação da participação de somenos importância (art. 53, § 3º)", ["DIRT2-CONCURSO-MONISTA"],
   [f"{A31}, slide 50", f"{CPM}, art. 53, § 3º, p. 33"], ["SOPA T1 2024 q. 20 (civil e militar em furto, p. 7)"], T, (T,T,T),
   ["supor que partícipe fica impune", "exigir execução do verbo para toda responsabilização"]),
  ("DIRT2-COAUTORIA-LIMITES", "05-concurso-de-agentes", "Crimes que não admitem coautoria e crimes de autoria coletiva necessária (motim)", ["DIRT2-CONCURSO-MONISTA"],
   [f"{A31}, slides 51–52", f"{CPM}, art. 149, p. 73"], ["Dois slides com exemplos"], T, (T,T,T),
   ["tratar motim como crime que pode ser praticado por um só", "negar qualquer participação em deserção"]),
  ("DIRT2-AGRAVANTES-CABECAS", "05-concurso-de-agentes", "Agravação no concurso (art. 53, § 2º) e cabeças (§§ 4º–5º)", ["DIRT2-CONCURSO-MONISTA"],
   [f"{A31}, slides 53–54", f"{CPM}, art. 53, §§ 2º, 4º e 5º, p. 32–33"], ["Dois slides literais"], T, (T,T,T),
   ["esquecer que oficiais são cabeças quando o crime é cometido com inferiores", "não agravar quem instiga subordinado"]),
  ("DIRT2-COMUNICABILIDADE", "05-concurso-de-agentes", "Circunstâncias pessoais (art. 53, § 1º) e impunibilidade do ajuste não tentado (art. 54)", ["DIRT2-CONCURSO-MONISTA"],
   [f"{CPM}, art. 53, § 1º, p. 32; art. 54, p. 33"], ["Adjacência normativa — não aparece nos slides"], F, (F,F,T),
   ["comunicar condição pessoal não elementar", "punir ajuste de crime que nem chegou a ser tentado"]),
  # ── 06
  ("DIRT2-CRIME-MILITAR-CONCEITO", "06-crime-militar", "Crime militar: tipicidade indireta pelos arts. 9º (paz) ou 10 (guerra) do CPM", [],
   [f"{A31}, slide 55", f"{CPM}, arts. 9º–10, p. 18–21"], ["Slide conceitual; SOPA q. 17 (p. 6)"], T, (T,T,T),
   ["chamar de militar todo crime praticado por militar", "dispensar o enquadramento em inciso do art. 9º"]),
  ("DIRT2-PROPRIO-IMPROPRIO", "06-crime-militar", "Crime militar × crime propriamente militar (furto × deserção)", ["DIRT2-CRIME-MILITAR-CONCEITO"],
   [f"{A31}, slides 56–58", f"{CPM}, art. 240, p. 107; art. 187, p. 85", f"{CF}, art. 5º, LXI, p. 18"], ["Três slides; P1 2022/2023 cobram falta de marinheiro por dez dias (correlação de jurisdição)"], T, (T,T,T),
   ["classificar furto como propriamente militar", "exigir oito dias exatos para a deserção"]),
  ("DIRT2-TRANSGRESSAO", "06-crime-militar", "Crime militar × transgressão disciplinar; concurso da mesma natureza (EM art. 42, § 2º)", ["DIRT2-CRIME-MILITAR-CONCEITO"],
   [f"{A31}, slide 59 (cita ‘Lei nº 6.080/80’ — [POSSÍVEL ERRO NA FONTE])", f"{EM}, art. 42 e § 2º, p. 9", f"{CPM}, art. 19, p. 23"], ["Slide específico"], T, (T,T,T),
   ["aplicar pena disciplinar e penal pelo mesmo fato da mesma natureza", "citar a lei com número errado"]),
  ("DIRT2-ART9-I", "06-crime-militar", "Art. 9º, I: crimes definidos de modo diverso ou só previstos no CPM, qualquer que seja o agente", ["DIRT2-CRIME-MILITAR-CONCEITO"],
   [f"{A31}, slide 60", f"{CPM}, art. 9º, I, p. 18"], ["Slide literal"], T, (T,T,T), ["exigir sujeito ativo militar no inciso I"]),
  ("DIRT2-ART9-II", "06-crime-militar", "Art. 9º, II: crimes do CPM e da legislação penal praticados por militar nas alíneas a–e", ["DIRT2-CRIME-MILITAR-CONCEITO"],
   [f"{A31}, slides 61", f"{CPM}, art. 9º, II, a–e, p. 18–19"], ["SOPA T1 2024 q. 17 (militares da ativa fora de lugar sujeito à administração militar, p. 6)"], T, (T,T,T),
   ["exigir lugar sujeito à administração militar na alínea a", "esquecer que a alínea c dispensa o lugar"]),
  ("DIRT2-ART9-III", "06-crime-militar", "Art. 9º, III: crimes de militar da reserva, reformado ou civil contra as instituições militares", ["DIRT2-CRIME-MILITAR-CONCEITO"],
   [f"{A31}, slide 62", f"{CPM}, art. 9º, III, a–d, p. 19"], ["Slide literal; base da submissão de civil à JMU"], T, (T,T,T),
   ["afirmar que civil nunca comete crime militar", "afirmar que todo crime de civil em quartel é militar"]),
  ("DIRT2-ART9-DOLOSO-VIDA", "06-crime-militar", "Crimes dolosos contra a vida de civil: júri (§ 1º) e JMU nos contextos do § 2º", ["DIRT2-ART9-II"],
   [f"{A31}, slide 63", f"{A41}, slides 37–40", f"{CPM}, art. 9º, §§ 1º–2º, p. 19–20", f"{CPPM}, art. 82, § 2º, p. 54"], ["Aparece nas duas aulas"], T, (T,T,T),
   ["mandar ao júri homicídio de civil em GLO das Forças Armadas", "aplicar o § 2º a militar estadual"]),
  ("DIRT2-ART10-GUERRA", "06-crime-militar", "Crimes militares em tempo de guerra (art. 10, I–IV)", ["DIRT2-CRIME-MILITAR-CONCEITO"],
   [f"{A31}, slides 64–67", f"{CPM}, art. 10, p. 21; art. 355, p. 154"], ["Quatro slides"], T, (F,T,T),
   ["supor que crimes de paz deixam de ser militares na guerra"]),
  # ── 07
  ("DIRT2-CRIME-160", "07-crimes-militares-em-especie", "Desrespeito a superior (art. 160) e forma majorada", ["DIRT2-ART9-II"],
   [f"{A31}, slide 68", f"{CPM}, art. 160 e parágrafo único, p. 76–77"], ["Crime do cotidiano militar"], T, (T,T,T),
   ["dispensar a presença de outro militar", "esquecer ‘oficial de dia’ na majorante (omitido no slide)"]),
  ("DIRT2-CRIME-163", "07-crimes-militares-em-especie", "Insubordinação — recusa de obediência (art. 163)", ["DIRT2-ART9-II"],
   [f"{A31}, slide 69", f"{CPM}, art. 163, p. 77"], ["Relação com hierarquia e obediência"], T, (T,T,T),
   ["tratar ordem manifestamente ilegal como ordem de serviço exigível"]),
  ("DIRT2-CRIME-172", "07-crimes-militares-em-especie", "Uso indevido de uniforme, distintivo ou insígnia por qualquer pessoa (art. 172)", ["DIRT2-ART9-I"],
   [f"{A31}, slide 70", f"{CPM}, art. 172, p. 79; art. 171, p. 79"], ["Tipo que admite sujeito ativo civil"], T, (T,T,T),
   ["confundir com o art. 171 (militar que usa insígnia superior)"]),
  ("DIRT2-CRIME-174", "07-crimes-militares-em-especie", "Rigor excessivo (art. 174)", ["DIRT2-ART9-II"],
   [f"{A31}, slide 71", f"{CPM}, art. 174, p. 80"], ["Pena de suspensão do exercício do posto"], T, (T,T,T),
   ["confundir com violência contra inferior (art. 175)", "supor pena de detenção"]),
  ("DIRT2-CRIME-203", "07-crimes-militares-em-especie", "Dormir em serviço (art. 203)", ["DIRT2-ART9-II"],
   [f"{A31}, slide 72", f"{CPM}, art. 203, p. 90"], ["Situações navais nomeadas no tipo"], T, (T,T,T),
   ["exigir resultado danoso", "limitar a sentinelas"]),
  ("DIRT2-CRIME-209-210", "07-crimes-militares-em-especie", "Lesão corporal dolosa (art. 209) e culposa (art. 210)", ["DIRT2-DOLO", "DIRT2-CULPA"],
   [f"{A31}, slide 73", f"{CPM}, arts. 209–210, p. 94–95"], ["Integra dolo/culpa com crime em espécie"], T, (T,T,T),
   ["enquadrar lesão culposa no art. 209", "ignorar o § 6º (lesão levíssima como infração disciplinar)"]),
  # ── 08
  ("DIRT2-DPPM-CONCEITO", "08-pjm-e-instauracao-do-ipm", "Direito Processual Penal Militar: conceito, CPPM (DL 1.002/69), paz e guerra", [],
   [f"{A41}, slides 3–5"], ["Objetivo 4.1 da aula"], T, (T,T,T), ["confundir CPM (DL 1.001) com CPPM (DL 1.002)"]),
  ("DIRT2-PJM", "08-pjm-e-instauracao-do-ipm", "Polícia Judiciária Militar: conceito, finalidades e titulares (CPPM arts. 7º–8º)", ["DIRT2-DPPM-CONCEITO"],
   [f"{A41}, slides 6–10 (slide 6 cita ‘CPMM’ — [POSSÍVEL ERRO NA FONTE])", f"{CPPM}, arts. 7º–8º, p. 21–23"], ["Objetivos 4.1–4.3"], T, (T,T,T),
   ["atribuir PJM ao MPM ou ao juiz", "tratar a PJM como órgão da Justiça Militar"]),
  ("DIRT2-PJM-DELEGACAO", "08-pjm-e-instauracao-do-ipm", "Delegação para instaurar IPM: posto superior ou mais antigo; infrator de posto igual ou superior", ["DIRT2-PJM"],
   [f"{A41}, slide 14 (‘quem receba tal delegação’)", f"{CPPM}, art. 7º, §§ 1º–5º, p. 22–23; art. 10, §§ 1º e 5º, p. 25–26"], ["Base do distrator encarregado × autoridade delegante"], F, (F,T,T),
   ["delegar a oficial mais moderno que o indiciado", "encarregado seguir no IPM após surgirem indícios contra oficial mais antigo"]),
  ("DIRT2-IPM-CONCEITO", "08-pjm-e-instauracao-do-ipm", "IPM: apuração sumária, instrução provisória e finalidade (art. 9º)", ["DIRT2-PJM"],
   [f"{A41}, slides 11–13", f"{CPPM}, art. 9º e parágrafo único, p. 24"], ["Objetivo 4.4"], T, (T,T,T),
   ["tratar o IPM como processo com contraditório pleno", "negar valor instrutório definitivo às perícias regulares"]),
  ("DIRT2-IPM-INSTAURACAO", "08-pjm-e-instauracao-do-ipm", "Instauração: portaria, objeto, encarregado (art. 15), escrivão (art. 11), 48 h (DGPM-315) e modos do art. 10", ["DIRT2-IPM-CONCEITO"],
   [f"{A41}, slides 14–17", f"{CPPM}, arts. 10, 11 e 15, p. 24–28", "DGPM-315, item 8.2.2 — citado no slide 16; documento não fornecido"], ["Quatro slides; prazo de 48 h só no slide"], T, (T,T,T),
   ["confundir o prazo administrativo de 48 h com prazo do CPPM", "escrivão sargento para indiciado oficial"]),
  ("DIRT2-MEDIDAS-URGENTES", "08-pjm-e-instauracao-do-ipm", "Providências antes da instauração: art. 10, § 2º, e art. 12", ["DIRT2-IPM-INSTAURACAO"],
   [f"{A41}, slides 18–22", f"{CPPM}, art. 10, § 2º, p. 25; art. 12, p. 26–27", "NORDINAVRIO nº 02-1 — citado no slide 22; documento não fornecido"], ["Cinco slides"], T, (T,T,T),
   ["aguardar a portaria para preservar o local", "supor que só o comandante pode agir"]),
  # ── 09
  ("DIRT2-ENCARREGADO-ATRIBUICOES", "09-oitivas-garantias-e-sigilo", "Atribuições do encarregado do IPM (art. 13)", ["DIRT2-IPM-INSTAURACAO"],
   [f"{A41}, slide 23", f"{CPPM}, art. 13, p. 27–28"], ["Slide literal"], T, (T,T,T),
   ["atribuir ao encarregado arquivamento ou denúncia"]),
  ("DIRT2-OITIVAS", "09-oitivas-garantias-e-sigilo", "Regras das oitivas: 7h–18h, 4 horas, descanso e ciência da qualidade do depoente (art. 19)", ["DIRT2-ENCARREGADO-ATRIBUICOES"],
   [f"{A41}, slide 24", f"{CPPM}, art. 19 e §§ 1º–3º, p. 29–30"], ["Números memorizáveis"], T, (T,T,T),
   ["ouvir às 22h sem urgência registrada", "inquirir 5 horas seguidas"]),
  ("DIRT2-TESTEMUNHA-INDICIADO", "09-oitivas-garantias-e-sigilo", "Qualidade material de investigado × rótulo de testemunha; silêncio, advogado e prova ilícita", ["DIRT2-OITIVAS"],
   [f"{A41}, slides 24–25 (ementa do STM HC 0000209-20.2016.7.00.0000)", f"{CF}, art. 5º, LV, LVI e LXIII, p. 18"], ["Caso real indicado pelo próprio professor"], T, (T,T,T),
   ["aceitar o rótulo formal de testemunha", "achar que a ilicitude anula todo o IPM automaticamente"]),
  ("DIRT2-SIGILO-ACESSO", "09-oitivas-garantias-e-sigilo", "Sigilo do IPM × acesso do defensor aos elementos já documentados", ["DIRT2-TESTEMUNHA-INDICIADO"],
   [f"{A41}, slide 26", f"{CPPM}, art. 16, p. 28", "STF, Súmula Vinculante 14 — [NÃO CONFIRMADO NA FONTE PRIMÁRIA]: páginas oficiais bloqueadas ao acesso automatizado nesta sessão"], ["Alerta expresso do prompt de autoria"], T, (T,T,T),
   ["ensinar sigilo absoluto contra o defensor", "estender o acesso a diligências em andamento"]),
  ("DIRT2-INCOMUNICABILIDADE", "09-oitivas-garantias-e-sigilo", "Incomunicabilidade (art. 17) e detenção sem flagrante (art. 18): não recepção ensinada", ["DIRT2-TESTEMUNHA-INDICIADO"],
   [f"{A41}, slide 27 (atribui ambos ao art. 18 — [POSSÍVEL ERRO NA FONTE])", f"{CPPM}, arts. 17–18, p. 28–29", f"{CF}, art. 5º, LXI–LXIII, p. 18; art. 136, § 3º, IV, p. 119"], ["Slide com destaque ‘não’"], T, (T,T,T),
   ["aplicar incomunicabilidade de três dias", "prender indiciado por 30 dias sem ordem judicial"]),
  # ── 10
  ("DIRT2-PRAZOS-IPM", "10-prazos-relatorio-arquivamento-e-foro", "Prazos: preso 20 dias (da prisão), solto 40 dias (da instauração), prorrogação de 20 só para solto", ["DIRT2-IPM-INSTAURACAO"],
   [f"{A41}, slide 28", f"{CPPM}, art. 20 e §§ 1º–3º, p. 30–31"], ["Prazos memorizáveis; distrator preso × solto"], T, (T,T,T),
   ["prorrogar prazo de indiciado preso", "contar o prazo do preso da instauração"]),
  ("DIRT2-RELATORIO-AUTOS", "10-prazos-relatorio-arquivamento-e-foro", "Autos em um só volume, relatório e conclusão; solução da autoridade delegante", ["DIRT2-PRAZOS-IPM"],
   [f"{A41}, slide 29", f"{CPPM}, arts. 21–22, p. 31–32"], ["Slide com destaques"], T, (T,T,T),
   ["concluir o relatório com juízo de condenação", "omitir a infração disciplinar (art. 22)"]),
  ("DIRT2-REMESSA-ARQUIVAMENTO", "10-prazos-relatorio-arquivamento-e-foro", "Remessa ao juízo, MPM e vedação de arquivamento pela autoridade militar", ["DIRT2-RELATORIO-AUTOS"],
   [f"{A41}, slides 30 e 32 (fluxo)", f"{CPPM}, arts. 23–26 e 29–30, p. 32–34"], ["Fluxo gráfico do professor"], T, (T,T,T),
   ["encarregado ou comandante arquivar", "juiz arquivar de ofício sem requerimento do MPM"]),
  ("DIRT2-DISPENSA-IPM", "10-prazos-relatorio-arquivamento-e-foro", "Dispensa do IPM: flagrante suficiente, honra por escrito/publicação, desacato e desobediência judicial", ["DIRT2-IPM-CONCEITO"],
   [f"{A41}, slide 31", f"{CPPM}, arts. 27–28, p. 33–34", f"{CPM}, arts. 341 e 349, p. 147–148"], ["Slide literal"], T, (T,T,T),
   ["dispensar IPM em desacato a superior hierárquico", "esquecer o exame de corpo de delito no flagrante"]),
  ("DIRT2-SINDICANCIA", "10-prazos-relatorio-arquivamento-e-foro", "IPM × sindicância: finalidade, prazo de 40 dias e vedações", ["DIRT2-IPM-CONCEITO"],
   [f"{A41}, slides 33–34", f"{CPPM}, art. 10, f, p. 25", "Norma administrativa da MB de origem da sindicância — não fornecida"], ["Dois slides"], T, (T,T,T),
   ["prender envolvido em sindicância", "buscar e apreender fora da OM nomeante"]),
  ("DIRT2-FORO-MILITAR", "10-prazos-relatorio-arquivamento-e-foro", "Foro militar: CF arts. 124 e 125, § 4º; CPPM art. 82; crime militar × crime de militar", ["DIRT2-ART9-DOLOSO-VIDA"],
   [f"{A41}, slides 35–40", f"{CF}, art. 124, p. 108; art. 125, § 4º, p. 109", f"{CPPM}, art. 82, p. 53–54",
    "STF, HC 109.544 e Inq. 4.923 — [NÃO CONFIRMADO NA FONTE PRIMÁRIA]: páginas oficiais bloqueadas ao acesso automatizado nesta sessão"],
   ["Objetivo 4.5; P1 2022/2023 correlação de jurisdição"], T, (T,T,T),
   ["competência pela pessoa e não pelo crime", "confundir JMU com Justiça Militar estadual"]),
  # ── 11
  ("DIRT2-JMU-ORGAOS", "11-jmu-e-stm", "Órgãos da Justiça Militar da União listados no slide 4 (Lei 8.457/92, art. 1º)", ["DIRT2-FORO-MILITAR"],
   [f"{A42}, slide 4", f"{CF}, art. 122, p. 108", "Lei nº 8.457/1992 — citada no slide; texto não fornecido"], ["Slide 4 dentro do recorte"], T, (T,T,T),
   ["incluir o MPM entre os órgãos da JMU"]),
  ("DIRT2-STM-COMPOSICAO", "11-jmu-e-stm", "Composição do STM: 15 ministros vitalícios (3 MB, 4 EB, 3 FAB, 5 civis)", ["DIRT2-JMU-ORGAOS"],
   [f"{A42}, slides 5–6", f"{CF}, art. 123 e parágrafo único, p. 108"], ["Números memorizáveis; distratores naturais"], T, (T,T,T),
   ["trocar 3 da MB por 4", "esquecer a aprovação do Senado e o limite de idade dos civis"]),
  ("DIRT2-STM-COMPETENCIA", "11-jmu-e-stm", "Competência do STM apresentada no slide 7: originária (oficiais-generais, HC, HD) e recursal", ["DIRT2-STM-COMPOSICAO"],
   [f"{A42}, slide 7", f"{CF}, art. 124, parágrafo único, p. 108", "Lei nº 8.457/1992 — base legal da competência; texto não fornecido"], ["Último slide do recorte"], T, (T,T,T),
   ["trocar competência originária por recursal", "atribuir ao STM julgamento de oficial subalterno em 1ª instância"]),
]

MODULOS = [
  ("00-mapa-e-metodo", "Mapa da T2 e método de caso", "máxima"),
  ("01-principios-e-lei-no-tempo-e-espaco", "Princípios e lei penal militar no tempo e no espaço", "muito alta"),
  ("02-fato-tipico-dolo-culpa-preterdolo", "Fato típico, dolo, culpa e preterdolo", "máxima"),
  ("03-ilicitude-culpabilidade-e-excludentes", "Ilicitude, culpabilidade e excludentes", "máxima"),
  ("04-iter-criminis-tentativa-e-desistencia", "Iter criminis, tentativa, desistência e crime impossível", "muito alta"),
  ("05-concurso-de-agentes", "Concurso de agentes", "muito alta"),
  ("06-crime-militar", "Crime militar: arts. 9º e 10 do CPM", "máxima"),
  ("07-crimes-militares-em-especie", "Crimes militares em espécie dos slides", "alta"),
  ("08-pjm-e-instauracao-do-ipm", "Polícia Judiciária Militar e instauração do IPM", "máxima"),
  ("09-oitivas-garantias-e-sigilo", "Oitivas, garantias, sigilo e defesa no IPM", "máxima"),
  ("10-prazos-relatorio-arquivamento-e-foro", "Prazos, relatório, arquivamento, dispensa, sindicância e foro", "máxima"),
  ("11-jmu-e-stm", "Justiça Militar da União e STM (Aula 4.2, slides 1–7)", "muito alta"),
]
