# Módulo 00 e 01 — questões canônicas.
# Campos: n, tipo (OBJ|VF|COR|DIS), nivel (N1–N4), ctx (aplicação contextualizada), conceitos, modos (None = todas),
# competencia, fonte, armadilha, tempo, e campos por tipo. Alternativas: lista de (texto, explicação).
from conceitos import A31, A41, A42, CPM, CPPM, CF, EM

M00 = [
 dict(n=1, tipo="OBJ", nivel="N2", ctx=True, conceitos=["DIRT2-ESCOPO"],
  competencia="Delimitar o que pode ser cobrado na T2 a partir do recorte do professor.",
  enunciado="Um aspirante monta seu plano de revisão com os três decks da T2. No arquivo da Aula 4.2 encontra, depois do slide 7 (competência do STM), dezenas de slides sobre a organização territorial da Justiça Militar da União e sobre outros órgãos e processos. Qual plano respeita a delimitação registrada para a T2?",
  alternativas=[
   ("Estudar a Aula 4.2 somente até o slide 7 (órgãos, composição e competência do STM) e não usar o conteúdo dos slides seguintes, nem mesmo como comparação.",
    "Correta. A delimitação transcrita da mensagem do professor encerra a Aula 4.2 no slide físico 7."),
   ("Estudar toda a Aula 4.2, porque o arquivo integra o Capítulo 4 e o objetivo do slide 3 anuncia temas mais amplos.",
    "Errada. O objetivo listado no slide 3 não prevalece sobre a delimitação posterior do professor, que é a autoridade sobre inclusão e exclusão."),
   ("Excluir apenas os órgãos colegiados expressamente mencionados na mensagem do professor, mantendo o restante dos slides posteriores ao 7.",
    "Errada. O recorte termina no slide 7; tudo o que vem depois está fora."),
   ("Estudar os slides posteriores apenas para reconhecer ‘pegadinhas’, já que o professor poderia usá-los em alternativas erradas.",
    "Errada. A exclusão é absoluta, inclusive em exemplos, comparações e distratores."),
  ], correta=0,
  comentario="O plano correto usa o Capítulo 3 inteiro, a Aula 4.1 inteira e a Aula 4.2 até o slide 7. O limite é físico e foi conferido no próprio deck.",
  fonte=f"MANIFESTO_FONTES_DIR.md §4 (transcrição da delimitação); {A42}, slides 3, 7 e 8.",
  armadilha="Tomar o objetivo do slide 3 da Aula 4.2 como escopo da prova.", tempo=2),
 dict(n=2, tipo="DIS", nivel="N2", ctx=True, conceitos=["DIRT2-METODO"],
  competencia="Organizar uma resposta discursiva pela cadeia de fundamentação que recebe crédito parcial.",
  contexto="Em uma discursiva de 1,0 ponto, um aspirante escreveu apenas: “Houve crime militar, conforme o art. 9º do CPM.” O fato narrado envolvia dois militares da ativa, um deles de serviço, e uma alegação de legítima defesa.",
  enunciado="Explique por que essa resposta tende a receber pouca ou nenhuma pontuação e reescreva o esqueleto de uma resposta completa, sem resolver o mérito.",
  gabarito="**Gabarito:** a resposta afirma uma conclusão e cita um artigo sem (1) selecionar os fatos juridicamente relevantes, (2) formular a questão jurídica, (3) indicar o inciso/alínea aplicável, (4) aplicar a norma aos fatos, (5) enfrentar a exceção alegada (legítima defesa) e (6) concluir de forma fundamentada. Esqueleto: “Fatos relevantes: ... Questão: o fato é crime militar e há excludente? Norma: CPM art. 9º, II, alínea ..., e art. 42, II/44. Aplicação: ... Exceção: a legítima defesa exige ...; no caso ... Conclusão: ...”.\n\n**Resposta plena:** percorre os seis elos com os fatos do caso. **Parcial:** acerta norma e conclusão, mas não aplica aos fatos ou ignora a excludente. **Insuficiente:** apenas cita artigo ou conclui por palavra-chave.",
  criterios=["Identifica a ausência de questão jurídica e de fatos selecionados (0,2)", "Aponta a falta de inciso/alínea e de aplicação (0,3)", "Aponta a exceção não enfrentada (0,2)", "Propõe esqueleto com os seis elos (0,3)", "Não pontua: repetir ‘art. 9º’ sem aplicação"],
  fonte="perfil-cobranca.json; DIR P1 2022 SOLUÇÃO PADRÃO.pdf, p. 6–7 (espelho por item com fundamentação).",
  armadilha="Acreditar que citar o artigo correto basta.", tempo=6),
]

M01 = [
 dict(n=1, tipo="VF", nivel="N1", ctx=False, conceitos=["DIRT2-PRINC-IRRETRO"],
  competencia="Reconhecer o alcance literal da lei supressiva de incriminação no CPM.",
  afirmacao="Pelo CPM, a lei posterior que deixa de considerar o fato como crime faz cessar a vigência da sentença condenatória irrecorrível, inclusive quanto aos efeitos de natureza civil.",
  correta=False,
  comentario="Falsa. O art. 2º do CPM faz cessar a própria vigência da sentença condenatória irrecorrível, **salvo quanto aos efeitos de natureza civil**. A abolição da figura penal não apaga, por exemplo, o dever de reparar o dano.",
  fonte=f"{CPM}, art. 2º, p. 16; {A31}, slide 5; {CF}, art. 5º, XL, p. 17.",
  armadilha="Estender a abolitio aos efeitos civis.", tempo=1),
 dict(n=2, tipo="OBJ", nivel="N2", ctx=False, conceitos=["DIRT2-LUGAR-CRIME"],
  competencia="Aplicar a teoria mista do lugar do crime adotada pelo CPM.",
  enunciado="Sobre o lugar do crime no Código Penal Militar, assinale a alternativa correta.",
  alternativas=[
   ("Nos crimes comissivos adota-se a ubiquidade; nos omissivos, considera-se o lugar em que deveria realizar-se a ação omitida.",
    "Correta. É a síntese do art. 6º e do slide 9 (‘Teoria Mista: Ubiquidade (comissivos) e Atividade (omissivos)’)."),
   ("Em todos os crimes adota-se a teoria da atividade, a mesma usada para o tempo do crime.",
    "Errada. A atividade é a regra do **tempo** (art. 5º). Para o lugar, nos comissivos, o art. 6º alcança também onde se produziu ou deveria produzir-se o resultado."),
   ("Nos crimes comissivos adota-se a teoria do resultado; nos omissivos, a ubiquidade.",
    "Errada. Inverte e distorce: comissivos seguem a ubiquidade; omissivos, o lugar da ação omitida."),
   ("Considera-se praticado o fato apenas onde se produziu o resultado, salvo sob forma de participação.",
    "Errada. O art. 6º inclui expressamente o lugar da atividade, no todo ou em parte, ‘ainda que sob forma de participação’."),
  ], correta=0,
  comentario="O CPM separa tempo (atividade) e lugar (ubiquidade nos comissivos; lugar da ação devida nos omissivos).",
  fonte=f"{CPM}, art. 6º, p. 17; {A31}, slides 7–9.", armadilha="Transportar a regra do tempo para o lugar.", tempo=2),
 dict(n=3, tipo="COR", nivel="N2", ctx=False, conceitos=["DIRT2-PRINC-LEGALIDADE", "DIRT2-PRINC-IRRETRO", "DIRT2-PRINC-GARANTIAS"],
  competencia="Associar cada princípio penal constitucional ao seu conteúdo normativo.",
  titulo="Associe o princípio (slide 5 da Aula 3.1) ao conteúdo da CF/88",
  chaves=[("A", "Legalidade — art. 5º, XXXIX"), ("B", "Irretroatividade — art. 5º, XL"), ("C", "Responsabilidade pessoal — art. 5º, XLV"), ("D", "Vedação de penas — art. 5º, XLVII"), ("E", "Presunção de inocência — art. 5º, LVII")],
  itens=[("A lei penal não retroagirá, salvo para beneficiar o réu.", "B"), ("Não há crime sem lei anterior que o defina, nem pena sem prévia cominação legal.", "A"), ("Ninguém será considerado culpado até o trânsito em julgado de sentença penal condenatória.", "E"), ("Não haverá pena de banimento.", "D"), ("Nenhuma pena passará da pessoa do condenado.", "C")],
  comentario="Correspondência literal com a CF/88. O slide 5 remete legalidade e irretroatividade também aos arts. 1º e 2º do CPM.",
  fonte=f"{A31}, slide 5; {CF}, art. 5º, XXXIX–XLVII, p. 17, e LVII, p. 18.", armadilha="Trocar legalidade (reserva legal/anterioridade) por irretroatividade.", tempo=2),
 dict(n=4, tipo="OBJ", nivel="N3", ctx=True, conceitos=["DIRT2-TEMPO-CRIME"],
  competencia="Fixar o momento do crime para aferir a menoridade penal.",
  enunciado="Um civil com 17 anos e 11 meses, durante visitação pública a uma base naval, golpeia com faca um cabo de serviço no portão. O cabo permanece internado e morre 40 dias depois, quando o agressor já completou 18 anos. Um colega sustenta que, como a morte ocorreu após a maioridade, o agressor responde como imputável. Assinale a análise correta.",
  alternativas=[
   ("O agressor é penalmente inimputável, pois o crime se considera praticado no momento da ação (CPM art. 5º) e a CF declara inimputáveis os menores de 18 anos (art. 228).",
    "Correta. É exatamente o raciocínio do slide 6: teoria da atividade e inimputabilidade pela CF."),
   ("O agressor é imputável, pois pela teoria do resultado o crime se consuma com a morte, ocorrida após a maioridade.",
    "Errada. O CPM não adota a teoria do resultado para o tempo do crime; consumação e momento do crime não se confundem."),
   ("O agressor é imputável, pois o CPM adota a ubiquidade, bastando que ação ou resultado ocorram após os 18 anos.",
    "Errada. A ubiquidade é adotada para o **lugar** dos crimes comissivos, não para o tempo."),
   ("O agressor pode ser imputável se revelar discernimento, porque tinha mais de 16 anos (CPM art. 50).",
    "Errada. O texto do art. 50 do CPM no corpus admite essa hipótese, mas a CF, norma superior, declara inimputáveis os menores de 18 anos, e o slide 6 adota a CF. [APROFUNDAMENTO ANALÍTICO DE SUPORTE] Regra infraconstitucional anterior incompatível com a Constituição não prevalece sobre ela."),
  ], correta=0,
  comentario="Fatos relevantes: idade na data do golpe; morte posterior. Questão: qual momento define a imputabilidade? Norma: CPM art. 5º (atividade) e CF art. 228. Aplicação: na ação, 17 anos e 11 meses. Conclusão: inimputável. O fato de o golpe ser em base naval e contra militar de serviço é ruído para esta pergunta.",
  fonte=f"{A31}, slide 6; {CPM}, art. 5º, p. 17; {CF}, art. 228, p. 202; {CPM}, art. 50, p. 31.",
  armadilha="Usar a data do resultado; confundir tempo com lugar.", tempo=3),
 dict(n=5, tipo="OBJ", nivel="N3", ctx=True, conceitos=["DIRT2-TERRITORIALIDADE"],
  competencia="Aplicar a extensão do território nacional a navios sob comando militar.",
  enunciado="Um rebocador de propriedade de empresa privada brasileira foi requisitado por ordem legal da autoridade naval e passou a operar sob comando de um capitão-tenente em apoio a uma operação. Atracado em porto estrangeiro, um marinheiro embarcado subtrai equipamento de outro militar a bordo. Quanto à aplicação da lei penal militar brasileira:",
  alternativas=[
   ("Aplica-se, pois a embarcação sob comando militar é navio para o CPM e, onde quer que se encontre, é extensão do território nacional, ainda que de propriedade privada.",
    "Correta. Combina o art. 7º, § 1º (extensão do território, ainda que de propriedade privada) com o § 3º (navio é toda embarcação sob comando militar)."),
   ("Não se aplica, pois a embarcação é de propriedade privada e não integra a Marinha.",
    "Errada. O § 1º dispensa a propriedade pública: ‘ainda que de propriedade privada’."),
   ("Aplica-se somente se o crime atentar contra as instituições militares, porque o fato ocorreu em porto estrangeiro.",
    "Errada. Essa exigência é do § 2º, para aeronaves e navios **estrangeiros** em lugar sujeito à administração militar."),
   ("Não se aplica enquanto a justiça do país do porto não declinar de sua jurisdição.",
    "Errada. O caput do art. 7º aplica a lei penal militar ao crime fora do território, ‘ainda que o agente esteja sendo processado ou tenha sido julgado pela justiça estrangeira’."),
  ], correta=0,
  comentario="O dado decisivo é o comando militar por ordem legal; a propriedade e o porto estrangeiro são distratores.",
  fonte=f"{A31}, slides 10–12; {CPM}, art. 7º, caput e §§ 1º–3º, p. 17–18.", armadilha="Exigir propriedade pública ou aplicar o § 2º a navio brasileiro.", tempo=3),
 dict(n=6, tipo="VF", nivel="N3", ctx=True, conceitos=["DIRT2-TERRITORIALIDADE"],
  competencia="Distinguir os requisitos cumulativos do art. 7º, § 2º, do CPM.",
  afirmacao="Um navio mercante estrangeiro está atracado no cais de uma base naval brasileira. Um tripulante estrangeiro furta o relógio de outro tripulante estrangeiro a bordo. Por ter ocorrido em lugar sujeito à administração militar, aplica-se automaticamente a lei penal militar brasileira.",
  correta=False,
  comentario="Falsa. O § 2º do art. 7º exige, cumulativamente, (1) navio ou aeronave estrangeiro em lugar sujeito à administração militar **e** (2) crime que atente contra as instituições militares. O furto de bem particular entre tripulantes não evidencia o segundo requisito.",
  fonte=f"{CPM}, art. 7º, § 2º, p. 17; {A31}, slide 12.", armadilha="Tratar o lugar como requisito suficiente.", tempo=2),
 dict(n=7, tipo="OBJ", nivel="N3", ctx=True, conceitos=["DIRT2-PRINC-IRRETRO"],
  competencia="Aplicar a retroatividade da lei mais benigna após o trânsito em julgado e o critério de comparação das leis.",
  enunciado="Um sargento foi condenado definitivamente por crime militar. Meses depois, lei nova reduz a pena mínima do tipo, mas aumenta o prazo de um efeito secundário da condenação. A defesa pede a aplicação apenas da parte favorável da lei nova, mantendo da lei antiga o prazo menor. Assinale a alternativa correta.",
  alternativas=[
   ("A lei posterior que favorece o agente retroage mesmo após sentença irrecorrível, mas, para saber qual é mais favorável, as leis são consideradas separadamente, cada uma no conjunto de suas normas aplicáveis ao fato.",
    "Correta. Art. 2º, § 1º (retroatividade mesmo após sentença irrecorrível) e § 2º (comparação de cada lei no seu conjunto)."),
   ("A lei nova não pode retroagir, porque já houve trânsito em julgado.",
    "Errada. O § 1º afirma a retroatividade ‘ainda quando já tenha sobrevindo sentença condenatória irrecorrível’."),
   ("O juiz deve combinar as partes mais favoráveis das duas leis, pois a CF manda retroagir o que beneficia o réu.",
    "Errada. O § 2º do art. 2º do CPM determina a comparação de cada lei no conjunto de suas normas, o que afasta a combinação de fragmentos."),
   ("Trata-se de abolitio criminis, que extingue a própria sentença.",
    "Errada. A lei não deixou de considerar o fato crime; apenas alterou a pena. É hipótese do § 1º, não do caput."),
  ], correta=0,
  comentario="Distinguir abolitio (caput) de lex mitior (§ 1º) e aplicar o critério de apuração da maior benignidade (§ 2º).",
  fonte=f"{CPM}, art. 2º, §§ 1º–2º, p. 16; {CF}, art. 5º, XL, p. 17; {A31}, slide 5.", armadilha="Combinar leis; negar retroatividade após trânsito em julgado.", tempo=3),
 dict(n=8, tipo="OBJ", nivel="N2", ctx=True, conceitos=["DIRT2-PRINC-GARANTIAS"],
  competencia="Identificar penas vedadas pela Constituição e sua única exceção.",
  enunciado="Um parlamentar apresenta projeto de lei que altera o CPM para punir a deserção, em tempo de paz, com trabalhos forçados em obras militares e, em tempo de guerra declarada, com pena de morte. Considerando os princípios do slide 5 da Aula 3.1:",
  alternativas=[
   ("A pena de trabalhos forçados é vedada em qualquer situação; a pena de morte é admitida somente em caso de guerra declarada.",
    "Correta. CF art. 5º, XLVII, ‘a’ (morte, salvo guerra declarada) e ‘c’ (trabalhos forçados)."),
   ("Ambas as penas são admitidas porque se trata de crime propriamente militar.",
    "Errada. A natureza militar do crime não afasta as vedações constitucionais."),
   ("Ambas são vedadas, pois a Constituição não admite pena de morte em nenhuma hipótese.",
    "Errada. A alínea ‘a’ ressalva a guerra declarada."),
   ("Trabalhos forçados seriam admitidos com a anuência do condenado.",
    "Errada. A vedação não comporta consentimento."),
  ], correta=0,
  comentario="A exceção única da pena de morte é a guerra declarada; trabalhos forçados, banimento, penas cruéis e de caráter perpétuo são vedados.",
  fonte=f"{CF}, art. 5º, XLVII, p. 17; {A31}, slide 5.", armadilha="Supor que a natureza militar do crime flexibiliza as vedações.", tempo=2),
 dict(n=9, tipo="OBJ", nivel="N4", ctx=True, conceitos=["DIRT2-LUGAR-CRIME", "DIRT2-TEMPO-CRIME", "DIRT2-TERRITORIALIDADE", "DIRT2-PRINC-IRRETRO"],
  competencia="Integrar tempo, lugar, território por extensão e irretroatividade em um mesmo fato.",
  enunciado="Em 10 de março, a bordo de navio de guerra brasileiro em águas internacionais, um cabo agride dolosamente outro militar, que é desembarcado e morre em hospital de país estrangeiro em 2 de abril. Em 20 de março entrou em vigor lei que aumentou a pena do crime. A tripulação discute: (I) o crime pode ser considerado praticado tanto no navio quanto no país do hospital; (II) aplica-se a lei mais grave, porque o resultado ocorreu após sua vigência; (III) a lei penal militar brasileira alcança o fato; (IV) o cabo era de serviço no convés. Estão corretas apenas:",
  alternativas=[
   ("I e III.", "Correta. I: comissivo — ubiquidade (art. 6º). III: navio sob comando militar é extensão do território (art. 7º, § 1º). II é falsa: tempo pela atividade (art. 5º) e a lei mais grave não retroage. IV é fato irrelevante, não análise."),
   ("I, II e III.", "Errada. II confunde o tempo do crime com o do resultado; a lei posterior mais grave não alcança conduta de 10 de março (CF art. 5º, XL)."),
   ("II e III.", "Errada. Além do erro em II, descarta I, que decorre da ubiquidade."),
   ("III e IV.", "Errada. IV é dado factual sem conteúdo jurídico para as questões postas e I foi indevidamente descartada."),
  ], correta=0,
  comentario="Cadeia: fatos (conduta a bordo em 10/3, morte no exterior em 2/4, lei mais grave em 20/3) → questões (lugar, tempo, lei aplicável, alcance territorial) → normas (arts. 5º, 6º, 7º § 1º; CF art. 5º, XL) → aplicação → exceção (retroatividade só benéfica) → conclusão: I e III.",
  fonte=f"{CPM}, arts. 5º–7º, p. 17; {CF}, art. 5º, XL, p. 17; {A31}, slides 5–12.", armadilha="Usar o resultado para o tempo e para a lei aplicável.", tempo=4),
 dict(n=10, tipo="OBJ", nivel="N4", ctx=True, conceitos=["DIRT2-PRINC-LEGALIDADE", "DIRT2-PRINC-IRRETRO"],
  competencia="Separar reserva legal, anterioridade e retroatividade em sucessão de normas.",
  enunciado="Em janeiro, uma portaria interna de um distrito naval declarou ‘crime militar’, com pena de detenção, fotografar áreas restritas. Em fevereiro, um marinheiro fotografou uma área restrita. Em maio, entrou em vigor lei federal que tipificou exatamente a mesma conduta. Em agosto, outra lei revogou a tipificação de maio. Assinale a conclusão correta.",
  alternativas=[
   ("Não há crime pelo fato de fevereiro: a portaria não pode criar crime, a lei de maio não retroage e, de todo modo, a lei de agosto deixou de considerar o fato crime.",
    "Correta. Reserva legal e anterioridade (art. 1º; CF XXXIX), irretroatividade da lei mais grave (CF XL) e abolitio (art. 2º). Eventual repercussão disciplinar não é objeto da pergunta."),
   ("Há crime desde fevereiro, pois a portaria foi confirmada pela lei de maio.",
    "Errada. Ato infralegal não define crime, e a lei de maio não convalida conduta anterior."),
   ("Há crime pela lei de maio, que retroage por tratar da mesma conduta.",
    "Errada. Lei penal mais grave não retroage."),
   ("O fato é crime até agosto, quando a revogação extingue apenas a pena, mantendo a condenação.",
    "Errada. Não houve crime em fevereiro; além disso, a lei supressiva faz cessar a própria vigência da sentença condenatória, salvo efeitos civis."),
  ], correta=0,
  comentario="Três camadas independentes chegam à mesma conclusão; a questão testa se o aluno reconhece cada uma sem depender da última.",
  fonte=f"{CPM}, arts. 1º–2º, p. 16; {CF}, art. 5º, XXXIX–XL, p. 17; {A31}, slide 5.", armadilha="Aceitar que regulamento cria crime ou que lei posterior convalida.", tempo=4),
 dict(n=11, tipo="VF", nivel="N2", ctx=True, conceitos=["DIRT2-PRINC-GARANTIAS"],
  competencia="Aplicar a presunção de inocência ao estado do processo.",
  afirmacao="Um oficial condenado em primeira instância por crime militar, com recurso ainda pendente, pode ser tratado como culpado para todos os efeitos penais, porque a Justiça Militar é especializada.",
  correta=False,
  comentario="Falsa. A CF, art. 5º, LVII, só permite considerar alguém culpado após o trânsito em julgado da sentença penal condenatória; a especialização da jurisdição não altera a garantia.",
  fonte=f"{CF}, art. 5º, LVII, p. 18; {A31}, slide 5.", armadilha="Supor regime diverso para a Justiça Militar.", tempo=1),
 dict(n=12, tipo="OBJ", nivel="N3", ctx=True, conceitos=["DIRT2-PRINC-GARANTIAS"],
  competencia="Aplicar a pessoalidade da pena e suas extensões patrimoniais.",
  enunciado="Um suboficial condenado definitivamente por crime militar com dano ao patrimônio sob administração militar morre antes de cumprir a pena. A União pretende executar a pena privativa de liberdade contra o filho e cobrar dele, sem limite, a reparação do dano. Assinale a alternativa correta.",
  alternativas=[
   ("A pena não passa ao filho; a obrigação de reparar o dano pode ser estendida aos sucessores até o limite do valor do patrimônio transferido.",
    "Correta. CF art. 5º, XLV."),
   ("Nem a pena nem a reparação podem alcançar os sucessores.",
    "Errada. A reparação e o perdimento de bens podem ser estendidos, nos termos da lei, até o limite do patrimônio transferido."),
   ("A pena privativa de liberdade não passa, mas a reparação alcança todo o patrimônio do filho.",
    "Errada. O limite é o valor do patrimônio transferido."),
   ("Por se tratar de crime contra o patrimônio militar, a pena pode ser convertida em multa e cobrada dos herdeiros.",
    "Errada. Não há essa exceção; nenhuma pena passa da pessoa do condenado."),
  ], correta=0,
  comentario="Distinção entre pena (intransmissível) e efeitos patrimoniais (transmissíveis com limite).",
  fonte=f"{CF}, art. 5º, XLV, p. 17; {A31}, slide 5.", armadilha="Tratar reparação como pena ou eliminar o limite.", tempo=2),
 dict(n=13, tipo="DIS", nivel="N3", ctx=True, conceitos=["DIRT2-LUGAR-CRIME", "DIRT2-TEMPO-CRIME"],
  competencia="Determinar tempo e lugar de crime omissivo e fundamentar.",
  contexto="Um oficial de serviço em uma organização militar em Niterói recebe, às 20h, ordem de acionar o socorro para um marinheiro ferido que se encontra em um posto destacado em Arraial do Cabo. Ele deliberadamente não aciona. O marinheiro morre na madrugada, em Arraial do Cabo. Em data posterior, entra em vigor lei que agrava a pena do crime correspondente.",
  enunciado="Indique, com fundamento, (a) o lugar do crime e (b) o momento do crime para fins de lei aplicável. Aponte o fato que costuma induzir ao erro.",
  gabarito="**Gabarito:** (a) Crime omissivo: considera-se praticado no lugar em que deveria realizar-se a ação omitida (CPM art. 6º, parte final) — Niterói, onde o oficial deveria acionar o socorro. A ubiquidade (atividade ou resultado) é regra dos comissivos; o lugar da morte (Arraial do Cabo) não define o lugar do crime omissivo. (b) Tempo: momento da ação ou omissão, ainda que outro seja o do resultado (art. 5º) — 20h, quando deveria agir. A lei posterior mais grave não retroage (CF art. 5º, XL). Fato indutor de erro: o local e a hora da morte.\n\n**Resposta plena:** identifica a omissão, aplica a parte final do art. 6º e o art. 5º, afasta a lei mais grave. **Parcial:** acerta o tempo mas aplica ubiquidade ao lugar (ou vice-versa). **Insuficiente:** indica o local da morte com base no resultado.",
  criterios=["Questão identificada: crime omissivo e momento/lugar (0,2)", "Norma: art. 6º (parte final) e art. 5º do CPM (0,2)", "Aplicação: Niterói e 20h (0,3)", "Limite: ubiquidade não se aplica a omissivo; lei mais grave não retroage (0,2)", "Conclusão coerente (0,1)"],
  fonte=f"{CPM}, arts. 5º–6º, p. 17; {CF}, art. 5º, XL, p. 17; {A31}, slides 6–9.", armadilha="Aplicar ubiquidade ao omissivo.", tempo=7),
 dict(n=15, tipo="VF", nivel="N1", ctx=False, conceitos=["DIRT2-DP-CONCEITO", "DIRT2-PRINC-LEGALIDADE"],
  competencia="Reconhecer a natureza do Direito Penal e a exclusividade do poder punitivo estatal.",
  afirmacao="Segundo a aula, o Direito Penal é ramo do Direito Público que disciplina o poder punitivo do Estado, exercido por este com exclusividade; por isso, uma organização militar pode definir crimes por portaria interna quando se tratar de assunto disciplinar.",
  correta=False,
  comentario="Falsa. A primeira parte reproduz o slide 4. A conclusão é incompatível com a legalidade: só lei anterior define crime e comina pena (CF art. 5º, XXXIX; CPM art. 1º). Portaria pode regular a disciplina, não criar crime.",
  fonte=f"{A31}, slides 4–5; {CF}, art. 5º, XXXIX, p. 17; {CPM}, art. 1º, p. 16.", armadilha="Confundir poder disciplinar com poder de definir crimes.", tempo=1),
 dict(n=14, tipo="DIS", nivel="N4", ctx=True, conceitos=["DIRT2-TERRITORIALIDADE", "DIRT2-PRINC-IRRETRO", "DIRT2-PRINC-LEGALIDADE"],
  competencia="Construir fundamentação completa sobre alcance espacial e sucessão de leis penais.",
  contexto="Uma lancha de empresa privada foi requisitada por ordem legal e colocada sob comando de um primeiro-tenente para transporte de material a um navio da MB fundeado em águas estrangeiras. Durante o trajeto, um sargento embarcado destrói dolosamente parte do material militar. Ele é processado no país costeiro. Depois do fato, lei penal militar nova (a) reduz a pena do crime e (b) cria nova agravante aplicável ao caso.",
  enunciado="A lei penal militar brasileira alcança o fato? Qual lei deve ser aplicada? Fundamente cada conclusão e indique o limite que impede uma solução ‘mista’.",
  gabarito="**Gabarito:** Alcance: sim. A lancha, sob comando militar, é navio para o CPM (art. 7º, § 3º) e extensão do território nacional onde quer que se encontre, ainda que de propriedade privada (§ 1º). Mesmo fora do território, a lei militar se aplica ainda que haja processo no estrangeiro (caput). Lei aplicável: a lei posterior que ‘de qualquer outro modo favorece o agente’ retroage (art. 2º, § 1º; CF art. 5º, XL); porém a verificação da maior benignidade exige comparar cada lei no conjunto de suas normas aplicáveis ao fato (§ 2º). Limite: não se combina a redução da lei nova com a ausência de agravante da lei antiga; aplica-se integralmente a lei que, no conjunto, for mais favorável. Legalidade: a agravante nova não pode ser aplicada isoladamente a fato anterior.\n\n**Plena:** três dispositivos do art. 7º + § 1º e § 2º do art. 2º + conclusão sobre a vedação da combinação. **Parcial:** acerta alcance, mas propõe combinação de leis. **Insuficiente:** nega alcance por ser propriedade privada ou por haver processo estrangeiro.",
  criterios=["Questões identificadas: alcance espacial e sucessão de leis (0,2)", "Normas: art. 7º caput, §§ 1º e 3º; art. 2º §§ 1º–2º; CF XL (0,2)", "Aplicação aos fatos (lancha requisitada, comando militar, processo estrangeiro) (0,3)", "Limite: vedação de combinar leis e irretroatividade da agravante (0,2)", "Conclusão (0,1)"],
  fonte=f"{CPM}, arts. 2º e 7º, p. 16–18; {CF}, art. 5º, XXXIX–XL, p. 17; {A31}, slides 5 e 10–12.", armadilha="Propor combinação de leis.", tempo=9),
]
