from conceitos import A31, A41, A42, CPM, CPPM, CF, EM

M02 = [
 dict(n=1, tipo="VF", nivel="N1", ctx=False, conceitos=["DIRT2-CULPA"],
  competencia="Reconhecer a excepcionalidade do crime culposo.",
  afirmacao="Pelo CPM, salvo os casos expressos em lei, ninguém pode ser punido por fato previsto como crime senão quando o pratica dolosamente.",
  correta=True,
  comentario="Verdadeira. É o parágrafo único do art. 33, reproduzido no slide 22: a forma culposa só é punível quando a lei a prevê expressamente.",
  fonte=f"{CPM}, art. 33, parágrafo único, p. 26; {A31}, slide 22.", armadilha="Supor que todo crime admite forma culposa.", tempo=1),
 dict(n=2, tipo="OBJ", nivel="N2", ctx=False, conceitos=["DIRT2-DOLO"],
  competencia="Distinguir as formas de dolo apresentadas pelo professor e a redação do CPM.",
  enunciado="Assinale a alternativa que corresponde, respectivamente, ao dolo direto, ao dolo alternativo e ao dolo eventual, conforme o slide 17 da Aula 3.1 e o art. 33, I, do CPM.",
  alternativas=[
   ("Quis e conheceu o resultado; quis indiferentemente um resultado ou outro; não quis o resultado, mas conheceu o risco — o CPM fala em ‘assumiu o risco de produzi-lo’.",
    "Correta. Reproduz o slide 17 e conecta o dolo eventual à expressão legal do art. 33, I."),
   ("Quis o resultado; previu o resultado e confiou que não ocorreria; não previu o resultado previsível.",
    "Errada. A segunda e a terceira descrições são de culpa (art. 33, II), não de dolo."),
   ("Assumiu o risco; quis o resultado; quis um ou outro resultado.",
    "Errada. A ordem está trocada."),
   ("Quis o resultado; quis um resultado mais grave que o obtido; causou resultado além da intenção.",
    "Errada. ‘Resultado além da intenção’ descreve o preterdolo (slide 23), não o dolo eventual."),
  ], correta=0,
  comentario="O ponto sensível é a fórmula do dolo eventual: o slide diz ‘conheceu do risco’; a lei exige ‘assumiu o risco de produzi-lo’. Conhecer o risco e confiar que ele não se realizará é culpa consciente (art. 33, II, parte final).",
  fonte=f"{A31}, slides 16–17 e 23; {CPM}, art. 33, I–II, p. 26.", armadilha="Tomar ‘conhecer o risco’ como suficiente para o dolo eventual.", tempo=2),
 dict(n=3, tipo="COR", nivel="N2", ctx=True, conceitos=["DIRT2-CULPA", "DIRT2-DOLO"],
  competencia="Classificar condutas pelos elementos subjetivos e modalidades de culpa.",
  titulo="Associe cada situação à classificação correta",
  chaves=[("A", "Imprudência (imprevisão ativa)"), ("B", "Negligência (imprevisão passiva)"), ("C", "Imperícia (falta de conhecimento técnico)"), ("D", "Dolo alternativo")],
  itens=[
   ("Motorista habilitado de viatura faz curva em velocidade excessiva no pátio e atinge um pedestre.", "A"),
   ("Encarregado deixa, dias a fio, de substituir o cabo de aço gasto de um guincho, que se rompe e fere um marinheiro.", "B"),
   ("Marinheiro sem qualificação opera o guindaste de bordo e deixa cair a carga sobre um colega.", "C"),
   ("Cabo dispara contra dois desafetos que conversam juntos, indiferente a qual deles atingir.", "D"),
  ],
  comentario="Os três primeiros seguem os exemplos-tipo do professor (velocidade, freios gastos, pessoa não habilitada). O último: vontade indiferente entre resultados é dolo indireto alternativo.",
  fonte=f"{A31}, slides 17 e 19–21; {CPM}, art. 33, p. 26.", armadilha="Trocar negligência (omissão de cautela) por imprudência (ação arriscada).", tempo=3),
 dict(n=4, tipo="OBJ", nivel="N2", ctx=True, conceitos=["DIRT2-FATO-TIPICO"],
  competencia="Aplicar a superveniência de causa relativamente independente ao nexo causal.",
  enunciado="Um marinheiro fere dolosamente um colega com um soco no rosto (lesão sem risco de vida). A vítima é levada de ambulância ao hospital naval, e a ambulância é abalroada por um caminhão; a vítima morre em razão do acidente. Quanto ao resultado morte:",
  alternativas=[
   ("Não é imputado ao agressor, porque a causa superveniente relativamente independente produziu, por si só, o resultado; ele responde pelos fatos anteriores (a lesão).",
    "Correta. CPM art. 29, § 1º."),
   ("É imputado ao agressor, porque sem o soco a vítima não estaria na ambulância.",
    "Errada. A regra da equivalência do caput é limitada pelo § 1º quando a causa superveniente, por si só, produz o resultado."),
   ("É imputado ao agressor a título de preterdolo.",
    "Errada. Preterdolo exige que o resultado agravador decorra da própria conduta e seja ao menos culposo (art. 34); aqui o nexo foi rompido."),
   ("Não há crime algum, porque o resultado final foi produzido por terceiro.",
    "Errada. Os fatos anteriores imputam-se a quem os praticou: permanece a lesão corporal."),
  ], correta=0,
  comentario="Fato típico exige nexo de causalidade (slide 15). O art. 29, § 1º, corta a imputação do resultado, mas preserva a responsabilidade pelo que foi praticado antes.",
  fonte=f"{A31}, slide 15; {CPM}, art. 29, caput e § 1º, p. 24–25.", armadilha="Aplicar a equivalência dos antecedentes sem o limite do § 1º.", tempo=3),
 dict(n=5, tipo="OBJ", nivel="N3", ctx=True, conceitos=["DIRT2-DOLO", "DIRT2-CULPA"],
  competencia="Distinguir dolo eventual de culpa consciente pelos dados subjetivos do enunciado.",
  enunciado="Durante manobra, um cabo conduz uma viatura em alta velocidade por uma área onde há militares em forma. Ele percebe que pode atingir alguém, mas, confiando em sua habilidade, acredita sinceramente que conseguirá desviar. Atinge e fere um soldado. Qual é o elemento subjetivo?",
  alternativas=[
   ("Culpa: previu o resultado, mas supôs levianamente que não se realizaria ou que poderia evitá-lo.",
    "Correta. É a parte final do art. 33, II (culpa consciente)."),
   ("Dolo eventual: conheceu o risco, o que basta para o dolo.",
    "Errada. O CPM exige que o agente ‘assuma o risco de produzir’ o resultado; a confiança sincera em evitá-lo afasta a assunção do risco."),
   ("Dolo direto: quis e conheceu o resultado.",
    "Errada. Não há vontade de ferir."),
   ("Não há elemento subjetivo, pois se tratava de manobra militar.",
    "Errada. O contexto de manobra não exclui dolo ou culpa; pode, inclusive, ser relevante para o art. 9º, II, ‘d’, em outra análise."),
  ], correta=0,
  comentario="Contrafactual: se o cabo pensasse ‘se atingir, atingiu’, aceitando o resultado, haveria dolo eventual. A diferença está na atitude diante do resultado previsto, não na previsão em si.",
  fonte=f"{A31}, slides 16–18; {CPM}, art. 33, I–II, p. 26.", armadilha="Dolo eventual × culpa consciente.", tempo=3),
 dict(n=6, tipo="VF", nivel="N3", ctx=True, conceitos=["DIRT2-FATO-TIPICO"],
  competencia="Aplicar a omissão penalmente relevante do garantidor.",
  afirmacao="Um sargento designado por escala para vigiar a piscina da organização militar durante o treino de natação se afasta para usar o celular e um aluno se afoga. Pelo CPM, a omissão do sargento pode ser causa relevante do resultado, porque ele tinha obrigação de vigilância e podia agir.",
  correta=True,
  comentario="Verdadeira. O art. 29, § 2º, torna a omissão relevante quando o omitente devia e podia agir; o dever incumbe a quem tem obrigação de cuidado, proteção ou vigilância ou assumiu a responsabilidade de impedir o resultado. Se houve dolo ou culpa é a etapa seguinte da análise.",
  fonte=f"{CPM}, art. 29, § 2º, p. 25; {A31}, slide 15 (‘conduta humana, por ação ou omissão’).", armadilha="Supor que só ações causam resultados.", tempo=2),
 dict(n=7, tipo="OBJ", nivel="N3", ctx=True, conceitos=["DIRT2-PRETERDOLO", "DIRT2-CRIME-209-210"],
  competencia="Enquadrar o crime preterdoloso e o resultado agravador no CPM.",
  enunciado="Em discussão no alojamento, um marinheiro dá um empurrão violento em outro para machucá-lo. A vítima cai, bate a cabeça na quina de um armário e morre. As circunstâncias mostram que o agressor não quis a morte nem assumiu o risco de produzi-la, mas o resultado era previsível. Assinale o enquadramento mais adequado.",
  alternativas=[
   ("Lesão corporal com resultado morte (CPM art. 209, § 3º, parte final): dolo na lesão e culpa na morte — crime preterdoloso.",
    "Correta. Resultado além da intenção (slide 23), responsabilidade pelo resultado agravador ao menos culposo (art. 34) e forma do art. 209, § 3º."),
   ("Homicídio doloso, porque a morte decorreu de agressão intencional.",
    "Errada. A intenção era lesionar; não houve dolo, nem eventual, quanto à morte."),
   ("Lesão corporal leve apenas, pois a morte não foi querida.",
    "Errada. O resultado previsível é imputável a título de culpa (art. 34)."),
   ("Lesão corporal culposa (art. 210), porque o resultado final foi culposo.",
    "Errada. A conduta inicial foi dolosa; o art. 210 cuida da lesão integralmente culposa."),
  ], correta=0,
  comentario="Cadeia: conduta dolosa (lesão) → resultado mais grave → previsibilidade (culpa) → art. 34 → art. 209, § 3º. Se o resultado fosse imprevisível, o agente responderia só pela lesão.",
  fonte=f"{A31}, slide 23; {CPM}, art. 34, p. 26; art. 209, § 3º, p. 94.", armadilha="Tratar todo resultado de agressão intencional como doloso.", tempo=3),
 dict(n=8, tipo="OBJ", nivel="N2", ctx=True, conceitos=["DIRT2-CULPA", "DIRT2-CRIME-209-210"],
  competencia="Verificar a existência de previsão legal de forma culposa antes de concluir pela punição.",
  enunciado="Ao limpar o convés, um marinheiro, por descuido, deixa um balde no alto de uma escada; o balde cai e fere levemente um cabo. O encarregado afirma que ‘não há crime porque não houve intenção’. Assinale a análise correta.",
  alternativas=[
   ("Pode haver crime: a lesão corporal tem forma culposa expressamente prevista (art. 210), o que satisfaz a exigência do parágrafo único do art. 33.",
    "Correta. A excepcionalidade da culpa é superada porque há previsão expressa."),
   ("Não há crime, porque ninguém é punido senão por dolo.",
    "Errada. A regra ressalva ‘os casos expressos em lei’."),
   ("Há crime doloso, pois o marinheiro quis deixar o balde ali.",
    "Errada. Querer a conduta descuidada não é querer o resultado lesivo."),
   ("Há apenas transgressão disciplinar, porque o CPM não trata de lesão sem intenção.",
    "Errada. O art. 210 trata exatamente da lesão culposa."),
  ], correta=0,
  comentario="Primeiro verifique se o tipo admite forma culposa; depois examine dever de cuidado, previsibilidade e resultado involuntário (slide 18).",
  fonte=f"{CPM}, art. 33, parágrafo único, p. 26; art. 210, p. 95; {A31}, slides 18 e 22.", armadilha="Negar crime culposo por ausência de intenção.", tempo=2),
 dict(n=9, tipo="OBJ", nivel="N4", ctx=True, conceitos=["DIRT2-DOLO", "DIRT2-CULPA", "DIRT2-PRETERDOLO", "DIRT2-FATO-TIPICO"],
  competencia="Classificar elementos subjetivos de vários agentes em um único episódio.",
  enunciado="No estande de tiro: (I) o Cabo Alfa, irritado, atira nas pernas do Soldado Bravo para feri-lo; o projétil atinge a femoral e Bravo morre, resultado previsível e não aceito por Alfa. (II) O Sargento Charlie, encarregado do estande, tinha visto a arma de Alfa carregada com munição real fora do horário e nada fez, porque ‘não era da sua conta’. (III) O Soldado Delta, ao ver a cena, dispara para o alto para chamar atenção, confiando que o tiro não atingiria ninguém; o projétil ricocheteia e fere um civil. (IV) Fora do estande, um militar ouve os tiros e comenta que ‘alguém vai morrer’. Assinale a alternativa correta.",
  alternativas=[
   ("I é preterdolo; II exige verificar se Charlie tinha dever de vigilância e podia agir, para que sua omissão seja causal; III é culpa (previu e confiou que não ocorreria); IV é irrelevante penalmente.",
    "Correta. Separa corretamente os quatro comportamentos e preserva a etapa de verificação do dever de agir (art. 29, § 2º)."),
   ("I é homicídio doloso; II é participação dolosa automática; III é dolo eventual; IV é incitação.",
    "Errada. I não teve dolo de matar; II não se converte em participação sem vínculo subjetivo nem análise do dever de agir; III descreve confiança na não ocorrência (culpa); IV não é conduta típica."),
   ("I é lesão corporal leve; II é negligência já comprovada; III é caso fortuito; IV é irrelevante.",
    "Errada. I ignora o resultado previsível (art. 34); II afirma culpa sem examinar dever e possibilidade de agir; III ignora a previsão do resultado."),
   ("I é preterdolo; II é irrelevante porque omissão não causa resultado; III é culpa; IV é irrelevante.",
    "Errada. Omissão pode ser causa relevante quando há dever e possibilidade de agir (art. 29, § 2º)."),
  ], correta=0,
  comentario="Questão de ‘quatro agentes, quatro institutos’: o candidato precisa isolar cada conduta. O ruído (irritação, horário, comentário do terceiro) não altera o enquadramento.",
  fonte=f"{A31}, slides 15–23; {CPM}, arts. 29, 33 e 34, p. 24–26.", armadilha="Contaminar a análise de um agente com o resultado causado por outro.", tempo=5),
 dict(n=10, tipo="OBJ", nivel="N4", ctx=True, conceitos=["DIRT2-DOLO", "DIRT2-PRETERDOLO", "DIRT2-FATO-TIPICO"],
  competencia="Aplicar contrafactuais sobre elemento subjetivo e nexo causal.",
  enunciado="Um suboficial golpeia um marinheiro com um bastão para lesioná-lo. Considere quatro versões: (1) a vítima morre do golpe, resultado previsível e não aceito; (2) a vítima morre do golpe, e o suboficial pensava ‘se morrer, morreu’; (3) a vítima, apenas ferida, morre no incêndio do hospital; (4) a vítima morre porque tinha uma doença rara que tornava a morte absolutamente imprevisível. Assinale a correspondência correta.",
  alternativas=[
   ("(1) preterdolo; (2) dolo eventual quanto à morte; (3) só a lesão, por causa superveniente que por si só produziu o resultado; (4) só a lesão, pois o resultado agravador não foi causado ao menos culposamente.",
    "Correta. Arts. 33, I (assumir o risco), 34 (culpa mínima no resultado agravador) e 29, § 1º (causa superveniente)."),
   ("(1) dolo eventual; (2) preterdolo; (3) homicídio; (4) preterdolo.",
    "Errada. Inverte 1 e 2 e desconsidera o art. 29, § 1º, e a imprevisibilidade em 4."),
   ("(1) preterdolo; (2) preterdolo; (3) preterdolo; (4) preterdolo.",
    "Errada. Em 2 há assunção do risco (dolo eventual); em 3 o nexo é cortado; em 4 falta culpa."),
   ("(1) lesão; (2) dolo eventual; (3) preterdolo; (4) homicídio culposo.",
    "Errada. Em 1 a morte previsível é imputada; em 3 o nexo foi cortado; em 4 não há culpa."),
  ], correta=0,
  comentario="Quatro alterações pontuais produzem quatro soluções. É o formato de contrafactual exigido pelo perfil: o dado alterado é sempre subjetivo ou causal.",
  fonte=f"{CPM}, arts. 29, § 1º, 33, I, e 34, p. 24–26; {A31}, slides 17 e 23.", armadilha="Responder por palavra-chave ‘morte’.", tempo=5),
 dict(n=11, tipo="VF", nivel="N2", ctx=True, conceitos=["DIRT2-DOLO"],
  competencia="Reconhecer o dolo alternativo em situação concreta.",
  afirmacao="Um marinheiro arremessa uma barra de ferro contra um colega querendo, indiferentemente, feri-lo ou matá-lo. Segundo a classificação apresentada em aula, trata-se de dolo indireto alternativo.",
  correta=True,
  comentario="Verdadeira. O slide 17 define o dolo alternativo como a vontade indiferente entre um resultado ou outro, espécie de dolo indireto.",
  fonte=f"{A31}, slide 17.", armadilha="Chamar de eventual toda forma de dolo não direto.", tempo=1),
 dict(n=12, tipo="OBJ", nivel="N3", ctx=True, conceitos=["DIRT2-CULPA", "DIRT2-ELEMENTOS-CRIME"],
  competencia="Verificar os elementos do crime culposo antes de classificar a modalidade.",
  enunciado="Um marinheiro, cumprindo rigorosamente todas as normas de segurança, aciona um guincho recém-revisado. Um defeito oculto de fábrica, impossível de ser percebido, faz o cabo romper e ferir um colega. Assinale a alternativa correta.",
  alternativas=[
   ("Não há crime culposo, porque faltam a inobservância do dever de cuidado e a previsibilidade.",
    "Correta. Os elementos do slide 18 não se completam: houve observância do cuidado e o resultado era imprevisível."),
   ("Há imperícia, porque o marinheiro não percebeu o defeito técnico.",
    "Errada. Imperícia é falta ou insuficiência de conhecimento técnico; o enunciado não a descreve e o defeito era imperceptível."),
   ("Há negligência, porque o cabo rompeu.",
    "Errada. A negligência pressupõe deixar de adotar cautela devida; o resultado sozinho não prova culpa."),
   ("Há dolo eventual, pois todo guincho oferece risco.",
    "Errada. Risco inerente não é assunção do risco de produzir o resultado."),
  ], correta=0,
  comentario="Resultado lesivo involuntário, sozinho, não é culpa: exija a violação do dever de cuidado e a previsibilidade.",
  fonte=f"{A31}, slides 18–21; {CPM}, art. 33, II, p. 26.", armadilha="Responsabilizar pelo resultado sem culpa.", tempo=3),
 dict(n=13, tipo="DIS", nivel="N3", ctx=True, conceitos=["DIRT2-DOLO", "DIRT2-CULPA"],
  competencia="Fundamentar a distinção entre dolo eventual e culpa consciente com contrafactual.",
  contexto="Um cabo, de serviço como motorista, dirige uma viatura militar em uma rua da vila naval a 90 km/h, sabendo que há crianças brincando. Um colega adverte; o cabo responde: ‘Relaxa, eu controlo’. Uma criança atravessa e é gravemente ferida.",
  enunciado="Classifique o elemento subjetivo, fundamente no CPM e explique qual alteração da fala do cabo mudaria a classificação.",
  gabarito="**Gabarito:** a fala ‘eu controlo’ indica que o cabo previu o resultado, mas supôs levianamente que não ocorreria ou que poderia evitá-lo — culpa consciente, pela parte final do art. 33, II; a modalidade é imprudência (imprevisão ativa: velocidade excessiva, como no slide 19). Não há dolo eventual porque o art. 33, I, exige que o agente assuma o risco de produzir o resultado. Contrafactual: se respondesse ‘se atropelar, azar’, aceitaria o resultado — dolo eventual. A classificação da lesão e do crime militar é etapa posterior.\n\n**Plena:** distingue previsão de assunção do risco, cita art. 33, I e II, e formula o contrafactual. **Parcial:** conclui por culpa sem explicar por que não há dolo eventual. **Insuficiente:** conclui por dolo eventual apenas pela velocidade.",
  criterios=["Questão: dolo eventual ou culpa consciente (0,2)", "Norma: art. 33, I e II, e slide 17/19 (0,2)", "Aplicação à fala e à conduta (0,3)", "Contrafactual correto (0,2)", "Conclusão (0,1)"],
  fonte=f"{A31}, slides 16–19; {CPM}, art. 33, p. 26.", armadilha="Presumir dolo eventual pela gravidade.", tempo=7),
 dict(n=14, tipo="DIS", nivel="N4", ctx=True, conceitos=["DIRT2-FATO-TIPICO", "DIRT2-PRETERDOLO", "DIRT2-CULPA"],
  competencia="Resolver caso com nexo causal, resultado agravador e culpa de terceiro.",
  contexto="No convés, o Marinheiro Eco empurra o Marinheiro Foxtrot para machucá-lo. Foxtrot cai e fratura o crânio. O Cabo Golf, responsável pela enfermaria naquele turno, demora uma hora para atender por estar jogando no celular. Foxtrot morre; o laudo diz que a fratura, sem atendimento, levaria à morte, e que o atendimento imediato ‘provavelmente’ o salvaria.",
  enunciado="Analise a responsabilidade de Eco e de Golf pelo resultado morte, indicando normas, requisitos e o ponto de incerteza do enunciado.",
  gabarito="**Gabarito:** Eco: conduta dolosa de lesão; morte previsível e não querida → resultado agravador imputável ao menos a título de culpa (art. 34), configurando lesão com resultado morte (art. 209, § 3º, parte final). A demora no atendimento não é causa que, ‘por si só’, produziu a morte (art. 29, § 1º): a fratura já levaria ao óbito — nexo mantido. Golf: omissão; tinha dever de cuidado (responsável pela enfermaria) e podia agir (art. 29, § 2º). A culpa (negligência, slide 20) depende de nexo: o laudo diz ‘provavelmente’ o salvaria — ponto de incerteza probatória que deve ser explicitado; a conclusão sobre imputação da morte a Golf exige prova de que a ação devida teria evitado o resultado. Havendo, responde por forma culposa se prevista em lei.\n\n**Plena:** separa as condutas, aplica arts. 29 §§ 1º–2º, 33 II e 34, e declara a incerteza do laudo. **Parcial:** acerta Eco, mas imputa a Golf a morte automaticamente. **Insuficiente:** afirma que a demora de Golf rompe o nexo de Eco.",
  criterios=["Questões: nexo, resultado agravador e omissão de terceiro (0,2)", "Normas: arts. 29 §§ 1º–2º, 33 II, 34, 209 § 3º (0,2)", "Aplicação separada a Eco e Golf (0,3)", "Limite: incerteza do laudo e causa não autônoma (0,2)", "Conclusão (0,1)"],
  fonte=f"{CPM}, arts. 29, 33, 34 e 209, § 3º, p. 24–26 e 94; {A31}, slides 15, 18–20 e 23.", armadilha="Achar que a culpa posterior de terceiro sempre rompe o nexo.", tempo=10),
]

M03 = [
 dict(n=1, tipo="VF", nivel="N1", ctx=False, conceitos=["DIRT2-EXCL-ILICITUDE"],
  competencia="Reconhecer o efeito jurídico das excludentes do art. 42.",
  afirmacao="Nas hipóteses do art. 42 do CPM (estado de necessidade, legítima defesa, estrito cumprimento do dever legal e exercício regular de direito), o crime subsiste, mas o agente fica isento de pena.",
  correta=False,
  comentario="Falsa. O caput diz ‘Não há crime quando o agente pratica o fato’ nessas situações: a ilicitude é excluída, logo não há crime. ‘Isento de pena’ é linguagem de outras hipóteses, não do art. 42.",
  fonte=f"{CPM}, art. 42, p. 29; {A31}, slides 25–26.", armadilha="Confundir exclusão do crime com isenção de pena.", tempo=1),
 dict(n=2, tipo="OBJ", nivel="N2", ctx=False, conceitos=["DIRT2-EXCL-ILICITUDE"],
  competencia="Identificar os requisitos legais do estado de necessidade excludente do crime.",
  enunciado="Segundo o art. 43 do CPM, NÃO é requisito do estado de necessidade como excludente do crime:",
  alternativas=[
   ("Que o mal causado seja igual ou superior ao mal evitado.",
    "Correta (não é requisito). O art. 43 exige o contrário: mal causado ‘consideravelmente inferior’ ao evitado."),
   ("Perigo certo e atual, que o agente não provocou.",
    "Errada. É requisito expresso."),
   ("Impossibilidade de evitar o perigo de outro modo.",
    "Errada. É requisito expresso (‘nem podia de outro modo evitar’)."),
   ("Que o agente não seja legalmente obrigado a arrostar o perigo.",
    "Errada. É requisito expresso."),
  ], correta=0,
  comentario="A ponderação de bens do art. 43 é mais exigente que ‘menor valor’: o mal causado deve ser consideravelmente inferior. Quem tem dever legal de enfrentar o perigo não o invoca.",
  fonte=f"{CPM}, art. 43, p. 29; {A31}, slide 25.", armadilha="Aceitar sacrifício de bem equivalente.", tempo=2),
 dict(n=3, tipo="COR", nivel="N2", ctx=False, conceitos=["DIRT2-EXCL-ILICITUDE", "DIRT2-EXCL-COMANDANTE"],
  competencia="Associar cada excludente ao seu elemento definidor.",
  titulo="Associe o elemento definidor à excludente",
  chaves=[("A", "Legítima defesa"), ("B", "Estado de necessidade"), ("C", "Excludente do comandante (art. 42, parágrafo único)")],
  itens=[
   ("Uso moderado dos meios necessários contra agressão injusta, atual ou iminente.", "A"),
   ("Quem tem obrigação legal de enfrentar o perigo não pode invocá-la.", "B"),
   ("Emprego de meios violentos contra subalternos para executar manobras urgentes e salvar a unidade.", "C"),
   ("Perigo certo e atual não provocado pelo agente.", "B"),
   ("Repulsa a ataque dirigido a direito de terceiro.", "A"),
  ],
  comentario="Legítima defesa responde a agressão humana injusta (art. 44), inclusive a direito de outrem; estado de necessidade responde a perigo (art. 43); a excludente do comandante tem sujeito, situação e finalidades próprias.",
  fonte=f"{CPM}, arts. 42–44, p. 29; {A31}, slides 25–27.", armadilha="Chamar de legítima defesa a reação a perigo não humano.", tempo=3),
 dict(n=4, tipo="OBJ", nivel="N3", ctx=True, conceitos=["DIRT2-EXCL-COMANDANTE"],
  competencia="Aplicar a excludente específica do comandante de navio.",
  enunciado="Um incêndio atinge a praça de máquinas de um navio em mar aberto. Parte da guarnição, em pânico, se recusa a descer para combater o fogo. O comandante, para salvar a unidade e as vidas a bordo, puxa à força dois marinheiros e os empurra para a escotilha, ferindo-os levemente. Assinale a alternativa correta.",
  alternativas=[
   ("Não há crime: comandante de navio, na iminência de perigo ou grave calamidade, pode compelir subalternos por meios violentos a executar manobras urgentes para salvar a unidade ou vidas.",
    "Correta. É o parágrafo único do art. 42 (slide 27)."),
   ("Há crime de rigor excessivo, pois o comandante excedeu a faculdade de punir.",
    "Errada. Não houve punição de subordinado, mas compulsão para manobra urgente em situação prevista em lei."),
   ("Há legítima defesa, pois a recusa dos marinheiros era agressão injusta.",
    "Errada. A recusa não é agressão; o CPM traz excludente específica para a hipótese."),
   ("A excludente só beneficiaria o comandante se houvesse ordem escrita de autoridade superior.",
    "Errada. A lei não exige ordem superior; exige qualidade de comandante, iminência de perigo/calamidade e finalidade legal."),
  ], correta=0,
  comentario="Contrafactual: se o comandante agredisse os marinheiros depois de extinto o incêndio, ‘para dar exemplo’, faltariam iminência de perigo e finalidade legal — a excludente não se aplica e o fato deve ser analisado nos tipos da parte especial.",
  fonte=f"{CPM}, art. 42, parágrafo único, p. 29; {A31}, slide 27.", armadilha="Estender a excludente a punição posterior.", tempo=3),
 dict(n=5, tipo="OBJ", nivel="N3", ctx=True, conceitos=["DIRT2-IMPUTABILIDADE"],
  competencia="Distinguir embriaguez voluntária de embriaguez fortuita completa ou incompleta.",
  enunciado="Em licença, um marinheiro bebe um refrigerante no qual um desconhecido, sem que ele soubesse, misturou grande quantidade de álcool. Inteiramente incapaz de entender o que fazia, agride um cabo. Assinale a alternativa correta; considere também a variação em que ele apenas teve reduzida a capacidade de entendimento.",
  alternativas=[
   ("Na embriaguez completa por caso fortuito, não é imputável; se a capacidade estava apenas reduzida, continua imputável, mas a pena pode ser reduzida de um a dois terços.",
    "Correta. Art. 49, caput e parágrafo único (slide 31)."),
   ("Em ambas as situações é imputável, porque ninguém se exime alegando embriaguez.",
    "Errada. O art. 49 prevê inimputabilidade por embriaguez completa fortuita ou por força maior."),
   ("Em ambas as situações é inimputável, pois não quis beber álcool.",
    "Errada. Na incompleta a imputabilidade permanece; só a pena pode ser reduzida."),
   ("É inimputável somente se a embriaguez resultar de doença mental.",
    "Errada. Mistura o art. 48 com o art. 49."),
  ], correta=0,
  comentario="Contrafactual: se ele próprio decidisse beber até perder o controle, a embriaguez não seria fortuita e o art. 49 não o beneficiaria.",
  fonte=f"{CPM}, art. 49, p. 31; {A31}, slides 30–31.", armadilha="Beneficiar embriaguez voluntária.", tempo=3),
 dict(n=6, tipo="VF", nivel="N3", ctx=True, conceitos=["DIRT2-INEXIGIBILIDADE"],
  competencia="Aplicar o limite da obediência hierárquica.",
  afirmacao="Um tenente ordena diretamente a um sargento que espanque um preso para obter confissão. O sargento cumpre a ordem. Como agiu em estrita obediência a ordem direta de superior hierárquico em matéria de serviço, apenas o tenente responde pelo crime.",
  correta=False,
  comentario="Falsa. Pelo art. 38, § 2º, se a ordem tem por objeto a prática de ato manifestamente criminoso, é punível também o inferior. O tenente responde como autor da ordem (§ 1º), mas isso não afasta a responsabilidade do sargento.",
  fonte=f"{CPM}, art. 38, b e §§ 1º–2º, p. 28; {A31}, slide 36.", armadilha="Tratar qualquer ordem como excludente.", tempo=2),
 dict(n=7, tipo="OBJ", nivel="N3", ctx=True, conceitos=["DIRT2-ERRO-DIREITO"],
  competencia="Aplicar o erro de direito do art. 35 e sua exceção.",
  enunciado="Um marinheiro recém-incorporado, lendo mal uma instrução, supõe sinceramente e de modo escusável que pode deixar o posto de serviço para buscar alimentação sem autorização, e o faz. Em outra situação, um civil, por erro escusável de interpretação, supõe lícito usar em evento público um distintivo militar que não lhe pertence. Sobre o art. 35 do CPM:",
  alternativas=[
   ("Para o civil, a pena pode ser atenuada ou substituída; para o marinheiro, o benefício não se aplica se o crime atentar contra o dever militar.",
    "Correta. O art. 35 exclui do benefício o crime que atente contra o dever militar. [INFERÊNCIA PEDAGÓGICA] Abandono de posto (art. 195) está no Título III da parte especial, ‘Dos crimes contra o serviço militar e o dever militar’."),
   ("Ambos ficam isentos de pena, pois o erro foi escusável.",
    "Errada. O art. 35 não isenta: permite atenuar ou substituir a pena."),
   ("Nenhum dos dois tem benefício, porque ninguém se escusa de cumprir a lei alegando que não a conhece.",
    "Errada. A LINDB (slide 32) convive com o art. 35 do CPM, que prevê atenuação/substituição."),
   ("Ambos têm a pena atenuada, pois a exceção do dever militar só vale para oficiais.",
    "Errada. A exceção é objetiva, pelo tipo de crime, e não pela graduação."),
  ], correta=0,
  comentario="O ‘erro de direito’ no CPM é causa de atenuação ou substituição, não de exclusão da culpabilidade, e tem exceção expressa.",
  fonte=f"{CPM}, art. 35, p. 26; art. 172, p. 79; art. 195, p. 88; {A31}, slides 32 e 35.", armadilha="Transformar erro de direito em isenção.", tempo=3),
 dict(n=8, tipo="OBJ", nivel="N2", ctx=True, conceitos=["DIRT2-INEXIGIBILIDADE"],
  competencia="Aplicar a restrição do art. 40 à coação irresistível.",
  enunciado="Uma sentinela abandona o posto porque um desconhecido, por telefone, ameaça divulgar fotos comprometedoras se ela não sair. Sobre a alegação de coação irresistível:",
  alternativas=[
   ("Nos crimes com violação do dever militar, só a coação física ou material pode ser invocada; ameaça moral não afasta a culpabilidade.",
    "Correta. Art. 40 do CPM (slide 37)."),
   ("A coação moral irresistível afasta a culpabilidade em qualquer crime militar.",
    "Errada. O art. 40 restringe a coação invocável nos crimes com violação do dever militar."),
   ("A coação irresistível é excludente de ilicitude.",
    "Errada. O art. 38 a trata como hipótese de ausência de culpabilidade (‘não é culpado’)."),
   ("A sentinela fica isenta porque respondem apenas os autores da coação.",
    "Errada. A regra do § 1º do art. 38 pressupõe coação apta a excluir a culpabilidade, o que o art. 40 afasta aqui."),
  ], correta=0,
  comentario="O dado ‘sentinela abandona o posto’ ativa o art. 40; ‘ameaça por telefone’ é coação moral.",
  fonte=f"{CPM}, arts. 38, a, e 40, p. 28; {A31}, slides 36–37.", armadilha="Ignorar a restrição do art. 40.", tempo=2),
 dict(n=9, tipo="OBJ", nivel="N4", ctx=True, conceitos=["DIRT2-ELEMENTOS-CRIME", "DIRT2-EXCL-ILICITUDE", "DIRT2-INEXIGIBILIDADE", "DIRT2-IMPUTABILIDADE"],
  competencia="Estratificar o crime para vários agentes e localizar em que degrau cada um é afastado.",
  enunciado="Considere: (I) o Cabo Hotel mata um invasor armado que atirava contra a guarda, usando moderadamente a arma; (II) o Sargento India aponta uma arma para a cabeça do Marinheiro Juliet e o obriga, sem qualquer possibilidade de resistência física, a quebrar o cadeado de um depósito de munição; (III) o Soldado Kilo, com doença mental que o torna inteiramente incapaz de entender o caráter ilícito, agride um colega; (IV) o Cabo Lima, sabendo que uma ordem de superior é manifestamente criminosa, a cumpre. Assinale a alternativa correta.",
  alternativas=[
   ("Em I falta ilicitude (não há crime); em II Juliet não é culpado e India responde; em III falta imputabilidade; em IV Lima é punível junto com quem ordenou.",
    "Correta. I: arts. 42, II, e 44. II: art. 38, a, e § 1º (coação que suprime a faculdade de agir). III: art. 48. IV: art. 38, § 2º."),
   ("Em I falta tipicidade; em II India e Juliet respondem igualmente; em III há crime com pena reduzida; em IV só o superior responde.",
    "Errada. I é típico (matou alguém), mas lícito; II ignora o art. 38, § 1º; III descreve incapacidade total; IV ignora o art. 38, § 2º."),
   ("Em I falta culpabilidade; em II falta ilicitude; em III falta imputabilidade; em IV falta culpabilidade.",
    "Errada. Troca os degraus em I, II e IV."),
   ("Em todos os casos há crime, mas com isenção de pena.",
    "Errada. Em I não há crime; os demais têm soluções diferentes."),
  ], correta=0,
  comentario="Mesmo formato dos exercícios do professor (slides 38–40), agora com quatro agentes e um distrator de ordem ilegal. [INFERÊNCIA PEDAGÓGICA] Em II, a arma encostada e a impossibilidade de resistir descrevem coação que suprime a faculdade de agir.",
  fonte=f"{A31}, slides 13 e 25–40; {CPM}, arts. 38, 42, 44 e 48, p. 28–31.", armadilha="Trocar o degrau (tipicidade, ilicitude, culpabilidade).", tempo=5),
 dict(n=10, tipo="OBJ", nivel="N4", ctx=True, conceitos=["DIRT2-INEXIGIBILIDADE", "DIRT2-EXCL-ILICITUDE"],
  competencia="Distinguir obediência hierárquica, estrito cumprimento do dever legal e excesso na execução.",
  enunciado="Um capitão-tenente, legitimamente responsável por uma operação de busca autorizada, ordena a um sargento que imobilize um suspeito que resiste. O sargento imobiliza o suspeito e, já dominado e algemado, desfere-lhe vários chutes ‘para aprender’. Assinale a análise correta.",
  alternativas=[
   ("A imobilização inicial pode estar amparada pelo cumprimento de dever legal e da ordem; os chutes após a dominação são excesso na execução, pelo qual o sargento é punível.",
    "Correta. A ordem lícita cobre a execução regular; o art. 38, § 2º, pune o inferior quando ‘há excesso nos atos ou na forma de execução’."),
   ("Tudo está amparado pela obediência hierárquica, pois houve ordem direta em matéria de serviço.",
    "Errada. A ordem não abrangia agressão após a dominação; há excesso."),
   ("O capitão-tenente responde pelos chutes como autor da ordem.",
    "Errada. A ordem não tinha por objeto os chutes; o § 1º do art. 38 não transfere automaticamente ao superior o excesso do inferior."),
   ("Nada está amparado, porque qualquer uso de força contra suspeito é crime.",
    "Errada. A imobilização necessária em diligência legítima pode estar coberta pelo estrito cumprimento do dever legal (art. 42, III)."),
  ], correta=0,
  comentario="O caso separa dois momentos: força necessária (lícita) e violência gratuita (excesso). A análise por momentos é o que diferencia a resposta N4.",
  fonte=f"{CPM}, art. 38, § 2º, p. 28; art. 42, III, p. 29; {A31}, slides 26 e 36.", armadilha="Estender a cobertura da ordem ao excesso.", tempo=5),
 dict(n=11, tipo="VF", nivel="N2", ctx=False, conceitos=["DIRT2-ERRO-DIREITO"],
  competencia="Relacionar a LINDB ao tratamento do erro de direito no CPM.",
  afirmacao="Como a LINDB estabelece que ninguém se escusa de cumprir a lei alegando que não a conhece, o CPM não confere nenhuma consequência ao erro escusável sobre a ilicitude do fato.",
  correta=False,
  comentario="Falsa. O CPM, art. 35, permite atenuar ou substituir a pena quando o agente supõe lícito o fato por ignorância ou erro de interpretação da lei escusáveis, salvo nos crimes que atentam contra o dever militar.",
  fonte=f"{A31}, slides 32 e 35; {CPM}, art. 35, p. 26.", armadilha="Tomar a regra da LINDB como absoluta no CPM.", tempo=1),
 dict(n=12, tipo="DIS", nivel="N3", ctx=True, conceitos=["DIRT2-IMPUTABILIDADE", "DIRT2-ELEMENTOS-CRIME"],
  competencia="Fundamentar a exclusão ou a redução pela imputabilidade.",
  contexto="Durante confraternização em uma organização militar, um cabo recebe de um colega, como ‘brincadeira’, bebida com substância que ele desconhecia. Parcialmente desorientado, mas ainda com alguma compreensão, danifica um equipamento e fere um soldado.",
  enunciado="O cabo é imputável? Qual a consequência penal? Fundamente e aponte o contrafactual que levaria à solução oposta.",
  gabarito="**Gabarito:** a embriaguez não foi voluntária: decorreu de ato de terceiro desconhecido pelo agente — caso fortuito (art. 49). Como ele não estava inteiramente incapaz, mas sem a plena capacidade de entendimento, permanece imputável e a pena pode ser reduzida de um a dois terços (parágrafo único). A análise da tipicidade e da ilicitude (danos e lesão) precede a culpabilidade (slides 13 e 38–40). Contrafactual: se a intoxicação o tornasse inteiramente incapaz de entender o caráter criminoso, seria inimputável (caput). Se ele tivesse ingerido voluntariamente, não haveria o benefício. O colega que adulterou a bebida tem responsabilidade a ser examinada à parte.\n\n**Plena:** caso fortuito, incompleta, redução, contrafactual. **Parcial:** reconhece fortuito, mas declara inimputabilidade. **Insuficiente:** afirma que embriaguez nunca afasta responsabilidade.",
  criterios=["Questão: imputabilidade e natureza da embriaguez (0,2)", "Norma: art. 49, caput e parágrafo único (0,2)", "Aplicação: fortuita e incompleta (0,3)", "Limite/contrafactual: completa ou voluntária (0,2)", "Conclusão (0,1)"],
  fonte=f"{CPM}, art. 49, p. 31; {A31}, slides 30–31 e 38–40.", armadilha="Declarar inimputável sem incapacidade total.", tempo=7),
 dict(n=13, tipo="DIS", nivel="N4", ctx=True, conceitos=["DIRT2-INEXIGIBILIDADE", "DIRT2-EXCL-ILICITUDE", "DIRT2-ERRO-DIREITO"],
  competencia="Resolver caso com ordem superior, coação e erro sobre a licitude em crime contra o dever militar.",
  contexto="O Suboficial Mike ordena ao Cabo November, sentinela do paiol, que deixe o posto por duas horas ‘para ajudar numa mudança particular’ e ameaça ‘acabar com a carreira’ de November se ele recusar. November sai, supondo que ordem de superior sempre deve ser cumprida. Na ausência, material é furtado por terceiros.",
  enunciado="Analise a responsabilidade de November quanto ao abandono do posto, examinando obediência hierárquica, coação irresistível e erro de direito. Indique a posição de Mike.",
  gabarito="**Gabarito:** (1) Obediência hierárquica (art. 38, b) exige ordem direta de superior **em matéria de serviço**; ordem para ajudar em mudança particular não é matéria de serviço, e deixar o posto é manifestamente contrário ao dever — não exclui a culpabilidade (§ 2º). (2) Coação: a ameaça à carreira é coação moral; nos crimes com violação do dever militar só se invoca coação física ou material (art. 40). (3) Erro de direito: supor que toda ordem deve ser cumprida é erro sobre a licitude; o art. 35 não se aplica a crime que atente contra o dever militar [INFERÊNCIA PEDAGÓGICA: abandono de posto integra o Título III, ‘crimes contra o serviço militar e o dever militar’]. Conclusão: November não se beneficia. Mike: como November continua culpável, a regra do art. 38, § 1º (responde só o autor da coação ou da ordem) não se aplica; Mike, que determinou e coagiu subordinado, deve ser analisado como concorrente (art. 53, com a agravante do § 2º, II ou III — tema do módulo 05) e nos tipos pertinentes. O furto por terceiros é fato distinto.\n\n**Plena:** três institutos afastados com fundamento e posição de Mike. **Parcial:** afasta obediência, mas aceita coação moral ou erro de direito. **Insuficiente:** conclui que ordem de superior exclui o crime.",
  criterios=["Questões: três teses defensivas e posição do superior (0,2)", "Normas: arts. 35, 38 b e §§, 40 (0,2)", "Aplicação: matéria particular, ameaça moral, crime contra o dever militar (0,3)", "Limites/exceções corretamente usados (0,2)", "Conclusão (0,1)"],
  fonte=f"{CPM}, arts. 35, 38, 40 e 195, p. 26–28 e 88; {A31}, slides 35–37.", armadilha="Aceitar ‘ordem é ordem’.", tempo=10),
 dict(n=14, tipo="OBJ", nivel="N3", ctx=True, conceitos=["DIRT2-ESTADO-NEC-EXCULPANTE"], modos=["completo"],
  competencia="Distinguir o estado de necessidade exculpante do justificante.",
  enunciado="Em um naufrágio, um marinheiro, para salvar o próprio irmão, retira de outro náufrago o único colete salva-vidas disponível; o outro náufrago morre. Não era exigível conduta diversa. Assinale a solução adequada no CPM.",
  alternativas=[
   ("Estado de necessidade exculpante (art. 39): não é culpado, ainda que o direito sacrificado seja igual ou superior ao protegido.",
    "Correta. O art. 39 admite sacrifício de direito ‘ainda quando superior ao direito protegido’, afastando a culpabilidade quando não era exigível conduta diversa."),
   ("Estado de necessidade justificante (art. 43): não há crime.",
    "Errada. O art. 43 exige mal causado consideravelmente inferior ao evitado; vida por vida não atende ao requisito."),
   ("Legítima defesa de terceiro.",
    "Errada. O outro náufrago não praticava agressão injusta."),
   ("Não há solução no CPM; aplica-se apenas atenuação genérica.",
    "Errada. O art. 39 trata expressamente da hipótese."),
  ], correta=0,
  comentario="[APROFUNDAMENTO ANALÍTICO DE SUPORTE] O CPM tem dois estados de necessidade: um exclui o crime (art. 43), outro a culpabilidade (art. 39). O slide trata apenas do art. 42; o art. 39 é adjacência normativa do Completo.",
  fonte=f"{CPM}, arts. 39 e 43, p. 28–29.", armadilha="Tratar todo estado de necessidade como justificante.", tempo=3),
 dict(n=15, tipo="VF", nivel="N3", ctx=True, conceitos=["DIRT2-EXCESSO"], modos=["completo"],
  competencia="Aplicar o regime do excesso nas excludentes.",
  afirmacao="Um cabo repele legitimamente uma agressão, mas, por culpa, excede os limites da necessidade e causa lesão maior que a necessária. Pelo CPM, ele responde pelo fato a título de culpa, se punível nessa forma, e não será punido se o excesso resultou de escusável surpresa ou perturbação de ânimo.",
  correta=True,
  comentario="Verdadeira. Art. 45 e parágrafo único. Se o excesso fosse doloso, o juiz poderia atenuar a pena (art. 46).",
  fonte=f"{CPM}, arts. 45–46, p. 30.", armadilha="Supor que o excesso sempre anula a excludente por inteiro e gera crime doloso.", tempo=2),
]
