from conceitos import A31, A41, A42, CPM, CPPM, CF, EM

M04 = [
 dict(n=1, tipo="VF", nivel="N1", ctx=False, conceitos=["DIRT2-ITER"],
  competencia="Reconhecer a punibilidade de cada fase do iter criminis.",
  afirmacao="Segundo a aula, os atos preparatórios, por já manifestarem a vontade criminosa, são puníveis como tentativa.",
  correta=False,
  comentario="Falsa. O slide 42 afirma que os atos preparatórios são ‘ainda impuníveis — somente indícios’; a tentativa exige início da execução (CPM art. 30, II).",
  fonte=f"{A31}, slides 41–42; {CPM}, art. 30, II, p. 25.", armadilha="Antecipar a punição para a preparação.", tempo=1),
 dict(n=2, tipo="OBJ", nivel="N2", ctx=False, conceitos=["DIRT2-TENTATIVA"],
  competencia="Conhecer a pena da tentativa no CPM, inclusive a exceção omitida no slide.",
  enunciado="Sobre a pena da tentativa no CPM, assinale a alternativa correta.",
  alternativas=[
   ("Pune-se com a pena do crime diminuída de um a dois terços, podendo o juiz, em caso de excepcional gravidade, aplicar a pena do crime consumado.",
    "Correta. Texto do art. 30, parágrafo único. O slide 44 menciona só a redução; a exceção está na lei."),
   ("Pune-se sempre com a pena do crime diminuída de um a dois terços, sem exceção.",
    "Errada. Ignora a ressalva da excepcional gravidade."),
   ("Pune-se com a metade da pena do crime consumado.",
    "Errada. A redução é variável (1/3 a 2/3), não fixa."),
   ("Não se pune a tentativa nos crimes militares, salvo previsão expressa.",
    "Errada. A regra geral do art. 30 alcança os crimes do CPM."),
  ], correta=0,
  comentario="Distrator clássico: a regra ‘sempre reduz’. Conferir a lei evita repetir a síntese incompleta do slide.",
  fonte=f"{CPM}, art. 30, parágrafo único, p. 25; {A31}, slide 44.", armadilha="Omitir a exceção da excepcional gravidade.", tempo=2),
 dict(n=3, tipo="COR", nivel="N2", ctx=True, conceitos=["DIRT2-ITER"],
  competencia="Situar condutas nas fases do iter criminis.",
  titulo="Plano de um cabo para destruir o motor de uma lancha: associe cada ato à fase",
  chaves=[("A", "Cogitação"), ("B", "Atos preparatórios"), ("C", "Início da execução"), ("D", "Consumação")],
  itens=[
   ("Durante o serviço, pensa em como inutilizar o motor sem ser descoberto.", "A"),
   ("Compra, fora da OM, um produto corrosivo.", "B"),
   ("Abre o reservatório do motor e começa a despejar o corrosivo.", "C"),
   ("O motor fica inutilizado.", "D"),
  ],
  comentario="O critério do slide 42 é o ataque ao bem jurídico: comprar o produto ainda não o ataca; despejá-lo no motor, sim.",
  fonte=f"{A31}, slides 41–43.", armadilha="Tratar a compra do meio como execução.", tempo=2),
 dict(n=4, tipo="OBJ", nivel="N2", ctx=True, conceitos=["DIRT2-TENTATIVA", "DIRT2-ITER"],
  competencia="Distinguir tentativa de crime consumado diverso.",
  enunciado="Um marinheiro, querendo matar um desafeto, dispara duas vezes contra ele. A vítima é atingida no ombro, recebe socorro rápido e sobrevive. O agressor foi contido pelos colegas antes de disparar de novo. Assinale o enquadramento.",
  alternativas=[
   ("Homicídio tentado: iniciada a execução, a morte não ocorreu por circunstâncias alheias à vontade do agente.",
    "Correta. Dolo de matar, execução iniciada e interrupção externa (contenção e socorro) — art. 30, II."),
   ("Lesão corporal consumada, porque o resultado foi apenas lesão.",
    "Errada. O enquadramento segue o dolo (matar), não apenas o resultado obtido."),
   ("Desistência voluntária, porque ele não disparou novamente.",
    "Errada. Ele não parou por vontade própria: foi contido."),
   ("Crime impossível, porque o socorro impediu a morte.",
    "Errada. O meio (arma de fogo) era eficaz e o objeto (pessoa viva) próprio."),
  ], correta=0,
  comentario="Contrafactual: se, podendo continuar, ele guardasse a arma por decisão própria, haveria desistência voluntária e responderia só pela lesão (art. 31).",
  fonte=f"{CPM}, arts. 30–32, p. 25–26; {A31}, slides 44–46.", armadilha="Enquadrar pelo resultado, não pelo dolo.", tempo=2),
 dict(n=5, tipo="OBJ", nivel="N3", ctx=True, conceitos=["DIRT2-DESIST-ARREP", "DIRT2-TENTATIVA"],
  competencia="Aferir a voluntariedade na interrupção da execução.",
  enunciado="Um cabo começa a forçar a porta do paiol para subtrair munição. (1) Na versão A, ele para porque o alarme dispara. (2) Na versão B, ninguém aparece, nada o impede, mas ele pensa na família, desiste e vai embora. Assinale a alternativa correta.",
  alternativas=[
   ("Versão A: tentativa; versão B: desistência voluntária, respondendo apenas pelos atos já praticados.",
    "Correta. A interrupção por fator externo é tentativa (art. 30, II); a interrupção por vontade própria, podendo prosseguir, é desistência voluntária (art. 31)."),
   ("Ambas são desistência voluntária, pois em ambas ele parou.",
    "Errada. Parar por causa do alarme não é voluntário no sentido do art. 31."),
   ("Ambas são tentativa, pois houve início de execução.",
    "Errada. O início da execução é comum às duas; o que as distingue é a causa da interrupção."),
   ("Versão A: crime impossível; versão B: fato atípico.",
    "Errada. Não há ineficácia absoluta do meio nem impropriedade do objeto; e em B subsistem os atos praticados (por exemplo, dano à porta)."),
  ], correta=0,
  comentario="Pergunta-chave: ‘ele podia continuar e não quis, ou quis e não pôde?’. Na desistência, os atos já praticados podem configurar outro crime.",
  fonte=f"{CPM}, arts. 30–31, p. 25; {A31}, slides 44–45.", armadilha="Confundir voluntariedade com simples parada.", tempo=3),
 dict(n=6, tipo="VF", nivel="N3", ctx=True, conceitos=["DIRT2-DESIST-ARREP"],
  competencia="Aplicar o arrependimento eficaz.",
  afirmacao="Um marinheiro solta as amarras de segurança de um colega que trabalha pendurado no costado para que ele caia no mar e se afogue. Arrependido, pula no mar, resgata o colega, que sobrevive apenas com escoriações. Pelo CPM, ele só responde pelos atos já praticados, e não por tentativa de homicídio.",
  correta=True,
  comentario="Verdadeira. Esgotada a execução, o agente impediu que o resultado se produzisse (art. 31, parte final): arrependimento eficaz. Responde pelo que já causou (as escoriações e o perigo gerado, conforme o tipo aplicável).",
  fonte=f"{CPM}, art. 31, p. 25; {A31}, slide 45.", armadilha="Punir por tentativa quem evitou o resultado.", tempo=2),
 dict(n=7, tipo="OBJ", nivel="N3", ctx=True, conceitos=["DIRT2-CRIME-IMPOSSIVEL", "DIRT2-TENTATIVA"],
  competencia="Distinguir ineficácia absoluta de ineficácia relativa do meio.",
  enunciado="Querendo matar um sargento, um soldado aperta o gatilho de uma pistola de instrução que, por construção, não tem mecanismo de disparo. Em outra ocasião, outro soldado dispara com arma verdadeira, mas a munição falha por estar velha. Assinale a alternativa correta.",
  alternativas=[
   ("No primeiro caso há crime impossível por ineficácia absoluta do meio; no segundo, tentativa, pois o meio era apenas relativamente ineficaz.",
    "Correta. A pistola inerte jamais dispararia (art. 32); a arma real com munição falha poderia disparar."),
   ("Ambos são crime impossível, pois nenhum tiro foi disparado.",
    "Errada. A falha da munição é circunstância acidental; o meio não era absolutamente ineficaz."),
   ("Ambos são tentativa, pois houve dolo e início de execução.",
    "Errada. O art. 32 afasta qualquer pena quando o meio é absolutamente ineficaz."),
   ("No primeiro caso há tentativa com pena reduzida; no segundo, desistência.",
    "Errada. Não houve desistência: o soldado quis disparar."),
  ], correta=0,
  comentario="Absoluto × relativo: pergunte se aquele meio, naquelas condições, poderia em algum momento produzir o resultado.",
  fonte=f"{CPM}, arts. 30 e 32, p. 25–26; {A31}, slides 44 e 46.", armadilha="Tratar falha acidental como impossibilidade absoluta.", tempo=3),
 dict(n=8, tipo="OBJ", nivel="N3", ctx=False, conceitos=["DIRT2-DESIST-ARREP"],
  competencia="Identificar imprecisão técnica na formulação do arrependimento eficaz.",
  enunciado="O slide 45 define arrependimento eficaz como a situação em que ‘o agente já consumou o crime pretendido, só faltando o resultado’. À luz do art. 31 e do conceito de consumação do art. 30, I, qual formulação é tecnicamente mais precisa?",
  alternativas=[
   ("O agente já praticou os atos de execução, mas impede que o resultado se produza; se houvesse consumação, não haveria o que impedir.",
    "Correta. Consumação é a reunião de todos os elementos da definição legal (art. 30, I). No arrependimento eficaz o resultado é evitado; logo não houve consumação. [POSSÍVEL ERRO NA FONTE] A expressão do slide deve ser lida como ‘esgotou a execução’."),
   ("O agente consuma o crime e depois repara o dano.",
    "Errada. Reparação após a consumação não é arrependimento eficaz do art. 31."),
   ("O agente interrompe a execução antes de terminá-la.",
    "Errada. Isso é desistência voluntária."),
   ("O agente não chega a iniciar a execução.",
    "Errada. Sem início de execução não há sequer tentativa; estamos na preparação."),
  ], correta=0,
  comentario="O próprio slide diz ‘só faltando o resultado’, o que confirma a leitura correta; a palavra ‘consumou’ é imprópria.",
  fonte=f"{A31}, slide 45; {CPM}, arts. 30, I, e 31, p. 25.", armadilha="Aceitar literalmente ‘já consumou’.", tempo=2),
 dict(n=9, tipo="OBJ", nivel="N4", ctx=True, conceitos=["DIRT2-ITER", "DIRT2-TENTATIVA", "DIRT2-DESIST-ARREP", "DIRT2-CRIME-IMPOSSIVEL"],
  competencia="Classificar vários agentes em fases e institutos distintos do iter criminis.",
  enunciado="Quatro militares, sem relação entre si, querem matar o mesmo desafeto: (I) Papa compra um veneno e o guarda no armário, sem usar; (II) Quebec coloca açúcar no café da vítima, acreditando ser um veneno fulminante; (III) Romeo dá uma facada na vítima e, quando poderia continuar, larga a faca e vai embora por decisão própria; a vítima sobrevive com lesão; (IV) Sierra dá a facada, é agarrado por um sargento e a vítima sobrevive. Assinale a alternativa correta.",
  alternativas=[
   ("I: atos preparatórios impuníveis; II: crime impossível; III: desistência voluntária, responde pela lesão; IV: tentativa de homicídio.",
    "Correta. Arts. 30–32 e slides 42–46."),
   ("I: tentativa; II: tentativa; III: tentativa; IV: tentativa.",
    "Errada. Ignora a preparação (I), a ineficácia absoluta (II) e a voluntariedade (III)."),
   ("I: impunível; II: tentativa com pena reduzida; III: arrependimento eficaz; IV: lesão corporal.",
    "Errada. Açúcar é meio absolutamente ineficaz; Romeo interrompeu a execução (desistência, não arrependimento); Sierra tinha dolo de matar."),
   ("I: crime impossível; II: fato atípico por erro; III: tentativa; IV: desistência voluntária.",
    "Errada. Troca praticamente todas as categorias."),
  ], correta=0,
  comentario="Quatro personagens, quatro institutos. Observe que ‘querer matar’ é comum a todos; o que muda é a fase e a causa da não produção do resultado.",
  fonte=f"{CPM}, arts. 30–32, p. 25–26; {A31}, slides 41–46.", armadilha="Tratar todos por igual por terem o mesmo dolo.", tempo=5),
 dict(n=10, tipo="OBJ", nivel="N4", ctx=True, conceitos=["DIRT2-DESIST-ARREP", "DIRT2-TENTATIVA", "DIRT2-CRIME-IMPOSSIVEL"],
  competencia="Aplicar contrafactuais sobre o momento e a eficácia da atuação do agente.",
  enunciado="Um cabo corta quase todo o cabo de segurança do cinto de um marinheiro que subirá ao mastro. Variações: (A) antes de o marinheiro subir, o cabo avisa o encarregado, que troca o equipamento; (B) o marinheiro sobe, o cabo parcialmente cortado rompe e ele cai, mas é salvo pela rede de proteção instalada por terceiros; (C) o cabo descobre depois que o marinheiro jamais usaria aquele cinto, pois havia sido dispensado da faina desde a véspera; (D) antes de o marinheiro subir, um sargento percebe o corte e troca o equipamento. Assinale a correspondência correta.",
  alternativas=[
   ("A: arrependimento eficaz; B: tentativa; C: [PONTO DE INCERTEZA] depende de o objeto ser absolutamente impróprio no momento da conduta; D: tentativa.",
    "Correta. A: esgotou a execução e impediu o resultado por ação própria (art. 31). B e D: o resultado não ocorreu por circunstâncias alheias (art. 30, II). C: o enunciado não permite afirmar, sem mais dados, se a vítima já estava fora de qualquer possibilidade de uso (impropriedade absoluta, art. 32) — a resposta precisa declarar o dado faltante."),
   ("A: desistência voluntária; B: crime impossível; C: tentativa; D: arrependimento eficaz.",
    "Errada. Em A a execução estava esgotada; B não tem meio ineficaz; D não teve atuação do agente."),
   ("A: tentativa; B: tentativa; C: crime impossível; D: tentativa.",
    "Errada. Ignora a atuação eficaz do próprio agente em A e trata C como certo sem os dados necessários."),
   ("A: arrependimento eficaz; B: lesão consumada; C: fato atípico; D: desistência voluntária.",
    "Errada. B segue o dolo de matar; em D o agente não desistiu."),
  ], correta=0,
  comentario="A alternativa correta explicita a incerteza em C, conforme o padrão de fundamentação: lacuna fática se declara, não se preenche.",
  fonte=f"{CPM}, arts. 30–32, p. 25–26; {A31}, slides 44–46.", armadilha="Chamar de arrependimento eficaz a intervenção de terceiro.", tempo=5),
 dict(n=11, tipo="VF", nivel="N2", ctx=False, conceitos=["DIRT2-DESIST-ARREP"],
  competencia="Reconhecer a consequência da desistência voluntária.",
  afirmacao="Na desistência voluntária, o agente responde pela tentativa do crime pretendido, com a pena reduzida de um a dois terços.",
  correta=False,
  comentario="Falsa. O art. 31 determina que o agente ‘só responde pelos atos já praticados’; não há punição por tentativa do crime visado.",
  fonte=f"{CPM}, art. 31, p. 25; {A31}, slide 45.", armadilha="Aplicar a pena da tentativa à desistência.", tempo=1),
 dict(n=12, tipo="OBJ", nivel="N2", ctx=True, conceitos=["DIRT2-ITER"],
  competencia="Fixar o início da execução pelo ataque ao bem jurídico.",
  enunciado="Com base no exemplo do homicídio desenvolvido no slide 43, em qual momento, no caso a seguir, começa a execução punível? Um marinheiro decide matar um colega, pede emprestada uma faca ao cozinheiro, espera o colega sair do rancho, aproxima-se por trás e ergue a faca para golpeá-lo, sendo contido.",
  alternativas=[
   ("Quando se aproxima e ergue a faca contra o colega, ameaçando concretamente a vida.",
    "Correta. É o paralelo com ‘aponta-lhe o revólver’ do slide 43."),
   ("Quando decide matar.", "Errada. Cogitação é impunível."),
   ("Quando pede a faca emprestada.", "Errada. Obter o instrumento é ato preparatório."),
   ("Quando espera o colega sair do rancho.", "Errada. Ainda não há ataque ao bem jurídico."),
  ], correta=0,
  comentario="Sendo contido, responde por tentativa de homicídio. O cozinheiro que emprestou a faca só teria relevância se soubesse do plano (concurso de agentes — módulo 05).",
  fonte=f"{A31}, slides 42–43; {CPM}, art. 30, II, p. 25.", armadilha="Antecipar a execução para a obtenção do meio.", tempo=2),
 dict(n=13, tipo="DIS", nivel="N3", ctx=True, conceitos=["DIRT2-DESIST-ARREP", "DIRT2-TENTATIVA"],
  competencia="Fundamentar a distinção entre tentativa, desistência e arrependimento com contrafactual.",
  contexto="Um sargento, com intenção de matar, coloca um artefato incendiário na cabine de um colega e aciona o temporizador. Minutos depois, arrependido, retorna, desliga o artefato e o retira. O colega nunca soube do fato; houve apenas um pequeno dano no piso.",
  enunciado="Enquadre a conduta, fundamente e explique como a solução mudaria se (a) o artefato fosse desligado por um marinheiro que passava ou (b) o sargento desistisse antes de acionar o temporizador.",
  gabarito="**Gabarito:** acionado o temporizador, a execução estava esgotada; o sargento impediu o resultado por ação própria — arrependimento eficaz (art. 31, parte final). Responde apenas pelos atos praticados (o dano ao piso e o que mais se configurar), não por tentativa de homicídio. (a) Se um terceiro desligasse, o resultado não ocorreria por circunstância alheia: tentativa (art. 30, II), com pena reduzida de 1/3 a 2/3, salvo excepcional gravidade. (b) Se desistisse antes de acionar, interromperia a execução em curso: desistência voluntária (art. 31, primeira parte), também respondendo pelos atos já praticados.\n\n**Plena:** distingue os três institutos pelo critério ‘quem impediu’ e ‘em que momento’. **Parcial:** acerta o caso principal, mas chama (b) de arrependimento. **Insuficiente:** conclui por tentativa de homicídio no caso principal.",
  criterios=["Questão: interrupção da execução e causa do não resultado (0,2)", "Norma: arts. 30, II, e 31 (0,2)", "Aplicação ao caso principal (0,3)", "Contrafactuais (a) e (b) corretos (0,2)", "Conclusão (0,1)"],
  fonte=f"{CPM}, arts. 30–31, p. 25; {A31}, slides 44–45.", armadilha="Tentativa × arrependimento eficaz.", tempo=7),
 dict(n=14, tipo="DIS", nivel="N4", ctx=True, conceitos=["DIRT2-CRIME-IMPOSSIVEL", "DIRT2-TENTATIVA", "DIRT2-ITER"],
  competencia="Resolver caso com crime impossível, tentativa e atos preparatórios, declarando o dado decisivo.",
  contexto="O Cabo Tango planeja explodir um gerador da OM. Em segredo, compra detonadores em um site. No dia marcado, instala o conjunto e aciona. Nada acontece. A perícia constata dois fatos: os detonadores eram réplicas de brinquedo, vendidas como tal; e o gerador estava desmontado para manutenção, mas a destruição da carcaça seria possível com explosivo verdadeiro.",
  enunciado="Tango responde por tentativa? Analise meio e objeto separadamente, indique o dispositivo e a consequência.",
  gabarito="**Gabarito:** compra dos detonadores = ato preparatório. Instalar e acionar = início da execução. Meio: réplicas de brinquedo não podem, em nenhuma circunstância, produzir explosão — ineficácia absoluta do meio. Objeto: a carcaça do gerador podia ser destruída — não há impropriedade absoluta do objeto. Basta a ineficácia absoluta de um dos dois (art. 32: ‘ineficácia absoluta do meio **ou** absoluta impropriedade do objeto’) para que seja impossível consumar o crime: nenhuma pena é aplicável. Não há tentativa. Contrafactual: com detonadores verdadeiros que falhassem por defeito, o meio seria relativamente ineficaz e haveria tentativa. A análise disciplinar é independente.\n\n**Plena:** separa meio e objeto, aplica a alternatividade do art. 32 e formula o contrafactual. **Parcial:** chega a crime impossível, mas pelo objeto (errado). **Insuficiente:** conclui por tentativa porque houve dolo.",
  criterios=["Questão: tentativa ou crime impossível (0,2)", "Norma: arts. 30, II, e 32 (0,2)", "Aplicação separada ao meio e ao objeto (0,3)", "Limite: absoluto × relativo e contrafactual (0,2)", "Conclusão (0,1)"],
  fonte=f"{CPM}, arts. 30 e 32, p. 25–26; {A31}, slides 41–46.", armadilha="Exigir meio e objeto ineficazes ao mesmo tempo.", tempo=9),
]

M05 = [
 dict(n=1, tipo="VF", nivel="N1", ctx=False, conceitos=["DIRT2-CONCURSO-MONISTA"],
  competencia="Reconhecer a teoria adotada pelo CPM no concurso de agentes.",
  afirmacao="O CPM adota a teoria monista: quem, de qualquer modo, concorre para o crime incide nas penas a este cominadas.",
  correta=True,
  comentario="Verdadeira. Art. 53, caput, apresentado no slide 49 como expressão da teoria monista.",
  fonte=f"{CPM}, art. 53, caput, p. 32; {A31}, slides 48–49.", armadilha="Confundir com a teoria pluralista.", tempo=1),
 dict(n=2, tipo="OBJ", nivel="N2", ctx=False, conceitos=["DIRT2-AGRAVANTES-CABECAS"],
  competencia="Aplicar a regra dos cabeças quando há oficiais entre os agentes.",
  enunciado="Quando um crime é cometido por inferiores e um ou mais oficiais, o CPM considera cabeças:",
  alternativas=[
   ("os oficiais, bem como os inferiores que exercem função de oficial.",
    "Correta. Art. 53, § 5º."),
   ("apenas quem efetivamente dirigiu a ação, seja oficial ou praça.",
    "Errada. Essa é a regra geral do § 4º para crimes de autoria coletiva necessária; o § 5º cria a presunção para oficiais."),
   ("o mais antigo dentre todos os agentes.", "Errada. A lei não usa o critério de antiguidade isolada."),
   ("somente os oficiais que instigaram a ação.", "Errada. O § 5º não exige instigação e inclui inferiores em função de oficial."),
  ], correta=0,
  comentario="Os §§ 4º e 5º convivem: o § 4º define cabeças pela conduta (dirigir, provocar, instigar, excitar) nos crimes de autoria coletiva necessária; o § 5º acrescenta a regra dos oficiais.",
  fonte=f"{CPM}, art. 53, §§ 4º–5º, p. 33; {A31}, slide 54.", armadilha="Esquecer os inferiores em função de oficial.", tempo=2),
 dict(n=3, tipo="COR", nivel="N2", ctx=True, conceitos=["DIRT2-AGRAVANTES-CABECAS"],
  competencia="Associar situações às agravantes do art. 53, § 2º.",
  titulo="Associe a conduta ao inciso do art. 53, § 2º",
  chaves=[("I", "Promove, organiza ou dirige a cooperação"), ("II", "Coage outrem à execução material"), ("III", "Instiga ou determina alguém sujeito à sua autoridade"), ("IV", "Executa ou participa mediante paga ou promessa")],
  itens=[
   ("Suboficial manda um marinheiro de sua divisão subtrair peças, e ele obedece.", "III"),
   ("Cabo aceita dinheiro para vigiar a porta durante o furto.", "IV"),
   ("Sargento distribui tarefas e horários entre os três participantes.", "I"),
   ("Tenente ameaça gravemente um soldado para que ele arrombe o cofre.", "II"),
  ],
  comentario="Os incisos descrevem papéis que tornam mais reprovável a contribuição; a agravação incide sobre o agente que ocupa o papel.",
  fonte=f"{CPM}, art. 53, § 2º, p. 32–33; {A31}, slide 53.", armadilha="Confundir organizar (I) com determinar subordinado (III).", tempo=2),
 dict(n=4, tipo="OBJ", nivel="N2", ctx=True, conceitos=["DIRT2-AUTORIA-PARTICIPACAO"],
  competencia="Distinguir autor e partícipe e a consequência da participação de somenos importância.",
  enunciado="Dois marinheiros furtam equipamentos de um depósito da OM. Um deles realiza a subtração; o outro apenas indica o horário da troca da guarda, sem entrar no depósito. Assinale a alternativa correta.",
  alternativas=[
   ("Quem subtrai é autor; quem apenas indicou o horário é partícipe e responde pelo mesmo crime, podendo ter a pena atenuada se sua participação for de somenos importância.",
    "Correta. Slide 50 e art. 53, caput e § 3º."),
   ("Só quem subtraiu responde, pois o outro não realizou a conduta típica.",
    "Errada. Pela teoria monista, quem de qualquer modo concorre incide nas penas do crime."),
   ("Ambos são autores com a mesma pena obrigatoriamente.",
    "Errada. O § 3º permite atenuação para participação de somenos importância."),
   ("O que indicou o horário responde por crime autônomo de favorecimento.",
    "Errada. A monista mantém um só crime para todos os concorrentes."),
  ], correta=0,
  comentario="Autor realiza a conduta típica; partícipe contribui sem realizá-la. A diferença não gera crimes diferentes, mas pode gerar penas diferentes.",
  fonte=f"{CPM}, art. 53, caput e § 3º, p. 32–33; {A31}, slide 50.", armadilha="Supor impunidade do partícipe.", tempo=2),
 dict(n=5, tipo="OBJ", nivel="N3", ctx=True, conceitos=["DIRT2-COAUTORIA-LIMITES", "DIRT2-CRIME-163"],
  competencia="Reconhecer crime de autoria coletiva necessária.",
  enunciado="Um único marinheiro, em sua estação, recusa-se a cumprir ordem de serviço dada pelo sargento. No dia seguinte, doze marinheiros reúnem-se no convés e, em conjunto, negam-se a cumprir a mesma ordem. Assinale a análise mais adequada.",
  alternativas=[
   ("A recusa isolada pode configurar insubordinação (art. 163); a reunião de militares recusando obediência em conjunto pode configurar motim, crime de autoria coletiva necessária (art. 149).",
    "Correta. O motim exige pluralidade (‘reunirem-se militares’); a recusa individual é enquadrada em outro tipo."),
   ("Ambos os fatos são motim, pois houve recusa de ordem.",
    "Errada. Um só agente não ‘se reúne’; motim é de autoria coletiva necessária."),
   ("Ambos os fatos são insubordinação em coautoria.",
    "Errada. Doze militares reunidos em recusa conjunta ajustam-se ao tipo coletivo do art. 149."),
   ("O segundo fato é apenas transgressão disciplinar, porque não houve violência.",
    "Errada. O art. 149, II e III, dispensa violência quando há recusa conjunta de obediência."),
  ], correta=0,
  comentario="[INFERÊNCIA PEDAGÓGICA] O texto do art. 149 pede reunião de militares com uma das condutas dos incisos; a exigência de pluralidade decorre do núcleo ‘reunirem-se’, apresentado no slide 52 como exemplo de autoria coletiva necessária.",
  fonte=f"{CPM}, arts. 149 e 163, p. 73 e 77; {A31}, slides 52 e 69.", armadilha="Chamar de motim a recusa individual.", tempo=3),
 dict(n=6, tipo="VF", nivel="N3", ctx=True, conceitos=["DIRT2-COAUTORIA-LIMITES", "DIRT2-CONCURSO-MONISTA"],
  competencia="Aplicar a vedação de coautoria em crimes que só o próprio agente pode praticar.",
  afirmacao="Dois marinheiros de navios diferentes combinam ausentar-se sem licença e ficam fora por mais de oito dias. Como planejaram juntos, são coautores de um único crime de deserção.",
  correta=False,
  comentario="Falsa. O slide 51 lista a deserção entre os crimes que não admitem coautoria: cada militar se ausenta da ‘unidade em que serve’ (art. 187) e realiza a própria deserção. [INFERÊNCIA PEDAGÓGICA] O ajuste não une as condutas em um só crime de coautoria; eventual participação de terceiro (por exemplo, instigação) é questão diversa, a ser examinada pelo art. 53.",
  fonte=f"{A31}, slide 51; {CPM}, art. 187, p. 85; art. 53, p. 32.", armadilha="Tratar ajuste prévio como coautoria em crime que só o próprio agente pratica.", tempo=2),
 dict(n=7, tipo="OBJ", nivel="N3", ctx=True, conceitos=["DIRT2-AGRAVANTES-CABECAS", "DIRT2-AUTORIA-PARTICIPACAO"],
  competencia="Aplicar agravantes e atenuante em concurso com papéis distintos.",
  enunciado="Um sargento convence um cabo de sua divisão a destruir documentos da OM. Um terceiro militar, que não pertence à divisão, aceita dinheiro para desligar as câmeras. Um quarto, amigo do cabo, apenas empresta uma lanterna, sabendo do plano. Assinale a alternativa correta.",
  alternativas=[
   ("O sargento tem a pena agravada por determinar subordinado; o que desligou as câmeras, por participar mediante paga; o que emprestou a lanterna pode ter a pena atenuada por participação de somenos importância.",
    "Correta. Art. 53, § 2º, III e IV, e § 3º."),
   ("Todos respondem com a mesma pena, pela teoria monista.",
    "Errada. A monista unifica o crime, não as penas: agravantes e atenuantes individualizam."),
   ("Só o cabo responde, porque foi o único a destruir os documentos.",
    "Errada. Quem concorre de qualquer modo incide nas penas."),
   ("O sargento tem a pena atenuada porque não executou o ato.",
    "Errada. Instigar subordinado é agravante, não atenuante."),
  ], correta=0,
  comentario="Relacione cada agente a um papel antes de pensar em pena; o enunciado traz um papel por inciso.",
  fonte=f"{CPM}, art. 53, §§ 2º–3º, p. 32–33; {A31}, slides 50 e 53.", armadilha="Achar que a monista iguala penas.", tempo=3),
 dict(n=8, tipo="OBJ", nivel="N3", ctx=True, conceitos=["DIRT2-AGRAVANTES-CABECAS", "DIRT2-COAUTORIA-LIMITES"],
  competencia="Identificar cabeças em crime coletivo com participação de oficial.",
  enunciado="Oito praças ocupam armadas o hangar de uma base, em desobediência a ordem superior. Um primeiro-tenente presente adere ao grupo sem dar ordens; um sargento, que naquela noite exercia a função de oficial de serviço, também adere; um cabo discursa incitando os demais. Quem são os cabeças?",
  alternativas=[
   ("O primeiro-tenente e o sargento em função de oficial, pelo § 5º, e o cabo que incitou, pelo § 4º.",
    "Correta. O § 5º alcança oficiais e inferiores em função de oficial; o § 4º, quem dirige, provoca, instiga ou excita a ação."),
   ("Somente o cabo, pois foi o único a incitar.",
    "Errada. Ignora a regra do § 5º."),
   ("Somente o primeiro-tenente, por ser o único oficial.",
    "Errada. Ignora o sargento em função de oficial e o cabo que incitou."),
   ("Ninguém, pois não houve violência contra superior.",
    "Errada. A ocupação de hangar em desobediência é conduta do art. 149, IV; estando armados, pode configurar a revolta (parágrafo único)."),
  ], correta=0,
  comentario="A presença de oficiais transforma a identificação dos cabeças: não é preciso provar liderança efetiva do oficial.",
  fonte=f"{CPM}, art. 53, §§ 4º–5º, p. 33; art. 149, IV e parágrafo único, p. 73; {A31}, slides 52 e 54.", armadilha="Exigir liderança efetiva do oficial.", tempo=3),
 dict(n=9, tipo="OBJ", nivel="N4", ctx=True, conceitos=["DIRT2-CONCURSO-MONISTA", "DIRT2-AUTORIA-PARTICIPACAO", "DIRT2-AGRAVANTES-CABECAS", "DIRT2-DESIST-ARREP"],
  competencia="Integrar concurso de agentes e desistência voluntária com vários agentes.",
  enunciado="Um sargento organiza com três cabos o furto de combustível da OM. Cabo Uniform aceita promessa de pagamento para dirigir o caminhão; Cabo Victor fica de vigia; Cabo Whiskey, que deveria abrir o tanque, desiste por decisão própria antes de começar e avisa que não participará, sem avisar ninguém de fora. Os demais executam o furto. Assinale a alternativa correta.",
  alternativas=[
   ("O sargento responde com agravante por organizar; Uniform, com agravante por paga; Victor responde pelo mesmo crime como partícipe; a situação de Whiskey exige verificar se sua contribuição anterior (ajuste e informações) concorreu para o crime consumado, pois a desistência voluntária do art. 31 se refere à própria execução.",
    "Correta. Aplica art. 53, § 2º, I e IV, e caput; e não transfere automaticamente a Whiskey o benefício do art. 31, que exige desistir da execução — o crime foi consumado pelos demais. O ponto de Whiskey depende do que ele efetivamente contribuiu."),
   ("Todos respondem igualmente, inclusive Whiskey, sem agravantes, pela teoria monista.",
    "Errada. Ignora as agravantes e presume a contribuição de Whiskey sem análise."),
   ("Whiskey não responde em nenhuma hipótese, porque desistiu voluntariamente.",
    "Errada. A desistência voluntária impede a consumação pelo próprio agente; aqui o crime se consumou por obra dos demais. A relevância de sua contribuição prévia precisa ser examinada."),
   ("O sargento não responde, porque não esteve no local.",
    "Errada. Organizar a cooperação é concorrer para o crime, com agravante."),
  ], correta=0,
  comentario="[INFERÊNCIA PEDAGÓGICA] O slide não trata da desistência de um coautor em crime consumado pelos demais; a questão exige declarar o dado decisivo (efetiva contribuição) em vez de adotar uma solução automática.",
  fonte=f"{CPM}, arts. 31 e 53, p. 25 e 32–33; {A31}, slides 45 e 49–53.", armadilha="Estender a desistência voluntária a quem apenas se retirou do plano.", tempo=6),
 dict(n=10, tipo="OBJ", nivel="N4", ctx=True, conceitos=["DIRT2-COAUTORIA-LIMITES", "DIRT2-AGRAVANTES-CABECAS", "DIRT2-CONCURSO-MONISTA"],
  competencia="Distinguir crime coletivo, crime que não admite coautoria e agravantes em um único episódio.",
  enunciado="Em um navio: (I) seis marinheiros, reunidos, negam-se em conjunto a obedecer ao imediato; (II) um capitão-tenente presente não participa, mas nada faz; (III) dois desses marinheiros, dias depois, ausentam-se sem licença por dez dias, cada um de seu navio; (IV) um cabo pagou a um dos marinheiros para que aderisse à recusa. Assinale a alternativa correta.",
  alternativas=[
   ("I pode ser motim; em IV o cabo concorre para o motim e quem aderiu mediante promessa tem a pena agravada; III são deserções de cada um, sem coautoria; II depende de tipo específico sobre omissão de oficial, que não integra os slides.",
    "Correta. I: art. 149; IV: art. 53 caput e § 2º, IV (executa ou participa mediante paga); III: slide 51; II: a omissão de quem presencia o motim é tratada em outro tipo (CPM art. 151, ‘omissão de lealdade militar’, p. 74), que não integra os slides — o § 5º do art. 53 não se aplica a quem não participou."),
   ("I é insubordinação individual de cada um; II é cabeça; III é coautoria em deserção; IV é atípico.",
    "Errada. Troca o tipo coletivo, presume liderança do oficial omisso sem base no recorte, admite coautoria em deserção e ignora o concurso do cabo."),
   ("I é motim; II é cabeça pelo § 5º; III é coautoria; IV é partícipe com pena atenuada.",
    "Errada. O § 5º pressupõe oficial entre os que cometem o crime; o CT não participou. Deserção não admite coautoria."),
   ("I é transgressão; II é atípico; III é um único crime continuado; IV é agravante do sargento.",
    "Errada. Não há base para essas qualificações."),
  ], correta=0,
  comentario="[LACUNA DE COBERTURA] O art. 151 do CPM (omissão de lealdade militar) não está nos slides; o curso apenas o identifica como limite, sem ensiná-lo nem cobrá-lo.",
  fonte=f"{CPM}, arts. 53 e 149, p. 32–33 e 73; {A31}, slides 49–54.", armadilha="Aplicar o § 5º a oficial que não participou.", tempo=6),
 dict(n=11, tipo="VF", nivel="N2", ctx=False, conceitos=["DIRT2-CONCURSO-MONISTA", "DIRT2-AUTORIA-PARTICIPACAO"],
  competencia="Distinguir unidade de crime e individualização de pena no concurso.",
  afirmacao="Por adotar a teoria monista, o CPM impede qualquer diferença de pena entre autor e partícipe.",
  correta=False,
  comentario="Falsa. A monista unifica o crime; o § 3º do art. 53 atenua a pena de quem teve participação de somenos importância, e o § 2º agrava a de quem ocupa certos papéis.",
  fonte=f"{CPM}, art. 53, §§ 2º–3º, p. 32–33; {A31}, slides 49–50.", armadilha="Monista = penas iguais.", tempo=1),
 dict(n=12, tipo="DIS", nivel="N3", ctx=True, conceitos=["DIRT2-AUTORIA-PARTICIPACAO", "DIRT2-AGRAVANTES-CABECAS"],
  competencia="Fundamentar a responsabilidade de cada concorrente.",
  contexto="Um suboficial determina que dois marinheiros de sua divisão retirem, sem autorização, baterias do estoque e as coloquem em seu carro. Um cabo de outra divisão, sabendo do plano, apenas segura a porta do depósito.",
  enunciado="Indique o papel de cada agente no concurso e os efeitos sobre a pena, com fundamento.",
  gabarito="**Gabarito:** trata-se de um só crime para todos (art. 53, caput — teoria monista). Os marinheiros realizam a subtração: autores. O suboficial determina a prática a subordinados: concorre para o crime com a agravante do § 2º, III (instiga ou determina alguém sujeito à sua autoridade). O cabo que segura a porta é partícipe (slide 50); se sua contribuição for de somenos importância, a pena é atenuada (§ 3º). Limite: a qualificação do crime em espécie e se é crime militar (art. 9º) são etapas posteriores; a obediência dos marinheiros à ordem não os exime, pois a ordem não é matéria de serviço e é manifestamente criminosa (art. 38, § 2º).\n\n**Plena:** papel + consequência de cada um + limite da obediência. **Parcial:** acerta papéis, mas omite agravante/atenuante. **Insuficiente:** afirma que só os executores respondem.",
  criterios=["Questão: papéis no concurso (0,2)", "Normas: art. 53 caput, §§ 2º III e 3º (0,2)", "Aplicação a cada agente (0,3)", "Limite: obediência hierárquica não exime (0,2)", "Conclusão (0,1)"],
  fonte=f"{CPM}, arts. 38 e 53, p. 28 e 32–33; {A31}, slides 49–53.", armadilha="Ignorar a agravante do superior.", tempo=7),
 dict(n=13, tipo="DIS", nivel="N4", ctx=True, conceitos=["DIRT2-COAUTORIA-LIMITES", "DIRT2-AGRAVANTES-CABECAS", "DIRT2-CONCURSO-MONISTA"],
  competencia="Construir resposta sobre crime coletivo, cabeças e limites da coautoria.",
  contexto="Em uma base, dez praças reúnem-se e ocupam, armadas, o paiol em desobediência a ordem superior. Entre elas está um sargento que exercia, naquele dia, a função de oficial de serviço. Um marinheiro discursa convocando os colegas. Dois cabos que participaram da ocupação ausentam-se da base, juntos, por nove dias logo depois.",
  enunciado="Enquadre a ocupação, identifique os cabeças e analise a ausência dos dois cabos quanto à possibilidade de coautoria.",
  gabarito="**Gabarito:** a ocupação de paiol por militares reunidos, em desobediência a ordem superior, ajusta-se ao art. 149, IV; estando armados, à forma do parágrafo único (revolta), com aumento de um terço para os cabeças. É crime de autoria coletiva necessária (slide 52). Cabeças: o sargento em função de oficial (§ 5º do art. 53) e o marinheiro que provoca/instiga/excita a ação (§ 4º). Ausência dos cabos: cada um realiza a própria deserção (art. 187 — mais de oito dias); deserção não admite coautoria (slide 51), ainda que tenham saído juntos. Limite: a análise de cada deserção é individual; o ajuste não cria crime único.\n\n**Plena:** tipo e forma armada, cabeças pelos dois parágrafos, deserções individuais. **Parcial:** acerta o motim, mas identifica apenas um cabeça ou admite coautoria na deserção. **Insuficiente:** enquadra tudo como transgressão ou insubordinação individual.",
  criterios=["Questões: tipo coletivo, cabeças, coautoria na deserção (0,2)", "Normas: arts. 149 IV e p. único; 53 §§ 4º–5º; 187 (0,2)", "Aplicação aos agentes (0,3)", "Limite: deserção individual; § 5º para inferior em função de oficial (0,2)", "Conclusão (0,1)"],
  fonte=f"{CPM}, arts. 53, 149 e 187, p. 32–33, 73 e 85; {A31}, slides 51–54.", armadilha="Um só cabeça; coautoria em deserção.", tempo=10),
 dict(n=14, tipo="OBJ", nivel="N3", ctx=True, conceitos=["DIRT2-COMUNICABILIDADE"], modos=["completo"],
  competencia="Aplicar a incomunicabilidade das circunstâncias pessoais e a impunibilidade do ajuste não tentado.",
  enunciado="(I) Um civil e um militar da ativa ajustam um crime, mas desistem antes de qualquer ato de execução. (II) Em outro caso, um marinheiro reincidente e um cabo primário cometem juntos um crime. Assinale a alternativa correta.",
  alternativas=[
   ("Em I, o ajuste não é punível se o crime não chega a ser tentado; em II, condições pessoais não se comunicam, salvo quando elementares do crime.",
    "Correta. Art. 54 e art. 53, § 1º."),
   ("Em I, ambos respondem por tentativa; em II, a reincidência se estende ao cabo.",
    "Errada. Sem início de execução não há tentativa; circunstância pessoal não elementar não se comunica."),
   ("Em I, só o militar responde; em II, ambos têm a mesma culpabilidade.",
    "Errada. O art. 54 não distingue; a culpabilidade é individual (§ 1º)."),
   ("Em I, há crime autônomo de ajuste; em II, a comunicação é automática pela teoria monista.",
    "Errada. Não há crime autônomo e a monista não comunica condições pessoais."),
  ], correta=0,
  comentario="[APROFUNDAMENTO ANALÍTICO DE SUPORTE] Dispositivos do CPM adjacentes ao art. 53 que não constam dos slides; úteis para resolver casos com vários agentes.",
  fonte=f"{CPM}, art. 53, § 1º, p. 32; art. 54, p. 33.", armadilha="Comunicar condição pessoal.", tempo=3),
]

M06 = [
 dict(n=1, tipo="VF", nivel="N1", ctx=False, conceitos=["DIRT2-CRIME-MILITAR-CONCEITO"],
  competencia="Reconhecer o critério legal de definição do crime militar.",
  afirmacao="Crimes militares são as infrações penais que se amoldam ao disposto no art. 9º ou no art. 10 do CPM.",
  correta=True,
  comentario="Verdadeira. É a definição do slide 55. O crime militar é definido pela lei (CF art. 124), e a porta de entrada é o art. 9º (paz) ou 10 (guerra).",
  fonte=f"{A31}, slide 55; {CPM}, arts. 9º–10, p. 18–21.", armadilha="Definir pela qualidade de militar do agente.", tempo=1),
 dict(n=2, tipo="OBJ", nivel="N2", ctx=False, conceitos=["DIRT2-ART9-II"],
  competencia="Identificar o requisito de lugar em cada alínea do art. 9º, II.",
  enunciado="No art. 9º, II, do CPM, em qual alínea o texto exige expressamente que o crime ocorra em lugar sujeito à administração militar?",
  alternativas=[
   ("Alínea ‘b’: militar em atividade contra militar da reserva, reformado, assemelhado ou civil.",
    "Correta. É a única das alíneas do inciso II que menciona ‘em lugar sujeito à administração militar’ como requisito."),
   ("Alínea ‘a’: militar em atividade contra militar na mesma situação.",
    "Errada. A alínea ‘a’ não menciona lugar."),
   ("Alínea ‘c’: militar em serviço ou em razão da função.",
    "Errada. A alínea ‘c’ diz ‘ainda que fora do lugar sujeito à administração militar’."),
   ("Alínea ‘e’: contra o patrimônio sob a administração militar.",
    "Errada. A alínea ‘e’ se refere ao patrimônio ou à ordem administrativa militar, não ao lugar do fato."),
  ], correta=0,
  comentario="Mapa rápido: a (ativa × ativa), b (lugar), c (serviço/função, dispensa lugar), d (manobras/exercício), e (patrimônio/ordem administrativa).",
  fonte=f"{CPM}, art. 9º, II, a–e, p. 18–19; {A31}, slide 61.", armadilha="Exigir lugar na alínea ‘a’.", tempo=2),
 dict(n=3, tipo="COR", nivel="N2", ctx=True, conceitos=["DIRT2-ART9-I", "DIRT2-ART9-II", "DIRT2-ART9-III"],
  competencia="Enquadrar fatos no inciso e alínea do art. 9º.",
  titulo="Associe o fato ao enquadramento do art. 9º do CPM",
  chaves=[("A", "Art. 9º, I"), ("B", "Art. 9º, II, ‘c’"), ("C", "Art. 9º, II, ‘e’"), ("D", "Art. 9º, III, ‘a’")],
  itens=[
   ("Civil subtrai combustível de tanque sob administração da Marinha.", "D"),
   ("Militar da ativa desvia material de consumo da própria OM.", "C"),
   ("Qualquer pessoa pratica crime que só o CPM define.", "A"),
   ("Militar em serviço de patrulha, fora da área militar, agride um civil.", "B"),
  ],
  comentario="Pergunte na ordem: o tipo é exclusivo do CPM (I)? O agente é militar da ativa (II) ou da reserva/reformado/civil (III)? Qual circunstância da alínea está presente?",
  fonte=f"{CPM}, art. 9º, I–III, p. 18–19; {A31}, slides 60–62.", armadilha="Enquadrar civil no inciso II.", tempo=3),
 dict(n=4, tipo="OBJ", nivel="N2", ctx=True, conceitos=["DIRT2-PROPRIO-IMPROPRIO"],
  competencia="Distinguir crime militar de crime propriamente militar.",
  enunciado="Comparando os exemplos usados em aula — furto simples (art. 240) e deserção (art. 187) —, assinale a alternativa correta.",
  alternativas=[
   ("A deserção é crime propriamente militar, pois só militar pode praticá-la; o furto pode ser crime militar se enquadrado no art. 9º, mas também existe na lei penal comum.",
    "Correta. É a distinção dos slides 56–58."),
   ("Ambos são propriamente militares porque estão no CPM.",
    "Errada. Estar no CPM não torna o crime propriamente militar."),
   ("O furto é propriamente militar quando praticado em quartel.",
    "Errada. O lugar pode torná-lo crime militar (art. 9º), não propriamente militar."),
   ("A deserção só é crime militar quando praticada em tempo de guerra.",
    "Errada. O art. 187 é crime de tempo de paz."),
  ], correta=0,
  comentario="[APROFUNDAMENTO ANALÍTICO DE SUPORTE] A distinção tem efeito constitucional: a CF, art. 5º, LXI, ressalva a prisão sem flagrante ou ordem judicial nos casos de transgressão militar ou crime propriamente militar.",
  fonte=f"{A31}, slides 56–58; {CPM}, arts. 187 e 240, p. 85 e 107; {CF}, art. 5º, LXI, p. 18.", armadilha="‘Está no CPM’ = propriamente militar.", tempo=2),
 dict(n=5, tipo="OBJ", nivel="N3", ctx=True, conceitos=["DIRT2-ART9-II"],
  competencia="Aplicar a alínea ‘c’ do art. 9º, II, fora de área militar.",
  enunciado="Uma patrulha naval, em missão de apoio a uma cidade atingida por enchente, está no centro urbano. Um cabo da patrulha, em serviço, agride um civil que o insultou. Fora do serviço, na mesma noite, outro cabo agride um civil em um bar. Assinale a alternativa correta.",
  alternativas=[
   ("A agressão do cabo em serviço é crime militar pela alínea ‘c’ do art. 9º, II, mesmo fora de lugar sujeito à administração militar; a agressão no bar, sem outra circunstância das alíneas, não é crime militar.",
    "Correta. A alínea ‘c’ dispensa o lugar quando o militar está em serviço ou atua em razão da função."),
   ("Ambas são crimes militares, pois os agentes são militares da ativa.",
    "Errada. Ser militar da ativa não basta; é preciso uma das alíneas."),
   ("Nenhuma é crime militar, porque ocorreram fora de área militar.",
    "Errada. A alínea ‘c’ alcança fatos fora do lugar sujeito à administração militar."),
   ("Só a agressão no bar é crime militar, porque não havia missão.",
    "Errada. A inversão não tem base legal."),
  ], correta=0,
  comentario="O dado decisivo é ‘em serviço’. O insulto do civil e a enchente são ruído para a classificação.",
  fonte=f"{CPM}, art. 9º, II, c, p. 18; {A31}, slide 61.", armadilha="Crime de militar = crime militar.", tempo=3),
 dict(n=6, tipo="VF", nivel="N3", ctx=True, conceitos=["DIRT2-ART9-II", "DIRT2-CRIME-MILITAR-CONCEITO"],
  competencia="Negar a qualificação militar quando nenhuma alínea incide.",
  afirmacao="Um sargento da ativa, de folga e em trajes civis, furta um celular de uma loja em shopping center. Por ser militar da ativa e o furto também estar previsto no CPM, o fato é crime militar.",
  correta=False,
  comentario="Falsa. O art. 9º, II, exige uma das alíneas: não há vítima militar da ativa (a), lugar sujeito à administração militar (b), serviço/função (c), manobras (d) nem patrimônio sob administração militar (e). Sem enquadramento, não é crime militar.",
  fonte=f"{CPM}, art. 9º, II, p. 18–19; {A31}, slides 55 e 61.", armadilha="Qualificar pelo agente.", tempo=2),
 dict(n=7, tipo="OBJ", nivel="N3", ctx=True, conceitos=["DIRT2-ART9-III"],
  competencia="Aplicar o inciso III a civil que atenta contra as instituições militares.",
  enunciado="Um civil, prestador de serviço de limpeza, entra na área de uma OM e subtrai ferramentas pertencentes à Marinha. No mesmo dia, outro civil agride, dentro da mesma OM, um militar em atividade que estava no exercício da função. Assinale a análise correta.",
  alternativas=[
   ("Ambos os fatos podem ser crimes militares: o primeiro pelo art. 9º, III, ‘a’ (patrimônio sob administração militar) e o segundo pelo art. 9º, III, ‘b’ (lugar sujeito à administração militar contra militar em atividade no exercício da função).",
    "Correta. O inciso III alcança civil contra as instituições militares nas hipóteses das alíneas."),
   ("Nenhum é crime militar, porque civil só responde perante a justiça comum.",
    "Errada. O art. 9º, III, prevê expressamente crime militar praticado por civil."),
   ("Só o primeiro é crime militar, porque agressão a pessoa nunca atenta contra instituição militar.",
    "Errada. A alínea ‘b’ trata de fato contra militar em atividade em lugar sujeito à administração militar."),
   ("Ambos são crimes militares pelo art. 9º, II, porque ocorreram em área militar.",
    "Errada. O inciso II pressupõe agente militar da ativa ou assemelhado."),
  ], correta=0,
  comentario="Verifique primeiro o agente (civil → inciso III) e depois a alínea. [NÃO CONFIRMADO NA FONTE PRIMÁRIA] O STF, HC 109.544, é indicado na transferência como caso sobre civil na JMU apenas em crime militar; não foi possível conferir o texto oficial.",
  fonte=f"{CPM}, art. 9º, III, a–b, p. 19; {A31}, slide 62.", armadilha="Civil nunca comete crime militar.", tempo=3),
 dict(n=8, tipo="OBJ", nivel="N3", ctx=True, conceitos=["DIRT2-TRANSGRESSAO"],
  competencia="Aplicar a regra do concurso entre crime e transgressão da mesma natureza.",
  enunciado="Um cabo de serviço como sentinela dorme no posto. O comandante aplica punição disciplinar pelo mesmo fato e remete o caso para apuração penal pelo art. 203 do CPM. O defensor alega dupla punição. Considerando o slide 59 e o Estatuto dos Militares:",
  alternativas=[
   ("No concurso de crime militar e transgressão disciplinar da mesma natureza, aplica-se somente a pena relativa ao crime (Lei 6.880/1980, art. 42, § 2º).",
    "Correta. O slide cita ‘Lei nº 6.080/80’, mas o dispositivo reproduzido é do Estatuto dos Militares, Lei nº 6.880/1980 — [POSSÍVEL ERRO NA FONTE]."),
   ("As duas punições se somam, porque as esferas são independentes.",
    "Errada. O art. 42, § 2º, afasta a cumulação quando crime e transgressão são da mesma natureza."),
   ("Aplica-se apenas a punição disciplinar, por ser mais rápida.",
    "Errada. A regra manda aplicar a pena relativa ao crime."),
   ("A Lei nº 6.080/80 proíbe a remessa para apuração penal.",
    "Errada. Além do número incorreto, o dispositivo não proíbe a apuração penal."),
  ], correta=0,
  comentario="Conferência: Lei 6880.pdf, art. 42, p. 9, reproduz exatamente o texto do slide. [APROFUNDAMENTO ANALÍTICO DE SUPORTE] O CPM, art. 19, esclarece que o Código não compreende as infrações dos regulamentos disciplinares.",
  fonte=f"{A31}, slide 59; {EM}, art. 42, § 2º, p. 9; {CPM}, arts. 19 e 203, p. 23 e 90.", armadilha="Somar sanções da mesma natureza.", tempo=3),
 dict(n=9, tipo="OBJ", nivel="N4", ctx=True, conceitos=["DIRT2-ART9-DOLOSO-VIDA", "DIRT2-ART9-II"],
  competencia="Aplicar os §§ 1º e 2º do art. 9º a crimes dolosos contra a vida de civil.",
  enunciado="Três fatos: (I) um fuzileiro naval, em operação de garantia da lei e da ordem realizada conforme o art. 142 da CF, mata dolosamente um civil; (II) um sargento da Marinha, de folga, em discussão de trânsito, mata dolosamente um civil; (III) um policial militar estadual, em serviço, mata dolosamente um civil. Considerando o CPM (edição do corpus) e os slides 38–40 da Aula 4.1, assinale a alternativa correta.",
  alternativas=[
   ("I: competência da Justiça Militar da União pelo art. 9º, § 2º, III; II: sem enquadramento no art. 9º, não é crime militar; III: o § 2º, que trata de militares das Forças Armadas, não se aplica.",
    "Correta. O § 2º é restrito às Forças Armadas e aos contextos enumerados. Em II falta alínea do art. 9º. Em III, o § 2º não incide; o § 1º (júri) e a CF, art. 125, § 4º (ressalva do júri quando a vítima for civil), orientam a análise."),
   ("Os três vão ao Tribunal do Júri, pelo § 1º do art. 9º.",
    "Errada. Ignora a exceção do § 2º para as Forças Armadas em GLO."),
   ("Os três são julgados pela Justiça Militar da União, pois todos os agentes são militares.",
    "Errada. Em II não há crime militar; em III o agente é militar estadual."),
   ("I e III vão à JMU por estarem em serviço; II vai ao júri.",
    "Errada. O § 2º não alcança policiais militares estaduais."),
  ], correta=0,
  comentario="O § 2º pede cumulativamente: (1) crime doloso contra a vida de civil, (2) militar das Forças Armadas, (3) contexto dos incisos. Falta qualquer um, a regra do § 1º ou a ausência de crime militar resolvem.",
  fonte=f"{CPM}, art. 9º, §§ 1º–2º, p. 19–20; {A41}, slides 36–40; {CF}, art. 125, § 4º, p. 109.", armadilha="Aplicar o § 2º a militar estadual.", tempo=5),
 dict(n=10, tipo="OBJ", nivel="N4", ctx=True, conceitos=["DIRT2-ART9-I", "DIRT2-ART9-II", "DIRT2-ART9-III", "DIRT2-PROPRIO-IMPROPRIO"],
  competencia="Classificar vários fatos quanto à natureza militar e à espécie de crime militar.",
  enunciado="Classifique: (I) um marinheiro deixa de retornar de férias e fica ausente por dez dias; (II) um civil usa indevidamente uniforme da Marinha em evento público (art. 172); (III) um cabo da ativa furta o relógio de um sargento da ativa em uma praia, ambos de folga; (IV) um militar reformado agride um amigo civil em churrasco particular. Assinale a alternativa correta.",
  alternativas=[
   ("I: crime propriamente militar; II: crime militar pelo art. 9º, I, embora praticado por civil; III: crime militar pelo art. 9º, II, ‘a’, pela literalidade do texto; IV: não é crime militar.",
    "Correta. I: deserção por caso assimilado (art. 188, I — tratado em aula pela figura do art. 187). II: tipo exclusivo do CPM, ‘qualquer que seja o agente’. III: alínea ‘a’ não exige lugar nem serviço. IV: reformado contra civil fora das hipóteses do inciso III."),
   ("I: crime militar impróprio; II: não é crime militar, pois o agente é civil; III: não é crime militar, pois ambos estavam de folga; IV: crime militar pelo inciso III.",
    "Errada. Ignora o inciso I para o civil, a literalidade da alínea ‘a’ e a exigência de ofensa às instituições militares no inciso III."),
   ("I: transgressão; II: crime comum; III: crime militar; IV: crime militar.",
    "Errada. A ausência superior a oito dias é deserção; IV não se enquadra."),
   ("I: crime propriamente militar; II: crime militar pelo inciso III; III: crime comum; IV: crime comum.",
    "Errada. II é inciso I (tipo exclusivo do CPM); III se ajusta à alínea ‘a’."),
  ], correta=0,
  comentario="[PONTO DE INCERTEZA] Em III, a resposta segue a literalidade do art. 9º, II, ‘a’, do corpus. Há indicação, na transferência, de precedente do STF segundo o qual a competência militar não alcança automaticamente todo crime de militar (Inq. 4.923) — [NÃO CONFIRMADO NA FONTE PRIMÁRIA]. Em prova, fundamente na lei e mencione a controvérsia se o enunciado pedir jurisprudência. [APROFUNDAMENTO ANALÍTICO DE SUPORTE] Em I, a não apresentação após férias é caso assimilado do art. 188, I.",
  fonte=f"{CPM}, arts. 9º, 172, 187 e 188, p. 18–19, 79 e 85; {A31}, slides 55–62 e 70.", armadilha="Negar crime militar a civil no inciso I.", tempo=6),
 dict(n=11, tipo="VF", nivel="N2", ctx=False, conceitos=["DIRT2-ART10-GUERRA"], modos=["pra-safar", "completo"],
  competencia="Reconhecer a permanência dos crimes militares de paz em tempo de guerra.",
  afirmacao="Em tempo de guerra, os crimes militares previstos para o tempo de paz continuam sendo crimes militares, ao lado dos especialmente previstos para o tempo de guerra.",
  correta=True,
  comentario="Verdadeira. Art. 10, I e II, do CPM (slide 64).",
  fonte=f"{CPM}, art. 10, I–II, p. 21; {A31}, slide 64.", armadilha="Supor substituição integral dos tipos na guerra.", tempo=1),
 dict(n=12, tipo="OBJ", nivel="N3", ctx=True, conceitos=["DIRT2-ART10-GUERRA"], modos=["pra-safar", "completo"],
  competencia="Aplicar o art. 10, IV, a crime comum em zona de operações.",
  enunciado="Em tempo de guerra, em zona de efetivas operações militares, uma pessoa pratica crime definido apenas na lei penal comum, sem correspondente no CPM. Assinale a alternativa correta.",
  alternativas=[
   ("É crime militar em tempo de guerra, pelo art. 10, IV, por ter sido praticado em zona de efetivas operações militares.",
    "Correta. O inciso IV alcança crimes da lei comum ou especial, ‘embora não previstos neste Código’, nesses locais."),
   ("Não é crime militar, pois não está previsto no CPM.",
    "Errada. O inciso IV existe exatamente para essa hipótese."),
   ("Só é crime militar se o agente for militar.",
    "Errada. O inciso IV não restringe o agente."),
   ("Só é crime militar se comprometer a segurança externa do País.",
    "Errada. Esse requisito é da alínea ‘b’ do inciso III, para crimes previstos no CPM."),
  ], correta=0,
  comentario="Contrafactual: fora de zona de operações e fora de território estrangeiro militarmente ocupado, o inciso IV não incide.",
  fonte=f"{CPM}, art. 10, III–IV, p. 21; {A31}, slides 66–67.", armadilha="Confundir requisitos dos incisos III e IV.", tempo=3),
 dict(n=13, tipo="DIS", nivel="N3", ctx=True, conceitos=["DIRT2-ART9-II", "DIRT2-CRIME-MILITAR-CONCEITO"],
  competencia="Fundamentar o enquadramento no art. 9º com seleção de fatos relevantes.",
  contexto="Durante exercício da Marinha em uma praia pública, um sargento da ativa, participante do exercício, lesiona dolosamente um pescador civil que se recusou a sair da área. O exercício havia sido divulgado com antecedência; a praia não é área militar.",
  enunciado="O fato é crime militar? Indique o inciso e a alínea, fundamente e aponte os fatos irrelevantes.",
  gabarito="**Gabarito:** agente militar da ativa → art. 9º, II. Vítima civil fora de lugar sujeito à administração militar → alínea ‘b’ não incide. O fato ocorreu ‘durante o período de manobras ou exercício’ → alínea ‘d’ (militar durante manobras ou exercício contra civil). Poder-se-ia examinar também a alínea ‘c’ se o sargento atuava em razão da função. Conclusão: crime militar (lesão corporal, art. 209, se dolosa). Irrelevantes: divulgação prévia do exercício; recusa do pescador (pode interessar a outra etapa, como excludentes, mas não à classificação).\n\n**Plena:** inciso II + alínea ‘d’ justificada + descarte da ‘b’ + fatos irrelevantes. **Parcial:** conclui por crime militar sem alínea correta. **Insuficiente:** nega crime militar por ser praia pública.",
  criterios=["Questão: natureza militar do fato (0,2)", "Norma: art. 9º, II, ‘d’ (e exame da ‘b’/‘c’) (0,2)", "Aplicação aos fatos (0,3)", "Limite: praia não é área militar; ruídos identificados (0,2)", "Conclusão (0,1)"],
  fonte=f"{CPM}, art. 9º, II, b–d, p. 18–19; art. 209, p. 94; {A31}, slide 61.", armadilha="Negar crime militar por ausência de área militar.", tempo=7),
 dict(n=14, tipo="DIS", nivel="N4", ctx=True, conceitos=["DIRT2-ART9-III", "DIRT2-ART9-DOLOSO-VIDA", "DIRT2-TRANSGRESSAO", "DIRT2-PROPRIO-IMPROPRIO"],
  competencia="Classificar e fundamentar vários fatos com efeitos distintos.",
  contexto="(1) Um civil, em visita autorizada a um navio, danifica equipamento de comunicação da Marinha. (2) Um cabo fuzileiro, durante operação de garantia da lei e da ordem realizada nos termos do art. 142 da CF, mata dolosamente um civil. (3) Um marinheiro ausenta-se sem licença por nove dias e, pelo mesmo fato, recebe punição disciplinar.",
  enunciado="Para cada fato, diga se há crime militar, indicando o fundamento e a consequência que o CPM ou o Estatuto dos Militares extrai da classificação.",
  gabarito="**Gabarito:** (1) Civil contra patrimônio sob administração militar → art. 9º, III, ‘a’: crime militar. (2) Crime doloso contra a vida de civil por militar das Forças Armadas no contexto do art. 9º, § 2º, III: competência da Justiça Militar da União, e não do júri (§ 1º). (3) Ausência por mais de oito dias → deserção (art. 187), crime propriamente militar; havendo concurso com transgressão da mesma natureza, aplica-se somente a pena relativa ao crime (Lei 6.880/1980, art. 42, § 2º — o slide 59 cita, com erro material, ‘Lei 6.080/80’).\n\n**Plena:** três enquadramentos com consequência correta. **Parcial:** acerta dois. **Insuficiente:** qualifica pelos agentes ou manda (2) ao júri.",
  criterios=["Questões: natureza de cada fato (0,2)", "Normas: art. 9º III ‘a’; § 2º III; art. 187; EM 42 § 2º (0,2)", "Aplicação (0,3)", "Limites: § 1º × § 2º; mesma natureza (0,2)", "Conclusão (0,1)"],
  fonte=f"{CPM}, arts. 9º e 187, p. 18–20 e 85; {EM}, art. 42, § 2º, p. 9; {A31}, slides 58–63.", armadilha="Mandar homicídio em GLO ao júri; somar punições.", tempo=10),
]
