from conceitos import A31, A41, A42, CPM, CPPM, CF, EM

M07 = [
 dict(n=1, tipo="VF", nivel="N1", ctx=False, conceitos=["DIRT2-CRIME-174"],
  competencia="Reconhecer a pena cominada ao rigor excessivo.",
  afirmacao="O crime de rigor excessivo (art. 174 do CPM) é punido com detenção de dois a seis meses.",
  correta=False,
  comentario="Falsa. A pena é de **suspensão do exercício do posto**, por dois a seis meses, se o fato não constitui crime mais grave (slide 71).",
  fonte=f"{CPM}, art. 174, p. 80; {A31}, slide 71.", armadilha="Trocar a espécie de pena.", tempo=1),
 dict(n=2, tipo="OBJ", nivel="N2", ctx=False, conceitos=["DIRT2-CRIME-160"],
  competencia="Identificar a elementar do desrespeito a superior.",
  enunciado="Qual elemento integra o tipo do art. 160 do CPM (desrespeito a superior)?",
  alternativas=[
   ("Que o desrespeito ocorra diante de outro militar.", "Correta. ‘Desrespeitar superior diante de outro militar’."),
   ("Que o fato ocorra em lugar sujeito à administração militar.", "Errada. O tipo não exige lugar."),
   ("Que haja violência contra o superior.", "Errada. Violência caracteriza outros tipos; o art. 160 descreve desrespeito."),
   ("Que o superior seja oficial-general.", "Errada. Oficial-general é hipótese de aumento (parágrafo único), não elementar."),
  ], correta=0,
  comentario="Sem a presença de outro militar, o art. 160 não se completa; a conduta pode interessar a outro tipo ou à esfera disciplinar.",
  fonte=f"{CPM}, art. 160, p. 76–77; {A31}, slide 68.", armadilha="Esquecer a elementar ‘diante de outro militar’.", tempo=1),
 dict(n=3, tipo="COR", nivel="N2", ctx=True, conceitos=["DIRT2-CRIME-160", "DIRT2-CRIME-163", "DIRT2-CRIME-172", "DIRT2-CRIME-174", "DIRT2-CRIME-203"],
  competencia="Associar condutas aos tipos ensinados.",
  titulo="Associe a conduta ao tipo do CPM",
  chaves=[("A", "Art. 160 — desrespeito a superior"), ("B", "Art. 163 — recusa de obediência"), ("C", "Art. 172 — uso indevido de uniforme"), ("D", "Art. 174 — rigor excessivo"), ("E", "Art. 203 — dormir em serviço")],
  itens=[
   ("Tenente pune subordinado ofendendo-o com palavras humilhantes na frente da tropa.", "D"),
   ("Marinheiro em plantão às máquinas é encontrado dormindo.", "E"),
   ("Cabo, na frente de colegas, dirige gestos de desprezo ao sargento.", "A"),
   ("Pessoa sem vínculo com a Marinha usa farda com distintivo de oficial em uma festa.", "C"),
   ("Marinheiro recusa-se a cumprir ordem de serviço do encarregado.", "B"),
  ],
  comentario="Pistas típicas: ‘diante de outro militar’ (160), ‘ordem sobre matéria de serviço’ (163), ‘a que não tenha direito’ (172), ‘faculdade de punir’ (174), ‘em serviço’ nas funções enumeradas (203).",
  fonte=f"{CPM}, arts. 160, 163, 172, 174 e 203, p. 76–90; {A31}, slides 68–72.", armadilha="Confundir rigor excessivo com desrespeito.", tempo=3),
 dict(n=4, tipo="OBJ", nivel="N2", ctx=True, conceitos=["DIRT2-CRIME-160"],
  competencia="Aplicar a majorante do desrespeito a superior.",
  enunciado="Na presença do cabo de serviço, um marinheiro desrespeita o oficial de quarto do navio. Assinale a consequência correta pelo art. 160 do CPM.",
  alternativas=[
   ("Desrespeito a superior com pena aumentada da metade, por ter sido praticado contra oficial de quarto.",
    "Correta. Parágrafo único: comandante da unidade, oficial-general, oficial de dia, de serviço ou de quarto."),
   ("Desrespeito simples, pois o aumento só se aplica a oficial-general.", "Errada. A lista inclui oficial de quarto."),
   ("Não há crime, pois o outro presente era de posto inferior ao ofendido.", "Errada. O tipo pede ‘outro militar’, sem exigir posto."),
   ("Insubordinação, porque o ofendido estava de serviço.", "Errada. Não houve recusa de ordem."),
  ], correta=0,
  comentario="Observação de fonte: o slide 68 escreve ‘oficial de serviço ou de quarto’ e omite ‘oficial de dia’, que consta do texto legal.",
  fonte=f"{CPM}, art. 160, parágrafo único, p. 77; {A31}, slide 68.", armadilha="Restringir a majorante.", tempo=2),
 dict(n=5, tipo="OBJ", nivel="N3", ctx=True, conceitos=["DIRT2-CRIME-163", "DIRT2-INEXIGIBILIDADE"],
  competencia="Delimitar a insubordinação pela natureza da ordem.",
  enunciado="(1) Um marinheiro recusa-se a limpar o convés conforme ordem do encarregado da faina. (2) Outro marinheiro recusa-se a obedecer a ordem de um sargento para agredir um preso. Assinale a alternativa correta.",
  alternativas=[
   ("Em (1) pode haver recusa de obediência (art. 163); em (2) não, pois a ordem não versa sobre matéria de serviço nem dever legal — e cumpri-la tornaria punível o próprio inferior (art. 38, § 2º).",
    "Correta. O art. 163 protege ordens sobre ‘assunto ou matéria de serviço, ou relativamente a dever imposto em lei, regulamento ou instrução’."),
   ("Ambos praticam insubordinação, pois toda ordem de superior deve ser cumprida.",
    "Errada. A ordem manifestamente criminosa não é objeto de proteção do tipo."),
   ("Nenhum pratica crime, porque a recusa só é crime com violência.", "Errada. O art. 163 não exige violência."),
   ("Em (2) há desrespeito a superior.", "Errada. Recusar ordem ilegal não é desrespeitar."),
  ], correta=0,
  comentario="Integração com o módulo 03: a ordem manifestamente criminosa não gera dever de obediência.",
  fonte=f"{CPM}, arts. 38, § 2º, e 163, p. 28 e 77; {A31}, slides 36 e 69.", armadilha="‘Ordem é ordem’.", tempo=3),
 dict(n=6, tipo="VF", nivel="N3", ctx=True, conceitos=["DIRT2-CRIME-203"],
  competencia="Reconhecer crime de mera conduta em serviço.",
  afirmacao="Um marinheiro escalado como vigia no passadiço cochila por alguns minutos sem que nada de anormal aconteça. Como não houve dano nem perigo concreto, não há crime de dormir em serviço.",
  correta=False,
  comentario="Falsa. O art. 203 descreve ‘dormir o militar, quando em serviço’ em funções como vigia; o tipo não exige resultado danoso.",
  fonte=f"{CPM}, art. 203, p. 90; {A31}, slide 72.", armadilha="Exigir resultado.", tempo=2),
 dict(n=7, tipo="OBJ", nivel="N3", ctx=True, conceitos=["DIRT2-CRIME-172", "DIRT2-ART9-I"],
  competencia="Distinguir os tipos de uso indevido de uniforme e o sujeito ativo.",
  enunciado="(1) Um civil usa farda da Marinha para obter vantagem em um evento. (2) Um cabo usa, em formatura, insígnia de sargento. Assinale a alternativa correta.",
  alternativas=[
   ("(1) pode ser o art. 172, praticável por qualquer pessoa e crime militar pelo art. 9º, I; (2) ajusta-se ao art. 171, próprio do militar que usa insígnia de posto ou graduação superior.",
    "Correta. O slide trata do art. 172; o art. 171 é a figura vizinha do militar."),
   ("Ambos são art. 172.", "Errada. O uso de insígnia superior por militar tem tipo específico (art. 171)."),
   ("(1) não é crime militar porque o agente é civil.", "Errada. O art. 9º, I, alcança crimes só definidos no CPM ‘qualquer que seja o agente’."),
   ("(2) é desrespeito a superior.", "Errada. Não há desrespeito descrito."),
  ], correta=0,
  comentario="[APROFUNDAMENTO ANALÍTICO DE SUPORTE] Art. 171 consta do CPM na mesma página do art. 172; é usado aqui só como contraste.",
  fonte=f"{CPM}, arts. 9º, I, 171 e 172, p. 18 e 79; {A31}, slide 70.", armadilha="Negar crime militar a civil.", tempo=3),
 dict(n=8, tipo="OBJ", nivel="N3", ctx=True, conceitos=["DIRT2-CRIME-209-210"],
  competencia="Enquadrar lesões pela intensidade e pelo elemento subjetivo.",
  enunciado="Em uma briga no alojamento, um cabo dá um tapa em um marinheiro que causa apenas vermelhidão passageira; a lesão é levíssima. Assinale a alternativa correta pelo CPM.",
  alternativas=[
   ("Em lesão levíssima, o juiz pode considerar a infração como disciplinar.",
    "Correta. Art. 209, § 6º."),
   ("É obrigatoriamente lesão corporal grave, pois ocorreu em lugar sujeito à administração militar.",
    "Errada. A gravidade da lesão depende do resultado (§§ 1º–2º), não do lugar."),
   ("É lesão culposa, porque a vítima não ficou incapacitada.", "Errada. A agressão foi intencional."),
   ("Não há qualquer consequência jurídica, pois não houve ferimento.", "Errada. Houve ofensa à integridade corporal; o § 6º dá ao juiz a opção disciplinar."),
  ], correta=0,
  comentario="Sequência: dolosa ou culposa? (209 × 210). Se dolosa, qual resultado? (caput, §§ 1º–3º). Há hipóteses de minoração (§§ 4º–6º)?",
  fonte=f"{CPM}, arts. 209–210, p. 94–95; {A31}, slide 73.", armadilha="Ignorar o § 6º.", tempo=2),
 dict(n=9, tipo="OBJ", nivel="N4", ctx=True, conceitos=["DIRT2-CRIME-174", "DIRT2-CRIME-160", "DIRT2-CRIME-163", "DIRT2-TRANSGRESSAO"],
  competencia="Resolver episódio com tipos subsidiários, reação do subordinado e esfera disciplinar.",
  enunciado="Um primeiro-tenente, ao punir um marinheiro por atraso, o obriga a ficar horas sob o sol e o chama de ‘inútil’ diante da divisão. Em seguida ordena que ele limpe o paiol; o marinheiro recusa e, diante dos colegas, faz um gesto obsceno ao tenente. Assinale a análise mais adequada.",
  alternativas=[
   ("O tenente pode responder por rigor excessivo (art. 174), se o fato não constituir crime mais grave; a recusa da ordem de serviço pode configurar o art. 163 e o gesto, o art. 160; a ilegalidade da punição anterior não torna lícita a recusa de ordem de serviço lícita posterior.",
    "Correta. Cada conduta é analisada pelo seu tipo; a cláusula de subsidiariedade (‘se o fato não constitui crime mais grave’) aparece nos três tipos."),
   ("Só o tenente responde, pois o marinheiro reagiu a abuso.", "Errada. O abuso anterior não autoriza desrespeito nem recusa a ordem de serviço lícita."),
   ("O tenente pratica desrespeito a inferior (art. 160) e o marinheiro rigor excessivo.", "Errada. Inverte os tipos: art. 160 protege o superior; art. 174 pune o excesso do superior."),
   ("Tudo é transgressão disciplinar, e nenhum crime militar ocorre por se tratar de relação interna.", "Errada. Os fatos têm tipos específicos no CPM."),
  ], correta=0,
  comentario="[PONTO DE INCERTEZA] Se a exposição prolongada ao sol causar lesão, a análise pode migrar para tipo mais grave; o enunciado não informa resultado, e a resposta não deve presumi-lo. A regra de não cumular pena disciplinar e penal da mesma natureza (EM art. 42, § 2º) vale para cada conduta.",
  fonte=f"{CPM}, arts. 160, 163 e 174, p. 76–80; {EM}, art. 42, § 2º, p. 9; {A31}, slides 59 e 68–71.", armadilha="Legitimar a reação do subordinado pelo abuso anterior.", tempo=6),
 dict(n=10, tipo="OBJ", nivel="N4", ctx=True, conceitos=["DIRT2-CRIME-209-210", "DIRT2-PRETERDOLO", "DIRT2-CULPA"],
  competencia="Enquadrar lesões de vários agentes pela forma dolosa, culposa, qualificada pelo resultado ou agravada.",
  enunciado="Em uma faina: (I) um cabo, irritado, empurra um marinheiro para machucá-lo; o marinheiro fica mais de 30 dias incapacitado para as ocupações habituais, resultado não querido mas previsível; (II) um sargento, operando equipamento sem observar a regra técnica da atividade, fere levemente dois marinheiros com uma só manobra; (III) um soldado fere culposamente um colega e, podendo, deixa de prestar imediato socorro. Assinale a alternativa correta.",
  alternativas=[
   ("I: lesão dolosa com resultado grave causado culposamente (art. 209, § 3º, primeira parte); II: lesão culposa com pena que pode ser agravada pela inobservância de regra técnica e aumentada por várias vítimas (art. 210, §§ 1º–2º); III: lesão culposa com pena que pode ser agravada pela omissão de socorro (art. 210, § 1º).",
    "Correta. Aplica corretamente os parágrafos dos arts. 209 e 210."),
   ("I: lesão grave dolosa (art. 209, § 1º); II: lesão dolosa leve; III: omissão de socorro autônoma.", "Errada. O § 1º exige produção dolosa do resultado grave; II é culposa; o § 1º do art. 210 trata da falta de socorro como agravante."),
   ("I: lesão leve; II: duas lesões culposas somadas; III: lesão culposa simples.", "Errada. Ignora o § 3º em I e as causas de agravamento/aumento em II e III."),
   ("I: homicídio tentado; II: dolo eventual; III: lesão dolosa.", "Errada. Não há dolo de matar nem assunção do risco descritos."),
  ], correta=0,
  comentario="Os §§ do art. 209 distinguem resultado grave doloso (§§ 1º–2º) de resultado grave culposo (§ 3º). No art. 210, o § 1º agrava e o § 2º aumenta.",
  fonte=f"{CPM}, arts. 34, 209 e 210, p. 26 e 94–95; {A31}, slides 23 e 73.", armadilha="Aplicar o § 1º a resultado não doloso.", tempo=6),
 dict(n=11, tipo="VF", nivel="N2", ctx=False, conceitos=["DIRT2-CRIME-163"],
  competencia="Reconhecer a cláusula de subsidiariedade expressa.",
  afirmacao="A pena do crime de recusa de obediência (art. 163) é de detenção de um a dois anos, se o fato não constitui crime mais grave.",
  correta=True,
  comentario="Verdadeira. Texto do art. 163 e do slide 69. A mesma cláusula aparece nos arts. 160 e 174.",
  fonte=f"{CPM}, art. 163, p. 77; {A31}, slide 69.", armadilha="Ignorar a subsidiariedade.", tempo=1),
 dict(n=12, tipo="OBJ", nivel="N3", ctx=True, conceitos=["DIRT2-CRIME-203", "DIRT2-INEXIGIBILIDADE"],
  competencia="Aplicar o art. 203 com alegação de ordem superior.",
  enunciado="Um sargento de ronda, após 30 horas sem descanso por ter sido mantido em serviço pelo comandante, adormece durante a ronda. A defesa alega que ‘cumpria ordem superior’. Assinale a análise correta.",
  alternativas=[
   ("O tipo do art. 203 se completa; a ordem de permanecer em serviço não é ordem para dormir, de modo que a obediência hierárquica não se aplica; circunstâncias pessoais podem ser consideradas na análise da culpabilidade e da pena.",
    "Correta. A tese de obediência não se ajusta ao fato; o esgotamento é dado a considerar nas etapas posteriores."),
   ("Não há crime, pois o sargento obedecia ordem direta em matéria de serviço.", "Errada. Não houve ordem para dormir."),
   ("Há crime de rigor excessivo pelo sargento.", "Errada. Rigor excessivo é conduta de quem pune subordinado."),
   ("Não há crime porque o sargento não era sentinela.", "Errada. O tipo inclui oficial ‘de ronda’ e, para não oficial, ‘ronda’ e serviço semelhante."),
  ], correta=0,
  comentario="[INFERÊNCIA PEDAGÓGICA] A eventual responsabilidade do comandante por manter o subordinado em serviço excessivo é questão distinta, não tratada nos slides.",
  fonte=f"{CPM}, arts. 38 e 203, p. 28 e 90; {A31}, slides 36 e 72.", armadilha="Transformar contexto de serviço em ordem para a conduta.", tempo=3),
 dict(n=13, tipo="DIS", nivel="N3", ctx=True, conceitos=["DIRT2-CRIME-160", "DIRT2-CRIME-172", "DIRT2-CRIME-203"],
  competencia="Enquadrar condutas com elementares e majorantes.",
  contexto="Em um mesmo dia: (a) um marinheiro, a sós com o comandante na sala dele, dirige-lhe palavras desrespeitosas; horas depois, repete as ofensas ao comandante na presença do cabo de dia; (b) um civil visita a OM vestindo, por brincadeira, farda completa de fuzileiro; (c) um cabo em serviço de plantão às máquinas adormece.",
  enunciado="Enquadre cada fato, indicando elementares e eventual causa de aumento.",
  gabarito="**Gabarito:** (a) A primeira ofensa, a sós, não preenche ‘diante de outro militar’ — não se completa o art. 160 (pode haver repercussão disciplinar ou outro tipo, não analisados). A segunda, diante do cabo de dia, configura desrespeito a superior; como a vítima é o comandante da unidade a que pertence o agente, a pena é aumentada da metade (parágrafo único). (b) Uso indevido de uniforme militar a que não tem direito (art. 172), praticável por qualquer pessoa; crime militar pelo art. 9º, I; a intenção de ‘brincadeira’ não afasta o dolo da conduta de usar indevidamente [INFERÊNCIA PEDAGÓGICA]. (c) Dormir em serviço (art. 203), sem exigência de resultado; ‘plantão às máquinas’ consta expressamente do tipo.\n\n**Plena:** separa as duas ofensas em (a), aplica a majorante e acerta (b) e (c). **Parcial:** trata (a) como um único crime. **Insuficiente:** nega crime militar em (b) por ser civil.",
  criterios=["Questões: elementares de cada tipo (0,2)", "Normas: arts. 160 e p. único, 172, 203, 9º I (0,2)", "Aplicação (0,3)", "Limite: ausência de outro militar na primeira ofensa (0,2)", "Conclusão (0,1)"],
  fonte=f"{CPM}, arts. 9º, 160, 172 e 203; {A31}, slides 68, 70 e 72.", armadilha="Ignorar a elementar da presença.", tempo=7),
 dict(n=14, tipo="DIS", nivel="N4", ctx=True, conceitos=["DIRT2-CRIME-209-210", "DIRT2-ART9-II", "DIRT2-CULPA", "DIRT2-TRANSGRESSAO"],
  competencia="Integrar crime militar, lesão culposa agravada e concurso com transgressão.",
  contexto="Durante exercício da Marinha em área civil, um sargento opera uma embarcação sem seguir a regra técnica de aproximação. Atinge dois banhistas civis, que sofrem lesões leves, e segue viagem sem prestar socorro, embora pudesse. O comandante aplica punição disciplinar ao sargento pelos mesmos fatos.",
  enunciado="Analise: natureza militar do fato, tipo e causas de agravamento/aumento, e a punição disciplinar.",
  gabarito="**Gabarito:** Natureza: militar da ativa, durante exercício, contra civil → art. 9º, II, ‘d’: crime militar. Tipo: não há dolo de lesionar; houve inobservância do dever de cuidado com previsibilidade → lesão culposa (art. 210). Agravamento: inobservância de regra técnica e falta de imediato socorro (§ 1º). Aumento: uma só ação culposa com lesões em várias pessoas (§ 2º: de um sexto até metade). Disciplinar: havendo concurso de crime militar e transgressão da mesma natureza, aplica-se somente a pena relativa ao crime (Lei 6.880/1980, art. 42, § 2º; slide 59, que cita o número da lei com erro material).\n\n**Plena:** quatro etapas com normas corretas. **Parcial:** acerta tipo, mas omite § 2º ou a regra do EM. **Insuficiente:** classifica como dolo eventual ou nega crime militar por ser área civil.",
  criterios=["Questões: natureza, tipo, causas e esfera disciplinar (0,2)", "Normas: art. 9º II ‘d’; 210 §§ 1º–2º; EM 42 § 2º (0,2)", "Aplicação (0,3)", "Limites: culpa × dolo eventual; mesma natureza (0,2)", "Conclusão (0,1)"],
  fonte=f"{CPM}, arts. 9º, 33 e 210, p. 18–19, 26 e 95; {EM}, art. 42, § 2º, p. 9; {A31}, slides 59, 61 e 73.", armadilha="Somar punições; negar crime militar fora de área militar.", tempo=10),
]

M08 = [
 dict(n=1, tipo="VF", nivel="N1", ctx=False, conceitos=["DIRT2-DPPM-CONCEITO"],
  competencia="Reconhecer a fonte e o âmbito temporal do DPPM.",
  afirmacao="As regras do Direito Processual Penal Militar estão essencialmente no Código de Processo Penal Militar (Decreto-Lei nº 1.002/1969), aplicável em tempo de paz e em tempo de guerra.",
  correta=True,
  comentario="Verdadeira. Slide 5 da Aula 4.1. Não confundir com o CPM, Decreto-Lei nº 1.001/1969 (slide 12 da Aula 3.1).",
  fonte=f"{A41}, slide 5; {A31}, slide 12.", armadilha="Trocar DL 1.001 (CPM) e DL 1.002 (CPPM).", tempo=1),
 dict(n=2, tipo="OBJ", nivel="N2", ctx=False, conceitos=["DIRT2-PJM"],
  competencia="Identificar as finalidades da Polícia Judiciária Militar.",
  enunciado="Segundo a Aula 4.1, NÃO é finalidade da Polícia Judiciária Militar:",
  alternativas=[
   ("Oferecer a denúncia quando houver indícios de autoria.", "Correta (não é finalidade). A ação penal militar é promovida por denúncia do MPM (CPPM art. 29)."),
   ("Apurar os fatos definidos como crime.", "Errada. É finalidade (slide 7; art. 8º, a)."),
   ("Auxiliar os órgãos do Ministério Público Militar e da Justiça Militar da União.", "Errada. É finalidade (slide 7; art. 8º, b)."),
   ("Cumprir as requisições do Ministério Público Militar.", "Errada. É finalidade (slide 7)."),
  ], correta=0,
  comentario="A PJM investiga e auxilia; o MPM acusa; o juiz decide.",
  fonte=f"{A41}, slide 7; {CPPM}, arts. 8º e 29, p. 23 e 34.", armadilha="Atribuir à PJM funções do MPM.", tempo=2),
 dict(n=3, tipo="COR", nivel="N2", ctx=True, conceitos=["DIRT2-PJM", "DIRT2-IPM-INSTAURACAO", "DIRT2-MEDIDAS-URGENTES"],
  competencia="Associar atos da fase investigativa a quem os pratica.",
  titulo="Associe o ato a quem o pratica",
  chaves=[("A", "Autoridade de PJM ou quem recebeu delegação"), ("B", "Encarregado do IPM"), ("C", "Oficial de dia, de serviço ou de quarto"), ("D", "Ministério Público Militar")],
  itens=[
   ("Baixar a portaria de instauração com o objeto da investigação.", "A"),
   ("Nomear o escrivão, se não o fez a autoridade delegante.", "B"),
   ("Dirigir-se ao local e preservar o estado das coisas antes da portaria.", "C"),
   ("Requisitar a instauração do IPM.", "D"),
  ],
  comentario="Slides 14–21: portaria pela autoridade (ou delegado); escrivão pelo encarregado (art. 11); providências do art. 12 pelo oficial do art. 10, § 2º; requisição pelo MPM (art. 10, c).",
  fonte=f"{A41}, slides 14–21; {CPPM}, arts. 10–12, p. 24–27.", armadilha="Confundir encarregado com autoridade instauradora.", tempo=2),
 dict(n=4, tipo="OBJ", nivel="N2", ctx=True, conceitos=["DIRT2-IPM-INSTAURACAO"],
  competencia="Aplicar a regra de designação do escrivão.",
  enunciado="O encarregado de um IPM em que o indiciado é capitão-tenente precisa designar escrivão. Quem pode ser designado segundo o CPPM?",
  alternativas=[
   ("Um segundo-tenente ou primeiro-tenente.", "Correta. Art. 11: indiciado oficial → segundo ou primeiro-tenente."),
   ("Um sargento, subtenente ou suboficial.", "Errada. Essa regra vale ‘nos demais casos’, isto é, indiciado não oficial."),
   ("Qualquer militar mais antigo que o indiciado.", "Errada. A lei fixa postos específicos."),
   ("Obrigatoriamente um capitão-tenente.", "Errada. O posto de capitão-tenente é referência para o encarregado (art. 15), não para o escrivão."),
  ], correta=0,
  comentario="O slide 15 resume: ‘Oficial subalterno, SO ou SG, conforme a antiguidade do indiciado’. O escrivão presta compromisso de sigilo (parágrafo único).",
  fonte=f"{CPPM}, arts. 11 e 15, p. 26–28; {A41}, slide 15.", armadilha="Aplicar a regra do indiciado praça.", tempo=2),
 dict(n=5, tipo="OBJ", nivel="N3", ctx=True, conceitos=["DIRT2-MEDIDAS-URGENTES"],
  competencia="Aplicar as providências anteriores à instauração.",
  enunciado="Às 2h, o oficial de quarto de um navio atracado é informado de que um marinheiro acaba de ferir outro com uma faca no refeitório. O comandante está em terra e a delegação para o IPM só poderá ser feita pela manhã. Assinale a conduta correta do oficial de quarto.",
  alternativas=[
   ("Ir ao local, providenciar que não se altere o estado das coisas, apreender a faca e objetos relacionados, prender o infrator observadas as regras legais e colher as provas possíveis, sem aguardar a delegação.",
    "Correta. Art. 10, § 2º, e art. 12, a–d (slides 18–21)."),
   ("Aguardar o comandante para não usurpar a competência de PJM.", "Errada. O aguardamento da delegação não obsta as providências imediatas."),
   ("Instaurar o IPM por portaria própria, como encarregado.", "Errada. As providências do art. 12 não se confundem com a instauração."),
   ("Limpar o refeitório e reunir as testemunhas no dia seguinte.", "Errada. Deve-se preservar o local enquanto necessário."),
  ], correta=0,
  comentario="Ruído: horário, comandante em terra. Dados decisivos: infração penal militar verificável na ocasião e oficial de quarto (art. 10, § 2º).",
  fonte=f"{CPPM}, arts. 10, § 2º, e 12, p. 25–27; {A41}, slides 18–22.", armadilha="Esperar a portaria.", tempo=3),
 dict(n=6, tipo="VF", nivel="N3", ctx=True, conceitos=["DIRT2-IPM-INSTAURACAO"],
  competencia="Distinguir prazo administrativo de prazo legal.",
  afirmacao="A autoridade tomou conhecimento de um fato na segunda-feira e baixou a portaria de IPM na sexta-feira. Um aspirante afirma que houve violação do prazo de 48 horas previsto no CPPM.",
  correta=False,
  comentario="Falsa quanto à fonte. O prazo máximo de 48 horas após o conhecimento do fato consta da DGPM-315, item 8.2.2, citada no slide 16 — norma administrativa da Marinha, não o CPPM. O descumprimento pode ter consequência administrativa, mas a afirmação atribui o prazo ao diploma errado. [INFORMAÇÃO NÃO PRESENTE NA FONTE] A DGPM-315 não foi fornecida; o curso usa apenas a citação do slide.",
  fonte=f"{A41}, slide 16; {CPPM}, art. 10, p. 24–25.", armadilha="Atribuir ao CPPM o prazo da DGPM-315.", tempo=2),
 dict(n=7, tipo="OBJ", nivel="N3", ctx=True, conceitos=["DIRT2-IPM-INSTAURACAO", "DIRT2-PJM"],
  competencia="Identificar os modos de início do IPM.",
  enunciado="Em uma OM, quatro situações chegam ao comandante. Em qual delas o IPM NÃO é iniciado por portaria da autoridade militar nos moldes do art. 10 do CPPM?",
  alternativas=[
   ("O Ministério Público Militar pretende baixar ele mesmo a portaria e designar o encarregado.",
    "Correta. O MPM **requisita** a instauração (art. 10, c); a portaria é ato da autoridade militar."),
   ("A sindicância aberta para apurar dano a viatura revela indício de crime militar.", "Errada. É modo previsto (art. 10, f; slide 17)."),
   ("O ofendido requer a instauração.", "Errada. É modo previsto (art. 10, e)."),
   ("A autoridade superior determina a instauração, por mensagem urgente confirmada depois por ofício.", "Errada. É modo previsto (art. 10, b)."),
  ], correta=0,
  comentario="O art. 10 prevê ainda o início ‘por decisão do Superior Tribunal Militar, nos termos do art. 25’ (alínea d), item omitido no slide 17.",
  fonte=f"{CPPM}, art. 10, a–f, p. 24–25; {A41}, slide 17.", armadilha="MPM instaura × requisita.", tempo=3),
 dict(n=8, tipo="OBJ", nivel="N3", ctx=True, conceitos=["DIRT2-PJM-DELEGACAO"], modos=["pra-safar", "completo"],
  competencia="Aplicar a regra de delegação quando o infrator é de posto igual ou superior.",
  enunciado="O comandante de um navio, capitão de fragata, toma conhecimento de indícios de crime militar praticado a bordo por um capitão de mar e guerra embarcado. Assinale a providência correta.",
  alternativas=[
   ("Comunicar o fato à autoridade superior competente para que ela faça a delegação a oficial de posto superior ao do indiciado (ou do mesmo posto, desde que mais antigo).",
    "Correta. Art. 10, § 1º, e art. 7º, §§ 2º–3º."),
   ("Instaurar o IPM e designar como encarregado o oficial mais antigo do navio.", "Errada. O infrator tem posto superior ao do comandante."),
   ("Instaurar o IPM e ser ele mesmo o encarregado.", "Errada. A delegação deve recair em oficial de posto superior ou mais antigo que o indiciado."),
   ("Arquivar o caso por falta de autoridade competente.", "Errada. A autoridade militar não arquiva e há solução legal (comunicação ao superior)."),
  ], correta=0,
  comentario="As providências urgentes do art. 12 continuam possíveis enquanto se aguarda a delegação (art. 10, § 2º).",
  fonte=f"{CPPM}, arts. 7º, §§ 2º–3º, e 10, § 1º, p. 22–25; {A41}, slides 14 e 18.", armadilha="Encarregado mais moderno que o indiciado.", tempo=3),
 dict(n=9, tipo="OBJ", nivel="N4", ctx=True, conceitos=["DIRT2-PJM-DELEGACAO", "DIRT2-IPM-INSTAURACAO", "DIRT2-ENCARREGADO-ATRIBUICOES"], modos=["pra-safar", "completo"],
  competencia="Corrigir a condução de IPM quando surgem indícios contra oficial mais antigo que o encarregado.",
  enunciado="Um capitão-tenente é encarregado de IPM sobre desvio de material, com um sargento como indiciado e um terceiro-sargento como escrivão. Durante as oitivas surgem indícios de que um capitão de corveta participou do desvio. Assinale a providência correta.",
  alternativas=[
   ("O encarregado deve tomar as providências para que suas funções sejam delegadas a outro oficial nos termos do art. 7º, § 2º; havendo indiciado oficial, o escrivão deverá ser segundo ou primeiro-tenente.",
    "Correta. Art. 10, § 5º (indícios contra oficial de posto superior ou mais antigo), art. 7º, § 2º, e art. 11."),
   ("O encarregado prossegue normalmente, pois foi regularmente designado.", "Errada. O § 5º do art. 10 exige a delegação a outro oficial."),
   ("O encarregado deve ouvir o capitão de corveta como testemunha para evitar a mudança de encarregado.", "Errada. Além de afrontar o § 5º, ouvir investigado como testemunha é a irregularidade discutida no HC do STM (slide 25)."),
   ("O encarregado deve encerrar o IPM e arquivá-lo, iniciando outro contra o oficial.", "Errada. A autoridade militar não arquiva IPM (art. 24)."),
  ], correta=0,
  comentario="Os prazos são deduzidos das interrupções pelo motivo do § 5º do art. 10 (art. 20, § 3º) [APROFUNDAMENTO ANALÍTICO DE SUPORTE].",
  fonte=f"{CPPM}, arts. 7º, 10, § 5º, 11, 20, § 3º, e 24, p. 22–32; {A41}, slides 15 e 25.", armadilha="Manter o encarregado mais moderno.", tempo=5),
 dict(n=10, tipo="OBJ", nivel="N4", ctx=True, conceitos=["DIRT2-PJM", "DIRT2-MEDIDAS-URGENTES", "DIRT2-IPM-CONCEITO", "DIRT2-IPM-INSTAURACAO"],
  competencia="Integrar PJM, providências urgentes, finalidade e instauração do IPM em um só caso.",
  enunciado="Um furto de fuzis é descoberto às 23h em um depósito de uma base de fuzileiros. O oficial de serviço isola o depósito, apreende um alicate encontrado no chão e colhe o nome de quem entrou. No dia seguinte, o comandante baixa portaria descrevendo o objeto e designa como encarregado um capitão-tenente, que nomeia um sargento como escrivão (os suspeitos são praças). O comandante determina, na portaria, que o encarregado ‘conclua pela culpa ou inocência dos envolvidos e aplique a punição’. Assinale a alternativa correta.",
  alternativas=[
   ("As providências do oficial de serviço, a portaria e as designações estão corretas; a determinação para o encarregado declarar culpa e punir penalmente é incompatível com a natureza do IPM, instrução provisória destinada a ministrar elementos para a ação penal.",
    "Correta. Arts. 9º, 10, § 2º, 11, 12 e 15; o relatório conclui sobre indícios (art. 22), sem julgamento."),
   ("A atuação do oficial de serviço foi irregular, pois só o encarregado pode apreender objetos.", "Errada. O art. 12, b, autoriza a apreensão antes da instauração."),
   ("O escrivão deveria ser oficial, pois o crime envolve armamento.", "Errada. A regra do art. 11 depende do posto do indiciado, não do objeto."),
   ("A portaria é nula porque não foi baixada em 48 horas contadas do furto.", "Errada. Foi baixada no dia seguinte, e o prazo de 48 horas (DGPM-315) conta do conhecimento; além disso, não é prazo do CPPM."),
  ], correta=0,
  comentario="O IPM apura; o encarregado relata; o MPM denuncia ou requer arquivamento; o juiz decide.",
  fonte=f"{CPPM}, arts. 9º–15 e 22, p. 24–32; {A41}, slides 7, 11–21 e 29.", armadilha="Atribuir ao IPM função de julgamento.", tempo=5),
 dict(n=11, tipo="VF", nivel="N2", ctx=False, conceitos=["DIRT2-IPM-CONCEITO"],
  competencia="Reconhecer a finalidade e o valor instrutório do IPM.",
  afirmacao="O IPM é instrução provisória cuja finalidade precípua é ministrar elementos necessários à propositura da ação penal; os exames, perícias e avaliações realizados regularmente por peritos idôneos são, porém, efetivamente instrutórios da ação penal.",
  correta=True,
  comentario="Verdadeira. Art. 9º e parágrafo único, resumidos no slide 13.",
  fonte=f"{CPPM}, art. 9º, p. 24; {A41}, slides 11–13.", armadilha="Negar valor instrutório às perícias regulares.", tempo=1),
 dict(n=12, tipo="OBJ", nivel="N2", ctx=False, conceitos=["DIRT2-PJM"],
  competencia="Identificar os titulares do poder de PJM e o erro de citação do slide.",
  enunciado="O slide 6 da Aula 4.1 atribui a definição de Polícia Judiciária Militar ao ‘Art. 7º CPMM’, e os slides 8–9 listam os titulares. Assinale a alternativa correta.",
  alternativas=[
   ("O diploma correto é o CPPM; seu art. 7º enumera as autoridades que exercem a PJM (entre elas comandantes de distritos navais, diretores e chefes de órgãos e comandantes de forças, unidades ou navios); a frase definitória citada no slide não aparece literalmente no art. 7º.",
    "Correta. ‘CPMM’ é [POSSÍVEL ERRO NA FONTE]; a definição transcrita no slide acompanha a referência a anexo de portaria da MB."),
   ("‘CPMM’ é sigla oficial do Código Penal Militar da Marinha.", "Errada. Não há diploma com essa sigla no corpus; o art. 7º citado é do CPPM."),
   ("O art. 7º do CPPM define a PJM exatamente com as palavras do slide.", "Errada. O texto do art. 7º (corpus, p. 21–22) enumera autoridades; não traz aquela definição."),
   ("A PJM é exercida apenas pelo Comandante da Marinha.", "Errada. A lista inclui várias autoridades, conforme as jurisdições."),
  ], correta=0,
  comentario="Registro de fonte: o slide deve ser lido como ‘art. 7º do CPPM’. A terminologia do corpus (‘ministros da Marinha’) é anterior à atual (‘Comandante da Marinha’), usada no slide 8.",
  fonte=f"{A41}, slides 6 e 8–9; {CPPM}, art. 7º, p. 21–22.", armadilha="Aceitar a sigla sem conferir o diploma.", tempo=2),
 dict(n=13, tipo="DIS", nivel="N3", ctx=True, conceitos=["DIRT2-MEDIDAS-URGENTES", "DIRT2-IPM-INSTAURACAO"],
  competencia="Fundamentar a atuação desde o conhecimento do fato até a portaria.",
  contexto="Em um sábado, o oficial de dia de uma capitania toma conhecimento de que um cabo acabou de ferir um marinheiro com uma barra de ferro no pátio. O comandante está em viagem e retorna na segunda-feira.",
  enunciado="Descreva, com fundamento, o que o oficial de dia deve fazer imediatamente e o que depende da autoridade de PJM, incluindo as regras de designação do encarregado e do escrivão.",
  gabarito="**Gabarito:** Imediato (art. 10, § 2º, e art. 12): o oficial de dia não aguarda a delegação; deve, se possível, dirigir-se ao local e preservar o estado das coisas, apreender a barra e objetos relacionados, efetuar a prisão do infrator observadas as regras legais (art. 244, citado no art. 12, c) e colher todas as provas. Depende da autoridade: a instauração por portaria, com objeto preciso (slide 14), nos modos do art. 10; a norma administrativa citada no slide 16 (DGPM-315) indica 48 horas do conhecimento. Encarregado: oficial, sempre que possível, de posto não inferior a capitão-tenente (art. 15). Escrivão: indiciado praça → sargento, subtenente ou suboficial (art. 11), designado pelo encarregado se não o fez a autoridade.\n\n**Plena:** separa atos urgentes e instauração, com as regras de designação. **Parcial:** omite a não necessidade de aguardar delegação. **Insuficiente:** afirma que nada pode ser feito até segunda-feira.",
  criterios=["Questão: atos urgentes × instauração (0,2)", "Normas: arts. 10 § 2º, 11, 12, 15 (0,2)", "Aplicação ao caso (0,3)", "Limite: 48 h é norma administrativa; escrivão conforme o indiciado (0,2)", "Conclusão (0,1)"],
  fonte=f"{CPPM}, arts. 10–15, p. 24–28; {A41}, slides 14–21.", armadilha="Aguardar o comandante.", tempo=7),
 dict(n=14, tipo="DIS", nivel="N4", ctx=True, conceitos=["DIRT2-PJM-DELEGACAO", "DIRT2-IPM-INSTAURACAO", "DIRT2-PJM"], modos=["pra-safar", "completo"],
  competencia="Resolver problema de competência para instaurar e conduzir IPM com hierarquia envolvida.",
  contexto="Um capitão de corveta, comandante de uma OM, recebe comunicação de que o seu imediato, capitão de corveta mais antigo que ele, teria desviado verba. O comandante designa, por portaria, um capitão-tenente como encarregado e um cabo como escrivão.",
  enunciado="Aponte os vícios e a solução legal, fundamentando.",
  gabarito="**Gabarito:** (1) Infrator de posto igual ao do comandante e mais antigo: a autoridade deve comunicar o fato à autoridade superior competente para que esta faça a delegação (art. 10, § 1º). (2) A delegação deve recair em oficial de posto superior ao do indiciado; não sendo possível, do mesmo posto, desde que mais antigo (art. 7º, §§ 2º–3º). Capitão-tenente é de posto inferior ao indiciado. (3) Escrivão: indiciado oficial → segundo ou primeiro-tenente (art. 11); cabo não atende. (4) As providências urgentes do art. 12 permanecem possíveis enquanto se aguarda a delegação (art. 10, § 2º). (5) Encarregado, sempre que possível, de posto não inferior a capitão-tenente (art. 15) — requisito mínimo que não supera a regra de hierarquia do art. 7º.\n\n**Plena:** três vícios e solução com arts. 7º, 10, 11. **Parcial:** identifica o vício do escrivão, mas não o da competência. **Insuficiente:** considera tudo regular porque o comandante é autoridade de PJM.",
  criterios=["Questões: competência para instaurar, encarregado, escrivão (0,2)", "Normas: arts. 7º §§ 2º–3º, 10 §§ 1º–2º, 11, 15 (0,2)", "Aplicação (0,3)", "Limite: art. 15 como mínimo × regra hierárquica (0,2)", "Conclusão (0,1)"],
  fonte=f"{CPPM}, arts. 7º, 10, 11 e 15, p. 22–28; {A41}, slides 8–9 e 14–15.", armadilha="Tomar a titularidade genérica de PJM como suficiente.", tempo=10),
]

M09 = [
 dict(n=1, tipo="VF", nivel="N1", ctx=False, conceitos=["DIRT2-OITIVAS"],
  competencia="Reconhecer o horário das inquirições no IPM.",
  afirmacao="No IPM, testemunhas e indiciado devem ser ouvidos durante o dia, entre as 7h e as 18h, salvo caso de urgência inadiável, que constará da respectiva assentada.",
  correta=True,
  comentario="Verdadeira. Art. 19 do CPPM e slide 24.",
  fonte=f"{CPPM}, art. 19, p. 29; {A41}, slide 24.", armadilha="Esquecer a exigência de registrar a urgência.", tempo=1),
 dict(n=2, tipo="OBJ", nivel="N2", ctx=False, conceitos=["DIRT2-OITIVAS"],
  competencia="Aplicar o limite de duração da inquirição.",
  enunciado="Sobre a duração das inquirições no IPM (art. 19, § 2º, do CPPM), assinale a alternativa correta.",
  alternativas=[
   ("A testemunha não será inquirida por mais de quatro horas consecutivas, sendo-lhe facultado descanso de meia hora sempre que tiver de prestar declarações além desse termo.",
    "Correta. Texto do § 2º."),
   ("A inquirição não pode ultrapassar duas horas.", "Errada. O limite é de quatro horas consecutivas."),
   ("Após quatro horas o descanso de uma hora é obrigatório.", "Errada. O descanso é de meia hora e é facultado."),
   ("Não há limite quando a testemunha é militar.", "Errada. A regra não distingue."),
  ], correta=0,
  comentario="O slide 24 resume: ‘não terá duração superior a 4 horas. Havendo necessidade, deve haver descanso de meia hora’.",
  fonte=f"{CPPM}, art. 19, § 2º, p. 29; {A41}, slide 24.", armadilha="Números trocados.", tempo=1),
 dict(n=3, tipo="COR", nivel="N2", ctx=True, conceitos=["DIRT2-OITIVAS", "DIRT2-SIGILO-ACESSO", "DIRT2-INCOMUNICABILIDADE", "DIRT2-TESTEMUNHA-INDICIADO"],
  competencia="Associar situações às regras de garantias no IPM.",
  titulo="Associe a situação à regra aplicável",
  chaves=[("A", "Deve ser informado da qualidade em que é ouvido"), ("B", "Encarregado pode permitir acesso do advogado"), ("C", "Regra ensinada como não recepcionada pela CF/88"), ("D", "Depoimento não concluído às 18h prossegue no dia seguinte")],
  itens=[
   ("Suspeito chamado a depor.", "A"),
   ("Advogado do indiciado pede para conhecer os autos.", "B"),
   ("Encarregado quer manter o indiciado preso sem comunicação com ninguém.", "C"),
   ("Inquirição iniciada às 16h ainda está em curso às 18h.", "D"),
  ],
  comentario="Slides 24, 26 e 27; CPPM arts. 16, 17 e 19, § 2º.",
  fonte=f"{A41}, slides 24–27; {CPPM}, arts. 16–19, p. 28–30.", armadilha="Tratar o sigilo como absoluto.", tempo=2),
 dict(n=4, tipo="OBJ", nivel="N2", ctx=True, conceitos=["DIRT2-OITIVAS"],
  competencia="Aplicar a regra do depoimento não concluído.",
  enunciado="Uma testemunha começa a depor às 15h. Às 18h o depoimento não terminou e não há urgência. Qual a providência correta?",
  alternativas=[
   ("Encerrar o depoimento às 18h, com assentada, e prosseguir no dia seguinte em hora determinada pelo encarregado.",
    "Correta. Art. 19, §§ 1º–2º."),
   ("Prosseguir até o fim, pois ainda não se completaram quatro horas.", "Errada. O limite das 18h independe das quatro horas."),
   ("Prosseguir até o fim, desde que haja descanso de meia hora.", "Errada. O descanso não autoriza ultrapassar as 18h sem urgência."),
   ("Anular o depoimento e reiniciá-lo outro dia.", "Errada. O depoimento é encerrado e retomado, não anulado."),
  ], correta=0,
  comentario="Dois limites convivem: janela horária (7h–18h) e duração (4 horas consecutivas). Se o dia seguinte não for útil, adia-se para o primeiro dia útil, salvo urgência (§ 3º).",
  fonte=f"{CPPM}, art. 19, §§ 1º–3º, p. 29–30; {A41}, slide 24.", armadilha="Aplicar só o limite de quatro horas.", tempo=2),
 dict(n=5, tipo="OBJ", nivel="N3", ctx=True, conceitos=["DIRT2-TESTEMUNHA-INDICIADO"],
  competencia="Reconhecer a qualidade material de investigado e as garantias correspondentes.",
  enunciado="Em IPM sobre sumiço de munição, o encarregado intima o cabo responsável pelo paiol ‘como testemunha’, embora já existam registros apontando que ele retirou as caixas. No termo, o cabo não é advertido de nada e acaba confessando. Considerando a ementa do STM reproduzida no slide 25:",
  alternativas=[
   ("O suposto autor deveria ser ouvido na qualidade de indiciado, podendo fazer-se acompanhar por advogado; sem advertência sobre o silêncio e a assistência de advogado, a declaração constitui prova ilícita que não deve integrar os autos.",
    "Correta. É a tese da ementa (STM, HC 0000209-20.2016.7.00.0000), coerente com a CF, art. 5º, LVI e LXIII."),
   ("A confissão é válida, pois testemunha tem o dever de dizer a verdade.", "Errada. O rótulo formal não se sobrepõe à situação material de investigado."),
   ("A confissão é válida, mas deve ser repetida em juízo.", "Errada. A ementa afirma que a prova é ilícita e não deve integrar os autos do inquérito."),
   ("Todo o IPM é nulo e deve ser arquivado pelo encarregado.", "Errada. A consequência apontada é a exclusão da prova; e a autoridade militar não arquiva IPM."),
  ], correta=0,
  comentario="[NÃO CONFIRMADO NA FONTE PRIMÁRIA] A ementa foi lida no slide 25; o inteiro teor e a ata oficiais do STM não puderam ser acessados nesta sessão. A resposta usa só a tese transcrita pelo professor.",
  fonte=f"{A41}, slides 24–25; {CF}, art. 5º, LVI e LXIII, p. 18.", armadilha="Aceitar o rótulo de testemunha.", tempo=3),
 dict(n=6, tipo="VF", nivel="N3", ctx=True, conceitos=["DIRT2-TESTEMUNHA-INDICIADO"],
  competencia="Aplicar a consequência da falta de advertência.",
  afirmacao="Se um investigado ouvido no IPM não foi advertido do direito ao silêncio e de ser assistido por advogado, a tese da ementa do STM apresentada em aula é que sua declaração constitui prova ilícita e não deve integrar os autos do inquérito.",
  correta=True,
  comentario="Verdadeira. Item 2 da ementa reproduzida no slide 25. [NÃO CONFIRMADO NA FONTE PRIMÁRIA] Inteiro teor não acessado.",
  fonte=f"{A41}, slide 25; {CF}, art. 5º, LVI, p. 18.", armadilha="Tratar como mera irregularidade sanável.", tempo=1),
 dict(n=7, tipo="OBJ", nivel="N3", ctx=True, conceitos=["DIRT2-SIGILO-ACESSO"],
  competencia="Conciliar o sigilo do IPM com o acesso do defensor.",
  enunciado="O advogado de um sargento indiciado pede ao encarregado acesso aos depoimentos já tomados e ao laudo já juntado. Pede também para ser avisado previamente de uma busca que ainda será realizada. O encarregado nega tudo, afirmando que ‘o IPM é sigiloso’. Assinale a análise mais adequada.",
  alternativas=[
   ("O sigilo (art. 16) não é absoluto contra a defesa quanto aos elementos já documentados; a diligência ainda não realizada pode ser preservada do conhecimento prévio.",
    "Correta. O slide 26 afirma que o encarregado pode permitir o acesso do advogado. [NÃO CONFIRMADO NA FONTE PRIMÁRIA] A distinção entre elementos documentados e diligências em curso corresponde à Súmula Vinculante 14 do STF, cujo texto oficial não pôde ser conferido nesta sessão."),
   ("A negativa é correta em tudo, porque o IPM é sigiloso por lei.", "Errada. O próprio art. 16 ressalva a possibilidade de conhecimento pelo advogado, e a CF assegura a assistência de advogado (art. 5º, LXIII)."),
   ("O advogado tem direito a tudo, inclusive a ser avisado da busca futura.", "Errada. O acesso defensivo não alcança diligência ainda não realizada, cuja eficácia depende do sigilo."),
   ("Só o juiz pode decidir sobre o acesso, nunca o encarregado.", "Errada. O art. 16 atribui ao encarregado a possibilidade de permitir o acesso."),
  ], correta=0,
  comentario="Fórmula de prova: ‘sigiloso, mas não contra o defensor quanto ao que já está documentado’. Evite as duas respostas absolutas.",
  fonte=f"{CPPM}, art. 16, p. 28; {A41}, slide 26; {CF}, art. 5º, LXIII, p. 18.", armadilha="Sigilo absoluto × acesso irrestrito.", tempo=3),
 dict(n=8, tipo="OBJ", nivel="N3", ctx=True, conceitos=["DIRT2-INCOMUNICABILIDADE"],
  competencia="Identificar dispositivos do CPPM ensinados como não recepcionados e o erro de citação do slide.",
  enunciado="Um encarregado de IPM, com base no CPPM, decide manter incomunicável por três dias um indiciado legalmente preso. Considerando o slide 27 e a CF/88, assinale a alternativa correta.",
  alternativas=[
   ("A incomunicabilidade está no art. 17 do CPPM (o slide a atribui ao art. 18) e é ensinada como não recepcionada; a CF veda a incomunicabilidade do preso até mesmo durante o estado de defesa (art. 136, § 3º, IV).",
    "Correta. [POSSÍVEL ERRO NA FONTE] O slide atribui incomunicabilidade e detenção ao art. 18; no corpus, incomunicabilidade é o art. 17 e detenção é o art. 18. [APROFUNDAMENTO ANALÍTICO DE SUPORTE] A vedação no estado de defesa reforça a incompatibilidade em situação normal."),
   ("É válida, pois o CPPM é lei especial e prevalece sobre a CF.", "Errada. Norma infraconstitucional não prevalece sobre a Constituição."),
   ("É válida por até três dias, desde que comunicada ao juiz.", "Errada. Reproduz o texto do art. 17 sem considerar a não recepção ensinada."),
   ("É válida apenas em crimes propriamente militares.", "Errada. A vedação constitucional à incomunicabilidade não traz essa ressalva."),
  ], correta=0,
  comentario="[PONTO DE INCERTEZA] Quanto à detenção sem flagrante do art. 18, o slide afirma a não recepção; a CF, art. 5º, LXI, contém ressalva para transgressão militar e crime propriamente militar. O corpus não resolve o alcance dessa ressalva sobre o art. 18; a questão cobra apenas a incomunicabilidade.",
  fonte=f"{A41}, slide 27; {CPPM}, arts. 17–18, p. 28–29; {CF}, art. 5º, LXI–LXIII, p. 18; art. 136, § 3º, IV, p. 119.", armadilha="Aplicar o texto do CPPM sem filtro constitucional.", tempo=3),
 dict(n=9, tipo="OBJ", nivel="N4", ctx=True, conceitos=["DIRT2-OITIVAS", "DIRT2-TESTEMUNHA-INDICIADO", "DIRT2-SIGILO-ACESSO", "DIRT2-ENCARREGADO-ATRIBUICOES"],
  competencia="Auditar a condução de um IPM identificando várias irregularidades e a consequência de cada uma.",
  enunciado="Em um IPM: (I) o encarregado ouve às 22h, sem registrar urgência, um marinheiro já apontado por câmeras como autor, qualificando-o como testemunha e sem adverti-lo; (II) nega ao advogado do indiciado acesso a laudo já juntado; (III) determina exame de corpo de delito na vítima; (IV) inquire outra testemunha das 8h às 13h sem pausa. Assinale a alternativa correta.",
  alternativas=[
   ("I viola o horário (art. 19) e a qualidade material de investigado, tornando a declaração prova ilícita segundo a ementa do STM; II contraria a leitura do sigilo como não oponível ao defensor quanto a elementos documentados; III é atribuição regular; IV excede quatro horas consecutivas sem o descanso facultado.",
    "Correta. Arts. 13, f, 16 e 19; slides 23–26."),
   ("Só I é irregular; II, III e IV estão amparados na discricionariedade do encarregado.", "Errada. II e IV também contrariam regras ensinadas."),
   ("I, II, III e IV são irregulares, pois exame de corpo de delito depende de ordem judicial.", "Errada. O art. 13, f, atribui ao encarregado determinar exames e perícias."),
   ("I é regular porque a urgência pode ser presumida em crime militar.", "Errada. A urgência deve ser inadiável e constar da assentada."),
  ], correta=0,
  comentario="[NÃO CONFIRMADO NA FONTE PRIMÁRIA] Ementa do STM (slide 25) e Súmula Vinculante 14 — textos oficiais não acessados. [INFERÊNCIA PEDAGÓGICA] Em IV, o texto legal faculta o descanso ‘sempre que tiver de prestar declarações além daquele termo’; a questão considera irregular a inquirição de cinco horas consecutivas sem pausa.",
  fonte=f"{CPPM}, arts. 13, 16 e 19, p. 27–30; {A41}, slides 23–26.", armadilha="Tratar todas as decisões do encarregado como discricionárias.", tempo=6),
 dict(n=10, tipo="OBJ", nivel="N4", ctx=True, conceitos=["DIRT2-TESTEMUNHA-INDICIADO", "DIRT2-INCOMUNICABILIDADE", "DIRT2-ENCARREGADO-ATRIBUICOES"],
  competencia="Distinguir o que o encarregado pode fazer, o que deve solicitar e o que não pode fazer.",
  enunciado="O encarregado de um IPM quer: (1) manter o indiciado preso incomunicável; (2) decretar a prisão preventiva do indiciado; (3) proceder a reconhecimento de pessoas; (4) ouvir como testemunha o próprio suspeito para ‘evitar que ele se cale’. Assinale a alternativa correta.",
  alternativas=[
   ("(1) não pode, conforme a não recepção ensinada; (2) não decreta — pode solicitar a decretação; (3) pode; (4) não pode, sob pena de ilicitude da prova.",
    "Correta. Slide 27; art. 18, parágrafo único (solicitação); art. 13, e; slide 25."),
   ("(1) pode por três dias; (2) pode decretar; (3) pode; (4) pode.", "Errada. Ignora a não recepção, a reserva de jurisdição e a tese do STM."),
   ("(1) não pode; (2) pode decretar em crime militar; (3) não pode sem juiz; (4) não pode.", "Errada. O encarregado não decreta prisão preventiva; reconhecimento é atribuição sua."),
   ("(1) pode; (2) não pode; (3) não pode; (4) pode, com advertência posterior.", "Errada. Advertência posterior não sana a oitiva sem as garantias."),
  ], correta=0,
  comentario="O relatório pode pronunciar-se sobre a conveniência da prisão preventiva (art. 22), mas decretar é ato judicial.",
  fonte=f"{CPPM}, arts. 13, 17, 18 e 22, p. 27–31; {A41}, slides 23, 25, 27 e 29.", armadilha="Atribuir poderes jurisdicionais ao encarregado.", tempo=5),
 dict(n=11, tipo="VF", nivel="N2", ctx=False, conceitos=["DIRT2-SIGILO-ACESSO"],
  competencia="Rejeitar a leitura absoluta do sigilo.",
  afirmacao="Como o IPM é sigiloso, o advogado do indiciado nunca pode ter acesso aos autos antes do oferecimento da denúncia.",
  correta=False,
  comentario="Falsa. O art. 16 do CPPM e o slide 26 afirmam que o encarregado pode permitir que o advogado tome conhecimento dos autos.",
  fonte=f"{CPPM}, art. 16, p. 28; {A41}, slide 26.", armadilha="Sigilo absoluto.", tempo=1),
 dict(n=12, tipo="OBJ", nivel="N2", ctx=False, conceitos=["DIRT2-ENCARREGADO-ATRIBUICOES"],
  competencia="Identificar atribuições do encarregado do IPM.",
  enunciado="NÃO é atribuição do encarregado do IPM:",
  alternativas=[
   ("Mandar arquivar os autos quando concluir que não houve crime.", "Correta (não é atribuição). Art. 24: a autoridade militar não pode mandar arquivar."),
   ("Proceder a acareações.", "Errada. É atribuição (art. 13, e; slide 23)."),
   ("Proceder a buscas e apreensões nos termos do CPPM.", "Errada. É atribuição (art. 13, h)."),
   ("Ouvir o ofendido, as testemunhas e o indiciado.", "Errada. É atribuição (art. 13, b–d)."),
  ], correta=0,
  comentario="Distrator recorrente: poderes decisórios (arquivar, denunciar, decretar prisão) não pertencem ao encarregado.",
  fonte=f"{CPPM}, arts. 13 e 24, p. 27–32; {A41}, slides 23 e 30.", armadilha="Encarregado arquiva.", tempo=1),
 dict(n=13, tipo="DIS", nivel="N3", ctx=True, conceitos=["DIRT2-TESTEMUNHA-INDICIADO", "DIRT2-OITIVAS"],
  competencia="Fundamentar a nulidade de oitiva de investigado rotulado como testemunha.",
  contexto="Em IPM sobre agressão, o encarregado intima o Cabo X como testemunha, embora dois depoimentos já o apontem como agressor. A oitiva começa às 17h30, termina às 21h, sem registro de urgência. O cabo não é advertido e admite ter agredido.",
  enunciado="Analise a validade da oitiva e o destino da declaração, com fundamento.",
  gabarito="**Gabarito:** Questão: validade da oitiva de quem é materialmente investigado. Norma: slide 24 (o depoente deve ter ciência da qualidade em que é ouvido); ementa do STM no slide 25 (suposto autor deve ser ouvido como indiciado, podendo ter advogado; a falta de advertência sobre silêncio e advogado gera prova ilícita que não deve integrar os autos); CF, art. 5º, LVI e LXIII; CPPM, art. 19 (horário). Aplicação: já havia indícios contra o cabo; foi rotulado testemunha; não houve advertência; a oitiva ultrapassou as 18h sem urgência registrada. Limite: a ilicitude atinge a declaração, não necessariamente os demais elementos independentes do IPM; e quem exclui ou declara ilícita a prova não é o encarregado sozinho arquivando o IPM. Conclusão: declaração ilícita, a ser desentranhada; os demais elementos seguem.\n\n**Plena:** qualidade material + advertência + horário + extensão da ilicitude. **Parcial:** reconhece a ilicitude, mas ignora o horário ou afirma nulidade de todo o IPM. **Insuficiente:** valida a confissão por ter sido espontânea. [NÃO CONFIRMADO NA FONTE PRIMÁRIA] inteiro teor do HC do STM.",
  criterios=["Questão: validade da oitiva (0,2)", "Normas: art. 19 CPPM; ementa STM; CF LVI e LXIII (0,2)", "Aplicação aos três vícios (0,3)", "Limite: alcance da ilicitude (0,2)", "Conclusão (0,1)"],
  fonte=f"{A41}, slides 24–25; {CPPM}, art. 19, p. 29; {CF}, art. 5º, LVI e LXIII, p. 18.", armadilha="Validar pela espontaneidade.", tempo=7),
 dict(n=14, tipo="DIS", nivel="N4", ctx=True, conceitos=["DIRT2-SIGILO-ACESSO", "DIRT2-INCOMUNICABILIDADE", "DIRT2-TESTEMUNHA-INDICIADO", "DIRT2-OITIVAS"],
  competencia="Elaborar parecer sobre garantias defensivas em IPM com vários atos questionados.",
  contexto="Um sargento está preso em flagrante por crime militar. O encarregado do IPM (a) determina que ele fique incomunicável ‘por três dias, conforme o CPPM’; (b) nega ao advogado acesso a todos os documentos, inclusive depoimentos já tomados; (c) marca a oitiva do sargento para as 19h, sem urgência; (d) recusa-se a informar ao advogado a data de uma busca que ainda fará.",
  enunciado="Na qualidade de assessor jurídico, indique quais atos são irregulares e quais são defensáveis, com fundamento e ressalvas de fonte.",
  gabarito="**Gabarito:** (a) Irregular: a incomunicabilidade (CPPM art. 17 — o slide 27 cita art. 18 [POSSÍVEL ERRO NA FONTE]) é ensinada como não recepcionada; a CF garante ao preso comunicação com família e advogado (art. 5º, LXII–LXIII) e veda a incomunicabilidade até no estado de defesa (art. 136, § 3º, IV). (b) Irregular em parte: o IPM é sigiloso (art. 16), mas o encarregado pode permitir o acesso do advogado, e a leitura ensinada é de que os elementos já documentados não são oponíveis ao defensor [NÃO CONFIRMADO NA FONTE PRIMÁRIA — SV 14]. (c) Irregular: oitiva entre 7h e 18h, salvo urgência inadiável registrada (art. 19); ademais, deve ser ouvido como indiciado e advertido do silêncio e da assistência de advogado (slides 24–25; CF LXIII). (d) Defensável: diligência ainda não realizada pode ser preservada do conhecimento prévio, sob pena de frustração.\n\n**Plena:** quatro atos com fundamento e ressalvas. **Parcial:** trata (b) e (d) da mesma forma. **Insuficiente:** considera o sigilo absoluto ou aplica o art. 17 literalmente.",
  criterios=["Questões: quatro atos (0,2)", "Normas: CPPM 16, 17, 19; CF 5º LXII–LXIII, 136 § 3º IV (0,2)", "Aplicação (0,3)", "Limites e ressalvas de fonte (documentado × em curso; erro do slide) (0,2)", "Conclusão (0,1)"],
  fonte=f"{CPPM}, arts. 16–19, p. 28–30; {A41}, slides 24–27; {CF}, art. 5º, LXII–LXIII, p. 18; art. 136, § 3º, IV, p. 119.", armadilha="Tratar todos os atos como igualmente ilegais ou legais.", tempo=10),
]
