from conceitos import A31, A41, A42, CPM, CPPM, CF, EM

M10 = [
 dict(n=1, tipo="VF", nivel="N1", ctx=False, conceitos=["DIRT2-REMESSA-ARQUIVAMENTO"],
  competencia="Reconhecer a vedação de arquivamento pela autoridade militar.",
  afirmacao="A autoridade militar não pode mandar arquivar autos de inquérito, ainda que o IPM conclua pela inexistência de crime ou pela inimputabilidade do indiciado.",
  correta=True,
  comentario="Verdadeira. CPPM art. 24; slide 30 (‘em hipótese alguma’).",
  fonte=f"{CPPM}, art. 24, p. 32; {A41}, slide 30.", armadilha="Admitir arquivamento quando a conclusão é favorável ao indiciado.", tempo=1),
 dict(n=2, tipo="OBJ", nivel="N2", ctx=False, conceitos=["DIRT2-PRAZOS-IPM"],
  competencia="Conhecer os prazos de conclusão do IPM e seus termos iniciais.",
  enunciado="Sobre os prazos do IPM (art. 20 do CPPM), assinale a alternativa correta.",
  alternativas=[
   ("Indiciado preso: 20 dias, contados do dia em que se executar a ordem de prisão; solto: 40 dias, contados da instauração; somente o prazo do solto pode ser prorrogado por mais 20 dias pela autoridade militar superior.",
    "Correta. Art. 20, caput e § 1º; slide 28."),
   ("Preso: 40 dias; solto: 20 dias; ambos prorrogáveis por 20 dias.", "Errada. Inverte os prazos e estende a prorrogação ao preso."),
   ("Preso e solto: 40 dias da instauração, prorrogáveis pelo juiz.", "Errada. Os prazos e termos iniciais são distintos; a prorrogação é da autoridade militar superior."),
   ("Preso: 20 dias da instauração; solto: 40 dias da instauração; prorrogação de 20 dias para ambos.", "Errada. O termo inicial do preso é a execução da prisão e a prorrogação é só do solto."),
  ], correta=0,
  comentario="O slide 28 não menciona os termos iniciais; a lei os fixa. Prorrogação exige exames/perícias iniciados não concluídos ou diligência indispensável e pedido oportuno (§ 1º).",
  fonte=f"{CPPM}, art. 20, p. 30; {A41}, slide 28.", armadilha="Prorrogar o prazo do preso.", tempo=2),
 dict(n=3, tipo="COR", nivel="N2", ctx=True, conceitos=["DIRT2-DISPENSA-IPM"],
  competencia="Identificar hipóteses de dispensa do IPM.",
  titulo="O IPM pode ser dispensado? Associe",
  chaves=[("S", "Sim — hipótese de dispensa ensinada"), ("N", "Não — não é hipótese de dispensa")],
  itens=[
   ("Auto de prisão em flagrante que, por si só, esclarece o fato e a autoria.", "S"),
   ("Crime contra a honra decorrente de publicação cujo autor está identificado.", "S"),
   ("Desacato a superior hierárquico dentro da OM.", "N"),
   ("Desobediência a decisão da Justiça Militar.", "S"),
   ("Furto de material em que ainda não se sabe o autor.", "N"),
  ],
  comentario="A dispensa por desacato refere-se à autoridade judiciária militar (CPM art. 341), não a superior hierárquico. O slide 31 omite a exigência de autor identificado nos crimes contra a honra e a hipótese de fato e autoria esclarecidos por documentos (art. 28, a).",
  fonte=f"{CPPM}, arts. 27–28, p. 33–34; {CPM}, arts. 341 e 349, p. 147–148; {A41}, slide 31.", armadilha="Estender a dispensa a qualquer desacato.", tempo=2),
 dict(n=4, tipo="OBJ", nivel="N2", ctx=True, conceitos=["DIRT2-RELATORIO-AUTOS"],
  competencia="Identificar o conteúdo obrigatório do relatório do IPM.",
  enunciado="Ao concluir um IPM sobre extravio de munição, o encarregado redige relatório. Qual conteúdo está de acordo com o CPPM?",
  alternativas=[
   ("Diligências feitas, pessoas ouvidas, resultados obtidos, dia, hora e lugar do fato; em conclusão, se há infração disciplinar a punir ou indício de crime, pronunciando-se justificadamente sobre a conveniência da prisão preventiva no caso de crime.",
    "Correta. Art. 22."),
   ("Declaração de culpa do indiciado e pena sugerida.", "Errada. O relatório não julga nem fixa pena."),
   ("Pedido de arquivamento, se não houver crime.", "Errada. A autoridade militar não arquiva (art. 24); o arquivamento é judicial, a requerimento do MPM."),
   ("Apenas a lista das pessoas ouvidas, pois a conclusão cabe ao MPM.", "Errada. O relatório deve ser minucioso e conter conclusão."),
  ], correta=0,
  comentario="O slide 29 fala em ‘indício de crime, autoria e conveniência da prisão preventiva’; a lei acrescenta a possibilidade de concluir por infração disciplinar a punir.",
  fonte=f"{CPPM}, arts. 21–22, p. 31; {A41}, slide 29.", armadilha="Relatório com juízo condenatório.", tempo=2),
 dict(n=5, tipo="OBJ", nivel="N3", ctx=True, conceitos=["DIRT2-PRAZOS-IPM"],
  competencia="Contar o prazo do IPM quando a prisão ocorre após a instauração.",
  enunciado="Um IPM é instaurado em 1º de março com o indiciado solto. Em 11 de março, o indiciado é preso por ordem judicial, executada no mesmo dia. Qual é o raciocínio correto sobre o prazo de conclusão?",
  alternativas=[
   ("Com a prisão, incide o prazo de 20 dias contado do dia em que se executou a ordem de prisão, sem possibilidade da prorrogação prevista para o solto.",
    "Correta. Art. 20: prazo do preso conta da execução da prisão; a prorrogação do § 1º refere-se ao ‘último prazo’ (solto)."),
   ("Continua o prazo de 40 dias contado de 1º de março, prorrogável por 20.", "Errada. A situação de preso atrai o prazo e o termo inicial próprios."),
   ("O prazo passa a ser de 20 dias contado de 1º de março, logo já estaria quase vencido.", "Errada. O termo inicial do preso é a execução da prisão."),
   ("Soma-se 40 + 20 dias, pois houve as duas situações.", "Errada. Não há soma de prazos."),
  ], correta=0,
  comentario="[INFERÊNCIA PEDAGÓGICA] O art. 20 não trata expressamente da mudança de situação no curso do IPM; a solução aplica o prazo do preso a partir da execução da prisão, conforme a literalidade do termo inicial. No CPM, art. 16, inclui-se o dia do começo no cômputo dos prazos; o CPPM tem regras próprias não tratadas nos slides.",
  fonte=f"{CPPM}, art. 20, p. 30; {A41}, slide 28.", armadilha="Contar o prazo do preso da instauração.", tempo=3),
 dict(n=6, tipo="VF", nivel="N3", ctx=True, conceitos=["DIRT2-DISPENSA-IPM"],
  competencia="Delimitar a dispensa do IPM nos crimes contra a administração da Justiça Militar.",
  afirmacao="Um marinheiro desacata o imediato do navio durante uma faina. Como o desacato está entre as hipóteses de dispensa ensinadas, o IPM pode ser dispensado.",
  correta=False,
  comentario="Falsa. A dispensa refere-se ao desacato à **autoridade judiciária militar** (CPPM art. 28, c, remetendo ao CPM art. 341), não a superior hierárquico.",
  fonte=f"{CPPM}, art. 28, c, p. 34; {CPM}, art. 341, p. 147; {A41}, slide 31.", armadilha="Qualquer desacato.", tempo=2),
 dict(n=7, tipo="OBJ", nivel="N3", ctx=True, conceitos=["DIRT2-SINDICANCIA"],
  competencia="Distinguir IPM e sindicância e seus limites.",
  enunciado="Durante sindicância sobre a morte de um marinheiro em acidente de serviço, o sindicante quer: (1) prender um cabo suspeito de ter alterado o local; (2) solicitar exumação; (3) realizar busca na casa do cabo, fora da OM. Surgem, ainda, indícios de crime militar. Assinale a alternativa correta.",
  alternativas=[
   ("Nenhuma das três medidas é admitida em sindicância; os indícios de crime militar autorizam a instauração de IPM, que é modo previsto no art. 10, ‘f’, do CPPM.",
    "Correta. Slides 33–34 e CPPM art. 10, f."),
   ("As três são admitidas, pois a sindicância apura óbito.", "Errada. O slide 34 veda as três."),
   ("Só a busca é vedada, porque ocorre fora da OM.", "Errada. Prisão e exumação também são vedadas."),
   ("O sindicante deve converter a sindicância em ação penal.", "Errada. Ação penal é promovida pelo MPM."),
  ], correta=0,
  comentario="A sindicância é apuração simplificada, especialmente quando é evidente a inocorrência de crime ou contravenção disciplinar; surgindo indício de crime, o caminho é o IPM. [INFORMAÇÃO NÃO PRESENTE NA FONTE] A norma administrativa que regula a sindicância não foi fornecida; o curso usa apenas os slides.",
  fonte=f"{A41}, slides 33–34; {CPPM}, art. 10, f, p. 25.", armadilha="Dar à sindicância poderes do IPM.", tempo=3),
 dict(n=8, tipo="OBJ", nivel="N3", ctx=True, conceitos=["DIRT2-FORO-MILITAR", "DIRT2-ART9-DOLOSO-VIDA"],
  competencia="Aplicar a remessa de IPM à justiça comum nos crimes dolosos contra a vida de civil.",
  enunciado="Um IPM apura homicídio doloso praticado por um sargento da Marinha contra civil em lugar sujeito à administração militar, fora dos contextos do art. 9º, § 2º, do CPM. Assinale o destino dos autos.",
  alternativas=[
   ("A Justiça Militar encaminhará os autos do IPM à justiça comum (CPPM art. 82, § 2º), pois a competência é do Tribunal do Júri (CPM art. 9º, § 1º).",
    "Correta. Slides 37–38 da Aula 4.1."),
   ("Os autos permanecem na Justiça Militar da União, pois o fato ocorreu em lugar sujeito à administração militar.", "Errada. Fora do § 2º, o § 1º atribui a competência ao júri."),
   ("O encarregado remete os autos diretamente ao Tribunal do Júri.", "Errada. O art. 82, § 2º, atribui à Justiça Militar o encaminhamento."),
   ("O IPM é arquivado por incompetência da PJM.", "Errada. Não há arquivamento por esse motivo; há encaminhamento."),
  ], correta=0,
  comentario="O lugar pode fazer do fato crime militar (art. 9º, II, ‘b’), mas o § 1º desloca a competência para o júri, salvo os contextos do § 2º.",
  fonte=f"{CPPM}, art. 82, § 2º, p. 54; {CPM}, art. 9º, §§ 1º–2º, p. 19–20; {A41}, slides 37–40.", armadilha="Competência pelo lugar.", tempo=3),
 dict(n=9, tipo="OBJ", nivel="N4", ctx=True, conceitos=["DIRT2-PRAZOS-IPM", "DIRT2-RELATORIO-AUTOS", "DIRT2-REMESSA-ARQUIVAMENTO"],
  competencia="Auditar o encerramento de um IPM com vários atos sucessivos.",
  enunciado="Em IPM com indiciado solto, instaurado em 2 de maio, o encarregado: (I) pede prorrogação em 30 de maio, porque uma perícia iniciada não terminou, e a autoridade superior concede 20 dias; (II) conclui o relatório afirmando que ‘o indiciado é culpado e deve ser condenado’; (III) remete os autos ao comandante, que, discordando, ‘arquiva o IPM’; (IV) o MPM, depois, recebe os autos e requer arquivamento, que o juiz determina. Assinale a alternativa correta.",
  alternativas=[
   ("I é regular; II é inadequado, pois o relatório indica indícios e não julga; III é vedado (art. 24); IV é o caminho legal do arquivamento.",
    "Correta. Art. 20, § 1º; art. 22; art. 24; slide 30."),
   ("I é irregular porque a prorrogação só cabe ao juiz; II é regular; III é regular; IV é irregular.", "Errada. Troca a autoridade da prorrogação e admite o arquivamento pela autoridade militar."),
   ("I, II, III e IV são regulares.", "Errada. II e III contrariam a natureza do IPM e o art. 24."),
   ("I é irregular porque o pedido foi feito após 40 dias; II e III são irregulares; IV é irregular porque só o MPM arquiva.", "Errada. O pedido de 30/5 foi feito antes do término dos 40 dias, e o arquivamento é determinado pelo juiz a requerimento do MPM."),
  ], correta=0,
  comentario="O § 1º exige pedido em tempo oportuno, de modo a ser atendido antes do término do prazo; 30 de maio está folgadamente dentro dos 40 dias contados de 2 de maio, qualquer que seja a regra de cômputo adotada.",
  fonte=f"{CPPM}, arts. 20, 22 e 24, p. 30–32; {A41}, slides 28–30.", armadilha="Comandante arquiva quando discorda.", tempo=6),
 dict(n=10, tipo="OBJ", nivel="N4", ctx=True, conceitos=["DIRT2-FORO-MILITAR", "DIRT2-ART9-DOLOSO-VIDA", "DIRT2-ART9-II"],
  competencia="Distribuir competências entre JMU, Justiça Militar estadual e júri.",
  enunciado="Indique a competência: (I) militar do Exército em operação de garantia da lei e da ordem conforme o art. 142 da CF mata dolosamente um civil; (II) policial militar estadual, em serviço, lesiona outro policial militar em serviço; (III) policial militar estadual, em serviço, mata dolosamente um civil; (IV) marinheiro de folga furta o celular de um civil em uma praça. Assinale a alternativa correta.",
  alternativas=[
   ("I: Justiça Militar da União; II: Justiça Militar estadual; III: júri; IV: não é crime militar, logo não é da Justiça Militar.",
    "Correta. CPM art. 9º, § 2º, III; CF art. 125, § 4º (JME, ressalvado o júri quando a vítima for civil); IV sem alínea do art. 9º."),
   ("I: júri; II: JMU; III: JME; IV: JMU.", "Errada. Desconsidera o § 2º, confunde a JMU com a estadual e qualifica IV pelo agente."),
   ("I: JMU; II: JMU; III: JMU; IV: JMU.", "Errada. A JMU não julga militares estaduais e IV não é crime militar."),
   ("I: JMU; II: JME; III: JME; IV: justiça comum por ser crime de militar em folga, mas militar.", "Errada. Em III há a ressalva do júri; IV não é crime militar."),
  ], correta=0,
  comentario="[NÃO CONFIRMADO NA FONTE PRIMÁRIA] Os precedentes indicados na transferência (STF, HC 109.544 e Inq. 4.923) não puderam ser lidos; a solução se apoia apenas na CF, no CPM e no CPPM do corpus. Organização territorial da JMU fica fora do recorte.",
  fonte=f"{CF}, arts. 124 e 125, § 4º, p. 108–109; {CPM}, art. 9º, p. 18–20; {A41}, slides 35–40.", armadilha="Confundir JMU e JME; competência pela pessoa.", tempo=6),
 dict(n=11, tipo="VF", nivel="N2", ctx=True, conceitos=["DIRT2-REMESSA-ARQUIVAMENTO"],
  competencia="Identificar quem determina o arquivamento do IPM.",
  afirmacao="Recebidos os autos, se o Ministério Público Militar entender que não há base para denúncia, ele próprio determina o arquivamento do IPM.",
  correta=False,
  comentario="Falsa. Pelo slide 30, apenas o Juiz Federal da Justiça Militar, a requerimento do representante do MPM, poderá mandar arquivar os autos do IPM. O fluxo do slide 32 simplifica a seta ‘não oferece denúncia → arquivamento’.",
  fonte=f"{A41}, slides 30 e 32; {CPPM}, arts. 24–25, p. 32–33.", armadilha="MPM arquiva sozinho.", tempo=1),
 dict(n=12, tipo="OBJ", nivel="N3", ctx=True, conceitos=["DIRT2-REMESSA-ARQUIVAMENTO"],
  competencia="Aplicar a possibilidade de novo IPM após o arquivamento.",
  enunciado="Um IPM foi arquivado por falta de indícios de autoria. Meses depois, surgem imagens novas que identificam o autor. Assinale a alternativa correta.",
  alternativas=[
   ("O arquivamento não obsta a instauração de outro IPM se novas provas aparecerem, ressalvados o caso julgado e a extinção da punibilidade.",
    "Correta. Art. 25 do CPPM."),
   ("Nada pode ser feito, pois o arquivamento faz coisa julgada.", "Errada. O art. 25 permite novo inquérito com novas provas."),
   ("O comandante pode desarquivar o IPM por ato próprio.", "Errada. A autoridade militar não arquiva nem desarquiva autos judiciais; o juiz remete ao MPM (§ 1º)."),
   ("Só é possível se o autor confessar.", "Errada. Basta prova nova quanto ao fato, ao indiciado ou a terceiro."),
  ], correta=0,
  comentario="O juiz, verificando a hipótese, remete os autos ao MPM para os fins do art. 10, ‘c’ (requisição de IPM).",
  fonte=f"{CPPM}, art. 25, p. 33; {A41}, slide 30.", armadilha="Arquivamento definitivo.", tempo=2),
 dict(n=13, tipo="DIS", nivel="N3", ctx=True, conceitos=["DIRT2-PRAZOS-IPM", "DIRT2-RELATORIO-AUTOS", "DIRT2-REMESSA-ARQUIVAMENTO"],
  competencia="Fundamentar a condução do encerramento do IPM.",
  contexto="Um IPM com indiciado solto chega ao 38º dia com uma perícia de balística iniciada e não concluída. O encarregado pretende (a) pedir prorrogação ao juiz; (b) concluir o relatório declarando o indiciado ‘culpado’; (c) enviar os autos ao comandante para arquivamento se a perícia não confirmar a autoria.",
  enunciado="Corrija as três intenções, com fundamento.",
  gabarito="**Gabarito:** (a) A prorrogação de 20 dias cabe à **autoridade militar superior**, não ao juiz, e só para indiciado solto, quando houver exames ou perícias iniciados e não concluídos ou diligência indispensável; o pedido deve ser feito em tempo oportuno, antes do término (art. 20, § 1º). No 38º dia, o pedido é oportuno se atendido até o 40º. Não havendo nova prorrogação, laudos posteriores são remetidos ao juiz para juntada (§ 2º). (b) O relatório menciona diligências, pessoas ouvidas, resultados, dia, hora e lugar e conclui se há infração disciplinar a punir ou indício de crime, com manifestação sobre a prisão preventiva — sem declarar culpa (art. 22; slide 29). (c) A autoridade militar não pode mandar arquivar (art. 24); os autos vão ao Juiz Federal da Justiça Militar e o arquivamento só ocorre por decisão judicial a requerimento do MPM (slide 30).\n\n**Plena:** três correções com a autoridade certa em cada uma. **Parcial:** corrige (c), mas mantém o juiz em (a). **Insuficiente:** valida o arquivamento pelo comandante.",
  criterios=["Questões: prorrogação, relatório, arquivamento (0,2)", "Normas: arts. 20 §§ 1º–2º, 22, 24 (0,2)", "Aplicação (0,3)", "Limites: prazo oportuno; laudos posteriores (0,2)", "Conclusão (0,1)"],
  fonte=f"{CPPM}, arts. 20–24, p. 30–32; {A41}, slides 28–30.", armadilha="Prorrogação judicial.", tempo=7),
 dict(n=14, tipo="DIS", nivel="N4", ctx=True, conceitos=["DIRT2-FORO-MILITAR", "DIRT2-CRIME-MILITAR-CONCEITO", "DIRT2-DISPENSA-IPM", "DIRT2-SINDICANCIA"],
  competencia="Elaborar solução integrada sobre instrumento de apuração e foro.",
  contexto="Em uma OM, três fatos chegam ao comandante: (1) um civil, ex-prestador de serviço, é preso em flagrante ao sair com geradores da Marinha, e o auto de flagrante esclarece fato e autoria; (2) um marinheiro morre afogado em treinamento e, até aqui, nada indica crime ou transgressão; (3) um cabo de folga, em shopping, agride fisicamente outro civil.",
  enunciado="Para cada fato, indique o instrumento de apuração adequado e o foro, fundamentando e declarando o que não pode ser afirmado com os dados.",
  gabarito="**Gabarito:** (1) Civil contra patrimônio sob administração militar → crime militar (CPM art. 9º, III, ‘a’) → Justiça Militar (CF art. 124). O auto de prisão em flagrante que, por si só, esclarece fato e autoria dispensa o IPM (CPPM art. 27; slide 31), ressalvados exames exigidos (corpo de delito quando houver vestígios, identificação e avaliação da coisa quando o valor influir na pena) e com breve relatório. (2) Apuração simplificada de óbito quando evidente a inocorrência de crime ou contravenção disciplinar: sindicância (slide 33), sem prisão, exumação ou busca fora da OM (slide 34); surgindo indício de crime militar, instaura-se IPM (art. 10, f). (3) Militar da ativa de folga contra civil fora de área militar: sem alínea do art. 9º, II → não é crime militar → não é da Justiça Militar; não cabe IPM como instrumento de crime militar. Não se pode afirmar, sem mais dados, eventual repercussão disciplinar.\n\n**Plena:** instrumento e foro corretos nos três, com as ressalvas. **Parcial:** acerta foro, mas exige IPM em (1) ou prisão na sindicância em (2). **Insuficiente:** manda (3) à Justiça Militar por ser militar.",
  criterios=["Questões: instrumento e foro por fato (0,2)", "Normas: CF 124; CPM 9º; CPPM 10 f, 27; slides 31–34 (0,2)", "Aplicação (0,3)", "Limites e dados faltantes (0,2)", "Conclusão (0,1)"],
  fonte=f"{CF}, art. 124, p. 108; {CPM}, art. 9º, p. 18–19; {CPPM}, arts. 10 e 27, p. 24–33; {A41}, slides 31–35.", armadilha="Foro pela pessoa; IPM obrigatório.", tempo=10),
]

M11 = [
 dict(n=1, tipo="VF", nivel="N1", ctx=False, conceitos=["DIRT2-STM-COMPOSICAO"],
  competencia="Reconhecer a composição numérica do STM.",
  afirmacao="O Superior Tribunal Militar compõe-se de quinze ministros vitalícios, nomeados pelo Presidente da República.",
  correta=True,
  comentario="Verdadeira. Slide 5 da Aula 4.2 e CF art. 123, que acrescenta: depois de aprovada a indicação pelo Senado Federal.",
  fonte=f"{A42}, slide 5; {CF}, art. 123, p. 108.", armadilha="Esquecer a vitaliciedade ou a aprovação do Senado.", tempo=1),
 dict(n=2, tipo="OBJ", nivel="N2", ctx=False, conceitos=["DIRT2-STM-COMPOSICAO"],
  competencia="Distribuir as vagas militares e civis do STM.",
  enunciado="Assinale a distribuição correta das vagas do STM.",
  alternativas=[
   ("3 oficiais-generais da Marinha, 4 do Exército, 3 da Aeronáutica (todos da ativa e do posto mais elevado) e 5 civis.", "Correta. Slide 5; CF art. 123."),
   ("4 da Marinha, 3 do Exército, 3 da Aeronáutica e 5 civis.", "Errada. Troca Marinha e Exército."),
   ("3 de cada Força e 6 civis.", "Errada. O Exército tem 4 vagas e são 5 civis."),
   ("5 militares e 10 civis.", "Errada. São 10 militares e 5 civis."),
  ], correta=0,
  comentario="Memorização estruturada: 10 militares (3-4-3) + 5 civis (3 advogados + 2 juízes/MPM) = 15.",
  fonte=f"{A42}, slides 5–6; {CF}, art. 123, p. 108.", armadilha="3-4-3 invertido.", tempo=1),
 dict(n=3, tipo="COR", nivel="N2", ctx=False, conceitos=["DIRT2-STM-COMPOSICAO"],
  competencia="Associar números e requisitos à composição do STM.",
  titulo="Associe o número ao elemento da composição do STM",
  chaves=[("A", "15"), ("B", "4"), ("C", "3"), ("D", "5"), ("E", "35")],
  itens=[
   ("Total de ministros.", "A"),
   ("Oficiais-generais do Exército.", "B"),
   ("Advogados entre os civis.", "C"),
   ("Ministros civis.", "D"),
   ("Idade mínima (‘mais de’) dos ministros civis.", "E"),
  ],
  comentario="A CF, art. 123, parágrafo único (redação da EC 122/2022), fala em ‘mais de trinta e cinco e menos de setenta anos’ e exige, para os advogados, notório saber jurídico, conduta ilibada e mais de dez anos de efetiva atividade profissional — detalhes não presentes no slide.",
  fonte=f"{A42}, slide 5; {CF}, art. 123, p. 108.", armadilha="Trocar números.", tempo=2),
 dict(n=4, tipo="OBJ", nivel="N2", ctx=False, conceitos=["DIRT2-JMU-ORGAOS"],
  competencia="Identificar órgãos da Justiça Militar da União listados no slide 4.",
  enunciado="Com base no slide 4 da Aula 4.2 (Lei nº 8.457/92, art. 1º), qual das opções NÃO é órgão da Justiça Militar da União?",
  alternativas=[
   ("Ministério Público Militar.", "Correta (não é órgão). O MPM atua perante a JMU, mas não integra a lista de órgãos do slide 4."),
   ("Superior Tribunal Militar.", "Errada. Consta da lista (e da CF, art. 122, I)."),
   ("Corregedoria da Justiça Militar.", "Errada. Consta da lista."),
   ("Juízes Federais da Justiça Militar, titulares e substitutos.", "Errada. Consta da lista."),
  ], correta=0,
  comentario="O MPM é titular da ação penal militar (CPPM art. 29). [INFORMAÇÃO NÃO PRESENTE NA FONTE] O texto da Lei nº 8.457/1992 não foi fornecido; a lista é a do slide.",
  fonte=f"{A42}, slide 4; {CF}, art. 122, p. 108; {CPPM}, art. 29, p. 34.", armadilha="Incluir o MPM no Judiciário.", tempo=1),
 dict(n=5, tipo="OBJ", nivel="N3", ctx=True, conceitos=["DIRT2-STM-COMPETENCIA"],
  competencia="Identificar a competência originária do STM apresentada em aula.",
  enunciado="Um vice-almirante é acusado de crime militar. No mesmo período, um capitão-tenente impetra habeas corpus diretamente no STM. Considerando o slide 7 da Aula 4.2, assinale a alternativa correta.",
  alternativas=[
   ("O STM processa e julga originariamente o oficial-general nos crimes militares, e o slide também inclui os pedidos de habeas corpus e habeas data entre as competências originárias.",
    "Correta. Reproduz o slide 7."),
   ("O vice-almirante é julgado em primeira instância e o STM só atua em recurso.", "Errada. Oficiais-generais das Forças Armadas estão na competência originária."),
   ("O STM não julga habeas corpus.", "Errada. O slide lista habeas corpus e habeas data."),
   ("O STM julga originariamente qualquer oficial.", "Errada. O slide restringe a oficiais-generais."),
  ], correta=0,
  comentario="[INFORMAÇÃO NÃO PRESENTE NA FONTE] O slide não detalha as hipóteses em que o HC é da competência originária do STM (autoridade coatora etc.); o curso não amplia esse ponto por falta de texto legal no corpus.",
  fonte=f"{A42}, slide 7; {CF}, art. 124, parágrafo único, p. 108.", armadilha="Estender a competência originária a todo oficial.", tempo=2),
 dict(n=6, tipo="VF", nivel="N3", ctx=True, conceitos=["DIRT2-STM-COMPETENCIA"],
  competencia="Delimitar a competência originária do STM.",
  afirmacao="Um capitão de fragata acusado de crime militar será processado e julgado originariamente pelo STM, por ser oficial superior.",
  correta=False,
  comentario="Falsa. O slide 7 restringe a competência originária criminal do STM a oficiais-generais das Forças Armadas. O órgão de primeira instância para os demais não integra o recorte da T2 e não é cobrado.",
  fonte=f"{A42}, slide 7.", armadilha="Oficial superior × oficial-general.", tempo=1),
 dict(n=7, tipo="OBJ", nivel="N3", ctx=True, conceitos=["DIRT2-STM-COMPETENCIA"],
  competencia="Identificar a competência recursal do STM.",
  enunciado="Um sargento condenado por crime militar na primeira instância da Justiça Militar da União quer recorrer. Segundo o slide 7, a quem cabe julgar a apelação?",
  alternativas=[
   ("Ao STM, que julga as apelações e os recursos das decisões das Auditorias da Justiça Militar.", "Correta. Slide 7."),
   ("Ao STF, pois é o único tribunal superior em matéria penal.", "Errada. O slide atribui ao STM o julgamento das apelações."),
   ("Ao Tribunal de Justiça do Estado.", "Errada. Não é órgão da JMU."),
   ("Ao próprio juízo que condenou.", "Errada. A apelação é julgada pelo tribunal."),
  ], correta=0,
  comentario="Fixe a dupla função do STM no recorte: originária (oficiais-generais; HC; HD) e recursal (apelações e recursos das Auditorias).",
  fonte=f"{A42}, slide 7.", armadilha="Enviar ao STF.", tempo=2),
 dict(n=8, tipo="OBJ", nivel="N4", ctx=True, conceitos=["DIRT2-STM-COMPETENCIA", "DIRT2-STM-COMPOSICAO", "DIRT2-FORO-MILITAR"],
  competencia="Integrar composição, competência do STM e natureza militar do crime.",
  enunciado="Considere: (I) um general de exército é acusado de crime militar; (II) um almirante de esquadra é acusado de furto de celular em um shopping, de folga, sem qualquer circunstância do art. 9º do CPM; (III) um civil com mais de 35 e menos de 70 anos, advogado de notório saber e conduta ilibada com 12 anos de atividade, é nomeado ministro do STM sem aprovação do Senado; (IV) um sargento condenado em primeira instância da JMU apela. Assinale a alternativa correta.",
  alternativas=[
   ("I e IV são competência do STM (originária e recursal); II não é crime militar, logo não é da Justiça Militar; III contraria a CF, que exige aprovação da indicação pelo Senado.",
    "Correta. Slide 7; CPM art. 9º; CF arts. 123 e 124."),
   ("I, II e IV são do STM, pois os agentes são militares; III é regular.", "Errada. A Justiça Militar julga crimes militares, não pessoas; e a CF exige aprovação do Senado."),
   ("Só I é do STM; IV vai ao STF; III é regular.", "Errada. Apelações das Auditorias são julgadas pelo STM; nomeação sem Senado é irregular."),
   ("I e II são do STM (oficiais-generais); IV é da primeira instância; III é regular.", "Errada. II não é crime militar e IV é recurso ao STM."),
  ], correta=0,
  comentario="O filtro ‘é crime militar?’ precede ‘qual órgão?’. Essa ordem evita o erro de competência pela pessoa.",
  fonte=f"{A42}, slides 5–7; {CF}, arts. 123–124, p. 108; {CPM}, art. 9º, p. 18–19.", armadilha="Competência pela qualidade de oficial-general sem crime militar.", tempo=5),
 dict(n=9, tipo="DIS", nivel="N3", ctx=True, conceitos=["DIRT2-STM-COMPOSICAO", "DIRT2-JMU-ORGAOS"],
  competencia="Explicar a composição do STM e conferir o slide com a Constituição.",
  contexto="Em uma revisão em grupo, um aspirante afirma: ‘O STM tem 15 ministros: 5 militares de cada Força e os civis são escolhidos entre advogados, juízes e o MPM, que também é órgão da Justiça Militar’.",
  enunciado="Corrija a afirmação, indicando o que o slide ensina e o que a CF acrescenta.",
  gabarito="**Gabarito:** Correções: (1) são 15 ministros vitalícios, nomeados pelo Presidente da República, **depois de aprovada a indicação pelo Senado** (CF art. 123); (2) militares: 3 da Marinha, 4 do Exército e 3 da Aeronáutica, oficiais-generais da ativa do posto mais elevado (‘4 estrelas’, slide 5) — total 10, não 15; (3) 5 civis, com mais de 35 e menos de 70 anos (CF, redação da EC 122/2022): 3 advogados de notório saber jurídico e conduta ilibada, com mais de dez anos de atividade, e 2 por escolha paritária entre juízes auditores e membros do MPM (o slide fala em ‘Juízes Federais da Justiça Militar’, denominação atual usada pelo professor); (4) o MPM não é órgão da JMU no slide 4, que lista STM, Corregedoria, Juiz-Corregedor Auxiliar, os demais órgãos judiciários indicados e Juízes Federais da Justiça Militar.\n\n**Plena:** quatro correções com a CF. **Parcial:** corrige os números, mas mantém o MPM como órgão. **Insuficiente:** só repete ‘15 ministros’.",
  criterios=["Questão: erros da afirmação (0,2)", "Normas: slide 5 e CF art. 123; slide 4 (0,2)", "Aplicação/correções (0,3)", "Limites: requisitos que só a CF traz; terminologia (0,2)", "Conclusão (0,1)"],
  fonte=f"{A42}, slides 4–6; {CF}, arts. 122–123, p. 108.", armadilha="MPM como órgão; 5 por Força.", tempo=6),
 dict(n=10, tipo="DIS", nivel="N4", ctx=True, conceitos=["DIRT2-STM-COMPETENCIA", "DIRT2-FORO-MILITAR", "DIRT2-ART9-II"],
  competencia="Resolver caso de competência do STM filtrando antes a natureza militar do fato.",
  contexto="Um contra-almirante, comandante de distrito naval, (a) é acusado de desviar recursos sob administração militar; (b) meses depois, de folga e em viagem particular, agride um civil em um restaurante; (c) um sargento condenado pela primeira instância da JMU no processo relativo a outro desvio apela.",
  enunciado="Indique, para cada situação, se há competência do STM e em que modalidade (originária ou recursal), fundamentando.",
  gabarito="**Gabarito:** (a) Militar da ativa contra patrimônio sob a administração militar → art. 9º, II, ‘e’ → crime militar; o acusado é oficial-general das Forças Armadas → competência **originária** do STM (slide 7). (b) Folga, viagem particular, vítima civil, fora de lugar sujeito à administração militar e sem serviço → nenhuma alínea do art. 9º → não é crime militar; a condição de oficial-general não atrai a Justiça Militar (CF art. 124: a JM julga crimes militares). (c) Apelação de decisão da primeira instância da JMU → competência **recursal** do STM (slide 7). Limite: o recorte não abrange a organização da primeira instância, que não precisa ser descrita.\n\n**Plena:** filtro de crime militar antes da competência + modalidade correta nos três. **Parcial:** acerta (a) e (c), mas atribui (b) ao STM. **Insuficiente:** decide tudo pela patente.",
  criterios=["Questões: natureza militar e modalidade da competência (0,2)", "Normas: CF 124; CPM 9º II ‘e’; slide 7 (0,2)", "Aplicação às três situações (0,3)", "Limite: competência não é pela pessoa; recorte da 1ª instância (0,2)", "Conclusão (0,1)"],
  fonte=f"{A42}, slide 7; {CF}, art. 124, p. 108; {CPM}, art. 9º, II, p. 18–19.", armadilha="Competência pela patente.", tempo=9),
]

# ─────────────────────────────── Simulados ───────────────────────────────
SG01 = [  # Diagnóstico — cobre toda a matriz
 dict(n=1, tipo="OBJ", nivel="N2", ctx=True, conceitos=["DIRT2-TEMPO-CRIME", "DIRT2-LUGAR-CRIME"],
  competencia="Diagnóstico: tempo e lugar do crime.",
  enunciado="Um cabo, a bordo de navio atracado em Salvador, envia uma encomenda com explosivo que detona em Recife dias depois, ferindo um sargento. Para lugar e tempo do crime, respectivamente, o CPM considera:",
  alternativas=[
   ("Lugar: Salvador e Recife (ubiquidade nos comissivos); tempo: o do envio (atividade).", "Correta. Arts. 5º e 6º."),
   ("Lugar: só Recife; tempo: o da explosão.", "Errada. Aplica a teoria do resultado às duas regras."),
   ("Lugar: só Salvador; tempo: o da explosão.", "Errada. Inverte as teorias."),
   ("Lugar: onde deveria realizar-se a ação omitida; tempo: o do envio.", "Errada. A regra da ação omitida é dos omissivos."),
  ], correta=0, comentario="Tempo: atividade. Lugar dos comissivos: ubiquidade.",
  fonte=f"{CPM}, arts. 5º–6º, p. 17; {A31}, slides 6–9.", armadilha="Mesma teoria para tempo e lugar.", tempo=2),
 dict(n=2, tipo="VF", nivel="N2", ctx=True, conceitos=["DIRT2-DOLO", "DIRT2-CULPA"],
  competencia="Diagnóstico: dolo eventual × culpa consciente.",
  afirmacao="Quem prevê o resultado e confia sinceramente que conseguirá evitá-lo age com dolo eventual, pois conheceu o risco.",
  correta=False, comentario="Falsa. É culpa (art. 33, II, parte final). Dolo eventual exige assumir o risco de produzir o resultado.",
  fonte=f"{CPM}, art. 33, p. 26; {A31}, slide 17.", armadilha="Conhecer o risco = dolo.", tempo=1),
 dict(n=3, tipo="OBJ", nivel="N2", ctx=True, conceitos=["DIRT2-EXCL-ILICITUDE", "DIRT2-INEXIGIBILIDADE"],
  competencia="Diagnóstico: degrau do crime afastado.",
  enunciado="Um marinheiro destrói o cadeado de um armário de outro militar para retirar um extintor e apagar um incêndio que ameaçava o alojamento. Qual degrau do conceito de crime é afastado?",
  alternativas=[
   ("A ilicitude, por estado de necessidade: não há crime.", "Correta. Perigo atual não provocado, mal causado consideravelmente inferior (arts. 42, I, e 43)."),
   ("A culpabilidade, por inexigibilidade de conduta diversa.", "Errada. O caso preenche a excludente de ilicitude do art. 43."),
   ("A tipicidade, porque não houve dolo.", "Errada. Houve vontade de romper o cadeado."),
   ("Nenhum; há crime com pena reduzida.", "Errada. O art. 42 exclui o crime."),
  ], correta=0, comentario="Bens em conflito: cadeado × vidas e alojamento.",
  fonte=f"{CPM}, arts. 42–43, p. 29; {A31}, slides 25–26.", armadilha="Isenção de pena.", tempo=2),
 dict(n=4, tipo="OBJ", nivel="N2", ctx=True, conceitos=["DIRT2-DESIST-ARREP", "DIRT2-TENTATIVA"],
  competencia="Diagnóstico: desistência × tentativa.",
  enunciado="Um soldado começa a serrar a corrente do portão do paiol e para quando ouve a aproximação da ronda. Enquadramento:",
  alternativas=[
   ("Tentativa, pois a execução não prosseguiu por circunstância alheia à sua vontade.", "Correta. Art. 30, II."),
   ("Desistência voluntária, pois parou.", "Errada. Parou por fator externo."),
   ("Arrependimento eficaz.", "Errada. Não esgotou a execução nem impediu resultado por ação própria."),
   ("Ato preparatório impunível.", "Errada. Serrar a corrente já ataca o bem."),
  ], correta=0, comentario="‘Podia e não quis’ × ‘quis e não pôde’.",
  fonte=f"{CPM}, arts. 30–31, p. 25; {A31}, slides 44–45.", armadilha="Parar = desistir.", tempo=2),
 dict(n=5, tipo="VF", nivel="N2", ctx=False, conceitos=["DIRT2-AGRAVANTES-CABECAS"],
  competencia="Diagnóstico: cabeças.",
  afirmacao="Quando o crime é cometido por inferiores e um ou mais oficiais, são considerados cabeças os oficiais, assim como os inferiores que exercem função de oficial.",
  correta=True, comentario="Verdadeira. Art. 53, § 5º.",
  fonte=f"{CPM}, art. 53, § 5º, p. 33; {A31}, slide 54.", armadilha="Esquecer inferiores em função de oficial.", tempo=1),
 dict(n=6, tipo="OBJ", nivel="N3", ctx=True, conceitos=["DIRT2-ART9-II", "DIRT2-ART9-III"],
  competencia="Diagnóstico: crime militar pelo agente e pela alínea.",
  enunciado="Qual dos fatos é crime militar pelo CPM (edição do corpus)?",
  alternativas=[
   ("Militar reformado furta material do almoxarifado de uma OM.", "Correta. Art. 9º, III, ‘a’ (patrimônio sob administração militar)."),
   ("Militar da ativa, de folga, agride um civil em sua casa.", "Errada. Nenhuma alínea do art. 9º, II."),
   ("Civil agride outro civil na praia em frente a uma base.", "Errada. Não atinge instituição militar nas hipóteses do inciso III."),
   ("Militar da reserva ofende a honra de um amigo civil em festa particular.", "Errada. Não há hipótese do inciso III."),
  ], correta=0, comentario="Inciso III: reserva, reformado ou civil contra as instituições militares nas alíneas.",
  fonte=f"{CPM}, art. 9º, p. 18–19; {A31}, slides 61–62.", armadilha="Qualificar pelo agente.", tempo=3),
 dict(n=7, tipo="OBJ", nivel="N2", ctx=True, conceitos=["DIRT2-CRIME-163", "DIRT2-CRIME-160"],
  competencia="Diagnóstico: tipos em espécie.",
  enunciado="Um marinheiro, sozinho com o sargento na oficina, recusa a ordem de serviço de desmontar uma bomba. Qual tipo pode estar configurado?",
  alternativas=[
   ("Recusa de obediência (art. 163).", "Correta. Ordem sobre matéria de serviço."),
   ("Desrespeito a superior (art. 160).", "Errada. Não houve desrespeito e faltaria outro militar presente."),
   ("Rigor excessivo (art. 174).", "Errada. É crime do superior que pune."),
   ("Motim (art. 149).", "Errada. Exige reunião de militares."),
  ], correta=0, comentario="Uma elementar por tipo decide a questão.",
  fonte=f"{CPM}, arts. 149, 160, 163 e 174; {A31}, slides 52 e 68–71.", armadilha="Motim individual.", tempo=2),
 dict(n=8, tipo="OBJ", nivel="N2", ctx=True, conceitos=["DIRT2-MEDIDAS-URGENTES"],
  competencia="Diagnóstico: providências antes da portaria.",
  enunciado="O oficial de serviço encontra um marinheiro ferido e o agressor com a arma na mão. O que pode fazer antes da portaria?",
  alternativas=[
   ("Preservar o local, apreender a arma, prender o infrator observadas as regras legais e colher provas.", "Correta. Art. 12."),
   ("Nada, até a delegação.", "Errada. Art. 10, § 2º."),
   ("Instaurar o IPM e nomear escrivão.", "Errada. Instauração é ato da autoridade de PJM ou delegado."),
   ("Mandar arquivar se o agressor alegar legítima defesa.", "Errada. A autoridade militar não arquiva."),
  ], correta=0, comentario="Providências urgentes ≠ instauração.",
  fonte=f"{CPPM}, arts. 10, § 2º, 12 e 24; {A41}, slides 18–21.", armadilha="Esperar a portaria.", tempo=2),
 dict(n=9, tipo="VF", nivel="N2", ctx=True, conceitos=["DIRT2-TESTEMUNHA-INDICIADO"],
  competencia="Diagnóstico: qualidade do depoente.",
  afirmacao="Se o encarregado já dispõe de indícios de que a pessoa é autora do fato, pode ouvi-la como testemunha, desde que registre isso no termo.",
  correta=False, comentario="Falsa. O suposto autor deve ser ouvido como indiciado, com advertência sobre silêncio e advogado (slides 24–25; ementa do STM — [NÃO CONFIRMADO NA FONTE PRIMÁRIA]).",
  fonte=f"{A41}, slides 24–25; {CF}, art. 5º, LXIII, p. 18.", armadilha="Rótulo formal.", tempo=1),
 dict(n=10, tipo="OBJ", nivel="N2", ctx=False, conceitos=["DIRT2-PRAZOS-IPM"],
  competencia="Diagnóstico: prazos.",
  enunciado="Indiciado solto, IPM instaurado, perícia iniciada e não concluída ao final do prazo. Prazo e prorrogação:",
  alternativas=[
   ("40 dias da instauração, prorrogáveis por 20 pela autoridade militar superior.", "Correta. Art. 20, § 1º."),
   ("20 dias da instauração, prorrogáveis por 20.", "Errada. 20 dias é o prazo do preso."),
   ("40 dias, prorrogáveis pelo juiz por 40.", "Errada. Autoridade e duração erradas."),
   ("40 dias, improrrogáveis.", "Errada. O solto admite prorrogação."),
  ], correta=0, comentario="Preso 20 / solto 40 (+20).",
  fonte=f"{CPPM}, art. 20, p. 30; {A41}, slide 28.", armadilha="Prorrogação judicial.", tempo=1),
 dict(n=11, tipo="OBJ", nivel="N2", ctx=False, conceitos=["DIRT2-STM-COMPOSICAO", "DIRT2-STM-COMPETENCIA"],
  competencia="Diagnóstico: STM.",
  enunciado="Assinale a alternativa correta sobre o STM no recorte da T2.",
  alternativas=[
   ("15 ministros (3 MB, 4 EB, 3 FAB, 5 civis); julga originariamente oficiais-generais das Forças Armadas nos crimes militares e as apelações das decisões das Auditorias.", "Correta. Slides 5 e 7."),
   ("15 ministros, 5 de cada Força; julga originariamente todos os oficiais.", "Errada. Números e competência errados."),
   ("10 ministros militares e nenhum civil; só julga recursos.", "Errada. Há 5 civis e competência originária."),
   ("15 ministros; o MPM integra o tribunal.", "Errada. O MPM não é órgão da JMU."),
  ], correta=0, comentario="Composição e dupla competência.",
  fonte=f"{A42}, slides 4–7; {CF}, art. 123, p. 108.", armadilha="5 por Força.", tempo=2),
 dict(n=12, tipo="DIS", nivel="N3", ctx=True, conceitos=["DIRT2-FORO-MILITAR", "DIRT2-REMESSA-ARQUIVAMENTO", "DIRT2-CRIME-MILITAR-CONCEITO"],
  competencia="Diagnóstico integrado: da natureza do fato ao destino dos autos.",
  contexto="Um IPM apura furto de munição praticado por um cabo da ativa dentro do paiol da OM. Ao final, o encarregado conclui que ‘não há provas de autoria’ e o comandante determina o arquivamento.",
  enunciado="Diga se o fato é crime militar, qual é o foro e qual deveria ser o encaminhamento dos autos.",
  gabarito="**Gabarito:** militar da ativa contra patrimônio sob administração militar → art. 9º, II, ‘e’: crime militar → Justiça Militar (CF art. 124). A autoridade militar não pode arquivar (CPPM art. 24): os autos devem ser remetidos ao Juiz Federal da Justiça Militar (art. 23; slide 30); o arquivamento, se for o caso, só por decisão judicial a requerimento do MPM. Novas provas permitem novo IPM (art. 25).\n\n**Plena:** três etapas. **Parcial:** acerta crime militar, mas aceita o arquivamento pelo comandante. **Insuficiente:** afirma que falta de prova autoriza arquivamento administrativo.",
  criterios=["Natureza do fato (0,3)", "Foro (0,2)", "Vedação do art. 24 (0,3)", "Encaminhamento correto (0,2)"],
  fonte=f"{CPM}, art. 9º, II, e; {CPPM}, arts. 23–25; {CF}, art. 124; {A41}, slides 30–35.", armadilha="Comandante arquiva.", tempo=6),
]

SG02 = [  # Nível prova — formatos mistos e casos densos
 dict(n=1, tipo="OBJ", nivel="N3", ctx=True, conceitos=["DIRT2-TERRITORIALIDADE", "DIRT2-ART9-II"],
  competencia="Prova: alcance espacial e natureza militar.",
  enunciado="Em porto estrangeiro, a bordo de navio de guerra brasileiro, um sargento lesiona dolosamente um cabo, ambos da ativa. O país do porto processa o sargento. Assinale a alternativa correta.",
  alternativas=[
   ("Aplica-se a lei penal militar brasileira, ainda que haja processo estrangeiro, e o fato é crime militar pelo art. 9º, II, ‘a’.", "Correta. Art. 7º, caput e § 1º; art. 9º, II, a."),
   ("Não se aplica a lei brasileira enquanto houver processo estrangeiro.", "Errada. O caput do art. 7º diz o contrário."),
   ("Aplica-se, mas o fato é crime comum, pois ocorreu no exterior.", "Errada. O navio é extensão do território e há alínea ‘a’."),
   ("Aplica-se só se o crime atentar contra as instituições militares.", "Errada. Esse requisito é do § 2º (navios estrangeiros)."),
  ], correta=0, comentario="Dois filtros independentes: alcance da lei (art. 7º) e natureza militar (art. 9º).",
  fonte=f"{CPM}, arts. 7º e 9º, p. 17–19; {A31}, slides 10–12 e 61.", armadilha="Exigir o § 2º para navio brasileiro.", tempo=3),
 dict(n=2, tipo="COR", nivel="N3", ctx=True, conceitos=["DIRT2-EXCL-ILICITUDE", "DIRT2-INEXIGIBILIDADE", "DIRT2-IMPUTABILIDADE", "DIRT2-ERRO-DIREITO"],
  competencia="Prova: consequência jurídica de cada tese defensiva.",
  titulo="Associe a situação à consequência",
  chaves=[("A", "Não há crime"), ("B", "Não é culpado; responde quem coagiu/ordenou"), ("C", "Não é imputável"), ("D", "Pena pode ser atenuada ou substituída")],
  itens=[
   ("Cabo repele moderadamente agressão injusta e atual a colega.", "A"),
   ("Marinheiro, sob coação física irresistível, danifica equipamento.", "B"),
   ("Soldado com doença mental que o torna inteiramente incapaz de entender o ilícito agride colega.", "C"),
   ("Civil supõe lícito, por erro escusável de interpretação da lei, usar distintivo militar.", "D"),
  ],
  comentario="Arts. 42/44 (A), 38 e § 1º (B), 48 (C), 35 (D).",
  fonte=f"{CPM}, arts. 35, 38, 42, 44 e 48; {A31}, slides 25–37.", armadilha="Tudo como ‘isento de pena’.", tempo=3),
 dict(n=3, tipo="OBJ", nivel="N3", ctx=True, conceitos=["DIRT2-PRETERDOLO", "DIRT2-CRIME-209-210", "DIRT2-FATO-TIPICO"],
  competencia="Prova: resultado agravador e nexo.",
  enunciado="Um cabo dá um soco para lesionar um marinheiro, que cai e sofre fratura; no hospital, morre de infecção hospitalar sem relação com a fratura, conforme laudo que descarta o nexo. Enquadramento do cabo:",
  alternativas=[
   ("Responde pela lesão; a causa superveniente que por si só produziu a morte exclui a imputação do resultado.", "Correta. Art. 29, § 1º."),
   ("Lesão com resultado morte, preterdolosa.", "Errada. O laudo descarta o nexo entre a lesão e a morte."),
   ("Homicídio doloso.", "Errada. Não houve dolo de matar."),
   ("Nada, pois a morte não lhe é imputável.", "Errada. A lesão permanece imputável."),
  ], correta=0, comentario="O dado decisivo está no laudo.",
  fonte=f"{CPM}, arts. 29 e 209; {A31}, slides 15 e 23.", armadilha="Preterdolo automático.", tempo=3),
 dict(n=4, tipo="VF", nivel="N3", ctx=True, conceitos=["DIRT2-AUTORIA-PARTICIPACAO", "DIRT2-CONCURSO-MONISTA"],
  competencia="Prova: monista e participação.",
  afirmacao="Um marinheiro que apenas vigia a porta, sabendo do furto praticado por colegas, não responde pelo furto porque não subtraiu nada; no máximo, pratica transgressão.",
  correta=False, comentario="Falsa. Quem de qualquer modo concorre incide nas penas do crime (art. 53); a participação de somenos importância pode atenuar a pena (§ 3º).",
  fonte=f"{CPM}, art. 53, p. 32–33; {A31}, slides 49–50.", armadilha="Partícipe impune.", tempo=1),
 dict(n=5, tipo="OBJ", nivel="N4", ctx=True, conceitos=["DIRT2-ART9-DOLOSO-VIDA", "DIRT2-FORO-MILITAR", "DIRT2-REMESSA-ARQUIVAMENTO"],
  competencia="Prova: competência e destino do IPM em crime doloso contra a vida de civil.",
  enunciado="Um IPM apura: (I) marinheiro que, de serviço no portão da OM, mata dolosamente um civil em discussão pessoal; (II) fuzileiro que, em atividade de natureza militar realizada conforme o art. 142 da CF, mata dolosamente um civil. Assinale a alternativa correta.",
  alternativas=[
   ("I: crime militar da competência do júri, com encaminhamento dos autos do IPM à justiça comum pela Justiça Militar; II: competência da JMU pelo art. 9º, § 2º, III.", "Correta. CPM art. 9º, §§ 1º–2º; CPPM art. 82, § 2º."),
   ("I e II: JMU, pois ambos estavam em serviço.", "Errada. Em I não há contexto do § 2º."),
   ("I e II: júri.", "Errada. II está no § 2º, III."),
   ("I: o encarregado remete ao júri; II: o comandante arquiva por legítima atuação.", "Errada. O encaminhamento é pela Justiça Militar e a autoridade militar não arquiva."),
  ], correta=0, comentario="‘Em serviço’ não basta para o § 2º: é preciso um dos contextos.",
  fonte=f"{CPM}, art. 9º, §§ 1º–2º; {CPPM}, arts. 24 e 82, § 2º; {A41}, slides 37–40.", armadilha="Serviço = § 2º.", tempo=5),
 dict(n=6, tipo="OBJ", nivel="N3", ctx=True, conceitos=["DIRT2-SIGILO-ACESSO", "DIRT2-OITIVAS"],
  competencia="Prova: sigilo e oitivas.",
  enunciado="O encarregado nega ao advogado do indiciado acesso a depoimentos já tomados e marca a oitiva do indiciado para 20h, sem urgência. Assinale a alternativa correta.",
  alternativas=[
   ("Ambos os atos são questionáveis: o sigilo não é oponível ao defensor quanto a elementos documentados e a oitiva deve ocorrer entre 7h e 18h salvo urgência registrada.", "Correta. Arts. 16 e 19; slides 24 e 26 [NÃO CONFIRMADO NA FONTE PRIMÁRIA — SV 14]."),
   ("Ambos são regulares, porque o IPM é sigiloso e inquisitivo.", "Errada. Contraria o art. 19 e a leitura ensinada do sigilo."),
   ("Só o horário é irregular.", "Errada. A negativa integral de acesso a elementos documentados também é questionável."),
   ("Só a negativa é irregular.", "Errada. O horário também contraria o art. 19."),
  ], correta=0, comentario="Dois vícios independentes.",
  fonte=f"{CPPM}, arts. 16 e 19; {A41}, slides 24 e 26.", armadilha="Sigilo absoluto.", tempo=3),
 dict(n=7, tipo="OBJ", nivel="N3", ctx=True, conceitos=["DIRT2-DISPENSA-IPM", "DIRT2-SINDICANCIA"],
  competencia="Prova: instrumento de apuração.",
  enunciado="Qual situação autoriza dispensar o IPM?",
  alternativas=[
   ("Auto de prisão em flagrante que, por si só, esclarece fato e autoria.", "Correta. Art. 27; slide 31."),
   ("Óbito de militar em que se suspeita de crime, apurado por sindicância.", "Errada. Indício de crime leva a IPM (art. 10, f)."),
   ("Desacato a superior hierárquico.", "Errada. A dispensa é para desacato à autoridade judiciária militar."),
   ("Furto de autor desconhecido.", "Errada. Não há esclarecimento de autoria."),
  ], correta=0, comentario="Leia a hipótese de dispensa inteira, com seus requisitos.",
  fonte=f"{CPPM}, arts. 10, 27–28; {A41}, slides 31–34.", armadilha="Qualquer desacato.", tempo=2),
 dict(n=8, tipo="OBJ", nivel="N3", ctx=True, conceitos=["DIRT2-CRIME-174", "DIRT2-INEXIGIBILIDADE"],
  competencia="Prova: rigor excessivo e ordem ilegal.",
  enunciado="Um capitão-tenente ordena a um sargento que obrigue um marinheiro punido a carregar sacos de areia durante toda a madrugada, ofendendo-o com palavras. O sargento cumpre. Assinale a análise mais adequada.",
  alternativas=[
   ("O oficial pode responder por rigor excessivo (se não houver crime mais grave); o sargento não se beneficia da obediência se a ordem for manifestamente criminosa, e deve-se verificar sua participação.", "Correta. Arts. 38, § 2º, e 174."),
   ("Só o sargento responde, por ter executado.", "Errada. O oficial excedeu a faculdade de punir."),
   ("Ninguém responde, pois houve punição regulamentar.", "Errada. A punição com rigor não permitido é o núcleo do art. 174."),
   ("O sargento responde por insubordinação.", "Errada. Ele não recusou a ordem."),
  ], correta=0, comentario="[PONTO DE INCERTEZA] O caráter ‘manifestamente’ criminoso da ordem depende de circunstâncias do caso concreto.",
  fonte=f"{CPM}, arts. 38 e 174; {A31}, slides 36 e 71.", armadilha="Punição regulamentar legitima tudo.", tempo=3),
 dict(n=9, tipo="VF", nivel="N3", ctx=True, conceitos=["DIRT2-STM-COMPETENCIA", "DIRT2-FORO-MILITAR"],
  competencia="Prova: competência do STM e natureza do crime.",
  afirmacao="Todo crime praticado por oficial-general das Forças Armadas é julgado originariamente pelo STM.",
  correta=False, comentario="Falsa. O slide 7 fala em oficiais-generais ‘nos crimes militares’; sem crime militar, não há competência da Justiça Militar (CF art. 124).",
  fonte=f"{A42}, slide 7; {CF}, art. 124.", armadilha="Competência pela patente.", tempo=1),
 dict(n=10, tipo="OBJ", nivel="N4", ctx=True, conceitos=["DIRT2-IPM-INSTAURACAO", "DIRT2-TESTEMUNHA-INDICIADO", "DIRT2-PRAZOS-IPM", "DIRT2-RELATORIO-AUTOS"],
  competencia="Prova: auditoria completa de IPM.",
  enunciado="IPM com indiciado praça solto: portaria sem descrição do objeto; escrivão cabo; suspeito ouvido como testemunha sem advertência; relatório no 55º dia sem prorrogação, concluindo ‘culpado’. Quantas irregularidades há, dentre as ensinadas?",
  alternativas=[
   ("Cinco: objeto não descrito; escrivão fora da regra; oitiva sem a qualidade e advertência; prazo excedido sem prorrogação; relatório com juízo de culpa.", "Correta. Slides 14–15, 24–25, 28–29; arts. 11, 20 e 22."),
   ("Três: escrivão, prazo e relatório.", "Errada. Omite objeto da portaria e oitiva."),
   ("Duas: prazo e relatório.", "Errada. Omite três vícios."),
   ("Nenhuma, pois o IPM é peça informativa.", "Errada. A natureza informativa não afasta as regras."),
  ], correta=0, comentario="Escrivão para indiciado praça: sargento, subtenente ou suboficial (art. 11).",
  fonte=f"{CPPM}, arts. 11, 20 e 22; {A41}, slides 14–15 e 24–29.", armadilha="IPM sem regras.", tempo=5),
 dict(n=11, tipo="DIS", nivel="N3", ctx=True, conceitos=["DIRT2-INEXIGIBILIDADE", "DIRT2-CRIME-203"],
  competencia="Prova: coação moral em crime contra o dever militar.",
  contexto="Um marinheiro de vigia no passadiço dorme após ingerir, por conta própria, medicamento que sabia causar sonolência. Alega que um superior o ameaçou de punição se não tomasse o remédio.",
  enunciado="Analise a tipicidade e a tese defensiva.",
  gabarito="**Gabarito:** tipicidade: dormir o militar em serviço como vigia (art. 203), sem exigência de resultado. Tese: ameaça de punição é coação moral; nos crimes com violação do dever militar só se invoca coação física ou material (art. 40); além disso, uma ameaça de punição disciplinar dificilmente suprime a faculdade de agir (art. 38, a) [INFERÊNCIA PEDAGÓGICA]. Se houve ordem, não era para dormir em serviço; eventual responsabilidade do superior se analisa à parte. Conclusão: tese não afasta a culpabilidade; circunstâncias podem pesar na pena.\n\n**Plena:** tipo + art. 40 + análise da ordem. **Parcial:** reconhece o tipo mas aceita a coação. **Insuficiente:** nega o crime por falta de resultado.",
  criterios=["Tipicidade (0,3)", "Art. 40 aplicado (0,3)", "Ordem × conduta (0,2)", "Conclusão (0,2)"],
  fonte=f"{CPM}, arts. 38, 40 e 203; {A31}, slides 36–37 e 72.", armadilha="Aceitar coação moral.", tempo=7),
 dict(n=12, tipo="DIS", nivel="N4", ctx=True, conceitos=["DIRT2-ART9-III", "DIRT2-AUTORIA-PARTICIPACAO", "DIRT2-TENTATIVA", "DIRT2-DISPENSA-IPM"],
  competencia="Prova: caso integrado Penal–Processual.",
  contexto="Um civil e um cabo da ativa combinam retirar baterias de um depósito naval. O cabo desliga as câmeras; o civil entra e é preso em flagrante ainda dentro do depósito, com as baterias nas mãos. O auto de flagrante esclarece o fato e a participação de ambos.",
  enunciado="Analise: natureza militar do fato para cada agente, consumação/tentativa (declarando se o enunciado permite concluir), concurso de agentes e necessidade de IPM.",
  gabarito="**Gabarito:** Natureza: cabo da ativa contra patrimônio sob administração militar → art. 9º, II, ‘e’; civil contra patrimônio sob administração militar → art. 9º, III, ‘a’. Consumação: o enunciado indica prisão dentro do depósito, com os bens nas mãos — a interrupção se deu por circunstância alheia; a conclusão entre tentativa e consumação depende do critério de consumação do furto, **não tratado nos slides** — declarar [PONTO DE INCERTEZA] e fundamentar a posição adotada com o conceito do art. 30, I (reunião de todos os elementos da definição legal). Concurso: teoria monista (art. 53); o cabo que desliga as câmeras concorre (partícipe ou coautor conforme a divisão de tarefas). IPM: o auto de flagrante que, por si só, esclarece fato e autoria constitui o inquérito, com breve relatório e exames necessários (CPPM art. 27).\n\n**Plena:** quatro eixos com a incerteza declarada. **Parcial:** omite a natureza militar do fato do civil ou exige IPM. **Insuficiente:** afirma que civil não comete crime militar.",
  criterios=["Natureza militar para os dois agentes (0,2)", "Consumação/tentativa com incerteza declarada (0,2)", "Concurso de agentes (0,2)", "Dispensa do IPM (0,2)", "Conclusão integrada (0,2)"],
  fonte=f"{CPM}, arts. 9º, 30 e 53; {CPPM}, art. 27; {A31}, slides 41–50 e 61–62; {A41}, slide 31.", armadilha="Consumação sem critério; IPM obrigatório.", tempo=12),
]

SG03 = [  # Acima da prova — N3/N4, integração Penal–Processual
 dict(n=1, tipo="OBJ", nivel="N4", ctx=True, conceitos=["DIRT2-PRINC-IRRETRO", "DIRT2-TEMPO-CRIME", "DIRT2-PRAZOS-IPM"],
  competencia="Acima da prova: sucessão de leis durante o IPM.",
  enunciado="Durante IPM com indiciado preso, entra em vigor lei que reduz a pena do crime investigado e outra que amplia de 20 para 30 dias o prazo do IPM de indiciado preso (hipotética). Assinale a alternativa correta.",
  alternativas=[
   ("A lei penal mais benéfica retroage; quanto ao prazo processual, o curso não autoriza concluir sua aplicação intertemporal sem conferir a regra do CPPM sobre aplicação no tempo — declarar a necessidade de verificação.", "Correta. CPM art. 2º, § 1º. [PONTO DE INCERTEZA] O CPPM, art. 5º (corpus, p. 21), trata da aplicação intertemporal das normas processuais, tema não ensinado nos slides."),
   ("Nenhuma das leis se aplica, pois o fato é anterior.", "Errada. A lei penal benéfica retroage."),
   ("Ambas se aplicam por serem favoráveis ao réu.", "Errada. Ampliação de prazo de prisão não é ‘favorável’ e a regra intertemporal processual é outra."),
   ("A lei penal só se aplica após o trânsito em julgado.", "Errada. A retroatividade benéfica independe da fase."),
  ], correta=0, comentario="Questão de nível acima da prova: exige separar direito material e processual e reconhecer limite do corpus ensinado.",
  fonte=f"{CPM}, art. 2º; {CPPM}, arts. 5º e 20; {A31}, slide 5; {A41}, slide 28.", armadilha="Tratar norma processual como penal.", tempo=6),
 dict(n=2, tipo="OBJ", nivel="N4", ctx=True, conceitos=["DIRT2-EXCL-COMANDANTE", "DIRT2-MEDIDAS-URGENTES", "DIRT2-REMESSA-ARQUIVAMENTO"],
  competencia="Acima da prova: excludente reconhecida na apuração e destino dos autos.",
  enunciado="Após avaria grave em alto-mar, o comandante compele marinheiros com violência a executar manobra urgente e salva o navio. Instaurado IPM, o encarregado conclui pela excludente do art. 42, parágrafo único. O comandante da força, satisfeito, determina o arquivamento. Assinale a alternativa correta.",
  alternativas=[
   ("A conclusão pela excludente pode constar do relatório, mas o IPM não pode ser arquivado pela autoridade militar; os autos vão ao juiz, e o arquivamento depende de requerimento do MPM.", "Correta. Arts. 22 e 24; slide 30."),
   ("O arquivamento é válido porque a excludente elimina o crime.", "Errada. O art. 24 veda o arquivamento mesmo quando o IPM conclui pela inexistência de crime."),
   ("O IPM era dispensável porque houve excludente.", "Errada. Excludente não é hipótese de dispensa do art. 28."),
   ("O encarregado deveria absolver o comandante.", "Errada. O IPM não julga."),
  ], correta=0, comentario="Material e processual convergem: ‘não há crime’ não autoriza arquivamento administrativo.",
  fonte=f"{CPM}, art. 42, parágrafo único; {CPPM}, arts. 22, 24 e 28; {A41}, slides 29–31.", armadilha="Excludente → arquivamento administrativo.", tempo=5),
 dict(n=3, tipo="OBJ", nivel="N4", ctx=True, conceitos=["DIRT2-TESTEMUNHA-INDICIADO", "DIRT2-CONCURSO-MONISTA", "DIRT2-ENCARREGADO-ATRIBUICOES"],
  competencia="Acima da prova: prova ilícita em concurso de agentes.",
  enunciado="Em IPM sobre furto em concurso, o encarregado ouve como testemunha, sem advertência, um marinheiro já apontado como coautor, que confessa e incrimina os demais. Não há outra prova contra um dos coautores. Assinale a alternativa mais adequada.",
  alternativas=[
   ("A declaração é prova ilícita segundo a tese ensinada e não deve integrar os autos; sem prova independente contra aquele coautor, faltarão indícios de autoria para a denúncia quanto a ele — o que o encarregado deve registrar sem arquivar.", "Correta. Slide 25; arts. 22, 24 e 30 do CPPM."),
   ("A confissão vale contra os outros, pois a ilicitude só beneficia quem confessou.", "Errada. A tese ensinada determina que a prova ilícita não integre os autos."),
   ("O encarregado deve arquivar quanto ao coautor sem prova.", "Errada. Art. 24."),
   ("Pela teoria monista, a prova contra um vale contra todos.", "Errada. A monista é regra de direito material, não de prova."),
  ], correta=0, comentario="[NÃO CONFIRMADO NA FONTE PRIMÁRIA] Ementa do STM lida no slide. [PONTO DE INCERTEZA] O alcance da ilicitude sobre provas derivadas não é tratado no recorte.",
  fonte=f"{A41}, slide 25; {CPPM}, arts. 22, 24 e 30; {CPM}, art. 53.", armadilha="Monista como regra probatória.", tempo=6),
 dict(n=4, tipo="VF", nivel="N4", ctx=True, conceitos=["DIRT2-ART9-III", "DIRT2-STM-COMPETENCIA", "DIRT2-FORO-MILITAR"],
  competencia="Acima da prova: civil, crime militar e competência do STM.",
  afirmacao="Um civil que furta material sob administração militar em concurso com um almirante acusado do mesmo crime militar será, por conexão com oficial-general, necessariamente julgado originariamente pelo STM, segundo o que foi ensinado.",
  correta=False, comentario="Falsa como afirmação categórica. O recorte ensina a competência originária do STM para oficiais-generais nos crimes militares (slide 7), mas não trata de conexão ou de extensão dessa competência a coautores civis. [LACUNA DE COBERTURA] Regras de conexão não integram o corpus ensinado; ‘necessariamente’ não pode ser afirmado.",
  fonte=f"{A42}, slide 7; {CPM}, art. 9º, III; {CF}, art. 124.", armadilha="Presumir regra não ensinada.", tempo=3),
 dict(n=5, tipo="OBJ", nivel="N4", ctx=True, conceitos=["DIRT2-CRIME-IMPOSSIVEL", "DIRT2-DISPENSA-IPM", "DIRT2-MEDIDAS-URGENTES"],
  competencia="Acima da prova: flagrante de conduta que pode ser crime impossível.",
  enunciado="O oficial de serviço prende em flagrante um cabo que ‘tentava sabotar’ o radar com uma ferramenta de plástico incapaz de causar dano; o equipamento, ademais, estava blindado. Assinale a alternativa correta.",
  alternativas=[
   ("As providências do art. 12 eram cabíveis diante do que era verificável na ocasião; a qualificação como crime impossível (art. 32) é juízo de mérito que não cabe ao oficial de serviço nem autoriza arquivamento administrativo.", "Correta. Arts. 12, 24 e 32."),
   ("O oficial de serviço deve soltar o cabo e arquivar o caso, pois é crime impossível.", "Errada. Não lhe cabe arquivar."),
   ("Há tentativa, porque houve prisão em flagrante.", "Errada. A prisão não define o enquadramento material."),
   ("O IPM é dispensado porque houve flagrante.", "Errada. Só se o auto, por si só, esclarecer fato e autoria (art. 27); e a análise do meio exige exame."),
  ], correta=0, comentario="[PONTO DE INCERTEZA] A legalidade da prisão diante de possível crime impossível depende do que era verificável no momento; o recorte não trata do art. 244 do CPPM.",
  fonte=f"{CPM}, art. 32; {CPPM}, arts. 12, 24 e 27; {A41}, slides 18–21 e 30–31.", armadilha="Decidir o mérito na fase de providências.", tempo=6),
 dict(n=6, tipo="OBJ", nivel="N4", ctx=True, conceitos=["DIRT2-PJM-DELEGACAO", "DIRT2-INCOMUNICABILIDADE", "DIRT2-PRAZOS-IPM"], modos=["pra-safar", "completo"],
  competencia="Acima da prova: hierarquia, prazos e garantias.",
  enunciado="No 15º dia de IPM com indiciado preso, surgem indícios contra oficial mais antigo que o encarregado. O encarregado, para ‘ganhar tempo’, mantém o preso incomunicável e aguarda a nova delegação. Assinale a alternativa correta.",
  alternativas=[
   ("A delegação a outro oficial é obrigatória (art. 10, § 5º) e as interrupções por esse motivo são deduzidas dos prazos (art. 20, § 3º); a incomunicabilidade não pode ser usada, conforme a não recepção ensinada.", "Correta. CPPM arts. 10, § 5º, 20, § 3º, e 17; slide 27."),
   ("O prazo de 20 dias vence normalmente e o preso deve ser solto no 20º dia, sem dedução.", "Errada. O § 3º do art. 20 prevê a dedução das interrupções."),
   ("A incomunicabilidade é válida por três dias enquanto se aguarda a delegação.", "Errada. Ensinada como não recepcionada."),
   ("O encarregado pode prosseguir, pois o indiciado original é praça.", "Errada. O § 5º do art. 10 exige a delegação."),
  ], correta=0, comentario="[APROFUNDAMENTO ANALÍTICO DE SUPORTE] A dedução do § 3º do art. 20 não aparece nos slides.",
  fonte=f"{CPPM}, arts. 10, § 5º, 17 e 20, § 3º; {A41}, slides 27–28.", armadilha="Usar a interrupção para restringir garantias.", tempo=6),
 dict(n=7, tipo="DIS", nivel="N4", ctx=True, conceitos=["DIRT2-ART9-II", "DIRT2-PRETERDOLO", "DIRT2-MEDIDAS-URGENTES", "DIRT2-TESTEMUNHA-INDICIADO", "DIRT2-FORO-MILITAR"],
  competencia="Acima da prova: caso Penal–Processual completo.",
  contexto="Às 23h, a bordo de navio atracado, um cabo empurra um marinheiro durante discussão para machucá-lo; o marinheiro bate a cabeça e morre. O oficial de quarto limpa o local ‘para não assustar a tripulação’. No dia seguinte, instaurado o IPM, o encarregado ouve o cabo como testemunha, sem advertência, e ele admite o empurrão.",
  enunciado="Resolva: natureza militar e enquadramento; falhas na fase preliminar e na oitiva, com consequências; foro.",
  gabarito="**Gabarito:** Natureza: militares da ativa entre si → art. 9º, II, ‘a’ (e lugar sujeito à administração militar): crime militar. Enquadramento: dolo de lesão e morte previsível não querida → preterdolo (art. 34; art. 209, § 3º, parte final), a confirmar pela prova da previsibilidade. Fase preliminar: o oficial de quarto deveria preservar o estado das coisas (art. 12, a); a limpeza compromete a prova — falha a registrar e apurar, sem que isso extinga a apuração. Oitiva: o cabo era suposto autor e deveria ser ouvido como indiciado, advertido do silêncio e da assistência de advogado; sua admissão é prova ilícita que não deve integrar os autos (slide 25; CF LVI, LXIII) [NÃO CONFIRMADO NA FONTE PRIMÁRIA — inteiro teor]. Foro: vítima militar → não incide a regra do crime doloso contra a vida de civil; Justiça Militar da União (CF art. 124). O relatório conclui sobre indícios, sem arquivar.\n\n**Plena:** cinco eixos corretos com ressalvas. **Parcial:** acerta a natureza, mas valida a admissão. **Insuficiente:** homicídio doloso na justiça comum.",
  criterios=["Natureza e enquadramento (0,2)", "Fase preliminar (0,2)", "Oitiva e ilicitude (0,2)", "Foro (0,2)", "Ressalvas e conclusão (0,2)"],
  fonte=f"{CPM}, arts. 9º, 34 e 209; {CPPM}, arts. 12 e 22; {CF}, arts. 5º e 124; {A31}, slides 23 e 61; {A41}, slides 18–25.", armadilha="Tratar a limpeza como irrelevante; validar a confissão.", tempo=14),
 dict(n=8, tipo="DIS", nivel="N4", ctx=True, conceitos=["DIRT2-AGRAVANTES-CABECAS", "DIRT2-COAUTORIA-LIMITES", "DIRT2-IPM-INSTAURACAO", "DIRT2-STM-COMPETENCIA"],
  competencia="Acima da prova: crime coletivo com oficial-general e apuração.",
  contexto="Em uma base, um contra-almirante lidera um grupo de praças que ocupa, armado, um hangar em desobediência a ordem superior. Um sargento em função de oficial participa. O comandante da base, capitão de mar e guerra, instaura IPM designando como encarregado um capitão-tenente.",
  enunciado="Enquadre o fato, identifique os cabeças, aponte o problema da instauração e o órgão competente para o julgamento do oficial-general.",
  gabarito="**Gabarito:** Fato: militares reunidos ocupando hangar em desobediência a ordem superior → art. 149, IV; armados → parágrafo único (revolta), com aumento para os cabeças. Cabeças: o contra-almirante (oficial — § 5º do art. 53; além disso dirige a ação — § 4º) e o sargento em função de oficial (§ 5º). Instauração: o infrator tem posto superior ao do comandante da base; deve haver comunicação à autoridade superior para delegação a oficial de posto superior ou mais antigo que o indiciado (CPPM arts. 7º, § 2º, e 10, § 1º — conteúdo do Pra Safar/Completo); o capitão-tenente não atende. Julgamento do oficial-general em crime militar: competência originária do STM (slide 7). O órgão de primeira instância para as praças não integra o recorte.\n\n**Plena:** quatro eixos. **Parcial:** omite a delegação ou um cabeça. **Insuficiente:** encara como transgressão coletiva.",
  criterios=["Enquadramento (0,2)", "Cabeças (0,2)", "Vício da instauração (0,2)", "Competência do STM (0,2)", "Limite do recorte (0,2)"],
  fonte=f"{CPM}, arts. 53 e 149; {CPPM}, arts. 7º e 10; {A31}, slides 52–54; {A42}, slide 7.", armadilha="Encarregado mais moderno; esquecer o § 5º.", tempo=14),
 dict(n=9, tipo="COR", nivel="N3", ctx=True, conceitos=["DIRT2-ENCARREGADO-ATRIBUICOES", "DIRT2-REMESSA-ARQUIVAMENTO", "DIRT2-PJM", "DIRT2-STM-COMPETENCIA"],
  competencia="Acima da prova: quem decide o quê.",
  titulo="Associe o ato ao único ator que pode praticá-lo",
  chaves=[("A", "Encarregado do IPM"), ("B", "Juiz Federal da Justiça Militar"), ("C", "Ministério Público Militar"), ("D", "STM")],
  itens=[
   ("Determinar o arquivamento do IPM.", "B"),
   ("Oferecer denúncia.", "C"),
   ("Proceder a acareações.", "A"),
   ("Julgar apelação de decisão da primeira instância da JMU.", "D"),
   ("Requerer o arquivamento do IPM.", "C"),
  ],
  comentario="Slides 23, 30, 32 e 7 (Aula 4.2); CPPM art. 29.",
  fonte=f"{A41}, slides 23, 30 e 32; {A42}, slide 7; {CPPM}, art. 29.", armadilha="MPM determina arquivamento.", tempo=3),
 dict(n=10, tipo="OBJ", nivel="N4", ctx=True, conceitos=["DIRT2-TRANSGRESSAO", "DIRT2-SINDICANCIA", "DIRT2-RELATORIO-AUTOS"],
  competencia="Acima da prova: esfera disciplinar e penal na apuração.",
  enunciado="Um IPM conclui que não há indício de crime, mas há infração disciplinar. Em outro caso, a sindicância conclui por transgressão e, depois, surgem indícios de crime militar da mesma natureza. Assinale a alternativa correta.",
  alternativas=[
   ("No primeiro, o relatório pode concluir por infração disciplinar a punir (art. 22), sem arquivamento pela autoridade militar; no segundo, os indícios levam a IPM (art. 10, f) e, havendo crime e transgressão da mesma natureza, aplica-se somente a pena do crime (EM art. 42, § 2º).", "Correta."),
   ("No primeiro, a autoridade arquiva e pune; no segundo, somam-se as sanções.", "Errada. Arts. 24 e EM 42, § 2º."),
   ("No primeiro, o MPM pune disciplinarmente; no segundo, a sindicância vira ação penal.", "Errada. Atores e instrumentos trocados."),
   ("Em ambos, nada mais pode ser feito após a primeira conclusão.", "Errada. O art. 10, f, e o art. 25 mostram o contrário."),
  ], correta=0, comentario="[PONTO DE INCERTEZA] O destino dos autos quando só há infração disciplinar deve observar a solução pela autoridade (art. 22, § 1º) e a vedação de arquivamento (art. 24); o recorte não detalha essa compatibilização.",
  fonte=f"{CPPM}, arts. 10, 22 e 24; {EM}, art. 42, § 2º; {A41}, slides 29–34; {A31}, slide 59.", armadilha="Somar sanções; arquivar.", tempo=6),
]
