# -*- coding: utf-8 -*-
"""Banco do Módulo 00 — método, lentes teóricas e discursiva."""

from helper import obj, vf, cor, dis

T = "00-metodo-e-matriz-de-cenarios"

QUESTOES = [
    vf("M00", "N1", 1, topico=T,
       conceitos=["REL-T2-M00-C001"],
       afirmacao="O arquivo cujo nome é “AULA 13.pdf” contém, no seu primeiro slide, o título interno “Aula 13 — Política Externa Brasileira”.",
       correta=False,
       comentario="**Falsa.** O arquivo “AULA 13.pdf” abre com “Aula 14 – SUE 1.11 PND, END, PESD”. O deslocamento é de uma unidade em todos os seis decks: quem quiser a Aula 13 (Política Externa Brasileira) precisa abrir “AULA 12.pdf” — que, além disso, traz as Aulas 13 e 14 emendadas. A regra do curso é simples: o número da aula é o do TÍTULO INTERNO, nunca o do nome do arquivo.",
       fonte="AULA 13.pdf, primeiro slide; AULA 12.pdf, primeiro slide.",
       competencia="Determinar a aula pelo título interno do deck, não pelo nome do arquivo.",
       erro="Confiar no nome da pasta ou do arquivo para identificar a aula."),

    obj("M00", "N2", 2, topico=T,
        conceitos=["REL-T2-M00-C002", "REL-T2-M02-C003"],
        enunciado="Um Aspirante encontra duas informações incompatíveis sobre a PND/END. O resumo de um colega e um deck em circulação dizem que a versão vigente é a de 2016, aprovada pelo Congresso em 2018. Outro deck da mesma aula, mais recente, diz que a versão atual é de 18 de novembro de 2025, com link para o Decreto nº 12.725. Aplicando a hierarquia das fontes adotada no curso, qual conduta é correta?",
        alternativas=[
            "Adotar a informação de 2016, porque é a que aparece em duas fontes contra uma, e maioria de testemunhos prevalece.",
            "Adotar a informação de 18/11/2025, porque entre dois slides do professor prevalece o mais recente, e registrar que decks antigos ainda citam 2016.",
            "Descartar as duas informações e responder apenas que a PND foi aprovada pelo Congresso em 2005, 2012 e 2018, evitando a data da versão.",
            "Adotar a informação de 2016 no estudo e a de 2025 na prova, porque o professor tende a cobrar o que está no material mais antigo, já consolidado.",
            "Buscar a resposta em pesquisa externa atual e adotá-la, porque a divergência entre os slides torna o corpus autorizado insuficiente.",
        ],
        correta=1,
        comentario="A hierarquia coloca o slide do professor no topo. Quando dois slides do MESMO professor sobre a MESMA aula divergem, a divergência não é erro de extração: é atualização. Prevalece o mais recente, e o registro da versão antiga vira matéria de pegadinha — aprovação pelo Congresso (2005, 2012, 2018) e versão em vigor (nov/2025) são coisas diferentes.",
        distratores=[
            "Errada. Contagem de testemunhos não é critério: o resumo do colega é nível 3 e o deck antigo foi superado pelo próprio professor.",
            "Correta. Entre slides do professor prevalece o mais recente; a informação antiga é preservada como registro, não como resposta.",
            "Errada. Omitir a informação disponível é perder ponto por silêncio; as duas datas coexistem com sentidos distintos.",
            "Errada. Não há evidência no corpus de que o professor cobre material superado, e estudar deliberadamente o dado errado é indefensável.",
            "Errada. A pesquisa externa está autorizada apenas para caixas de conjuntura datadas, nunca para substituir a explicação do professor.",
        ],
        fonte="AULA 13.pdf, slide “Política Nacional de Defesa/Estratégia Nacional de Defesa”; AULA 12.pdf, mesmo slide em versão anterior; fontes-manifesto.json, conflito CF-01.",
        competencia="Resolver conflito entre fontes aplicando a hierarquia declarada.",
        erro="Resolver divergência por contagem de fontes em vez de por hierarquia.",
        tempo=3),

    obj("M00", "N3", 3, topico=T,
        conceitos=["REL-T2-M00-C004", "REL-T2-M00-C005", "REL-T2-M00-C006"],
        enunciado="Um Estado costeiro de porte médio assina um acordo de cooperação em segurança marítima com uma potência extrarregional. O acordo cria um comitê permanente, prevê exercícios conjuntos anuais e transferência de tecnologia de sensores. Nos documentos internos do Estado costeiro, o acordo é justificado pela necessidade de monitorar uma área marítima onde uma terceira potência ampliou a presença de embarcações pesqueiras e de navios de pesquisa. Qual leitura explica melhor o caso, e por quê?",
        alternativas=[
            "Leitura liberal, porque a criação de um comitê permanente e de exercícios anuais institucionaliza a cooperação, e instituições são o objeto próprio da lente liberal.",
            "Leitura construtivista, porque a escolha do parceiro revela identidade compartilhada e normas comuns entre os dois Estados signatários.",
            "Leitura realista, porque a justificativa interna vincula o acordo à percepção de ameaça e ao ganho de capacidade de monitoramento, e cooperar por segurança é comportamento realista.",
            "Nenhuma leitura se aplica, porque cooperação e conflito pertencem a lentes distintas e o caso mistura as duas.",
            "Leitura liberal, porque a transferência de tecnologia aumenta a interdependência entre os signatários e reduz o incentivo ao conflito entre eles.",
        ],
        correta=2,
        comentario="O que decide é a variável explicativa PREDOMINANTE no enunciado, não a presença de uma palavra-pista. Há instituição no caso (comitê, exercícios), mas a justificativa declarada é percepção de ameaça e ganho de capacidade — segurança e poder. Estado realista coopera, e coopera justamente quando a cooperação serve à segurança. O slide do professor é explícito: no realismo, o imperativo central é manter a segurança e preservar o poder do Estado.",
        distratores=[
            "Errada. A existência de instituição é pista, não prova. O comitê é o meio; o fim declarado é segurança.",
            "Errada. O enunciado não traz identidade, norma ou valor compartilhado — traz percepção de ameaça material.",
            "Correta. A variável predominante é ameaça percebida e ganho de capacidade; a forma institucional é instrumento.",
            "Errada. A cooperação não é exterior ao realismo: o próprio slide trata cooperação a serviço de segurança e poder.",
            "Errada. Interdependência entre os signatários não é o motivo declarado; o motivo é a conduta de um terceiro ator.",
        ],
        fonte="AULA 15.pdf, slides “Segundo as principais Teorias em RI — 1. Realismo”, “2. Liberais” e “3. Construtivismo”; perfil-cobranca.json (aplicação inédita alta).",
        competencia="Classificar um cenário pela variável explicativa predominante, recusando a associação por palavra-chave.",
        erro="Classificar como liberal qualquer caso em que apareça uma instituição.",
        tempo=4,
        resolucao=[
            "1. Ator e objetivo: Estado costeiro de porte médio; objetivo declarado é monitorar área marítima.",
            "2. Ameaça percebida: ampliação da presença de uma terceira potência.",
            "3. Instrumento: acordo institucional com transferência de tecnologia.",
            "4. Teste da lente: o instrumento é institucional, mas a razão é de segurança. Predomina poder e segurança.",
            "5. Contraponto: a forma institucional cria expectativas e custos de ruptura, o que abre espaço para leitura liberal secundária — mas não é o que o enunciado destaca.",
        ],
        verificacao="Releia o enunciado procurando a JUSTIFICATIVA, não os substantivos. A justificativa é que decide."),

    cor("M00", "N3", 4, topico=T,
        conceitos=["REL-T2-M00-C005", "REL-T2-M00-C006", "REL-T2-M00-C007", "REL-T2-M00-C008"],
        titulo="Correlacione cada situação à lente que MELHOR a explica",
        chaves=[
            ("R", "Realismo — imperativo central: sobrevivência, poder e segurança em sistema anárquico"),
            ("L", "Liberalismo/institucionalismo — imperativo central: maximizar cooperação e ganhos da interdependência"),
            ("C", "Construtivismo — imperativo central: preservar e promover identidades, normas e valores tidos por legítimos"),
        ],
        itens=[
            ("Um país eleva o gasto de defesa depois de um rival regional incorporar submarinos de nova geração, sem qualquer mudança em seu discurso oficial sobre valores.", "R"),
            ("Dois vizinhos historicamente rivais passam a tratar a fronteira comum como área de livre circulação depois de uma geração de institucionalidade compartilhada, e as forças armadas de ambos deixam de planejar o vizinho como hipótese de emprego.", "C"),
            ("Um Estado adere a um organismo multilateral de comércio para reduzir incerteza sobre tarifas e ampliar previsibilidade para seus exportadores.", "L"),
            ("Um Estado que se declara defensor do multilateralismo veta, em um conselho, uma resolução que atingiria diretamente um aliado seu.", "R"),
            ("Um Estado nega o ensino da língua nativa em uma região incorporada e impõe a língua do centro político como única na escola.", "C"),
            ("Um bloco regional adota cláusula que suspende membros cujo governo rompa a ordem democrática, e a cláusula é acionada contra um membro.", "L"),
        ],
        comentario="A regra é sempre a mesma: identifique a variável que o enunciado destaca. **R** aparece quando o texto destaca ameaça, capacidade relativa ou interesse acima de norma declarada — inclusive quando o ator usa uma instituição para isso (o veto é instrumento institucional a serviço de interesse). **L** aparece quando o texto destaca redução de incerteza, ganho mútuo e regra que obriga o próprio autor. **C** aparece quando o texto destaca mudança na percepção de quem é amigo ou inimigo, ou a imposição/promoção de identidade. Note que o item do veto tem instituição e o item da cláusula democrática tem norma: a diferença é que no primeiro a instituição serve ao interesse do ator e no segundo a regra restringe o próprio bloco.",
        fonte="AULA 15.pdf, slides das três teorias; perfil-cobranca.json (correlação de melhores pares, formato observado na SOPA T1).",
        competencia="Atribuir a lente adequada pela variável predominante, distinguindo instituição-instrumento de instituição-restrição.",
        erro="Marcar L sempre que houver organismo ou norma no enunciado.",
        tempo=6),

    dis("M00", "N4", 5, topico=T,
        conceitos=["REL-T2-M00-C009", "REL-T2-M00-C008", "REL-T2-M00-C010"],
        contexto="Considere um Estado insular europeu que, por decisão majoritária em referendo, deixa um bloco de integração regional de que era membro há décadas. Ao longo do processo, dois conjuntos de razões apareceram no debate público: por um lado, recuperar o controle sobre fronteiras, sobre regulação econômica e sobre decisões judiciais de última instância; por outro, os custos de sair — barreiras alfandegárias novas, reorganização de cadeias produtivas, perda de acesso preferencial a um mercado vizinho e anos de negociação para reconstruir regras que já existiam.",
        enunciado="Construa as DUAS leituras possíveis desse caso, escolha a que explica melhor o resultado e justifique a escolha por evidência. Sua resposta deve deixar claro que a classificação depende do aspecto destacado, e não do fato em si.",
        gabarito=(
            "**Leitura realista.** Tese: predomina a lógica de soberania e autonomia decisória. Conceito: o imperativo realista é preservar a capacidade de decidir por si em sistema anárquico; interdependência profunda é vista como restrição à autonomia, não como ganho. Evidência: as razões de saída nomeiam controle de fronteiras, de regulação e de jurisdição de última instância — três dimensões de autoridade, não de bem-estar. Nexo: quem trata autoridade sobre o próprio território como bem não negociável aceita perda material para recuperá-la; logo, custo econômico conhecido não dissuade.\n\n"
            "**Leitura liberal/institucional.** Tese: predomina a lógica de interdependência e de custos de ruptura. Conceito: instituições reduzem incerteza e criam ganhos que se perdem ao sair; integração gera dependência mútua que encarece a saída. Evidência: barreiras alfandegárias novas, reorganização de cadeias, perda de acesso preferencial e anos de renegociação. Nexo: se a interdependência é o que explica o caso, o comportamento esperado seria permanecer — e é exatamente por isso que essa leitura explica melhor o CUSTO do que a DECISÃO.\n\n"
            "**Arbitragem.** A leitura que explica melhor o RESULTADO é a realista, porque o resultado foi sair apesar dos custos: a variável que prevaleceu na decisão foi autonomia, não bem-estar agregado. A leitura institucional explica melhor as CONSEQUÊNCIAS e a dificuldade da transição. Conclusão fundamentada: em casos ambíguos, a lente correta é a que explica a variável que o enunciado coloca em primeiro plano — aqui, se o comando pedisse as consequências da saída, a resposta mudaria de lente sem que o fato mudasse.\n\n"
            "**Nuance obrigatória.** Há ainda uma leitura construtivista defensável (identidade nacional distinta da identidade do bloco, construída historicamente), que não precisa ser desenvolvida, mas cuja menção demonstra que o aluno não trata o caso como binário.\n\n"
            "**Resposta insuficiente:** “É realismo porque o país buscou seus interesses.” Não diz qual interesse, qual condicionante, qual ação nem qual relação causal. **Resposta satisfatória:** constrói as duas leituras e escolhe uma, mas não diz qual evidência sustenta a escolha. **Resposta de nível MB:** constrói as duas, escolhe uma, ancora a escolha em evidência específica do enunciado, reconhece a leitura concorrente e explicita que a classificação depende do aspecto destacado."
        ),
        criterios=[
            "Constrói a leitura realista com conceito e evidência do enunciado (0,2)",
            "Constrói a leitura liberal/institucional com conceito e evidência do enunciado (0,2)",
            "Escolhe uma leitura e nomeia a evidência específica que a sustenta (0,3)",
            "Explicita que a classificação depende do aspecto destacado pelo enunciado (0,2)",
            "Reconhece uma leitura concorrente ou nuance sem abandonar a conclusão (0,1)",
            "Não pontua: afirmar a classificação sem nexo causal, ou tratar o caso como tendo resposta única e óbvia",
        ],
        fonte="AULA 15.pdf, slides das três teorias; P1 REL 2024, questão 1 (o Brexit aparece como estímulo de prova); Gabarito da P2 REL 2024 (padrão de resposta com mecanismo causal explícito); perfil-cobranca.json.",
        competencia="Sustentar uma conclusão em caso ambíguo, com duas leituras construídas e evidência que arbitre entre elas.",
        erro="Dar resposta única a caso ambíguo, ou classificar sem apontar a evidência.",
        tempo=12),

    obj("M00", "N3", 6, topico=T,
        conceitos=["REL-T2-M00-C003", "REL-T2-M00-C011"],
        enunciado="Aplicando a matriz de análise de cenários em dez passos, um Aspirante escreve sobre um Estado que, temendo o bloqueio de um estreito por onde passa a maior parte de sua energia importada, financia a construção de um porto em país terceiro e negocia um corredor ferroviário alternativo. Na matriz, o porto financiado e o corredor ferroviário ocupam qual posição, e por quê?",
        alternativas=[
            "Vulnerabilidades, porque dependem da estabilidade política do país terceiro.",
            "Recursos, porque passam a integrar as capacidades disponíveis ao Estado depois de concluídos.",
            "Instrumentos, porque são os meios efetivamente empregados para atuar sobre a vulnerabilidade identificada.",
            "Condicionantes, porque a geografia do estreito é o que determina a necessidade da obra.",
            "Objetivo, porque a conclusão da obra é o que o Estado pretende alcançar no cenário descrito.",
        ],
        correta=2,
        comentario="A matriz separa o que o ator TEM (recursos) do que ele USA (instrumentos), e ambos do que o ameaça (vulnerabilidades) e do que o restringe (condicionantes). O porto e o corredor são ações empregadas — instrumentos econômicos e de infraestrutura — dirigidas contra a vulnerabilidade do estreito. A vulnerabilidade é a dependência do estreito; o condicionante é a geografia; o objetivo é assegurar o fluxo energético.",
        distratores=[
            "Errada. A dependência do país terceiro é uma vulnerabilidade NOVA criada pelo instrumento, não a posição do instrumento na matriz.",
            "Errada. Recursos é o que está disponível; aqui há emprego deliberado de meios para um fim.",
            "Correta. Instrumento é o meio empregado: infraestrutura financiada e corredor negociado.",
            "Errada. O condicionante é a geografia do estreito, que existe independentemente da decisão.",
            "Errada. O objetivo é garantir o fluxo energético; a obra é meio, não fim.",
        ],
        fonte="matriz-cobertura.json (matriz de dez passos desta autoria); T2_2025.pdf, itens 2, 4 e 5 do trabalho; AULA 16.pdf, slide “Perspectiva Chinesa”.",
        competencia="Situar corretamente cada elemento de um cenário nos dez passos da matriz.",
        erro="Confundir recursos (o que tem) com instrumentos (o que usa).",
        tempo=3),

    obj("M00", "N2", 7, topico=T,
        conceitos=["REL-T2-M00-C016", "REL-T2-M00-C010"],
        enunciado="Em uma questão de asserção e razão, o Aspirante julga que as duas afirmativas são verdadeiras. O comando oferece, entre outras, as opções “ambas são verdadeiras e a II é justificativa da I” e “ambas são verdadeiras, mas a II NÃO é justificativa da I”. Qual é o procedimento correto antes de escolher entre as duas?",
        alternativas=[
            "Escolher a opção que afirma o nexo, porque duas afirmativas verdadeiras sobre o mesmo tema normalmente se explicam mutuamente.",
            "Verificar se a segunda afirmativa é causa suficiente e específica da primeira, e não apenas um fato verdadeiro do mesmo assunto, atentando para variantes que exigem explicação COMPLETA.",
            "Escolher a opção que nega o nexo, porque o professor usa essa alternativa com mais frequência nas provas do corpus.",
            "Reler apenas a primeira afirmativa, já que o nexo depende exclusivamente do que ela afirma.",
            "Escolher qualquer uma, porque quando as duas afirmativas são verdadeiras a diferença entre as opções é apenas de redação.",
        ],
        correta=1,
        comentario="Julgar as afirmativas é só a primeira metade do trabalho. A segunda é testar o NEXO: a afirmativa II precisa ser a razão da I, com suficiência e especificidade. O corpus traz duas armadilhas nesse ponto. Uma é a variante refinada “é a explicação COMPLETA da afirmativa 1”: uma razão que seja apenas um dos elementos necessários não é explicação completa. A outra é a alternativa em que ambas são verdadeiras e o nexo é falso, usada mais de uma vez nas provas.",
        distratores=[
            "Errada. Verdade das partes não implica relação causal entre elas.",
            "Correta. Testar suficiência e especificidade do nexo, e atentar para a exigência de explicação completa.",
            "Errada. Escolher por frequência estatística de gabarito é chute, não método — e o corpus não sustenta essa frequência.",
            "Errada. O nexo depende da relação entre as duas, o que exige reler as duas.",
            "Errada. A diferença entre afirmar e negar o nexo é substantiva e decide a questão.",
        ],
        fonte="SOPA REL T1 2024, questões 4, 5 e 10 (inclusive a variante “explicação completa”); Gabarito da P2 REL 2024, questões 6, 7, 9, 10 e 13; P1 REL 2024, questões 6 e 12.",
        competencia="Executar o procedimento de duas etapas em questões de asserção e razão.",
        erro="Aceitar o nexo porque as duas afirmativas são verdadeiras.",
        tempo=3),

    obj("M00", "N4", 8, topico=T,
        conceitos=["REL-T2-M00-C012", "REL-T2-M00-C013", "REL-T2-M00-C014", "REL-T2-M00-C015"],
        enunciado="Um grupo precisa escolher, entre os autores disponíveis, aquele cujos conceitos melhor explicam o seguinte conjunto: um Estado continental de grande extensão, com dois litorais separados por todo o território, que constrói uma passagem artificial entre os dois oceanos, estabelece uma rede de bases de reabastecimento em pontos de passagem obrigatória do comércio mundial e mantém uma esquadra capaz de operar longe da própria costa. Qual escolha é mais adequada, e por qual razão conceitual?",
        alternativas=[
            "Mackinder, porque a extensão continental do Estado o aproxima da condição de potência do interior eurasiático descrita em sua teoria.",
            "Mahan, porque os conceitos de comando do mar, de bases e de pontos de estrangulamento descrevem exatamente os três elementos do caso.",
            "Corbett, porque a existência de uma esquadra oceânica indica preferência por bloqueio e incursão em vez de batalha decisiva.",
            "Douhet, porque uma esquadra capaz de operar longe da costa depende de cobertura aérea e, portanto, do comando do ar.",
            "Haushofer, porque a construção da passagem artificial amplia o espaço vital do Estado para além de suas fronteiras originais.",
        ],
        correta=1,
        comentario="A regra que o próprio professor enuncia é de ADEQUAÇÃO: quanto mais o objeto se insere nas premissas da abordagem, maior o sucesso da análise. Os três elementos do caso — passagem artificial entre oceanos, rede de bases em pontos de passagem obrigatória e esquadra de alcance oceânico — são, um a um, os conceitos de Mahan: integração entre as duas costas, bases de reabastecimento e domínio dos choke points. Escolher o autor certo não basta: é preciso instrumentalizar os conceitos, e é isso que a alternativa correta faz.",
        distratores=[
            "Errada. Extensão continental não é a premissa de Mackinder: a premissa é a posição no interior eurasiático e o controle da Europa Oriental.",
            "Correta. Os três elementos do caso correspondem termo a termo aos conceitos de Mahan.",
            "Errada. Corbett se distingue por preferir controle a comando do mar; o caso descreve construção de comando, não estratégia de negação.",
            "Errada. Douhet trata do comando do ar e de bombardeio estratégico; a cobertura aérea de uma esquadra não é o objeto da sua teoria.",
            "Errada. Espaço vital de Haushofer é expansão territorial por necessidade orgânica do Estado, não abertura de via de comunicação marítima.",
        ],
        fonte="AULA 15.pdf, slide “Expansão geopolítica”; REL - T1 - IM415, seção 5 (repertório dos geopolíticos); SOPA REL T1 2024, questões 1 e 9 (regra de adequação entre objeto e premissa); T2_2025.pdf, item 3 do trabalho.",
        competencia="Escolher a lente teórica por adequação entre objeto e premissa, e instrumentalizar seus conceitos.",
        erro="Escolher o autor por associação vaga (país grande, logo Mackinder) em vez de por adequação conceitual.",
        tempo=4,
        verificacao="Liste os elementos concretos do caso e marque, ao lado de cada um, o conceito do autor que o cobre. O autor certo cobre todos."),
]
