# -*- coding: utf-8 -*-
"""Matriz canônica — Módulos 00, 01 e 02."""

# C(id, modulo, assunto, dep, fontes, prio, exam, rap, safar, prof, just, ex, vuln)
# prof/just: tuplas (rapido, pra-safar, completo). prof aceita None no rápido
# quando o conceito não está presente nessa modalidade.

R_ANC = "âncora — reconhecer e recuperar sob pressão de tempo"
P_APL = "aplicação — identificar em cenário novo e usar na resposta"
C_INT = "integração — mecanismo causal, exceção e leitura concorrente"
C_T3 = "T3 seletivo — comparação entre atores e arbitragem entre interpretações"
P_T3 = "T3 seletivo — sustenta interpretação e argumentação, aprofundado já no Pra Safar"

CONCEITOS = [
    # ─────────────────────────── M00 — método ────────────────────────────
    dict(
        id="REL-T2-M00-C001", modulo="00-metodo-e-matriz-de-cenarios",
        assunto="Recorte examinável da T2: aulas internas 13 a 18, com término em Rússia, e o deslocamento entre nome de arquivo e título interno do deck",
        dep=[], exam=True, rap=True, safar=True,
        fontes=["F01:primeiro slide", "F02:primeiro slide", "F03:primeiro slide",
                "F04:primeiro slide", "F05:primeiro slide", "F06:primeiro slide"],
        prio=["Sem o recorte o aluno estuda a coisa errada: os seis arquivos têm nome uma unidade menor que a aula que contêm."],
        prof=(R_ANC, P_APL, C_INT),
        just=("Evita a perda de tempo mais cara: estudar deck fora do escopo.",
              "Delimita o que pode e o que não pode aparecer numa resposta.",
              "Explica por que o deslocamento existe e como conferir pelo título interno."),
        ex=["AULA 12.pdf contém Aula 13 e Aula 14 emendadas.",
            "AULA 17.pdf é a Aula 18 (Rússia) e encerra o escopo."],
        vuln=["🔴 Estudar 'Aula 13' abrindo AULA 13.pdf, que é a Aula 14.",
              "🟠 Incluir Europa porque ela aparece depois de Rússia no resumo."],
    ),
    dict(
        id="REL-T2-M00-C002", modulo="00-metodo-e-matriz-de-cenarios",
        assunto="Hierarquia das fontes: slide > leitura autorizada > resumo de Aspirante > prova antiga (só formato) > pesquisa externa (só conjuntura datada)",
        dep=["REL-T2-M00-C001"], exam=True, rap=True, safar=True,
        fontes=["AUT:hierarquia declarada", "P02:padrão de correção por elementos"],
        prio=["Duas divergências reais do corpus (PND/END e Política Marítima Nacional) só se resolvem pela hierarquia."],
        prof=(R_ANC, P_APL, C_INT),
        just=("Uma linha: em dúvida, vale o slide.",
              "Resolve conflito concreto entre resumo e slide.",
              "Mostra as duas divergências documentadas e por que o resumo perdeu."),
        ex=["PND/END: resumo e deck antigo dizem 2016/2018; o deck atualizado diz Decreto 12.725, de 18/11/2025.",
            "PMN: o resumo diz 'defasada desde 1984/1994'; o slide registra o Decreto 12.481, de 02/06/2025."],
        vuln=["🔴 Tratar resumo de colega como autoridade.",
              "🟠 Usar prova antiga como conteúdo, e não como formato."],
    ),
    dict(
        id="REL-T2-M00-C003", modulo="00-metodo-e-matriz-de-cenarios",
        assunto="Matriz de análise de cenários em dez passos: ator, objetivo, condicionantes, vulnerabilidades, recursos, instrumentos, cálculo estratégico, lente teórica, contraponto, conclusão",
        dep=["REL-T2-M00-C001"], exam=True, rap=True, safar=True,
        fontes=["AUT:matriz desenhada a partir do perfil", "P06:itens 2, 3, 4 e 5 do trabalho de T2",
                "P05:respostas-padrão das discursivas"],
        prio=["É o roteiro único que serve à discursiva escrita e ao trabalho em grupo — os dois formatos possíveis da T2."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Dez perguntas decoradas substituem dez páginas de teoria na véspera.",
              "É o instrumento de trabalho de todos os módulos seguintes.",
              "Ganha os contrapontos e o passo de arbitragem entre leituras."),
        ex=["Aplicada ao AUKUS, à proibição da Huawei na Austrália e ao Canal de Kra.",
            "Os itens do trabalho de 2025 mapeiam um a um nos passos 2, 3, 6 e 8."],
        vuln=["🔴 Pular o passo 9 (contraponto) e entregar leitura única de caso ambíguo.",
              "🟠 Confundir recursos (o que tem) com instrumentos (o que usou)."],
    ),
    dict(
        id="REL-T2-M00-C004", modulo="00-metodo-e-matriz-de-cenarios",
        assunto="Imperativo estratégico: necessidade ou prioridade tida como essencial para o Estado alcançar objetivos nacionais, preservar segurança ou ampliar influência; orienta política externa, defesa, economia e diplomacia; muda com o contexto",
        dep=["REL-T2-M00-C003"], exam=True, rap=True, safar=True,
        fontes=["F04:slide \"Imperativo Estratégico\"", "F04:slide \"Exemplo prático\""],
        prio=["É o único conceito que o professor define formalmente em slide próprio e depois aplica a EUA, China e Rússia."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Palavra de ordem dos módulos 04, 05 e 06.",
              "Sem ele não se responde 'quais os três principais objetivos/desafios'.",
              "Inclui a mutabilidade e o contraste com interesse nacional e com objetivo declarado."),
        ex=["Guerra Fria: conter a expansão do rival era imperativo de EUA e URSS, e isso orientava alianças, ajuda econômica e estratégia militar."],
        vuln=["🔴 Tratar imperativo estratégico como sinônimo de objetivo de governo — ele é de Estado e sobrevive à alternância.",
              "🟠 Tratá-lo como fixo: o próprio slide diz que muda com o contexto."],
    ),
    dict(
        id="REL-T2-M00-C005", modulo="00-metodo-e-matriz-de-cenarios",
        assunto="Lente realista: em sistema internacional anárquico o imperativo central é sobrevivência; busca de poder e segurança, equilíbrio de poder, prevenção de ameaças, interesse nacional acima de considerações morais",
        dep=["REL-T2-M00-C004"], exam=True, rap=True, safar=True,
        fontes=["F04:slide \"Segundo as principais Teorias em RI — 1. Realismo\"", "P09:seção 1 (Hobbes, Maquiavel, Morgenthau, Waltz)"],
        prio=["A prova pede a lente, não o autor: 'aponte a alternativa que contenha apenas itens INCORRETOS' sobre aplicação de referenciais teóricos."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Reconhecer a lógica dominante em três segundos.",
              "Classificar cenário por variável explicativa predominante.",
              "Inclui o ponto que quase ninguém sabe: realistas também cooperam."),
        ex=["Um país aumenta gasto militar porque considera sua segurança ameaçada por rival regional."],
        vuln=["🔴 Confundir realismo com 'egoísmo', 'algo ruim' ou 'guerra'.",
              "🔴 Supor que Estado realista não coopera — coopera quando a cooperação serve à segurança ou ao poder.",
              "🟠 Responder 'é realismo porque o país buscou seus interesses' — não diz qual interesse, qual condicionante nem qual nexo."],
    ),
    dict(
        id="REL-T2-M00-C006", modulo="00-metodo-e-matriz-de-cenarios",
        assunto="Lente liberal/institucional: o imperativo não é apenas sobreviver, mas promover prosperidade, interdependência e cooperação; fortalecimento de instituições, expansão do comércio, promoção da democracia, solução pacífica",
        dep=["REL-T2-M00-C004"], exam=True, rap=True, safar=True,
        fontes=["F04:slide \"2. Liberais\"", "F04:slide \"2. Liberais (cont.)\"", "P09:seção 1"],
        prio=["Metade das questões de asserção e razão do corpus opõe leitura institucional a leitura de poder."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Reconhecer a lógica dominante.",
              "Classificar cenário e sustentar a escolha.",
              "Inclui a ambivalência da instituição: mecanismo de cooperação ou instrumento de poder."),
        ex=["Participação em OI (ONU, OMC) para reduzir incertezas e ampliar ganhos econômicos."],
        vuln=["🔴 Confundir liberalismo com ingenuidade ou com 'defender algo moral'.",
              "🟠 Supor que a presença de uma instituição no enunciado prova leitura liberal."],
    ),
    dict(
        id="REL-T2-M00-C007", modulo="00-metodo-e-matriz-de-cenarios",
        assunto="Lente construtivista: interesses não são fixos, são moldados por ideias, normas, identidades e valores compartilhados; construção social das ameaças; imperativo central é preservar e promover identidades e normas tidas por legítimas",
        dep=["REL-T2-M00-C004"], exam=True, rap=False, safar=True,
        fontes=["F04:slide \"3. Construtivismo\"", "F04:slide \"3. Construtivismo (cont.)\"", "P09:seção 1"],
        prio=["É a terceira lente definida em slide; a correlação da SOPA T1 cobrou construtivismo por caso (recepção distinta de refugiados)."],
        prof=(None, P_APL, C_T3),
        just=("Fora do Rápido: no tempo curto, as duas lentes que decidem a maioria dos casos são realismo e liberalismo.",
              "Necessária para casos em que nem poder nem instituição explicam a diferença de comportamento.",
              "Integrada à arbitragem entre as três leituras do mesmo fato."),
        ex=["A UE vê seus membros como parceiros e não como inimigos potenciais, por identidade comum construída historicamente."],
        vuln=["🟠 Usar construtivismo como saída fácil para qualquer caso cultural.",
              "🟡 Confundir identidade compartilhada com interesse convergente."],
    ),
    dict(
        id="REL-T2-M00-C008", modulo="00-metodo-e-matriz-de-cenarios",
        assunto="Palavras que acendem o radar e seus limites: termo-pista indica hipótese, nunca prova classificação; o que decide é a variável explicativa predominante no enunciado",
        dep=["REL-T2-M00-C005", "REL-T2-M00-C006", "REL-T2-M00-C007"], exam=True, rap=True, safar=True,
        fontes=["AUT:desenho antipegadinha", "P03:questões 1, 2, 3 e 6"],
        prio=["O professor constrói distratores exatamente sobre associação mecânica de palavra-chave."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Lista curta de pistas e a regra de ouro que impede o erro.",
              "Treina o passo de verificação antes de classificar.",
              "Inclui casos em que a mesma palavra puxa para lentes opostas."),
        ex=["'Soberania' aparece tanto em leitura realista (autonomia decisória) quanto liberal (igualdade jurídica dos Estados).",
            "'Tratado' não prova leitura liberal: AUKUS é tratado e é contenção."],
        vuln=["🔴 Tratar palavra-chave como gabarito automático."],
    ),
    dict(
        id="REL-T2-M00-C009", modulo="00-metodo-e-matriz-de-cenarios",
        assunto="Caso ambíguo e leitura predominante: o Brexit como clínica de interpretação — leitura realista por soberania, autonomia e controle; leitura liberal/institucional por integração, regras, interdependência e custos da ruptura",
        dep=["REL-T2-M00-C008"], exam=True, rap=True, safar=True,
        fontes=["AUT:clínica construída sobre as duas lentes dos slides", "P01:questão 1 (texto sobre Brexit e mídias digitais)",
                "F06:slide \"Geopolítica da Rússia (Dugin)\" (recomendação de separar Reino Unido e Europa)"],
        prio=["O Brexit está no corpus como estímulo de prova e é o caso em que a resposta depende do aspecto destacado pelo enunciado."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Ensina a regra: a classificação segue o aspecto destacado, não o fato.",
              "Treina as duas construções e a escolha justificada.",
              "Acrescenta a leitura construtivista e o teste de qual explicação cobre mais evidências do enunciado."),
        ex=["Enunciado que enfatiza recuperar controle de fronteiras e de regulação puxa leitura realista.",
            "Enunciado que enfatiza custo alfandegário, cadeias e acordo de retirada puxa leitura institucional."],
        vuln=["🔴 Dar resposta única a caso ambíguo.",
              "🟠 Concluir sem dizer qual evidência do enunciado sustenta a escolha."],
    ),
    dict(
        id="REL-T2-M00-C010", modulo="00-metodo-e-matriz-de-cenarios",
        assunto="Resposta discursiva em seis movimentos: tese, conceito, evidência, nexo causal, nuance ou contraponto, conclusão — e a correção por elementos exigidos com crédito parcial",
        dep=["REL-T2-M00-C003"], exam=True, rap=True, safar=True,
        fontes=["P05:respostas-padrão das questões 15, 17 e 18", "P02:correção por elementos faltantes",
                "P01:questões 14, 16, 17 e 18 com valor por subitem"],
        prio=["Nas provas escritas maiores o discursivo vale mais que o objetivo (5,3 de 10,0 na P1; 5,8 de 10,0 na P2)."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Seis palavras na ordem certa salvam pontos na véspera.",
              "É a forma de todas as respostas-modelo do curso.",
              "Inclui a comparação insuficiente / satisfatória / MB por módulo."),
        ex=["Resposta-padrão da P2 sobre a Austrália: tese, conceito (geopolítica de uma ilha), evidência (5G, ZTE, Huawei, investimento), nexo (segurança se sobrepõe a comércio), conclusão."],
        vuln=["🔴 Citar o autor ou o artigo sem instrumentalizar o conceito.",
              "🔴 Concluir sem nexo causal explícito.",
              "🟠 Omitir o elemento que o corretor lista — 'faltou mencionar' custa ponto."],
    ),
    dict(
        id="REL-T2-M00-C011", modulo="00-metodo-e-matriz-de-cenarios",
        assunto="Instrumentos de poder disponíveis a um ator: diplomacia, força militar, economia, instituições, normas, tecnologia e informação",
        dep=["REL-T2-M00-C003"], exam=True, rap=True, safar=True,
        fontes=["AUT:passo 6 da matriz", "P06:itens 4 e 5 do trabalho de T2", "P09:seção 3 (hard, soft, smart e sharp power)"],
        prio=["O trabalho de T2 exige nomear organizações, tratados e operações — ou seja, instrumentos."],
        prof=(R_ANC, P_APL, C_INT),
        just=("Checklist de sete instrumentos para não travar.",
              "Permite responder 'qual instrumento foi usado' em qualquer caso.",
              "Cruza instrumento com lente teórica e com face do poder."),
        ex=["Sanção econômica é instrumento econômico com objetivo de segurança.",
            "Adesão a tratado é instrumento institucional que pode servir a objetivo realista."],
        vuln=["🟠 Reduzir instrumento a força militar.",
              "🟡 Confundir instrumento com objetivo."],
    ),
    dict(
        id="REL-T2-M00-C012", modulo="00-metodo-e-matriz-de-cenarios",
        assunto="Geopolítica e oceanopolítica: distinção, e por que objetivos oceanopolíticos tendem a ser mais dinâmicos — oceano como massa única em fluxo, ordenamento jurídico próprio, compartilhamento inevitável, limites de confrontação definidos por relações de poder e não por proximidade territorial",
        dep=["REL-T2-M00-C003"], exam=True, rap=True, safar=True,
        fontes=["C02:seção 3.1 e princípios gerais", "P01:questão 4 (correlação Geopolítica × Oceanopolítica)",
                "P03:questão 6", "P09:seção 6", "P06:o trabalho pede objetivos \"geoceanopolíticos\""],
        prio=["O termo do enunciado do trabalho de 2025 é 'geoceanopolíticos'. A distinção já foi cobrada por correlação item a item."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Quatro diferenças decoradas resolvem a correlação.",
              "Necessária para ler qualquer objetivo marítimo dos quatro atores.",
              "Inclui Martinez Busch, fronteira integral, Mar Presencial e o deslocamento dos conflitos do plano terrestre para o oceânico."),
        ex=["Mahan e Spykman são nomes da geopolítica; Barbosa Jr. e More, divulgadores da oceanopolítica.",
            "O Chile sustenta 'Mar Presencial' com base em ocupação efetiva, desafiando o limite das 200 MN da CNUDM."],
        vuln=["🔴 Dizer que a oceanopolítica nasceu no Hemisfério Norte — nasceu no Sul, ainda que embase estratégias de potências do Norte.",
              "🟠 Tratar fronteira marítima como fronteira terrestre projetada na água."],
    ),
    dict(
        id="REL-T2-M00-C013", modulo="00-metodo-e-matriz-de-cenarios",
        assunto="Mahan no recorte da T2: poder marítimo, comando do mar, integração entre Marinha de Guerra e Marinha Mercante, bases e domínio dos choke points; a Grande Esquadra Branca e o Canal do Panamá como aplicação",
        dep=["REL-T2-M00-C012"], exam=True, rap=True, safar=True,
        fontes=["F04:slide \"Expansão geopolítica\"", "C03:seção sobre Mahan e Roosevelt",
                "P01:questão 14 (choke points de Mahan × Chatham House)", "P09:seção 5"],
        prio=["Mahan aparece em slide próprio da Aula 16 e foi cobrado em discursiva de 1,8 ponto."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Ferramenta obrigatória de qualquer caso marítimo.",
              "É a lente mais provável para instrumentalizar no trabalho de T2.",
              "Inclui o contraste com a abrangência maior dos choke points do Chatham House (canais, estreitos e infraestrutura litorânea de exportação, com efeito sobre segurança alimentar)."),
        ex=["A interligação entre as marinhas da costa leste e da costa oeste exigiu o Canal do Panamá.",
            "A crítica da correção da SOPA: faltou dizer que os choke points do Chatham House são essenciais à segurança alimentar mundial."],
        vuln=["🔴 Reduzir Mahan a 'ter muitos navios'.",
              "🟠 Achar que choke point de Mahan e do Chatham House são a mesma coisa."],
    ),
    dict(
        id="REL-T2-M00-C014", modulo="00-metodo-e-matriz-de-cenarios",
        assunto="Spykman no recorte da T2: Rimland e contenção; consolidar a hegemonia nas Américas como pré-requisito para conter a potência eurasiática; o 'mediterrâneo americano' e o papel atribuído à América do Sul",
        dep=["REL-T2-M00-C013"], exam=True, rap=True, safar=True,
        fontes=["F04:slide \"Expansão geopolítica\"", "F04:slide \"EUA — Imperativo Estratégico\"",
                "C03:seção sobre Spykman", "P03:questão 10 (asserção e razão)"],
        prio=["A SOPA T1 cobrou exatamente a relação entre Spykman e o pré-requisito sul-americano, em asserção e razão."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Explica por que o Brasil importa ao cálculo dos EUA.",
              "Lente central dos módulos 04 e 06.",
              "Inclui o detalhe que gera a pegadinha: pré-requisito não é o mesmo que explicação completa."),
        ex=["Spykman insere Venezuela e Colômbia no 'mundo intermediário' entre o norte e o sul do continente.",
            "AUKUS lido como contenção da China é aplicação de Spykman."],
        vuln=["🔴 Trocar Rimland por Heartland.",
              "🔴 Marcar 'a afirmativa 2 é a explicação completa' quando ela é apenas um dos elementos."],
    ),
    dict(
        id="REL-T2-M00-C015", modulo="00-metodo-e-matriz-de-cenarios",
        assunto="Ponte de pré-requisito: repertório geopolítico das aulas 4 e 5 — Mackinder (Heartland), Corbett (controle do mar em vez de comando), Haushofer (espaço vital e panregiões), Douhet e Seversky (poder aéreo), geopolíticos brasileiros (Travassos, Golbery, Meira Mattos, Therezinha de Castro)",
        dep=["REL-T2-M00-C013"], exam=False, rap=False, safar=True,
        fontes=["P09:seção 5", "C01:Travassos e Golbery", "C02:Meira Mattos e Therezinha de Castro",
                "P06:\"entre os geopolíticos estudados nas aulas 4 e 5, escolham aquele que...\""],
        prio=["Fora do escopo da T2, mas o trabalho de T2 obriga a escolher UM desses autores. Entra em poucas linhas, como ponte."],
        prof=(None, "reconhecimento — quem é quem, em uma linha cada", C_INT),
        just=("Fora do Rápido: não é conteúdo das aulas 13 a 18.",
              "Indispensável se a T2 repetir o formato de trabalho em grupo.",
              "Ganha o critério de adequação entre objeto de análise e premissa do autor."),
        ex=["Guerra da Ucrânia lida por Mackinder (Europa Oriental e Heartland) e por Spykman (Rimland).",
            "Golbery: área de reserva geral, plataforma central de manobra, área continental de soldadura."],
        vuln=["🟠 Citar o autor sem instrumentalizar o conceito — não pontua.",
              "🟡 Aplicar Douhet a um caso naval só porque há aeronaves envolvidas."],
    ),
    dict(
        id="REL-T2-M00-C016", modulo="00-metodo-e-matriz-de-cenarios",
        assunto="Formatos de cobrança e como neutralizá-los: comando invertido (INCORRETA, apenas itens INCORRETOS, a que NÃO contribui, TODAS simultaneamente), asserção e razão com a variante 'explicação completa', correlação de melhores pares, alternativa longa parcialmente verdadeira, e o formato de trabalho em grupo",
        dep=["REL-T2-M00-C010"], exam=True, rap=True, safar=True,
        fontes=["P01:questões 6, 7, 9 e 12", "P03:questões 1, 3, 4, 6, 9 e 10", "P05:questões 6, 7, 9, 10 e 13",
                "P06:estrutura e pesos", "AUT:perfil-cobranca.json"],
        prio=["Neutralizar o formato vale mais pontos que saber um conceito extra."],
        prof=(R_ANC, P_APL, C_INT),
        just=("Seis regras operacionais para a hora da prova.",
              "Treinada em todos os módulos com questões nos mesmos formatos.",
              "Inclui a incerteza declarada sobre o formato da T2 e a preparação para os dois cenários."),
        ex=["Em asserção e razão, julgar cada afirmativa isolada ANTES de avaliar o nexo.",
            "Em alternativa longa, ler até o fim: o erro costuma estar enxertado no meio."],
        vuln=["🔴 Responder 'apenas itens INCORRETOS' marcando o que é correto.",
              "🟠 Aceitar o nexo porque as duas afirmativas são verdadeiras."],
    ),

    # ─────────────── M01 — Política Externa Brasileira ───────────────────
    dict(
        id="REL-T2-M01-C001", modulo="01-politica-externa-brasileira",
        assunto="Dilema básico de uma política externa: interesses × meios de ação, mediados por princípios",
        dep=["REL-T2-M00-C003"], exam=True, rap=True, safar=True,
        fontes=["F01:slide \"Dilemas básicos de uma Política Externa\""],
        prio=["É a moldura que o professor põe antes de qualquer fase histórica; organiza todo o módulo."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Uma equação que organiza 200 anos de história.",
              "Permite explicar por que a mesma ambição gera políticas diferentes.",
              "Integra com capacidade nacional e contexto internacional."),
        ex=["Ambição de autonomia com pouca capacidade econômica produz autonomia pela distância; com capacidade, produz diversificação."],
        vuln=["🔴 Confundir interesse (o que se quer) com meio de ação (com o que se consegue).",
              "🟠 Tratar princípio como enfeite retórico: no caso brasileiro ele restringe o meio disponível."],
    ),
    dict(
        id="REL-T2-M01-C002", modulo="01-politica-externa-brasileira",
        assunto="Mediações que condicionam a política externa: circunstâncias históricas e políticas internas e externas, capacidade econômica interna e características econômicas externas, resultados mensuráveis dos relacionamentos e influência da sociedade",
        dep=["REL-T2-M01-C001"], exam=True, rap=True, safar=True,
        fontes=["F01:slide \"Dilemas básicos de uma Política Externa\""],
        prio=["São os 'fatores facilitadores/dificultadores' que o trabalho de T2 exige nominalmente."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Cinco condicionantes que cabem numa linha.",
              "Vira checklist de fatores facilitadores e dificultadores.",
              "Cruza com crise da dívida, commodities e instabilidade política interna."),
        ex=["A crise da dívida dos anos 1980 aparece como condicionante econômico em Sarney e Figueiredo.",
            "A 'fragmentação da sociedade' de Alsina Jr. é condicionante de influência social."],
        vuln=["🟠 Listar condicionantes sem dizer em que direção cada um empurra a decisão."],
    ),
    dict(
        id="REL-T2-M01-C003", modulo="01-politica-externa-brasileira",
        assunto="Precedentes coloniais: a preocupação portuguesa central era a defesa do território (Prata, litoral, Amazônia); principal aliado a Inglaterra desde o século XIV; ameaças Espanha (Tordesilhas, Prata), França (França Antártica, França Equinocial) e Províncias Unidas (Bahia, Pernambuco)",
        dep=["REL-T2-M01-C001"], exam=True, rap=False, safar=True,
        fontes=["F01:slide \"Precedentes históricos — Colônia\"", "F01:slide \"INVASÕES EXTERNAS À COLONIA\""],
        prio=["Explica dois padrões que atravessam o módulo: a aliança extrarregional de longa duração e a vulnerabilidade litorânea."],
        prof=(None, P_APL, C_INT),
        just=("Fora do Rápido: cronologia colonial não decide questão interpretativa no tempo curto.",
              "Serve como precedente indispensável do padrão 'aliado extrarregional contra vizinho ameaçador'.",
              "Ganha as datas das ocupações e a leitura de por que o litoral era o ponto frágil."),
        ex=["França Antártica 1555-1567; França Equinocial 1594-1615; Salvador 1624-1625; Olinda e Recife 1630-1654.",
            "Em 1642 Portugal cedeu em definitivo à Holanda o território do Golfo da Guiné."],
        vuln=["🟠 Narrar as invasões sem extrair o padrão: colônia rica e exposta pelo mar atrai potência naval.",
              "🟡 Datar a aliança inglesa no século XIX — o slide a situa desde o século XIV."],
    ),
    dict(
        id="REL-T2-M01-C004", modulo="01-politica-externa-brasileira",
        assunto="Império, 1ª fase (1822-1850): reconhecimento do país, questão do Prata (Cisplatina, crise no Uruguai), proibição inglesa ao tráfico negreiro; Grã-Bretanha declinante e EUA ascendente como apoios; Argentina como principal ameaça",
        dep=["REL-T2-M01-C003"], exam=True, rap=False, safar=True,
        fontes=["F01:slide \"Política Externa Brasileira (PEB) — Império – 1ª fase\"", "F01:slide \"GUERRA DA CISPLATINA\""],
        prio=["Inaugura a rivalidade platina que orienta a política externa por quase um século."],
        prof=(None, P_APL, C_INT),
        just=("Fora do Rápido.",
              "Fixa o eixo Prata como interesse permanente.",
              "Acrescenta o custo do reconhecimento e a assimetria com a Grã-Bretanha."),
        ex=["Guerra da Cisplatina 1825-1828, com batalhas no Rio Uruguai, Rio Negro, Montevidéu e Buenos Aires."],
        vuln=["🟠 Tratar a proibição do tráfico como tema apenas interno: era condicionante externo imposto pelo aliado."],
    ),
    dict(
        id="REL-T2-M01-C005", modulo="01-politica-externa-brasileira",
        assunto="Império, 2ª fase (1850-1889): Prata (Argentina, Uruguai, Guerra do Paraguai), livre navegação no rio Amazonas, Questão Christie (fim de 1862 a fim de 1865); apoio dos EUA especialmente a partir dos anos 1870; ameaça argentina",
        dep=["REL-T2-M01-C004"], exam=True, rap=False, safar=True,
        fontes=["F01:slide \"PEB - Império - 2ª fase (1850~1889)\"", "C01:Guerra da Tríplice Aliança"],
        prio=["A livre navegação do Amazonas é o precedente direto do interesse brasileiro sobre bacias internacionais."],
        prof=(None, P_APL, C_INT),
        just=("Fora do Rápido.",
              "Liga o Prata e a Amazônia como dois eixos simultâneos.",
              "Inclui a Questão Christie como caso de atrito com o aliado declinante."),
        ex=["Guerra da Tríplice Aliança 1864-1870."],
        vuln=["🟡 Datar a aproximação com os EUA no Império inteiro — o slide a situa a partir da década de 1870."],
    ),
    dict(
        id="REL-T2-M01-C006", modulo="01-politica-externa-brasileira",
        assunto="República Velha (1889-1930): aliança não-escrita com os EUA como anteparo a pretensões imperialistas europeias e por interesse econômico; resolução das questões fronteiriças pelo Barão do Rio Branco; integração e não-belicosidade com vizinhos; Argentina como preocupação principal; participação na I Guerra",
        dep=["REL-T2-M01-C005"], exam=True, rap=True, safar=True,
        fontes=["F01:slide \"PEB - República Velha (1889~1930)\"", "F01:slide \"CONFIGURAÇÃO DO TERRITÓRIO BRASILEIRO NA REPÚBLICA\"",
                "F01:Estudo Dirigido (\"Por que a aliança não-escrita ... foi benéfica para ambas as partes?\")"],
        prio=["O próprio Estudo Dirigido do professor pede a explicação do benefício mútuo dessa aliança."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Marco que o aluno precisa recuperar de memória.",
              "Caso-modelo de alinhamento que rendeu ganho concreto.",
              "Exige explicar o ganho de CADA lado, como o Estudo Dirigido pede."),
        ex=["Questão do Amapá 1903 (França), Pirara 1904 (Reino Unido), Acre 1903 (Bolívia), Palmas 1895 (Argentina).",
            "Preocupações secundárias: Reino Unido (apoio na Revolta da Armada, ocupação de Trindade), França e outras potências imperialistas na Amazônia."],
        vuln=["🔴 Chamar a aliança de tratado: ela é NÃO-ESCRITA.",
              "🟠 Responder o benefício só do lado brasileiro."],
    ),
    dict(
        id="REL-T2-M01-C007", modulo="01-politica-externa-brasileira",
        assunto="Heranças do Barão do Rio Branco: princípio da não-intervenção, abordagem basicamente pacífica para litígios e boa vizinhança — e por que continuam operantes",
        dep=["REL-T2-M01-C006"], exam=True, rap=True, safar=True,
        fontes=["F01:slide \"Principais heranças do Barão do Rio Branco\"",
                "F01:Estudo Dirigido (\"Por que a herança dos feitos do Barão do Rio Branco são tão importantes, ainda hoje?\")",
                "F01:slide \"PEB - Constituição de 1988\""],
        prio=["Estudo Dirigido explícito e ponte direta com o art. 4º da CF/88."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Três heranças e a razão de cada uma.",
              "Explica a continuidade entre 1902-1912 e 1988.",
              "Discute o custo estratégico da herança, na crítica de Alsina Jr."),
        ex=["Dez fronteiras resolvidas sem guerra reduzem permanentemente a necessidade de dissuasão terrestre.",
            "Os princípios reaparecem literalmente nos incisos III, IV e VII do art. 4º da CF/88."],
        vuln=["🟠 Tratar a herança como só simbólica: ela reduz custo de defesa e credencia o Brasil como mediador.",
              "🟡 Confundir não-intervenção (princípio) com neutralidade (postura conjuntural)."],
    ),
    dict(
        id="REL-T2-M01-C008", modulo="01-politica-externa-brasileira",
        assunto="Primeiro período Vargas (1930-1945): efeitos da crise econômica mundial, política comercial pendular com EUA e Alemanha, aprofundamento do alinhamento com a II Guerra, Volta Redonda, base dos EUA em Natal, Lend-Lease (5º maior recebedor) e FEB (único país latino-americano a enviar tropas)",
        dep=["REL-T2-M01-C006"], exam=True, rap=True, safar=True,
        fontes=["F01:slide \"PEB - 1º Período Vargas (1930-1945)\"", "F01:slide \"POSIÇÃO ESTRATÉGICA DO BRASIL\"",
                "F01:Estudo Dirigido (\"o alinhamento automático com a maior potência sempre apresentou resultados positivos?\")"],
        prio=["É o caso POSITIVO de barganha que o professor contrasta com o caso negativo de 1952. Estudo Dirigido explícito."],
        prof=(R_ANC, P_T3, C_T3),
        just=("O exemplo que responde à pergunta do professor sobre alinhamento.",
              "Mostra o mecanismo: ativo geográfico escasso vira barganha convertida em capacidade.",
              "Integra a posição do Nordeste, a autonomia das aeronaves de 1942 e a industrialização."),
        ex=["Os aviões não tinham autonomia para voar diretamente para a África: as bases do Nordeste eram insubstituíveis.",
            "A barganha converteu posição geográfica em siderurgia (Volta Redonda), material (Lend-Lease) e prestígio (FEB)."],
        vuln=["🔴 Chamar a política dos anos 1930 de alinhamento: ela é PENDULAR entre EUA e Alemanha até a entrada na guerra.",
              "🟠 Esquecer que a contrapartida foi obtida porque o ativo era escasso e urgente."],
    ),
    dict(
        id="REL-T2-M01-C009", modulo="01-politica-externa-brasileira",
        assunto="Pós-II Guerra (1946-1960): TIAR de 1947 sob Dutra; Acordo Militar com os EUA de 1952 e a tentativa frustrada de reeditar os ganhos dos anos 1940 (Guerra da Coreia, sem envio de tropas) sob Vargas; continuidade em Café Filho; desenvolvimento, Operação Pan-Americana e atração de capitais externos sob Juscelino",
        dep=["REL-T2-M01-C008"], exam=True, rap=True, safar=True,
        fontes=["F01:slide \"PEB - Pós II GM (1946~1960)\"", "C01:TIAR e Sistema Interamericano"],
        prio=["É o caso NEGATIVO de alinhamento: mesma estratégia, contexto diferente, resultado nulo."],
        prof=(R_ANC, P_T3, C_T3),
        just=("O contraste que fecha a resposta sobre alinhamento.",
              "Ensina que o valor da barganha depende da escassez do ativo no momento.",
              "Integra TIAR, OEA e a lógica de contenção hemisférica."),
        ex=["Em 1942 a posição do Nordeste era insubstituível; em 1952, na Coreia, o Brasil não tinha ativo comparável a oferecer.",
            "A OPA de Juscelino desloca a barganha do terreno militar para o do desenvolvimento."],
        vuln=["🔴 Responder que o alinhamento automático 'sempre' deu resultado — 1952 é o contraexemplo do próprio professor.",
              "🟠 Confundir TIAR (1947, assistência recíproca) com OEA (1948, Bogotá, organização)."],
    ),
    dict(
        id="REL-T2-M01-C010", modulo="01-politica-externa-brasileira",
        assunto="Política Externa Independente (1961-1964): retomada das relações com a URSS, repensar a aliança incondicional com os EUA, defesa da autodeterminação, ênfase nos três D (desarmamento, descolonização, desenvolvimento) e tentativa de ampliar a margem de manobra na bipolaridade rígida, abstraindo premissas ideológicas",
        dep=["REL-T2-M01-C009"], exam=True, rap=True, safar=True,
        fontes=["F01:slide \"PEB - Política Externa Independente (1961~1964)\"",
                "P01:questão 10 (cinco postulados da PEI, em Visentini)"],
        prio=["Já foi cobrada em questão objetiva de 0,4 com cinco alternativas próximas."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Os três D e o sentido da PEI.",
              "Base do primeiro tipo da síntese tipológica (autonomia pela distância).",
              "Inclui os cinco postulados e o teste de Cuba e da crise dos mísseis."),
        ex=["Cuba e a crise dos mísseis como teste da margem de manobra.",
            "Postulados (Visentini): paz e desarmamento; não-intervenção e autodeterminação; emancipação de territórios não autônomos; autonomia na formulação do desenvolvimento; ampliação de mercados, inclusive socialistas."],
        vuln=["🔴 Ler a PEI como aproximação do bloco socialista: é ampliação de margem de manobra, com ênfase regionalista.",
              "🟠 Confundir os três D com os princípios da CF/88."],
    ),
    dict(
        id="REL-T2-M01-C011", modulo="01-politica-externa-brasileira",
        assunto="Governos civis-militares (1964-1985): Castello Branco e o alinhamento automático; Costa e Silva e Médici e a flexibilização; Geisel e o Pragmatismo Responsável (reconhecimento da RPC e da independência de Angola, acordo nuclear com a Alemanha, denúncia do tratado militar com os EUA, TCA); Figueiredo e o Equilíbrio (Malvinas, Itaipu, secretário-geral da OEA, crise da dívida)",
        dep=["REL-T2-M01-C010"], exam=True, rap=True, safar=True,
        fontes=["F01:slide \"PEB - Governos civis-militares (1964~1985)\"", "C01:Itaipu e a aproximação com a Argentina"],
        prio=["Contém o único ciclo em que o Brasil passa de alinhamento automático a denúncia de tratado militar com o aliado."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Quatro rótulos e uma palavra-chave cada.",
              "Mostra que ideologia interna e política externa podem divergir.",
              "Explica por que Malvinas prepara o Mercosul."),
        ex=["Um governo militar anticomunista reconhece a China Popular e Angola independente: o pragmático vence o ideológico.",
            "O apoio diplomático de Figueiredo a Buenos Aires em 1982 é a plataforma da aproximação que gera o Mercosul."],
        vuln=["🔴 Supor alinhamento uniforme aos EUA em todo o período: só Castello Branco é alinhamento automático.",
              "🟠 Atribuir Itaipu a Figueiredo: o tratado é de 1973, sob Médici; a Figueiredo cabe o acordo com a Argentina."],
    ),
    dict(
        id="REL-T2-M01-C012", modulo="01-politica-externa-brasileira",
        assunto="Constituição de 1988, art. 4º: os dez princípios das relações internacionais e o parágrafo único sobre integração latino-americana",
        dep=["REL-T2-M01-C007"], exam=True, rap=True, safar=True,
        fontes=["F01:slide \"PEB - Constituição de 1988\"",
                "F01:Estudo Dirigido (\"Por que o Brasil deve buscar a integração da América Latina? Dê uma razão institucional e outra de política pragmática\")"],
        prio=["É a razão INSTITUCIONAL que o Estudo Dirigido exige, ao lado de uma razão pragmática."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Os dez incisos são âncora de memória de alto retorno.",
              "Fornece a fundamentação normativa de qualquer resposta sobre integração.",
              "Integra com Rio Branco, com o Mercosul e com o custo estratégico apontado por Alsina Jr."),
        ex=["I independência nacional; II prevalência dos direitos humanos; III autodeterminação dos povos; IV não-intervenção; V igualdade entre os Estados; VI defesa da paz; VII solução pacífica dos conflitos; VIII repúdio ao terrorismo e ao racismo; IX cooperação entre os povos; X concessão de asilo político.",
            "Parágrafo único: integração econômica, política, social e cultural dos povos da América Latina, visando a uma comunidade latino-americana de nações."],
        vuln=["🔴 Dizer que o parágrafo único manda integrar a América do Sul — o texto diz América Latina.",
              "🟠 Responder a integração só pela via pragmática, ignorando o mandamento constitucional."],
    ),
    dict(
        id="REL-T2-M01-C013", modulo="01-politica-externa-brasileira",
        assunto="Governos pós-1985 até Itamar: Sarney (ZOPACAS 1986, reatamento com Cuba, distensão com a Argentina, incremento com os vizinhos, impactos da crise da dívida); Collor e Itamar (continuidade, autonomia por modernização econômica, Mercosul 1991, Rio 92)",
        dep=["REL-T2-M01-C011"], exam=True, rap=True, safar=True,
        fontes=["F01:slide \"PEB - Governos pós-1985\" (Sarney, Collor/Itamar)", "C01:Declaração do Iguaçu e Tratado de Assunção"],
        prio=["ZOPACAS é pressuposto da PND e compõe o entorno estratégico — liga o módulo 01 aos módulos 02 e 03."],
        prof=(R_ANC, P_T3, C_T3),
        just=("ZOPACAS e Mercosul são âncoras que reaparecem em três módulos.",
              "É a 'transição' da síntese tipológica.",
              "Integra a Declaração do Iguaçu, a renúncia nuclear bélica e a cláusula democrática posterior."),
        ex=["Declaração do Iguaçu (1985): Atlântico Sul declarado zona de paz e cooperação, pressupondo renúncia a programas nucleares bélicos.",
            "ZOPACAS (1986) é instrumento de política externa que depois se torna pressuposto de política de defesa."],
        vuln=["🟠 Datar ZOPACAS em 1991 junto com o Mercosul.",
              "🟡 Tratar Rio 92 como tema ambiental apenas: é também projeção diplomática."],
    ),
    dict(
        id="REL-T2-M01-C014", modulo="01-politica-externa-brasileira",
        assunto="FHC — autonomia pela participação e integração: reinserção mais ativa no sistema econômico internacional e nos organismos internacionais, abertura da economia, assinatura do TNP e do Regime de Controle de Tecnologia de Mísseis, visão kantiana das RI nos anos 1990, CPLP 1996 e rejeição à ALCA na Cúpula das Américas em Quebec (2001)",
        dep=["REL-T2-M01-C013"], exam=True, rap=True, safar=True,
        fontes=["F01:slide \"PEB - Governos pós-1985 — FHC\"", "P01:questão 18 (continuidades e descontinuidades FHC/Lula)",
                "P02:correção da questão 18 (\"ele errou em dizer que foi aproximação c os eua\")"],
        prio=["Foi cobrado em discursiva de 1,5 ponto e a correção registra exatamente o erro que os alunos cometem."],
        prof=(R_ANC, P_T3, C_T3),
        just=("O rótulo e as três siglas.",
              "Base da comparação FHC/Lula, que é a discursiva mais provável do módulo.",
              "Inclui a tensão entre assinar TNP/MTCR e reivindicar assento no CSNU."),
        ex=["A CPLP é peça de construção do entorno estratégico brasileiro, o que a liga à Política Naval.",
            "Rejeitar a ALCA em 2001 mostra que participação não é subordinação."],
        vuln=["🔴 Descrever FHC como aproximação com os EUA: o rótulo é participação e integração multilateral. Esse erro foi corrigido literalmente na SOPA da P1.",
              "🟠 Esquecer que a rejeição à ALCA é de FHC, não de Lula."],
    ),
    dict(
        id="REL-T2-M01-C015", modulo="01-politica-externa-brasileira",
        assunto="Lula — autonomia pela diversificação: expansão preferencialmente Sul-Sul, abertura de embaixadas, IBAS, Unasul, BRICS e estratégia bifronte (América Latina × resto do mundo)",
        dep=["REL-T2-M01-C014"], exam=True, rap=True, safar=True,
        fontes=["F01:slide \"PEB - Governos pós-1985 — Lula\"", "P01:questão 18",
                "P02:correção da questão 18b (posição comum sobre o Conselho de Segurança)", "C01:Unasul e IIRSA"],
        prio=["A discursiva pede o que é COMUM entre FHC e Lula, e a correção diz qual é: reforma e assento permanente no CSNU."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Rótulo, siglas e a posição comum no CSNU.",
              "Completa a comparação FHC/Lula com continuidade e descontinuidade.",
              "Integra estratégia bifronte, IIRSA e a leitura de Magnoli sobre potência regional que vira ator global."),
        ex=["Posição comum a FHC e Lula: o CSNU está centrado nas potências vencedoras da II Guerra e não reflete a geopolítica do século XXI; daí a reivindicação de assento permanente e maior representatividade.",
            "A IIRSA torna a Amazônia central para a integração, apesar de não concentrar os fluxos mais densos de capital."],
        vuln=["🔴 Dizer que Lula abandonou a América do Sul: a estratégia é BIFRONTE.",
              "🟠 Responder a continuidade sem identificar o 'ente de maior poder geopolítico' da ONU como o Conselho de Segurança."],
    ),
    dict(
        id="REL-T2-M01-C016", modulo="01-politica-externa-brasileira",
        assunto="Dilma, Temer e Bolsonaro: continuidade burocrática e paralisia presidencial; imobilismo por crise política interna; alinhamento valorativo durante o governo Trump e distanciamento cauteloso durante o governo Biden",
        dep=["REL-T2-M01-C015"], exam=True, rap=True, safar=True,
        fontes=["F01:slide \"PEB - Governos pós-1985 — Temer, Bolsonaro\"", "F01:slide \"Síntese tipológica\""],
        prio=["Fecha a tipologia e introduz a distinção entre alinhamento valorativo e alinhamento pragmático."],
        prof=(R_ANC, P_APL, C_INT),
        just=("Dois rótulos curtos.",
              "Necessário para a tipologia completa.",
              "Discute alinhamento valorativo como categoria distinta do alinhamento automático de Castello."),
        ex=["Alinhamento valorativo se ancora em afinidade de governo; alinhamento automático, em cálculo de bloco. Um cai com a eleição do parceiro; o outro, não."],
        vuln=["🟠 Chamar de paralisia o governo Bolsonaro: o slide reserva 'paralisia' a Dilma e Temer.",
              "🟡 Confundir alinhamento valorativo com pragmatismo responsável."],
    ),
    dict(
        id="REL-T2-M01-C017", modulo="01-politica-externa-brasileira",
        assunto="Síntese tipológica da autonomia: autonomia pela distância (da PEI aos governos militares, exceto Castello) → transição (Sarney, Collor, Itamar) → autonomia pela participação (FHC) → autonomia pela diversificação (Lula) → paralisia (Dilma, Temer)",
        dep=["REL-T2-M01-C010", "REL-T2-M01-C014", "REL-T2-M01-C015", "REL-T2-M01-C016"], exam=True, rap=True, safar=True,
        fontes=["F01:slide \"Síntese tipológica\"", "A01:quadro de abertura (PEI → transição → FHC → Lula → paralisia)"],
        prio=["É o organizador final do módulo e a resposta mais provável de qualquer questão que peça 'fases da política externa'."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Cinco rótulos em ordem: o maior retorno por minuto do módulo.",
              "Permite classificar qualquer governo pela relação entre ambição e abertura.",
              "Integra os três tipos de autonomia com capacidade nacional e contexto internacional."),
        ex=["Distância: objetivos próprios sem muita abertura. Participação: abertura econômica e inserção em organismos. Diversificação: aprofundamento com parceiros desenvolvidos e em desenvolvimento, priorizando Sul-Sul."],
        vuln=["🔴 Incluir Castello Branco na autonomia pela distância — o slide o EXCETUA.",
              "🟠 Tratar os três tipos como graus de patriotismo em vez de combinações entre ambição e abertura."],
    ),
    dict(
        id="REL-T2-M01-C018", modulo="01-politica-externa-brasileira",
        assunto="Dilemas futuros da política externa brasileira: ambiente político e econômico internacional incerto, competição interestatal crescente, escolha de alianças, papel na América do Sul e Latina e o Atlântico Sul",
        dep=["REL-T2-M01-C017"], exam=True, rap=True, safar=True,
        fontes=["F01:slide \"PEB - Dilemas futuros\"", "F01:Estudo Dirigido (\"Escolha um dos quadrantes do slide 25 e aplique-o ao Brasil\")",
                "A01:fechamento do bloco da Aula 13 (bipolaridade EUA-China, guerra tarifária, Guerra da Ucrânia)"],
        prio=["O trabalho de T2 exige 'perspectiva de alteração futura' — este conceito é o gancho."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Quatro dilemas para abrir ou fechar qualquer resposta.",
              "Instrumento da parte prospectiva do trabalho e das discursivas.",
              "Integra competição interestatal por recursos, Atlântico Sul e a escolha entre alinhamento e diversificação."),
        ex=["O quadrante do documento britânico Global Britain in a Competitive Age (2021, p. 25) é o material do Estudo Dirigido.",
            "Bipolaridade EUA-China com guerra tarifária, Guerra da Ucrânia e disputa crescente por recursos naturais."],
        vuln=["🟠 Projetar futuro sem ancorar em condicionante presente: projeção sem mecanismo não pontua.",
              "🟡 Tratar o Atlântico Sul como tema militar apenas."],
    ),
    dict(
        id="REL-T2-M01-C019", modulo="01-politica-externa-brasileira",
        assunto="Bolivarianismo e pan-americanismo: Carta da Jamaica e o projeto de confederação hispano-americana; Congresso do Panamá de 1826 e seu fracasso; fragmentação territorial sob as oligarquias criollas; substituição do hispano-americanismo pelo pan-americanismo liderado pelos EUA",
        dep=["REL-T2-M01-C004"], exam=True, rap=False, safar=True,
        fontes=["C01:\"Do bolivarianismo ao pan-americanismo\"", "C01:p. 342-346"],
        prio=["Bibliografia OBRIGATÓRIA da Aula 13. Explica por que o Brasil nunca foi convidado de fato ao projeto bolivariano."],
        prof=(None, P_APL, C_T3),
        just=("Fora do Rápido.",
              "Explica a posição singular do Brasil na América Latina.",
              "Integra com a Doutrina Monroe, o Sistema Interamericano e a invenção da América Latina."),
        ex=["Bolívar não via no Brasil aliado antiespanhol e temia irritar a Grã-Bretanha; o governo imperial sabia do propósito de formar coligação antibrasileira na Cisplatina.",
            "'A América para os americanos... do norte' é a tradução do pan-americanismo, segundo Magnoli."],
        vuln=["🔴 Confundir hispano-americanismo (exclui as Américas britânica e portuguesa) com pan-americanismo (todo o hemisfério, sob liderança dos EUA).",
              "🟠 Tratar a fragmentação como acidente: ela reflete o interesse das oligarquias criollas e dos caudilhos."],
    ),
    dict(
        id="REL-T2-M01-C020", modulo="01-politica-externa-brasileira",
        assunto="Invenção da América Latina e o pensamento cepalino: panlatinismo de Chevalier, Napoleão III e o 'monroísmo às avessas', Maximiliano no México; Cepal (1948) com Prebisch e Furtado; Alalc (Montevidéu 1960) e sua substituição pela Aladi (1980); MCCA e Pacto Andino",
        dep=["REL-T2-M01-C019"], exam=True, rap=False, safar=True,
        fontes=["C01:\"Invenção da América Latina\"", "C01:p. 347-350"],
        prio=["Bibliografia obrigatória; explica por que os projetos de integração anteriores ao Mercosul fracassaram."],
        prof=(None, P_APL, C_INT),
        just=("Fora do Rápido.",
              "Fornece o mecanismo do fracasso: substituição de importações generalizada limita o comércio intrabloco.",
              "Integra rótulo geopolítico, teoria do desenvolvimento e desenho institucional."),
        ex=["Ironia registrada por Magnoli: a própria ênfase geral em substituição de importações limitou o crescimento do comércio na área da Alalc.",
            "O rótulo 'Latina' serviu a um projeto francês de fronteira contra os EUA e o Canadá."],
        vuln=["🟠 Tratar 'América Latina' como categoria natural: é representação geopolítica construída.",
              "🟡 Confundir Alalc (1960, zona de livre-comércio com cronograma) com Aladi (1980, metas flexíveis sem cronograma)."],
    ),
    dict(
        id="REL-T2-M01-C021", modulo="01-politica-externa-brasileira",
        assunto="Geopolítica brasileira clássica aplicada ao entorno: Travassos e os dois antagonismos geográficos (Atlântico × Pacífico; Prata × Amazonas), Bolívia e Paraguai como 'prisioneiros geopolíticos' da Argentina; Golbery e a projeção da área de reserva geral do Sudeste para a área continental de soldadura; ferrovias, Ponte da Amizade, BR-277 e o Tratado de Itaipu (1973)",
        dep=["REL-T2-M01-C011"], exam=True, rap=False, safar=True,
        fontes=["C01:\"O Brasil e a América do Sul\"", "C01:figura 21.1 (compartimentação geopolítica)", "P09:seção 5 (geopolítica no Brasil)"],
        prio=["É o repertório brasileiro que o trabalho de T2 pode exigir instrumentalizar, e explica Itaipu como operação geopolítica."],
        prof=(None, P_T3, C_T3),
        just=("Fora do Rápido.",
              "Dá ao aluno um teórico brasileiro para instrumentalizar, além de Mahan e Spykman.",
              "Integra infraestrutura, energia e influência: soldagem de interesses por obra física."),
        ex=["A Estrada de Ferro Noroeste do Brasil reduziu a dependência boliviana do porto de Buenos Aires.",
            "Itaipu concluiu a soldagem dos interesses paraguaios aos brasileiros e abriu a disputa com a Argentina que só se resolveu com o Mercosul."],
        vuln=["🟠 Ler Itaipu como projeto apenas energético.",
              "🟡 Trocar 'área de reserva geral' por 'área continental de soldadura'."],
    ),
    dict(
        id="REL-T2-M01-C022", modulo="01-politica-externa-brasileira",
        assunto="Mercosul e Unasul como instrumentos: Declaração do Iguaçu (1985), Tratado de Assunção (1991), Protocolo de Ouro Preto (1994) e a estrutura intergovernamental por consenso, Protocolo de Ushuaia (1998) e a cláusula democrática, adesão da Venezuela (2012); Unasul (2008) e a IIRSA",
        dep=["REL-T2-M01-C021", "REL-T2-M01-C013"], exam=True, rap=True, safar=True,
        fontes=["C01:\"Do Mercosul à Unasul\"", "P01:questão 12 (IIRSA e Amazônia, asserção e razão)",
                "F01:Estudo Dirigido (integração da América Latina)"],
        prio=["A IIRSA já foi cobrada em asserção e razão; o Mercosul é o instrumento institucional central do Brasil na região."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Quatro marcos e a cláusula democrática.",
              "Instrumento institucional a citar em qualquer resposta sobre integração.",
              "Integra o custo: a adesão da Venezuela ampliou o alcance geopolítico e reduziu a funcionalidade comercial."),
        ex=["Uruguai e Paraguai têm peso econômico reduzido e valor geopolítico elevado: eliminam fonte de atrito entre Brasil e Argentina.",
            "IIRSA: corredores de exportação e o papel central da Amazônia, apesar de não concentrar os fluxos mais densos de capital."],
        vuln=["🔴 Atribuir ao Mercosul órgãos supranacionais: a estrutura de Ouro Preto é INTERGOVERNAMENTAL e age por consenso.",
              "🟠 Datar a cláusula democrática em 1991: é o Protocolo de Ushuaia, de 1998."],
    ),

    # ───────────────────── M02 — PND, END e PESD ─────────────────────────
    dict(
        id="REL-T2-M02-C001", modulo="02-pnd-end-e-pesd",
        assunto="Grande Estratégia: coleção de planos e políticas que compreendem o esforço deliberado do Estado para reunir ferramentas políticas, militares, diplomáticas e econômicas em favor do interesse nacional (Peter Feaver); forte influência realista e horizonte de longo prazo",
        dep=["REL-T2-M00-C005"], exam=True, rap=True, safar=True,
        fontes=["A01:abertura do bloco da Aula 14 (conceito recuperado da explicação oral)",
                "F01:slide \"Pontos para Debate (segundo Alsina Jr.)\""],
        prio=["O resumo registra que o conceito é apresentado no início da aula e RESGATADO no final; é o fio condutor do módulo."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Uma definição operacional que organiza PND, END e PESD.",
              "É o conceito que liga política externa, defesa e economia numa só resposta.",
              "Integra a influência realista e a crítica de Alsina Jr. sobre a ausência de uma Grande Estratégia brasileira."),
        ex=["Reunir ferramenta diplomática (ZOPACAS), militar (PROSUB) e econômica (BID) sob um objetivo único é exercício de Grande Estratégia."],
        vuln=["🟠 Confundir Grande Estratégia (de Estado, de longo prazo, multi-instrumento) com estratégia militar (de campanha).",
              "🟡 Atribuir o conceito a documento oficial brasileiro: ele vem do debate acadêmico e entra pela discussão de Alsina Jr."],
    ),
    dict(
        id="REL-T2-M02-C002", modulo="02-pnd-end-e-pesd",
        assunto="Arquitetura documental da defesa: a PND é uma das políticas nacionais, com processo democrático de elaboração e decisão e necessidade de sensibilizar a sociedade (ex.: CADN); a PND define os objetivos, a END orienta as medidas e os setores para alcançá-los, e o Livro Branco de Defesa Nacional se dirige à sociedade e ao mundo",
        dep=["REL-T2-M02-C001"], exam=True, rap=True, safar=True,
        fontes=["F02:slide \"Política Nacional de Defesa\"", "F02:slide \"Estratégia Nacional de Defesa (END)\"",
                "A01:distinção PND / END / Livro Branco", "F01:organograma do Conselho de Defesa Nacional"],
        prio=["A distinção objetivo/medida/comunicação é a base de qualquer questão que troque um documento pelo outro."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Três documentos, três funções — a troca é a pegadinha mais previsível.",
              "Permite responder 'qual documento faz o quê' sem hesitação.",
              "Integra o processo de aprovação, os atores do Conselho de Defesa Nacional e a função externa do Livro Branco."),
        ex=["PND: o quê e por quê. END: como e por meio de quais capacidades. Livro Branco: transparência para a sociedade e para outros Estados.",
            "A END é o vínculo entre o posicionamento do País nas questões de Defesa e as ações necessárias para dotar o Estado de capacidade."],
        vuln=["🔴 Atribuir à END a definição dos objetivos — quem define objetivos é a PND.",
              "🟠 Tratar o Livro Branco como documento interno: ele é voltado principalmente à sociedade e ao mundo."],
    ),
    dict(
        id="REL-T2-M02-C003", modulo="02-pnd-end-e-pesd",
        assunto="Vigência e aprovação da PND/END: aprovada pelo Congresso em 2005, 2012 e 2018; versão em vigor de 18 de novembro de 2025 (Decreto nº 12.725), depois de uma proposta encaminhada em 2020",
        dep=["REL-T2-M02-C002"], exam=True, rap=True, safar=True,
        fontes=["F02:slide \"Política Nacional de Defesa/Estratégia Nacional de Defesa\" (versão atual 18 nov 2025, Decreto 12.725)",
                "F01:mesmo slide na versão anterior (\"Versão atual 2016, aprovada pelo Congresso em 2018\")",
                "AUT:conflito CF-01 do manifesto"],
        prio=["É a única divergência material entre dois testemunhos primários, e o professor atualizou o slide — sinal de que a data importa."],
        prof=(R_ANC, P_APL, C_INT),
        just=("Duas datas que não se confundem: aprovação pelo Congresso e versão em vigor.",
              "Evita errar por estudar deck antigo.",
              "Explica o conflito entre os dois decks e por que prevalece o mais recente."),
        ex=["Um deck em circulação ainda diz '2016, aprovada em 2018'; o deck atualizado diz 'versão atual 18 nov 2025'."],
        vuln=["🔴 Responder 2016 como versão vigente.",
              "🟠 Somar as três aprovações do Congresso (2005, 2012, 2018) como se fossem versões distintas em vigor."],
    ),
    dict(
        id="REL-T2-M02-C004", modulo="02-pnd-end-e-pesd",
        assunto="Entendimento da PND sobre a conjuntura internacional: instabilidade decorrente de novas ameaças — táticas convencionais e irregulares, conflitos urbanos, espaço cibernético e armas de destruição em massa",
        dep=["REL-T2-M02-C002"], exam=True, rap=True, safar=True,
        fontes=["F02:slide \"CONJUNTURA INTERNACIONAL / NOVAS AMEAÇAS\"", "A01:\"ameaças assimétricas\""],
        prio=["É a leitura oficial do sistema internacional — e o gancho para comparar com as ameaças do PEM 2040."],
        prof=(R_ANC, P_APL, C_INT),
        just=("Quatro ameaças em lista curta.",
              "Permite ligar documento de defesa a cenário internacional.",
              "Compara a lista da PND com a lista de ameaças do PEM 2040 e explica por que diferem."),
        ex=["O foco em instabilidade, e não em ameaça estatal definida, é o que justifica capacidades flexíveis em vez de um só vetor."],
        vuln=["🟠 Chamar de 'ameaça assimétrica' o que o slide chama de novas ameaças — a paráfrase é do resumo, não do slide.",
              "🟡 Confundir a lista da PND com a lista do PEM 2040 (que inclui pirataria, pesca ilegal, biopirataria)."],
    ),
    dict(
        id="REL-T2-M02-C005", modulo="02-pnd-end-e-pesd",
        assunto="Pressupostos da PND além dos princípios constitucionais: preparo, equipamento e motivação das Forças Armadas; manutenção do Atlântico Sul como Zona de Paz e Cooperação (ZOPACAS); estímulo à Base Industrial de Defesa; proteção e integração da Amazônia brasileira; defesa da exploração da Antártica somente para fins de pesquisa científica",
        dep=["REL-T2-M02-C004", "REL-T2-M01-C013"], exam=True, rap=True, safar=True,
        fontes=["F02:slide \"Alguns pressupostos da PND\"", "A01:detalhamento dos pressupostos (afastar bases ofensivas e armas nucleares; autonomia tecnológica)"],
        prio=["Cinco itens que ligam política externa (ZOPACAS), economia (BID) e território (Amazônia, Antártica) num só slide."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Cinco pressupostos — alto retorno por minuto.",
              "Cada pressuposto é um objetivo instrumentalizável numa resposta.",
              "Integra ZOPACAS com o entorno estratégico e a BID com autonomia tecnológica e produtiva."),
        ex=["ZOPACAS implica afastar bases ofensivas e evitar a presença de armas nucleares no Atlântico Sul.",
            "Estimular a BID é condição de autonomia: sem indústria própria, capacidade de defesa depende de terceiros."],
        vuln=["🔴 Dizer que a PND defende a exploração ECONÔMICA da Antártica — o pressuposto é pesquisa científica somente.",
              "🟠 Tratar a BID como tema industrial e não como condição de soberania."],
    ),
    dict(
        id="REL-T2-M02-C006", modulo="02-pnd-end-e-pesd",
        assunto="Objetivos Nacionais de Defesa (oito): garantir a soberania, o patrimônio nacional e a integridade territorial; assegurar a capacidade de Defesa para as missões constitucionais; promover a autonomia tecnológica e produtiva; preservar a coesão e a unidade nacionais; salvaguardar pessoas, bens, recursos e interesses nacionais no exterior; ampliar o envolvimento da sociedade; contribuir para a estabilidade regional e para a paz e segurança internacionais; incrementar a projeção do Brasil no concerto das Nações e sua inserção em processos decisórios internacionais",
        dep=["REL-T2-M02-C005"], exam=True, rap=True, safar=True,
        fontes=["F02:slides \"Objetivos Nacionais de Defesa\" (dois slides)", "AUT:conflito CF-03 do manifesto"],
        prio=["É a lista nominal mais cobrável do módulo e o ponto onde o resumo do Aspirante divergiu do slide."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Oito objetivos: a lista central do módulo.",
              "Cada objetivo é âncora para uma resposta sobre defesa e política externa.",
              "Integra o último objetivo com a reivindicação de assento no CSNU e com o apoio à política externa."),
        ex=["'Incrementar a projeção do Brasil no concerto das Nações' é a ponte entre defesa e a reivindicação de assento permanente no Conselho de Segurança.",
            "'Salvaguardar pessoas e interesses no exterior' justifica a evacuação de nacionais e a proteção de bens brasileiros fora do território."],
        vuln=["🔴 Incluir 'fortalecer a presença no entorno estratégico (ZOPACAS)' na lista: essa redação é do resumo, não do slide.",
              "🟠 Reduzir os objetivos a soberania e integridade territorial, ignorando autonomia tecnológica e coesão nacional."],
    ),
    dict(
        id="REL-T2-M02-C007", modulo="02-pnd-end-e-pesd",
        assunto="Capacidades Nacionais de Defesa (nove): proteção, pronta-resposta, dissuasão, coordenação e controle, gestão da informação, logística, mobilidade estratégica, mobilização e desenvolvimento tecnológico de defesa",
        dep=["REL-T2-M02-C006"], exam=True, rap=True, safar=True,
        fontes=["F02:slide \"Capacidades Nacionais de Defesa (CND)\"",
                "F02:Estudo Dirigido (\"Correlacione o conceito de multimodal com uma das Capacidades Nacionais de Defesa\")"],
        prio=["O Estudo Dirigido pede explicitamente correlação entre multimodal e uma CND: cobrança anunciada."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Nove capacidades — âncora de memória.",
              "É o vocabulário com que se responde 'com que meios'.",
              "Integra cada capacidade a um programa ou instrumento concreto."),
        ex=["Multimodal (atuar em vários domínios ou modais de forma integrada) correlaciona-se com mobilidade estratégica e com coordenação e controle.",
            "SisGAAz materializa gestão da informação e pronta-resposta."],
        vuln=["🔴 Confundir Capacidades Nacionais de Defesa (nove, END) com tarefas básicas do Poder Naval (quatro).",
              "🟠 Reduzir a lista às cinco que o resumo cita (proteção, pronta-resposta, dissuasão, logística, mobilização)."],
    ),
    dict(
        id="REL-T2-M02-C008", modulo="02-pnd-end-e-pesd",
        assunto="Águas Jurisdicionais Brasileiras (AJB): águas interiores e espaços marítimos em que o Brasil exerce jurisdição, em algum grau, sobre atividades, pessoas, instalações, embarcações e recursos naturais vivos e não vivos da massa líquida, do leito e do subsolo marinho, para controle e fiscalização; compreendem as 200 milhas marítimas contadas das linhas de base, acrescidas das águas sobrejacentes à extensão da plataforma continental além das 200 MN, onde ela ocorrer",
        dep=["REL-T2-M02-C007"], exam=True, rap=True, safar=True,
        fontes=["F02:slides \"Poder Naval (END)\" (definição de AJB)", "A01:AJB como ZEE + extensão da plataforma + águas interiores",
                "F02:Estudo Dirigido (\"O conceito de AJB ... abrange a Elevação do Rio Grande? Por quê?\")",
                "C02:Lei 8.617/1993 e LEPLAC"],
        prio=["Definição literal, longa e cobrável, e objeto de pergunta de julgamento no próprio Estudo Dirigido."],
        prof=(R_ANC, P_T3, C_T3),
        just=("A definição que sustenta metade das respostas marítimas.",
              "Permite decidir casos de jurisdição, como a Elevação do Rio Grande.",
              "Integra com a CNUDM, a Lei 8.617/1993, o LEPLAC e a Amazônia Azul."),
        ex=["A cláusula 'onde ela ocorrer' é o que permite discutir feições além das 200 MN.",
            "A jurisdição é exercida 'em algum grau': não é soberania plena em toda a extensão."],
        vuln=["🔴 Igualar AJB a mar territorial.",
              "🔴 Esquecer a expressão 'em algum grau': o grau de jurisdição varia por faixa.",
              "🟠 Afirmar categoricamente sobre a Elevação do Rio Grande sem discutir a extensão da plataforma continental submetida ao LEPLAC e à Comissão de Limites."],
    ),
    dict(
        id="REL-T2-M02-C009", modulo="02-pnd-end-e-pesd",
        assunto="Tarefas básicas do Poder Naval (END): controle de área marítima, negação do uso do mar, projeção de poder sobre terra e contribuição para a dissuasão; e o monitoramento do mar, inclusive a partir do espaço, que deve integrar o repertório de práticas e capacitações operacionais",
        dep=["REL-T2-M02-C008"], exam=True, rap=True, safar=True,
        fontes=["F02:slide \"Poder Naval (END) — Tarefas básicas\"",
                "F02:Estudo Dirigido (\"Correlacione alguma das tarefas básicas do Poder Naval com o conceito de Amazônia Azul\")",
                "A01:relação entre monitoramento do mar e SisGAAz"],
        prio=["Lista de quatro itens, com Estudo Dirigido explícito pedindo correlação com Amazônia Azul."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Quatro tarefas — âncora obrigatória.",
              "É a resposta ao 'com que meios e para quê' de qualquer questão naval.",
              "Integra as quatro tarefas com AJB, Amazônia Azul, SisGAAz e o complexo naval da foz do Amazonas."),
        ex=["Monitorar a Amazônia Azul é pressuposto de controle de área marítima; sem consciência situacional não há controle.",
            "O complexo naval previsto nas proximidades da foz do rio Amazonas amplia negação do uso do mar, controle de áreas marítimas e projeção de poder."],
        vuln=["🔴 Listar cinco tarefas básicas incluindo o monitoramento: o slide o apresenta como repertório a integrar, não como quinta tarefa.",
              "🟠 Confundir controle de área marítima (uso próprio assegurado) com negação do uso do mar (impedir o uso pelo adversário)."],
    ),
    dict(
        id="REL-T2-M02-C010", modulo="02-pnd-end-e-pesd",
        assunto="Setores estratégicos da defesa nacional e suas responsabilidades: nuclear (Marinha), cibernético (Exército) e espacial (Força Aérea)",
        dep=["REL-T2-M02-C007"], exam=True, rap=True, safar=True,
        fontes=["F02:slide \"SETORES ESTRATÉGICOS DA DEFESA NACIONAL\"", "F02:slide \"Responsabilidade pelos Setores Estratégicos\""],
        prio=["Três pares memorizáveis e facilmente embaralháveis em distrator."],
        prof=(R_ANC, P_APL, C_INT),
        just=("Três pares: custo baixo, retorno alto.",
              "Liga setor estratégico a programa concreto.",
              "Integra o setor nuclear ao PROSUB e o espacial ao monitoramento do mar a partir do espaço."),
        ex=["O setor nuclear sob a Marinha é o que sustenta o submarino de propulsão nuclear.",
            "O setor espacial sob a Força Aérea é o que viabiliza o monitoramento do mar a partir do espaço, previsto na END."],
        vuln=["🔴 Trocar cibernético (Exército) por espacial (Força Aérea).",
              "🟡 Supor que o setor nuclear sob a Marinha inclui armamento nuclear — o programa é de propulsão e ciclo do combustível."],
    ),
    dict(
        id="REL-T2-M02-C011", modulo="02-pnd-end-e-pesd",
        assunto="PESD 2020-2031: missão de preparar as Forças Armadas em permanente prontidão para a defesa da Pátria, garantia dos poderes constitucionais, garantia da lei e da ordem, atribuições subsidiárias e apoio à política externa; visão de futuro de ser efetivo participante do esforço nacional de defesa com Forças Armadas modernas, compatíveis, adequadamente preparadas e permanentemente prontas",
        dep=["REL-T2-M02-C002"], exam=True, rap=True, safar=True,
        fontes=["F02:slide \"Planejamento Estratégico Setorial de Defesa (PESD) 2020-2031 — Missão\"", "F02:slide \"PESD 2020-2031 — Visão de futuro\"",
                "A01:PESD elaborado pelo MD para transformar a END em ações e metas por Força"],
        prio=["A missão é o único texto do módulo que menciona expressamente o apoio à política externa."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Missão e visão em forma curta.",
              "O apoio à política externa é a ponte que o professor cobra por correlação.",
              "Integra a função do PESD de traduzir a END em metas por Força."),
        ex=["'Em apoio à política externa' no texto da missão é o que autoriza ler diplomacia naval como tarefa de defesa."],
        vuln=["🟠 Atribuir ao PESD a definição de objetivos: ele traduz a END em ações e metas.",
              "🟡 Trocar o horizonte 2020-2031 por 2040 (que é do PEM, da Marinha)."],
    ),
    dict(
        id="REL-T2-M02-C012", modulo="02-pnd-end-e-pesd",
        assunto="Mapa Estratégico Setorial e suas quatro perspectivas: Sociedade (contribuir para a dissuasão; aprimorar o preparo para a destinação constitucional; contribuir para o desenvolvimento nacional, o bem-estar e a responsabilidade sociais; incrementar o apoio à política externa); Processos Internos (governança e gestão estratégica; desenvolvimento científico, tecnológico e inovação; desenvolver os setores estratégicos); Aprendizado e Crescimento (efetividade dos sistemas de ensino; estudos de defesa; preservação do patrimônio histórico-cultural e culto aos valores, tradições e ética); Institucional (dimensão humana; compatibilizar orçamento com demandas; ampliar a interação com a sociedade)",
        dep=["REL-T2-M02-C011"], exam=True, rap=False, safar=True,
        fontes=["F02:slide \"MAPA ESTRATÉGICO SETORIAL\"", "F02:slides das quatro perspectivas",
                "F02:Estudo Dirigido (\"Correlacione diretamente o PESD e o ensino na Escola Naval\")"],
        prio=["Estudo Dirigido explícito: a correlação PESD × ensino na Escola Naval está na perspectiva Aprendizado e Crescimento."],
        prof=(None, P_T3, C_T3),
        just=("Fora do Rápido: quatro perspectivas com treze objetivos é volume demais para o tempo curto; o Rápido guarda só a perspectiva Sociedade, dentro do conceito C011.",
              "Necessário para responder a correlação anunciada pelo professor.",
              "Integra as quatro perspectivas como cadeia: aprendizado sustenta processos, que entregam resultado à sociedade."),
        ex=["A Escola Naval é instrumento direto de 'preservar a efetividade dos sistemas de ensino das Forças Armadas' e de 'estimular o desenvolvimento de Estudos de Defesa'.",
            "A formação do Aspirante é também 'incremento da preservação do patrimônio histórico-cultural e culto aos valores, às tradições e à ética'."],
        vuln=["🟠 Responder a correlação PESD × Escola Naval pela perspectiva Sociedade: o vínculo direto está em Aprendizado e Crescimento.",
              "🟡 Tratar as perspectivas como listas independentes, e não como cadeia de causa e efeito."],
    ),
    dict(
        id="REL-T2-M02-C013", modulo="02-pnd-end-e-pesd",
        assunto="Debate de Alsina Jr. ('Ensaios de Grande Estratégia Brasileira'): necessidade de uma Grande Estratégia; fragmentação da sociedade; defesa não é assunto apenas das Forças Armadas; quais as maiores ameaças à defesa do Brasil — e a tese de que as principais ameaças são internas (cultura excessivamente pacífica, cultura de defesa pouco consolidada, baixo investimento político e orçamentário, baixa prontidão militar, defesa subordinada à diplomacia)",
        dep=["REL-T2-M02-C001", "REL-T2-M01-C007"], exam=True, rap=False, safar=True,
        fontes=["F01:slide \"Pontos para Debate (segundo Alsina Jr.)\"", "A01:desenvolvimento da crítica de Alsina Jr. e a cronologia da Grande Estratégia Brasileira",
                "A01:conclusões de Milani e Nery"],
        prio=["É a única crítica ao próprio modelo brasileiro presente no corpus, e o professor a coloca como ponto para debate — formato de discursiva."],
        prof=(None, P_T3, C_T3),
        just=("Fora do Rápido: é ferramenta de argumentação, não âncora de memória.",
              "Fornece o contraponto obrigatório em qualquer resposta sobre defesa brasileira.",
              "Integra a crítica com a herança de Rio Branco, com o orçamento e com as recomendações de Milani e Nery."),
        ex=["O Brasil representa cerca de 50% da América do Sul em população, território, recursos militares e economia — e ainda assim não formulou uma Grande Estratégia.",
            "Alsina Jr.: a diplomacia brasileira é tão pacífica e conciliadora que enfraquece a autonomia das Forças Armadas.",
            "Milani e Nery: consenso das elites sobre desenvolvimento; relações civis-militares na estrutura do MD; integração entre Forças Armadas, universidades e setor privado para melhorar a BID; integração entre política externa e política de defesa."],
        vuln=["🔴 Ler a herança pacífica de Rio Branco apenas como ativo: para Alsina Jr. ela também é passivo estratégico.",
              "🟠 Atribuir a Alsina Jr. a tese de ameaça externa: as ameaças que ele destaca são internas."],
    ),
    dict(
        id="REL-T2-M02-C014", modulo="02-pnd-end-e-pesd",
        assunto="Cadeia objetivo → estratégia → capacidade → ação e sua leitura inversa: dado um programa ou uma ação concreta, remontar a capacidade que ele constrói, a diretriz da END que a orienta e o objetivo da PND que a justifica",
        dep=["REL-T2-M02-C006", "REL-T2-M02-C007", "REL-T2-M02-C009", "REL-T2-M02-C011"], exam=True, rap=True, safar=True,
        fontes=["F02:slide \"Estratégia Nacional de Defesa (END)\" (a END como vínculo entre posicionamento e ações)",
                "F02:Estudos Dirigidos por correlação", "AUT:perfil de integração alta"],
        prio=["Todos os Estudos Dirigidos do módulo pedem correlação entre níveis — este conceito É o método de responder a eles."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Quatro degraus na ordem certa.",
              "É a técnica que resolve qualquer 'correlacione X com Y'.",
              "Treina a leitura inversa, que é a forma difícil da cobrança."),
        ex=["PROSUB → capacidade de dissuasão e desenvolvimento tecnológico → diretriz de autonomia da END → objetivo de promover autonomia tecnológica e produtiva da PND.",
            "SisGAAz → gestão da informação e pronta-resposta → monitoramento do mar → objetivo de garantir soberania e integridade territorial."],
        vuln=["🔴 Parar na ação sem nomear a capacidade: 'o Brasil comprou submarinos' não é resposta.",
              "🟠 Saltar da ação ao objetivo sem passar pela capacidade — é onde se perde o ponto do nexo causal."],
    ),
]
