# -*- coding: utf-8 -*-
"""Matriz canônica — Módulos 05 e 06."""

from conceitos_m00_m02 import R_ANC, P_APL, C_INT, C_T3, P_T3

CONCEITOS = [
    # ────────────────────────── M05 — China ──────────────────────────────
    dict(
        id="REL-T2-M05-C001", modulo="05-china",
        assunto="Geografia chinesa como condicionante: a isoieta de 300 mm divide o país — cerca de 90% da população vive a leste dela, e a renda per capita é, em geral, maior desse lado; o coração econômico e financeiro está nas planícies do leste; e o país é cercado por zonas tampão naturais (platô tibetano, Himalaia, deserto de Gobi, Manchúria e Xinjiang), áridas ou de altíssima altitude",
        dep=["REL-T2-M00-C003"], exam=True, rap=True, safar=True,
        fontes=["F05:slides de mapas (isoieta, renda per capita por divisão administrativa, topografia)",
                "A01:leitura dos mapas (isoieta de 300 mm, 90% da população, zonas tampão)", "AUT:lacuna I-04"],
        prio=["Sem a geografia não se explica a dupla tensão nem o imperativo de integridade territorial."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Uma linha imaginária que explica a distribuição de gente e de renda.",
              "Base física de todo o raciocínio do módulo.",
              "Integra clima, relevo, população, renda e zonas tampão num só argumento."),
        ex=["A mesma linha que separa densidade populacional separa renda: geografia física convertida em desigualdade regional.",
            "As zonas tampão são naturais antes de serem políticas: aridez e altitude impedem avanço de exércitos."],
        vuln=["🟠 Tratar as zonas tampão chinesas como escolha política apenas: elas são primeiro um fato geográfico.",
              "🟡 Confundir isoieta (linha de igual precipitação) com isoterma ou com fronteira administrativa."],
    ),
    dict(
        id="REL-T2-M05-C002", modulo="05-china",
        assunto="Dupla tensão histórica litoral/interior: riqueza e cobiça externa no litoral, pobreza e ameaças terrestres no interior; o aumento da desigualdade em favor do litoral pressiona Beijing a redistribuir riqueza para o interior; a tensão política resultante faz as elites litorâneas provocarem centralização política por parte de Beijing, que lhes retira autonomia e fecha o regime; e a consequência é diminuição da abertura ao exterior, a autarcização",
        dep=["REL-T2-M05-C001"], exam=True, rap=True, safar=True,
        fontes=["F05:slide \"China - Dupla Tensão Histórica\"",
                "A01:mecanismo completo (comércio marítimo maior que o terrestre, cobiça menor que a ameaça terrestre, taxação das elites litorâneas, autarcização em Ming, Qing e Mao)",
                "C05:mecanismo prata/cobre (imposto em prata, transação em cobre, alta da prata e o interior contra o litoral)"],
        prio=["É o conceito estruturante do módulo: o professor o apresenta como CARACTERÍSTICA HISTÓRICA, não como episódio."],
        prof=(R_ANC, P_T3, C_T3),
        just=("O ciclo em quatro passos.",
              "É a lente que explica abertura e fechamento ao longo de séculos.",
              "Integra o mecanismo fiscal concreto: imposto em prata, transação em cobre, saída de prata e revolta do interior."),
        ex=["Autarcização em Ming (1368-1644), Qing (1644-1912) e no governo de Mao: o mesmo mecanismo em três épocas.",
            "Não dá para deixar fechado sempre (empobrece) nem aberto sempre (aumenta desigualdade e desagregação).",
            "O ópio mostrou o mecanismo em detalhe: camponeses transacionavam em cobre e pagavam imposto em prata; com a saída de prata, a prata subiu contra o cobre e o mesmo governo que não os protegia passou a tomar mais do seu dinheiro."],
        vuln=["🔴 Descrever a dupla tensão como conflito entre ricos e pobres: o mecanismo é político — desigualdade → pressão redistributiva → centralização → fechamento.",
              "🟠 Tratar a autarcização como opção ideológica: é resposta à ameaça de desagregação interna."],
    ),
    dict(
        id="REL-T2-M05-C003", modulo="05-china",
        assunto="Imperativo estratégico da China em três itens: manter a integridade territorial; evitar desigualdades significativas dentro do próprio território, para não fomentar desafios ao poder político centralizado; e manter abertura ao exterior para garantir prosperidade econômica, sem permitir a desagregação interna",
        dep=["REL-T2-M05-C002", "REL-T2-M00-C004"], exam=True, rap=True, safar=True,
        fontes=["F05:slide \"China - Imperativo Estratégico\"", "A01:CHINA – IMPERATIVO ESTRATÉGICO (três itens numerados)"],
        prio=["É o conceito central do módulo e a base de toda comparação com EUA e Rússia."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Três itens na ordem certa.",
              "Explica qualquer decisão chinesa, do Tibete ao Mar do Sul da China.",
              "Integra a tensão insolúvel entre abertura necessária e coesão necessária."),
        ex=["Os três itens formam um trilema: abertura gera prosperidade, prosperidade gera desigualdade, desigualdade ameaça a coesão, e a resposta à ameaça de coesão reduz a abertura.",
            "Xinjiang e Tibete são simultaneamente integridade territorial e zona tampão."],
        vuln=["🔴 Resumir o imperativo chinês a 'expandir': os três itens são de PRESERVAÇÃO — território, coesão e prosperidade.",
              "🟠 Tratar abertura ao exterior como fim em si: no slide ela é meio para a prosperidade, subordinada à coesão."],
    ),
    dict(
        id="REL-T2-M05-C004", modulo="05-china",
        assunto="Cronologia dinástica seletiva: Shang (1650-1050 a.C., primeira linha de governantes com registro escrito e evidência arqueológica, criou a primeira forma escrita do idioma), Zhou (1050-256 a.C., confucionismo e taoismo, conceito do Mandato do Céu), Qin (221-206 a.C., primeira unificação, governo burocrático centralizado, estradas, vias navegáveis, início da Grande Muralha, unificação de pesos, moedas e escrita), Han (206 a.C.-220 d.C., confucionismo como ideologia oficial, papel, bússola, Rota da Seda), Sui e Tang (618-907, apogeu, budismo, impressão em blocos de madeira e pólvora), Song (960-1279, bússola magnética para navegação de longa distância, primeiro papel-moeda oficial do mundo), Yuan (1279-1368, domínio mongol), Ming (1368-1644, restabelecimento do domínio chinês, Cidade Proibida) e Qing (1644-1911, manchus, última dinastia imperial, ocupação das zonas tampão)",
        dep=["REL-T2-M05-C003"], exam=True, rap=False, safar=True,
        fontes=["F05:slides das dinastias (Shang a Qing)",
                "A01:cronologia resumida com as conquistas territoriais por dinastia (Tang→Xinjiang, Yuan→Tibete, Qing→todas as zonas tampão)",
                "AUT:conflito CF-04 do manifesto"],
        prio=["A cronologia entra pelo que explica: unificação, ideologia de Estado, tecnologia de projeção e alcance territorial. A parte cerâmica dos slides foi cortada por não ter função avaliativa."],
        prof=(None, P_APL, C_INT),
        just=("Fora do Rápido: no tempo curto o aluno guarda Qin (unificação), Han (Rota da Seda) e Qing (última dinastia e zonas tampão), via C003 e C005.",
              "Necessária para datar o Mandato do Céu, a unificação e o alcance das zonas tampão.",
              "Integra cada dinastia à conquista territorial e à tecnologia que ela habilitou."),
        ex=["Tang foi a primeira a alcançar Xinjiang, por aliança com povos tártaros da Ásia Central; Yuan alcançou o Tibete; Qing ocupou todas as zonas tampão.",
            "Qin unificou pesos, moedas e escrita: padronização como tecnologia de integração territorial."],
        vuln=["🔴 Dizer que Zhou foi a primeira dinastia: a primeira com registro escrito e arqueológico é Shang, e foi Shang que criou a primeira forma escrita.",
              "🔴 Datar Qing até 1892: vai até 1911.",
              "🟠 Decorar a cronologia cerâmica: não tem função avaliativa e foi cortada do curso."],
    ),
    dict(
        id="REL-T2-M05-C005", modulo="05-china",
        assunto="Tianxia e o sistema sinocêntrico tributário: 'todos sob o céu' — conceito cultural que denotava o mundo geográfico ou o reino metafísico dos mortais e depois se associou à soberania política, com o centro distribuído à corte chinesa e irradiando concentricamente até os 'bárbaros' da franja; os quatro mecanismos (tornar o inimigo economicamente dependente com produtos sofisticados; doutrinação nos valores confucianos e na autoridade do Imperador, inclusive por casamento do herdeiro bárbaro com filha do Imperador; a igualdade que se torna vassalagem com o tempo; a noção de Império do Meio irradiando autoridade); e o sistema tributário (aceitação da subordinação, tributos periódicos ao detentor do Mandato Divino, adoção do calendário chinês, liberdade de comércio, reconhecimento de posição inferior com pouca violência empregada, e a obrigação do Imperador de manter a harmonia sob os Céus)",
        dep=["REL-T2-M05-C004"], exam=True, rap=True, safar=True,
        fontes=["F05:slides \"Tianxia\" (quatro slides)", "F05:slide \"Sistema sinocêntrico (tributário)\"",
                "F05:citação de Sun Tzu (\"levar tudo sob o céu intacto\")", "A01:TIANXIA e o exemplo do casamento dinástico"],
        prio=["É o contraponto conceitual direto ao Destino Manifesto e a base da expressão 'Mandato Divino' usada pelo professor."],
        prof=(R_ANC, P_T3, C_T3),
        just=("O que é e como funcionava, em quatro mecanismos.",
              "É a lente para ler a projeção chinesa contemporânea sem anacronismo.",
              "Integra Sun Tzu, dependência econômica e soft power como mecanismos de ordem hierárquica com pouca violência."),
        ex=["Sun Tzu: 'Seu objetivo deve ser levar tudo sob o céu intacto. Assim, suas tropas não estão desgastadas e seus ganhos serão completos.' — conquistar sem destruir o que se quer conquistar.",
            "O sistema tributário é hierárquico e de baixa violência: reconhece-se posição inferior, envia-se tributo, adota-se o calendário, e o comércio segue livre."],
        vuln=["🔴 Ler o sistema tributário como império territorial: era ordem hierárquica com baixa violência empregada.",
              "🟠 Traduzir Tianxia como 'império' — é 'todos sob o céu', e o Imperador tem o DEVER de manter a harmonia.",
              "🟡 Usar 'Mandato do Céu' e 'Mandato Divino' como conceitos distintos: no corpus são o mesmo."],
    ),
    dict(
        id="REL-T2-M05-C006", modulo="05-china",
        assunto="Século das Humilhações: I Guerra do Ópio e o Tratado de Nanquim, com Hong Kong entregue; II Guerra do Ópio (1856-1860), Tratado de Tianjin e Convenção de Pequim — abertura das portas chinesas aos estrangeiros, aceitação de diplomatas estrangeiros, permissão a missionários cristãos e legalização do ópio; locais com extraterritorialidade; e as revoltas fracassadas (Taiping e Boxers)",
        dep=["REL-T2-M05-C005", "REL-T2-M05-C002"], exam=True, rap=True, safar=True,
        fontes=["F05:slide \"China - Século das Humilhações\"", "A01:extraterritorialidade em Xangai; Boxers contra Reino Unido, França e Alemanha",
                "C05:mecanismo do desequilíbrio comercial (chá, prata, ópio), casus belli de 1839 e a memória nacional herdada pelo PCC"],
        prio=["É a memória estratégica que o professor usa para explicar a legitimidade do PCC e a leitura chinesa da pressão externa."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Duas guerras, três tratados, uma consequência.",
              "É o que explica por que a China lê exigência externa como humilhação.",
              "Integra o mecanismo comercial completo e a herança de legitimidade do PCC."),
        ex=["Mecanismo: obsessão britânica pelo chá → déficit pago em prata → ópio do norte da Índia como forma de recuperar a prata → tentativa chinesa de coibir → confisco de 20 mil caixas em 1839 → casus belli.",
            "O PCC herdou a memória nacional da I Guerra do Ópio; 'rejuvenescimento nacional' de Xi Jinping fala a esse sentimento e dá ao partido mais legitimidade que o marxismo."],
        vuln=["🔴 Reduzir as Guerras do Ópio a uma questão de droga: o mecanismo é de balança comercial e de pagamentos.",
              "🟠 Achar que o Tratado de Nanquim beneficiou só a Grã-Bretanha: França, Alemanha, EUA e Rússia exigiram tratamento semelhante, e Rússia e Japão conquistaram território."],
    ),
    dict(
        id="REL-T2-M05-C007", modulo="05-china",
        assunto="República, guerra civil e maoísmo: fim do império, warlords, Kuomintang × PCC, invasão japonesa e II Guerra, vitória do PCC em 1949; apoio inicial da URSS, coletivização, conquista de Xinjiang e Tibete (restabelecimento das zonas tampão), Grande Salto para a Frente (1958-1962) e seu fracasso, Grande Cisma (1960), Guerra China-Índia (1962, Arunachal Pradesh), estímulo a revoluções socialistas e Revolução Cultural (1966-1976) para abolir influências capitalistas, além da trégua com os EUA para antagonizar a URSS",
        dep=["REL-T2-M05-C006"], exam=True, rap=True, safar=True,
        fontes=["F05:slides \"China - Guerra Civil\", \"China - Maoísmo\" (dois slides), mapa dos senhores da guerra (1925)",
                "A01:mecanismo do Grande Salto (realocação de agricultores para siderurgia, manutenção da exportação agrícola, fome), razões do Grande Cisma (debate sobre difusão do comunismo), visita de Nixon em 1972 precedida por Kissinger em 1971, reconhecimento formal em 1979, entrada da RPC no CSNU em 1971"],
        prio=["Contém o caso mais rico de pragmatismo realista do corpus: dois Estados comunistas se dividem e a terceira potência explora a fenda."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Marcos e o motivo de cada um.",
              "É a sequência que explica a aproximação com os EUA e o assento no CSNU.",
              "Integra o mecanismo da fome, a lógica do cisma e a barganha triangular."),
        ex=["Grande Salto: realocar agricultores para a produção de aço reduziu a produção agrícola, mas a exportação agrícola foi mantida — resultado, fome com dezenas de milhões de mortos.",
            "A RPC entrou no CSNU em 1971 no contexto da aproximação com os EUA e do isolamento diplomático da República da China.",
            "A China reconhece o atrito de 1962 com a Índia não como guerra, mas como 'expedição punitiva'."],
        vuln=["🔴 Ler o Grande Cisma como divergência pessoal: era debate sobre difundir o comunismo (posição chinesa) ou consolidá-lo no próprio país (posição soviética), somado às concessões da URSS ao Ocidente.",
              "🟠 Datar a trégua com os EUA em 1949-1950: ela vem depois do cisma, com Kissinger em 1971 e Nixon em 1972.",
              "🟡 Confundir reconhecimento formal (1979) com reatamento de relações (1972)."],
    ),
    dict(
        id="REL-T2-M05-C008", modulo="05-china",
        assunto="Deng Xiaoping e a abertura controlada: pragmatismo econômico com recapitalização progressiva, acertos prévios com a diáspora chinesa, flexibilização agrícola e zonas econômicas especiais (ZEE); resultados — crescimento econômico sustentado, diminuição das tensões externas, fortalecimento do PCC (exemplo do Massacre da Praça da Paz Celestial, 1989) e resolução dos litígios territoriais, com exceção de Índia e Japão",
        dep=["REL-T2-M05-C007", "REL-T2-M05-C003"], exam=True, rap=True, safar=True,
        fontes=["F05:slides \"China Deng Xiao Ping\", \"China - ZEE\", \"Resultados\"",
                "A01:zonas econômicas especiais com incentivos fiscais atraindo capital estrangeiro; alerta para não confundir com zona econômica exclusiva; inflação e descontentamento antes de 1989"],
        prio=["É a demonstração viva do imperativo: abrir para prosperar sem perder a coesão. E contém a homonímia ZEE, que é pegadinha perfeita."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Quatro medidas e quatro resultados.",
              "Mostra o imperativo chinês funcionando na prática.",
              "Integra abertura, fortalecimento do partido e o custo político de 1989."),
        ex=["As ZEE chinesas são áreas com características capitalistas e incentivos fiscais para indústrias e empresas, atraindo capital estrangeiro.",
            "O fortalecimento do PCC aparece no slide como RESULTADO da abertura, não como obstáculo a ela."],
        vuln=["🔴 Confundir ZEE (zona econômica especial, chinesa, de política industrial) com ZEE (zona econômica exclusiva, da CNUDM, de direito do mar). O resumo do professor alerta expressamente para isso.",
              "🟠 Tratar 1989 como interrupção da abertura: o slide o apresenta dentro do resultado 'fortalecimento do PCC'.",
              "🟡 Dizer que todos os litígios foram resolvidos: Índia e Japão são exceção expressa."],
    ),
    dict(
        id="REL-T2-M05-C009", modulo="05-china",
        assunto="China pós-Deng e China recente: reafirmação do papel chinês no mundo, revisionismo 'soft', entrada na OMC, participação crescente nas missões de paz da ONU e aumento de influência na Ásia, África, Europa e América Latina; reestruturação econômica e vigor tecnológico, impacto dos custos trabalhistas, questão demográfica, Taiwan e litígios (Aksai Chin, Arunachal Pradesh, platô de Doklam, ilhas Diaoyu/Senkaku, Mar do Sul da China), assertividade militar e centralização política do PCC com destaque de Xi Jinping, no poder desde 2012 e o mais importante desde Mao",
        dep=["REL-T2-M05-C008"], exam=True, rap=True, safar=True,
        fontes=["F05:slides \"China Pós-Deng\" e \"China recente\"", "F05:mapas dos litígios (fronteira leste com a Índia, Doklam, Diaoyu/Senkaku, nine-dash line)",
                "A01:modelo de plataformas de exportação, deslocamento de empresas para Vietnã, Camboja e Laos, política do filho único de 1979 a 2015 e liberação de até três filhos em 2021",
                "AUT:conflito CF-04 (Doklam é com o Butão)"],
        prio=["Concentra os litígios nominais e os três vetores contemporâneos: tecnologia, demografia e assertividade."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Litígios nominais e três vetores.",
              "Permite situar qualquer notícia recente no quadro do imperativo.",
              "Integra o modelo de plataformas de exportação, o ciclo de custos trabalhistas e a armadilha demográfica."),
        ex=["Modelo de plataformas de exportação: China, Japão e os tigres asiáticos cresceram exportando; o que muda no tempo é o nível tecnológico, a complexidade produtiva e o grau de intervenção estatal.",
            "Com o progresso técnico os salários subiram, encareceram o custo trabalhista e empresas migraram para Vietnã, Camboja e Laos.",
            "Política do filho único de 1979 a 2015, abolida em 2015 e, em 2021, permissão de até três filhos por casal — a consequência é população economicamente ativa menor e custos previdenciários maiores."],
        vuln=["🔴 Situar o platô de Doklam como litígio com Bangladesh: é com o BUTÃO (o mapa do deck rotula Bhutan). O resumo do Aspirante erra esse ponto.",
              "🟠 Tratar o revisionismo chinês como ruptura declarada: o slide o qualifica como 'soft'.",
              "🟡 Confundir Aksai Chin (setor ocidental) com Arunachal Pradesh (setor oriental)."],
    ),
    dict(
        id="REL-T2-M05-C010", modulo="05-china",
        assunto="Taiwan: província considerada rebelde, para onde o Kuomintang de Chiang Kai-shek fugiu em 1949; a Resolução 2758 da Assembleia Geral da ONU (25/10/1971) e a disputa interpretativa sobre ela — para Pequim resolveu em definitivo a representação de toda a China e confirmou o princípio de Uma Só China; para os EUA e Taiwan tratou apenas da representação na ONU, sem determinar soberania territorial; distinção entre o PRINCÍPIO de Uma Só China (RPC) e a POLÍTICA de Uma Só China (EUA, com Taiwan Relations Act, Três Comunicados e Seis Garantias); ambiguidade estratégica; participação seletiva na OMC (2002) e na APEC como Chinese Taipei; escudo de silício dos semicondutores; e 12 parceiros diplomáticos formais em 2026",
        dep=["REL-T2-M05-C009", "REL-T2-M05-C003"], exam=True, rap=True, safar=True,
        fontes=["F05:slide \"China recente\" (Questão Taiwan)", "F05:mapa do Estreito de Taiwan com distâncias",
                "C08:integral", "A01:Taiwan como província rebelde desde 1949; RPC no CSNU em 1971 e isolamento da ROC"],
        prio=["É o litígio que liga integridade territorial (imperativo 1), Primeira Cadeia de Ilhas e rivalidade com os EUA — e tem uma distinção conceitual que produz pegadinha perfeita."],
        prof=(R_ANC, P_T3, C_T3),
        just=("A distinção princípio × política, em uma linha cada.",
              "Permite responder qualquer questão sobre o estreito sem simplificar.",
              "Integra reconhecimento, representação multilateral, ambiguidade estratégica e cadeia de semicondutores."),
        ex=["A Resolução 2758 'restaurou' os direitos da RPC e retirou os delegados de Chiang Kai-shek; suas consequências jurídicas permanecem disputadas — não se deve resumi-la a um ato que 'declarou Taiwan parte da China'.",
            "Ambiguidade estratégica: os EUA apoiam a capacidade de autodefesa taiwanesa sem definir de antemão como responderiam a um conflito militar.",
            "Escudo de silício: a liderança global em semicondutores (TSMC) é simultaneamente vulnerabilidade e proteção."],
        vuln=["🔴 Confundir o PRINCÍPIO de Uma Só China (RPC: Taiwan é parte inalienável e a RPC é o único governo legítimo) com a POLÍTICA de Uma Só China (EUA: reconhecem a RPC, não apoiam a independência, mantêm laços não oficiais).",
              "🔴 Afirmar que a Resolução 2758 decidiu a soberania territorial: ela tratou de representação, e a leitura é disputada.",
              "🟠 Dizer que Taiwan está isolada: ela participa da OMC e da APEC como Chinese Taipei."],
    ),
    dict(
        id="REL-T2-M05-C011", modulo="05-china",
        assunto="Mar do Sul da China e a nine-dash line: reivindicações sobrepostas de Filipinas, Vietnã, Malásia, Brunei e Indonésia sob a CNUDM contra a linha de nove traços reivindicada por China e Taiwan; Ilhas Paracel, Ilhas Spratly, Scarborough Shoal e a província de Hainan",
        dep=["REL-T2-M05-C009"], exam=True, rap=True, safar=True,
        fontes=["F05:mapa \"Mar do Sul da China\" (reivindicações de ZEE e nine-dash line)", "F05:slide \"Mar do Sul da China - A2/AD\"",
                "A01:militarização de ilhas artificiais (Spratly) e presença naval chinesa"],
        prio=["É o espaço onde o imperativo chinês colide diretamente com a CNUDM e com os aliados dos EUA."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Nomes dos arquipélagos e a natureza da disputa.",
              "É o cenário mais provável de qualquer questão aplicada sobre a China.",
              "Integra direito do mar, ilha artificial e negação de área."),
        ex=["A tensão é entre um título histórico (linha de nove traços) e um título convencional (ZEE medida das linhas de base, sob a CNUDM).",
            "Ilha artificial não gera os mesmos direitos que ilha — ponto que a própria P1 cobrou em caso com distâncias."],
        vuln=["🔴 Supor que ilha artificial gera mar territorial e ZEE.",
              "🟠 Atribuir a nine-dash line só à RPC: o mapa do deck a registra como reivindicação de China e Taiwan."],
    ),
    dict(
        id="REL-T2-M05-C012", modulo="05-china",
        assunto="A2/AD chinês por cadeias de ilhas: antiacesso (A2) é impedir a entrada do inimigo em determinada região estratégica, com mísseis balísticos de longo alcance e submarinos em locais estratégicos; negação de área (AD) é dificultar as ações do inimigo já dentro da região, com mísseis antinavio e interferência eletrônica; a China aplica A2 na região da Primeira Cadeia de Ilhas — das ilhas ao sul do Japão em Okinawa, passando por Taiwan e Filipinas, até o Estreito de Málaca — e AD de forma mais restrita às áreas de seu mar territorial (Spratly, Paracel, Hainan), com as mesmas ilhas servindo aos dois propósitos",
        dep=["REL-T2-M05-C011", "REL-T2-M04-C010"], exam=True, rap=True, safar=True,
        fontes=["F05:slide \"Mar do Sul da China - A2/AD\"", "F04:slide \"A2/AD - Anti-access/Area Denial\"",
                "A01:definição operacional de A2 e AD, alcance da Primeira Cadeia, ações que indicam A2 (mísseis e bases em Hainan, militarização de Spratly, presença naval)"],
        prio=["É o conceito militar mais técnico do curso e o único com distinção interna (A2 × AD) que o resumo detalha com meios distintos."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Duas siglas, dois alcances, dois conjuntos de meios.",
              "É a lente que explica a estrutura de força chinesa e a resposta americana.",
              "Integra geografia (cadeias de ilhas), meios (mísseis, submarinos, guerra eletrônica) e a doutrina de dispersão da frota americana."),
        ex=["A2 = manter o adversário FORA, com alcance longo. AD = dificultar a ação de quem já ENTROU, com alcance curto.",
            "Primeira Cadeia de Ilhas: Okinawa e ilhas ao sul do Japão, Taiwan, Filipinas e o Estreito de Málaca.",
            "Segunda Cadeia: Austrália, Guam e ilhas da Oceania. Terceira: Havaí."],
        vuln=["🔴 Trocar A2 por AD: o antiacesso é impedir a entrada; a negação de área é dificultar a ação de quem entrou.",
              "🟠 Supor que A2 e AD usam ilhas diferentes: o corpus registra que as mesmas ilhas servem aos dois.",
              "🟡 Colocar Taiwan na Segunda Cadeia."],
    ),
    dict(
        id="REL-T2-M05-C013", modulo="05-china",
        assunto="Dilema do Estreito de Málaca e a perspectiva chinesa de estar 'engaiolada': a China se vê cercada pela presença de bases americanas em países aliados (Japão, Coreia do Sul, Filipinas, Taiwan) e por meios navais e aéreos americanos; por isso busca alternativas terrestres de acesso ao mar (com apoio de Mianmar e Bangladesh) e investe na possibilidade do Canal de Kra, na Tailândia, temendo um bloqueio do Estreito de Málaca, por onde passa a maior parte de suas exportações e importações, inclusive insumos energéticos e alimentares",
        dep=["REL-T2-M05-C012", "REL-T2-M00-C013"], exam=True, rap=True, safar=True,
        fontes=["F05:slide \"Perspectiva Chinesa\" e mapa do Estreito de Málaca",
                "A01:PERSPECTIVA CHINESA (engaiolada, corredores terrestres, Canal de Kra)",
                "P05:questão 17 (Canal de Kra, precedentes de Suez e Panamá, interesses da Índia)",
                "C05:a China já não é autossuficiente — importa alimento e petróleo"],
        prio=["Foi cobrado em discursiva de 2,1 pontos na P2, com três subitens. É a vulnerabilidade estrutural mais explorada pelo professor."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Um estreito, uma vulnerabilidade, duas alternativas.",
              "É o melhor caso de chokepoint aplicado do curso.",
              "Integra Mahan, soberania de terceiros, interesses indianos e a perda de autossuficiência chinesa."),
        ex=["Resposta-padrão da P2: a iniciativa do canal busca contornar eventuais bloqueios do Estreito de Málaca por marinhas de outras nações, e aumentaria a influência chinesa no Golfo da Tailândia e na Baía de Bengala.",
            "Precedentes de Suez e Panamá: o funcionamento dos canais se deu com presença física de representantes das potências construtoras, inclusive em atividades de segurança — daí a questão sobre a soberania tailandesa.",
            "Não atenderia à Índia: aumentaria a influência chinesa em áreas onde a Índia projeta poder, como a Baía de Bengala e o Sudeste Asiático."],
        vuln=["🔴 Tratar o dilema de Málaca como problema comercial: é de segurança energética e alimentar.",
              "🟠 Esquecer que a China importa alimento e petróleo — historicamente autossuficiente, hoje não é.",
              "🟡 Responder o caso do canal sem considerar o efeito sobre a soberania do país anfitrião."],
    ),
    dict(
        id="REL-T2-M05-C014", modulo="05-china",
        assunto="Belt and Road (Um Cinturão, Uma Rota): Cinturão Econômico da Rota da Seda por terra e Rota da Seda Marítima do Século XXI, ligando o extremo do Leste Asiático à África Oriental e à Europa Central por rodovias, ferrovias, rotas oceânicas e portos; financiada majoritariamente com capital chinês (AIIB, China Development Bank, Bank of China, outros bancos estatais, Silk Road Fund); projeção de influência econômica e política, com países endividados junto a bancos chineses, mesmo a juros baixos, em relação de dependência; e a crítica indiana ao corredor China-Paquistão que atravessa a Caxemira ocupada",
        dep=["REL-T2-M05-C013"], exam=True, rap=True, safar=True,
        fontes=["F05:slide \"Investimentos no Exterior e One Belt, One Road\" e infográfico",
                "F05:link atualizado sobre o envolvimento da China na BRI em 2026",
                "A01:BRI como corredor econômico transcontinental por terra e mar, e a relação de dependência gerada"],
        prio=["É o instrumento econômico central da projeção chinesa e o que o Brasil e a América Latina encontram na prática."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Dois ramos, um financiador, um efeito.",
              "É o instrumento a nomear em qualquer resposta sobre projeção chinesa.",
              "Integra infraestrutura, endividamento, influência e a reação indiana e americana."),
        ex=["Dois ramos: cinturão terrestre (Xian–Ásia Central–Europa) e rota marítima (Fuzhou–Málaca–Índico–Mar Vermelho–Mediterrâneo).",
            "A Índia chamou o projeto de 'empresa colonial, deixando dívida e comunidades destruídas em seu rastro' e boicotou a cúpula.",
            "O Panamá aderiu em 2017 e saiu em 2025 sob pressão americana — a BRI é onde a competição EUA-China toca o hemisfério."],
        vuln=["🔴 Tratar a BRI como projeto só de infraestrutura: o efeito é de dependência e influência política.",
              "🟠 Esquecer o ramo marítimo: 'Um Cinturão' é terrestre, 'Uma Rota' é marítima."],
    ),
    dict(
        id="REL-T2-M05-C015", modulo="05-china",
        assunto="Modernização naval chinesa como evidência de estratégia: entre 2005 e 2020 o Congresso dos EUA registrou 49 novas corvetas, 35 naves de patrulha costeira com mísseis, 2 porta-aviões, 11 destróieres, 6 fragatas, 1 cruzador e 17 embarcações para ataque anfíbio; e a marinha chinesa passou a ter mais navios que a americana (332 contra 291, incluindo submarinos, segundo dado de 2020) — sem que isso signifique superioridade de tonelagem, alcance ou experiência",
        dep=["REL-T2-M05-C012", "REL-T2-M04-C011"], exam=True, rap=False, safar=True,
        fontes=["F05:slides \"Marinha Chinesa\" e \"A marinha chinesa possui agora mais navios que os EUA\"",
                "F05:citação do relatório do Departamento de Defesa dos EUA, 2024"],
        prio=["É o dado que mais produz conclusão apressada: mais navios não é mais poder naval."],
        prof=(None, P_T3, C_T3),
        just=("Fora do Rápido: no tempo curto vale o conceito (A2/AD), não a contagem.",
              "Necessário para recusar a conclusão apressada de superioridade naval.",
              "Integra contagem de cascos, composição de frota, alcance e rede de bases."),
        ex=["A composição revela a doutrina: corvetas e patrulhas com mísseis servem a A2/AD regional, não a projeção global.",
            "Comparar 332 contra 291 sem considerar tonelagem, porta-aviões, bases no exterior e experiência operacional é comparar números, não poder."],
        vuln=["🔴 Concluir superioridade naval chinesa a partir da contagem de cascos.",
              "🟠 Ignorar que a supremacia americana é potencializada por 9 marinhas aliadas entre as 12 seguintes."],
    ),
    dict(
        id="REL-T2-M05-C016", modulo="05-china",
        assunto="Rivalidade e interdependência EUA-China: a competição contemporânea reencena a lógica das Guerras do Ópio — uma potência ocidental insatisfeita quer redefinir os termos da relação econômica e a China está entre ser fraca demais para resistir e consciente demais do passado para ceder; a China não quer mais jogar pelas regras, quer participar de fazê-las; e a novidade histórica é que nunca houve, ao mesmo tempo, uma China poderosa e uns Estados Unidos poderosos",
        dep=["REL-T2-M05-C006", "REL-T2-M05-C014", "REL-T2-M04-C012"], exam=True, rap=True, safar=True,
        fontes=["C05:seções \"A New Chapter\" e \"Where History Diverges\"", "C06:seção final (competição incomparável; nunca houve China e EUA poderosos ao mesmo tempo)",
                "A01:guerra tarifária e bipolaridade EUA-China", "F04:slide \"Cenários — Forças-motrizes\""],
        prio=["É o conceito que fecha os módulos 04 e 05 e o mais provável em questão de integração entre módulos."],
        prof=(R_ANC, P_T3, C_T3),
        just=("A analogia e o seu limite.",
              "É a moldura de qualquer resposta sobre a competição sistêmica.",
              "Integra interdependência, memória histórica, legitimidade interna e limites da analogia."),
        ex=["Limite da analogia: a dinastia Qing era usurpadora estrangeira e perdia o controle; o PCC é han, jovem em termos dinásticos e não demonstra perder o controle.",
            "Interdependência é arma de dois gumes: fechar-se pode gerar revolução interna, integrar-se nos termos alheios pode gerar desilusão com um governo repressivo e incapaz de defender interesses.",
            "Aceitar as exigências de Washington seria visto na China como versão moderna dos tratados desiguais."],
        vuln=["🔴 Levar a analogia do ópio longe demais: há três diferenças estruturais registradas na fonte.",
              "🟠 Tratar a interdependência como garantia de paz — ela é também instrumento de coerção mútua."],
    ),

    # ────────────────────────── M06 — Rússia ─────────────────────────────
    dict(
        id="REL-T2-M06-C001", modulo="06-russia",
        assunto="Origens da sociedade russa: auge do Rus de Kiev no século XI, região multiétnica (eslavos, noruegueses, finlandeses, entre outros) que é origem também de Ucrânia e Bielorrússia; invasão e domínio mongol no século XIII (Horda de Ouro), com disputas sucessivas envolvendo o Reino da Polônia, o Império Russo e o Império Otomano",
        dep=["REL-T2-M00-C003"], exam=True, rap=True, safar=True,
        fontes=["F06:slide \"Rússia - Origens - Auge do Rus de Kiev\"",
                "A01:seção RÚSSIA (origem multiétnica e a pergunta sobre a justificativa da invasão)"],
        prio=["É a base do argumento histórico usado para justificar a invasão da Ucrânia — e o corpus traz a refutação explícita."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Data, região e caráter multiétnico.",
              "Permite avaliar criticamente a justificativa histórica da invasão.",
              "Integra origem compartilhada, prescrição histórica e Direito Internacional."),
        ex=["A refutação registrada no corpus: outras sociedades também têm origem naquela região, passaram-se mais de mil anos e a invasão desrespeitaria regras do Direito Internacional.",
            "Rus de Kiev é origem comum de Rússia, Ucrânia e Bielorrússia — o que enfraquece, e não fortalece, a reivindicação exclusiva."],
        vuln=["🔴 Aceitar a origem comum como título jurídico sobre território alheio.",
              "🟠 Tratar o Rus de Kiev como Estado russo: era multiétnico e anterior à formação russa."],
    ),
    dict(
        id="REL-T2-M06-C002", modulo="06-russia",
        assunto="Formação territorial em quatro etapas: Grão-Ducado de Moscou (1390-1530), com Moscou como centro político e religioso por efeito das invasões mongóis e da Horda de Ouro sobre Kiev; Czarismo russo (1547-1721), com expansão para a Sibéria e o Alasca; Império Russo (1721-1917) sob Pedro o Grande, alcançando sua maior extensão (Mar Cáspio, Mar Negro, ocupação total da Sibéria, parte da China) e caindo com a Revolução Russa",
        dep=["REL-T2-M06-C001"], exam=True, rap=True, safar=True,
        fontes=["F06:slides \"Grão-Ducado de Moscou\", \"Expansão do Czarismo Russo\", \"Império Russo\"",
                "A01:deslocamento do centro para o norte por efeito das invasões; título de Czar derivado de César; Pedro o Grande"],
        prio=["Cada etapa explica um interesse permanente: profundidade continental, saída para mares e centro protegido."],
        prof=(R_ANC, P_APL, C_INT),
        just=("Quatro períodos com datas.",
              "Explica a formação do centro Europa-Urais e a busca de mares.",
              "Integra a etapa histórica ao interesse permanente que ela cria."),
        ex=["O deslocamento do centro para Moscou é consequência da ocupação mongol de Kiev: o centro migra para onde é defensável.",
            "A expansão do czarismo para a Sibéria e o Alasca cria profundidade continental — e o Alasca acaba vendido aos EUA em 1867."],
        vuln=["🟠 Narrar as quatro etapas sem extrair o interesse que cada uma cria.",
              "🟡 Atribuir a maior extensão ao czarismo: é ao Império Russo, sob Pedro o Grande."],
    ),
    dict(
        id="REL-T2-M06-C003", modulo="06-russia",
        assunto="Imperativos estratégicos da Rússia: manter o seu centro Europa-Urais e protegê-lo com áreas tampão (Cáucaso, Mongólia, Bielorrússia, Finlândia, Países Bálticos, Polônia, Hungria); garantir o Cazaquistão em sua área de influência; e tentar o acesso aos mares — Pacífico (mas longe do seu centro), Mar Negro (controle turco) e Mar Báltico (refém de vários países)",
        dep=["REL-T2-M06-C002", "REL-T2-M00-C004"], exam=True, rap=True, safar=True,
        fontes=["F06:slide \"Imperativos Estratégicos\"", "A01:zonas tampão essenciais para proteger o centro Europa-Urais, onde ficam São Petersburgo e Moscou; governantes pró-Rússia"],
        prio=["É o conceito central do módulo e a chave da comparação com EUA e China."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Três imperativos e a lista de tampões.",
              "Explica cada ação russa do século XXI.",
              "Integra centro, tampão e acesso ao mar como um só problema geográfico."),
        ex=["O centro Europa-Urais concentra as principais cidades: São Petersburgo e Moscou.",
            "Cada um dos três acessos ao mar tem um defeito estrutural: o Pacífico é longe do centro, o Mar Negro depende da Turquia e o Báltico é cercado por países da OTAN.",
            "Interessa que os países tampão sejam governados por lideranças pró-Rússia, que mantenham boas relações."],
        vuln=["🔴 Listar o acesso aos mares como conquistado: o slide diz 'TENTAR o acesso'.",
              "🟠 Esquecer o Cazaquistão, que tem item próprio no slide.",
              "🟡 Confundir área tampão (protege o centro) com área de influência (garante alinhamento)."],
    ),
    dict(
        id="REL-T2-M06-C004", modulo="06-russia",
        assunto="Planície europeia e o problema da invasão terrestre: existe uma grande planície que se estende da Alemanha, passa pela Polônia e chega à Rússia, e esse tipo de relevo facilita a invasão de tropas terrestres — o que torna a profundidade territorial e as zonas tampão substitutos de fronteira defensável",
        dep=["REL-T2-M06-C003"], exam=True, rap=True, safar=True,
        fontes=["A01:Problema da Rússia 1 (a grande planície)", "F06:mapas de formação territorial e de pressão sobre a Europa",
                "F06:slide \"'Paranoia geopolítica'?\""],
        prio=["É o mecanismo causal que transforma geografia em comportamento — o coração analítico do módulo."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Uma planície, uma consequência.",
              "É o nexo que sustenta qualquer resposta sobre comportamento russo.",
              "Integra relevo, profundidade, memória de invasões e custo econômico de manter tampões."),
        ex=["Sem acidente geográfico que barre o avanço, a única defesa é distância — e distância se compra com território tampão.",
            "É por isso que a perda dos Estados tampão em 1991 é lida em Moscou como perda de defesa, não apenas de prestígio."],
        vuln=["🟠 Tratar a planície como curiosidade geográfica: ela é a premissa do raciocínio defensivo russo.",
              "🟡 Supor que profundidade territorial substitui capacidade militar — ela apenas compra tempo."],
    ),
    dict(
        id="REL-T2-M06-C005", modulo="06-russia",
        assunto="Os quatro problemas geográficos da Rússia: a planície europeia; a Ucrânia (se entra na UE ou na OTAN, fortalece a presença europeia, aproxima tropas e bases e acirra a disputa pelo Mar Negro); o Cáucaso (ligação do Oriente Médio com a Rússia, uma das regiões mais instáveis do planeta, com regiões separatistas e litígios, onde interessa manter presença, e mesmo avançar, para fazer frente à Turquia, país da OTAN com base americana e também disputante do Mar Negro); e a Ásia Central com os países tampão (os '-stões' e a Mongólia, tampão entre o sul da Rússia e China e Índia, com os quais interessa manter relação estável para que não se aliem a potências rivais nem entrem na OTAN)",
        dep=["REL-T2-M06-C004"], exam=True, rap=True, safar=True,
        fontes=["A01:Problemas da Rússia 1 a 4", "F06:slide \"Desafios para a Rússia\" (dois slides)",
                "F06:mapa \"Presión rusa sobre Europa\" (zona de influência, limite de segurança para Moscou, corredor de Kaliningrado)"],
        prio=["Organiza o módulo por PROBLEMA, e não por cronologia — é exatamente o formato que o trabalho de T2 pede (objetivos/desafios)."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Quatro problemas nomeados.",
              "É o esqueleto da resposta sobre objetivos e desafios russos.",
              "Integra cada problema ao instrumento usado e ao custo pago."),
        ex=["Ucrânia na OTAN dificulta a presença geoestratégica russa na Europa; Geórgia na OTAN dificulta a presença russa no Cáucaso.",
            "A Turquia é o nó do Cáucaso e do Mar Negro: membro da OTAN, com base americana, potência regional e detentora dos estreitos."],
        vuln=["🟠 Tratar os quatro problemas como lista: eles se encadeiam pelo mesmo mecanismo (centro exposto → necessidade de tampão → atrito com quem quer sair da esfera).",
              "🟡 Situar o Cazaquistão fora da Ásia Central ou esquecer a Mongólia."],
    ),
    dict(
        id="REL-T2-M06-C006", modulo="06-russia",
        assunto="Acesso aos mares e a condição de quase sem litoral: o Pacífico russo ao norte fica congelado boa parte do tempo (Mares da Sibéria e de Okhotsk); pelo Mar Negro é inevitável acessar os estreitos de Bósforo e Dardanelos, sob controle turco; no Báltico há países da OTAN e um estreito sob controle da Dinamarca, também da OTAN, e uma guerra poderia levar ao bloqueio desse estreito; o mesmo problema atinge Kaliningrado, enclave russo entre Polônia e Lituânia; e por isso é útil pensar a Rússia como um país sem litoral, que precisa de estratégia naval justamente para compensar o que lhe falta em acesso marítimo",
        dep=["REL-T2-M06-C005", "REL-T2-M00-C013"], exam=True, rap=True, safar=True,
        fontes=["A01:acesso aos mares e o caso de Kaliningrado", "F06:slide \"Imperativos Estratégicos\"",
                "F06:mapa \"Presión rusa sobre Europa\" (corredor de Kaliningrado, principais portos russos)",
                "C10:\"it's helpful to think of Russia as a landlocked country\""],
        prio=["É a formulação didática mais potente do módulo e o que liga Rússia à oceanopolítica do curso."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Três mares, três defeitos.",
              "É o que explica a doutrina marítima e o valor do Ártico.",
              "Integra gelo, estreitos de terceiros, enclave e perda de infraestrutura portuária em 1991."),
        ex=["A Rússia perdeu muita infraestrutura portuária, e com ela acesso a rotas de comércio, quando perdeu os Estados satélites soviéticos.",
            "Kaliningrado repete o problema em miniatura: banhado pelo Báltico, sua saída para o mar aberto passa pelo mesmo estreito dinamarquês."],
        vuln=["🔴 Concluir que uma fronteira marítima longa significa acesso ao oceano: a Rússia tem litoral extenso e não tem acesso direto aos oceanos abertos.",
              "🟠 Esquecer que Bósforo e Dardanelos estão sob controle de um país da OTAN."],
    ),
    dict(
        id="REL-T2-M06-C007", modulo="06-russia",
        assunto="'Paranoia geopolítica' como problema analítico: às vezes acertada (rivalidade com a Aliança Polaco-Lituana no século XVI, invasão por Napoleão, invasão por Hitler), às vezes não (anexação das repúblicas bálticas em 1939, invasão da Polônia em 1939, incorporação de fato da Europa Oriental depois da II Guerra); no século XXI, invasão da Geórgia (2008), anexação da Crimeia (2014) e invasão da Ucrânia (2022)",
        dep=["REL-T2-M06-C004"], exam=True, rap=True, safar=True,
        fontes=["F06:slide \"'Paranoia geopolítica'?\"", "A01:PARANOIA GEOPOLÍTICA (invasões sofridas e entorno mantido seguro pela própria Rússia)"],
        prio=["O próprio professor põe o termo entre aspas e com interrogação: é convite explícito a tratá-lo como problema, não como diagnóstico."],
        prof=(R_ANC, P_T3, C_T3),
        just=("A dupla lista: quando se justificou e quando não.",
              "Impede tanto a leitura de vítima quanto a de agressor puro.",
              "Integra memória estratégica, dilema de segurança e o problema de distinguir defesa de expansão."),
        ex=["A mesma percepção produziu defesa legítima (contra Napoleão e Hitler) e agressão (repúblicas bálticas e Polônia em 1939).",
            "As aspas e a interrogação no slide são o comando metodológico: a percepção de ameaça é dado a explicar, não justificativa a aceitar."],
        vuln=["🔴 Usar a 'paranoia geopolítica' como justificativa das ações de 2008, 2014 e 2022: o slide a apresenta como problema analítico.",
              "🔴 Negar qualquer fundamento à percepção russa: metade da lista do próprio slide é de invasões realmente sofridas.",
              "🟠 Confundir explicar com justificar."],
    ),
    dict(
        id="REL-T2-M06-C008", modulo="06-russia",
        assunto="Do Grande Jogo à Guerra Fria: Guerra dos Sete Anos, Guerras Napoleônicas, Guerra da Crimeia, o Grande Jogo do século XIX (disputa entre o Império Britânico e o Império Russo no contexto de uma China enfraquecida — a Grã-Bretanha querendo manter a Índia britânica e as rotas comerciais e controlar tampões como o Afeganistão, e a Rússia querendo acesso às águas quentes pela China e pela Índia), I Guerra Mundial e a retirada em 1917, formação da URSS em 1922 com repúblicas bálticas e do sul como Estados tampão do núcleo russo, II Guerra Mundial, e a Guerra Fria com o Pacto de Varsóvia",
        dep=["REL-T2-M06-C007"], exam=True, rap=True, safar=True,
        fontes=["F06:slides \"Guerra dos Sete Anos\", \"Guerras Napoleônicas\", \"Guerra da Crimeia\", \"O Grande Jogo (século XIX)\", \"I Guerra Mundial\", \"União Soviética\", \"II Guerra Mundial\", \"Guerra Fria\"",
                "A01:O Grande Jogo do século 19; URSS com Estados tampão protegendo a área coração; Pacto de Varsóvia"],
        prio=["O Grande Jogo é o precedente direto do desafio contemporâneo com a China na Ásia Central."],
        prof=(R_ANC, P_T3, C_T3),
        just=("A sequência e o padrão que ela revela.",
              "O Grande Jogo é o precedente indispensável do 'novo Grande Jogo'.",
              "Integra busca de águas quentes, disputa por tampões e a lógica de camadas da URSS."),
        ex=["Na URSS, as repúblicas bálticas e do sul funcionavam como Estados tampão da área coração: em cenário de guerra, o invasor teria de atravessá-las antes de alcançar a Rússia.",
            "O Grande Jogo já era disputa por tampões (Afeganistão) e por acesso a águas quentes (Índico)."],
        vuln=["🟠 Datar o Pacto de Varsóvia sem cuidado: o corpus traz 1953 no resumo, e o slide não confirma data. Trate-o como arranjo do início dos anos 1950 [PONTO DE INCERTEZA].",
              "🟡 Ler o Grande Jogo como disputa colonial genérica: era por tampões e por acesso ao mar quente."],
    ),
    dict(
        id="REL-T2-M06-C009", modulo="06-russia",
        assunto="Expansão da OTAN e a perda dos tampões: a fragmentação da URSS em 1991 tira da Rússia os Estados tampão; em seguida, países do Pacto de Varsóvia aderem à OTAN (Hungria, Romênia, República Tcheca, entre outros), com grande expressão em 2004 e depois em 2014; até meados de 2024 mais países entram, com destaque para Suécia e Finlândia, esta fazendo fronteira com a Rússia",
        dep=["REL-T2-M06-C008", "REL-T2-M06-C003"], exam=True, rap=True, safar=True,
        fontes=["F06:slides \"Pós-Guerra Fria (2000)\", \"OTAN em 2014\", \"OTAN em 2021\", \"OTAN em 2024\" e mapa com datas de adesão",
                "A01:Pós Guerra-Fria e a adesão de ex-membros do Pacto de Varsóvia",
                "P03:questão 3 (mapa da OTAN 2024 com Suécia e Finlândia)"],
        prio=["Foi cobrado com mapa em questão de itens incorretos, e é o mecanismo que fecha o argumento dos imperativos russos."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Datas de onda e o efeito sobre o tampão.",
              "É o nexo causal entre 1991 e as ações de 2008, 2014 e 2022.",
              "Integra perda de tampão, dilema de segurança e o efeito não pretendido da invasão de 2022."),
        ex=["Efeito não pretendido: a invasão de 2022 produziu exatamente o que a Rússia dizia querer evitar — a adesão de Suécia e Finlândia, esta com fronteira terrestre direta.",
            "A OTAN aumentou em 20% os gastos militares em 2025, com os aliados investindo 574 bilhões de dólares, e estabeleceu meta de 3,5% do PIB em gasto estritamente militar até 2035, mais 1,5% em segurança, totalizando 5%."],
        vuln=["🔴 Apresentar a expansão da OTAN como causa suficiente da invasão: é condicionante, não causa única, e o próprio resultado a intensificou.",
              "🟠 Esquecer que a Finlândia faz fronteira terrestre com a Rússia."],
    ),
    dict(
        id="REL-T2-M06-C010", modulo="06-russia",
        assunto="Desafios declarados para a Rússia: questão demográfica (população encolhendo, com alta parcela de idosos); conseguir dinamismo econômico que não dependa apenas de petróleo e gás; conter a expansão chinesa na Ásia Central (novo Grande Jogo, com mais atores) mantendo ao mesmo tempo aliança tática com a China; concluir a paz com o Japão (os dois estão em armistício, não em paz definitiva, com leve tensão no Mar de Okhotsk); impedir ou dificultar a entrada da Ucrânia e da Geórgia na OTAN; consolidar e aumentar a influência no Cáucaso (Armênia, Azerbaijão) e no Oriente Médio (Síria), contrabalançando a Turquia; e consolidar e aumentar a influência na Bielorrússia, sobre o Mar Negro e o Ártico",
        dep=["REL-T2-M06-C009"], exam=True, rap=True, safar=True,
        fontes=["F06:slides \"Desafios para a Rússia\" (dois slides)", "A01:DESAFIOS PARA A RÚSSIA (com o detalhe do armistício com o Japão e da BRI como novo Grande Jogo)",
                "F06:Estudo Dirigido (\"O estreitamento dos laços com a China é um elemento presente em todas as diretrizes geopolíticas analisadas na aula? Por quê? Ele seria sustentável, no longo prazo?\")"],
        prio=["É a lista que o Estudo Dirigido manda confrontar com Dugin e com os imperativos: cobrança anunciada."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Sete desafios nomeados.",
              "É o insumo da discursiva mais provável do módulo.",
              "Integra a contradição entre conter e aliar-se à China, que o Estudo Dirigido explora."),
        ex=["Contradição central: um desafio é CONTER a expansão chinesa na Ásia Central, e o mesmo item manda MANTER aliança tática com a China.",
            "Com o Japão a situação é de armistício (cessar-fogo), não de paz definitiva."],
        vuln=["🔴 Apresentar a relação com a China como aliança sem tensão: o slide a coloca dentro de um desafio de contenção.",
              "🟠 Dizer que Rússia e Japão assinaram paz: estão em armistício.",
              "🟡 Esquecer o Ártico, que aparece no último item."],
    ),
    dict(
        id="REL-T2-M06-C011", modulo="06-russia",
        assunto="Dugin e a Geopolítica da Rússia (1997): divisão do mundo em telurocracias (que se expandem militarmente por terra) e talassocracias (que se expandem pelo mar), e em Eurásia contra atlanticistas; recomendações de 1997 — invasão da Geórgia, anexação da Crimeia, separação entre Reino Unido e Europa, fragmentação da OTAN, divisionismo nos EUA e secessionismo no Reino Unido; e três eixos: Moscou-Berlim (saída de antigas repúblicas da URSS da UE e da OTAN), Moscou-Tóquio (contenção da ascensão da China) e Moscou-Teerã (influência no mundo islâmico)",
        dep=["REL-T2-M06-C010", "REL-T2-M00-C015"], exam=True, rap=True, safar=True,
        fontes=["F06:slides \"Geopolítica da Rússia (1997) Aleksandr Dugin\" e \"Geopolítica da Rússia (Dugin)\"",
                "A01:Dugin com o detalhe de cada eixo e o estado atual de cada um",
                "F06:Estudo Dirigido (\"aponte se a decisão da invasão da Ucrânia seguiu (ou não) tais aspectos\")"],
        prio=["É o teórico do módulo, o que o trabalho de T2 pediria para instrumentalizar, e o Estudo Dirigido manda testar a invasão contra as recomendações dele."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Duas categorias e três eixos.",
              "É a lente teórica do módulo e o instrumento do Estudo Dirigido.",
              "Integra o teste de aderência entre doutrina e prática, com os eixos que se paralisaram."),
        ex=["Duas recomendações de 1997 se cumpriram (Geórgia 2008, Crimeia 2014), mas o eixo Moscou-Tóquio, que existia para CONTER a China, foi abandonado na prática, porque a Rússia se aproximou da China.",
            "O eixo Moscou-Berlim estava latente e foi paralisado pela invasão da Ucrânia e pelo corte do gás russo, com a Alemanha em remilitarização e aumento de orçamento de defesa.",
            "O eixo Moscou-Teerã gera tensão com a Turquia, potência regional com bases da OTAN em seu território."],
        vuln=["🔴 Tratar Dugin como política oficial do Estado russo: é doutrina de 1997, e a prática divergiu dela em pontos centrais.",
              "🔴 Trocar telurocracia (expansão por terra) por talassocracia (expansão pelo mar).",
              "🟠 Concluir que a invasão da Ucrânia seguiu Dugin integralmente sem apontar o eixo Moscou-Tóquio, que foi contrariado."],
    ),
    dict(
        id="REL-T2-M06-C012", modulo="06-russia",
        assunto="Multipolaridade na visão russa: raiz na Doutrina Primakov dos anos 1990, com três objetivos duradouros — combater a dominação dos EUA, restaurar a influência russa no espaço pós-soviético e interromper a expansão da OTAN; a leitura crítica de que essa multipolaridade equivale ao retorno a esferas de influência, em que o poder se sobrepõe à lei e à soberania; e o argumento de que buscar multipolaridade é raro ponto de alinhamento estratégico entre Rússia e China",
        dep=["REL-T2-M06-C011"], exam=True, rap=True, safar=True,
        fontes=["C11:seções \"Multipolaridade Bipolar\" e \"A Armadilha Multipolar\"",
                "F06:bibliografia complementar (\"Visão da Rússia sobre Multipolaridade — Esferas de Influência e Subjugação das Nações\")"],
        prio=["A fonte está na bibliografia complementar do próprio slide e fornece o conceito que dá nome à visão russa de ordem."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Três objetivos da Doutrina Primakov.",
              "É o vocabulário para discutir ordem internacional na parte prospectiva.",
              "Integra a leitura crítica declarada e a leitura concorrente, sem adotar nenhuma como fato."),
        ex=["Os três objetivos de Primakov explicam os ultimatos de dezembro de 2021 à OTAN e aos EUA, exigindo retrocesso da presença militar ocidental perto das fronteiras russas.",
            "Leitura crítica da fonte: a multipolaridade russa significaria absorver território, arrastá-lo para estruturas de integração (BRICS, União Eurasiática, CEI) ou vinculá-lo a algum 'Estado da União'."],
        vuln=["🔴 Apresentar a análise de Gvineria como descrição neutra: é autor georgiano com posição declaradamente pró-ocidental, e há leituras concorrentes.",
              "🟠 Confundir multipolaridade como descrição de sistema (vários polos) com multipolaridade como projeto normativo (esferas de influência reconhecidas)."],
    ),
    dict(
        id="REL-T2-M06-C013", modulo="06-russia",
        assunto="Projeção marítima russa e a doutrina de 2022: doutrina marítima aprovada em 31/07/2022, substituindo a de 2001 emendada em 2015, que declara a dominação americana dos oceanos como ameaça primária ao território russo; define zonas de interesse vital (águas territoriais, ZEE, plataforma continental e a bacia do Ártico, inclusive a Rota Marítima do Norte) e zonas que afetam significativamente o desenvolvimento econômico (Azov, Mar Negro, Mediterrâneo oriental, Báltico e estreitos das Curilas); desloca a prioridade do Atlântico para o Ártico e o Pacífico; e enfrenta restrições materiais severas — frota muito inferior à soviética, dependência de componentes importados no setor civil (de 40% a 85%), estaleiros defasados, poucas bases no exterior e participação de cerca de 0,1% no transporte mundial de carga",
        dep=["REL-T2-M06-C006", "REL-T2-M06-C010"], exam=True, rap=True, safar=True,
        fontes=["C10:integral", "F06:bibliografia complementar (análise histórica da Marinha russa; \"the future looks bleak for Russia's struggling navy\")",
                "A01:acesso aos mares e o Ártico como objetivo"],
        prio=["É a única fonte do corpus que quantifica a distância entre ambição declarada e capacidade real — material perfeito para questão de análise de consequência."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Data, prioridade nova e o limite material.",
              "Permite avaliar ambição contra capacidade, que é o núcleo da análise estratégica.",
              "Integra doutrina, sanções, indústria naval, Rota Marítima do Norte e o horizonte de décadas."),
        ex=["Comparação registrada na fonte: nos anos 1980 a marinha soviética tinha mais de 1.300 navios; hoje são cerca de 70 submarinos e mais de 200 navios de superfície, muitos defasados.",
            "Cerca de 1,8 trilhão de rublos (aproximadamente 30 bilhões de dólares) comprometidos com o desenvolvimento da Rota Marítima do Norte até 2035.",
            "Os vizinhos não veem a nova doutrina como ameaça nova, porque entendem melhor que ninguém que a capacidade russa no mar é limitada, muitas vezes por razões internas."],
        vuln=["🔴 Concluir capacidade a partir de doutrina: a doutrina é declaração de intenção, e a fonte documenta o contrário em meios.",
              "🟠 Esquecer que o Ártico ganhou prioridade em relação ao Atlântico.",
              "🟡 Tratar a frota mercante russa como relevante: é cerca de 0,1% do transporte mundial de carga, com 65,7% operada sob bandeira estrangeira."],
    ),
    dict(
        id="REL-T2-M06-C014", modulo="06-russia",
        assunto="Teste de coerência entre doutrina, imperativos e prática: aplicar aos casos de 2008, 2014 e 2022 a checagem tripla — o ato serviu ao imperativo declarado? seguiu a doutrina de Dugin? e produziu consequências que favorecem ou contrariam os próprios objetivos russos?",
        dep=["REL-T2-M06-C003", "REL-T2-M06-C011", "REL-T2-M06-C012", "REL-T2-M06-C009"], exam=True, rap=True, safar=True,
        fontes=["F06:Estudo Dirigido (\"aponte as consequências da referida invasão, indicando aquelas que contribuirão positivamente e as que trarão resultados negativos para os objetivos mencionados\")",
                "C11:consequências para Geórgia, Moldávia e Armênia", "C10:efeito das sanções sobre portos e cadeias de valor"],
        prio=["O Estudo Dirigido pede literalmente o balanço de consequências positivas e negativas: é o formato da discursiva de fechamento do curso."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Três perguntas de checagem.",
              "É o método de responder à discursiva anunciada pelo professor.",
              "Integra imperativo, doutrina, consequência pretendida e consequência não pretendida."),
        ex=["Favorável ao objetivo: controle da Crimeia e de Sebastopol reforça a posição no Mar Negro.",
            "Contrário ao objetivo: adesão de Suécia e Finlândia à OTAN, paralisia do eixo Moscou-Berlim, corte do gás para a Europa, queda projetada de até 50% na movimentação de carga nos portos russos e aproximação com a China que contraria o eixo Moscou-Tóquio.",
            "Efeito regional: um acordo que recompense a agressão criaria precedente para Geórgia, Moldávia e Armênia — leitura da fonte C11, com posição declarada."],
        vuln=["🔴 Entregar só o lado favorável ou só o desfavorável: o Estudo Dirigido pede os dois.",
              "🟠 Julgar a decisão pelo resultado militar apenas, ignorando os efeitos sobre tampões, alianças e economia."],
    ),
]
