# -*- coding: utf-8 -*-
"""Matriz canônica — Módulos 05 e 06."""

from conceitos_m00_m02 import R_ANC, P_APL, C_INT, C_T3, P_T3

CONCEITOS = [
    # ────────────────────────── M05 — China ──────────────────────────────
    dict(
        id="REL-T2-M05-C001", modulo="05-china",
        assunto="Geografia chinesa como condicionante: a isoieta de 300 mm divide o país — cerca de 90% da população vive a leste dela, e a renda per capita é, em geral, maior desse lado; o coração econômico e financeiro está nas planícies do leste; e o país é cercado por zonas tampão naturais (platô tibetano, Himalaia, deserto de Gobi, Manchúria e Xinjiang), áridas ou de altíssima altitude",
        dep=["REL-T2-M00-C003"], exam=True, rap=True, safar=True,
        fontes=["F05:slides de mapas (isoieta, renda per capita por divisão administrativa, topografia)",
                "A01:leitura dos mapas (isoieta de 300 mm, 90% da população, zonas tampão)", "AUT:lacuna I-04"],
        prio=["Sem a geografia não se explica a dupla tensão nem o imperativo de integridade territorial."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Uma linha imaginária que explica a distribuição de gente e de renda.",
              "Base física de todo o raciocínio do módulo.",
              "Integra clima, relevo, população, renda e zonas tampão num só argumento."),
        ex=["A mesma linha que separa densidade populacional separa renda: geografia física convertida em desigualdade regional.",
            "As zonas tampão são naturais antes de serem políticas: aridez e altitude impedem avanço de exércitos."],
        vuln=["🟠 Tratar as zonas tampão chinesas como escolha política apenas: elas são primeiro um fato geográfico.",
              "🟡 Confundir isoieta (linha de igual precipitação) com isoterma ou com fronteira administrativa."],
    ),
    dict(
        id="REL-T2-M05-C002", modulo="05-china",
        assunto="Dupla tensão histórica litoral/interior: riqueza e cobiça externa no litoral, pobreza e ameaças terrestres no interior; o aumento da desigualdade em favor do litoral pressiona Beijing a redistribuir riqueza para o interior; a tensão política resultante faz as elites litorâneas provocarem centralização política por parte de Beijing, que lhes retira autonomia e fecha o regime; e a consequência é diminuição da abertura ao exterior, a autarcização",
        dep=["REL-T2-M05-C001"], exam=True, rap=True, safar=True,
        fontes=["F05:slide \"China - Dupla Tensão Histórica\"",
                "A01:mecanismo completo (comércio marítimo maior que o terrestre, cobiça menor que a ameaça terrestre, taxação das elites litorâneas, autarcização em Ming, Qing e Mao)",
                "C05:mecanismo prata/cobre (imposto em prata, transação em cobre, alta da prata e o interior contra o litoral)"],
        prio=["É o conceito estruturante do módulo: o professor o apresenta como CARACTERÍSTICA HISTÓRICA, não como episódio."],
        prof=(R_ANC, P_T3, C_T3),
        just=("O ciclo em quatro passos.",
              "É a lente que explica abertura e fechamento ao longo de séculos.",
              "Integra o mecanismo fiscal concreto: imposto em prata, transação em cobre, saída de prata e revolta do interior."),
        ex=["Autarcização em Ming (1368-1644), Qing (1644-1912) e no governo de Mao: o mesmo mecanismo em três épocas.",
            "Não dá para deixar fechado sempre (empobrece) nem aberto sempre (aumenta desigualdade e desagregação).",
            "O ópio mostrou o mecanismo em detalhe: camponeses transacionavam em cobre e pagavam imposto em prata; com a saída de prata, a prata subiu contra o cobre e o mesmo governo que não os protegia passou a tomar mais do seu dinheiro."],
        vuln=["🔴 Descrever a dupla tensão como conflito entre ricos e pobres: o mecanismo é político — desigualdade → pressão redistributiva → centralização → fechamento.",
              "🟠 Tratar a autarcização como opção ideológica: é resposta à ameaça de desagregação interna."],
    ),
    dict(
        id="REL-T2-M05-C003", modulo="05-china",
        assunto="Imperativo estratégico da China em três itens: manter a integridade territorial; evitar desigualdades significativas dentro do próprio território, para não fomentar desafios ao poder político centralizado; e manter abertura ao exterior para garantir prosperidade econômica, sem permitir a desagregação interna",
        dep=["REL-T2-M05-C002", "REL-T2-M00-C004"], exam=True, rap=True, safar=True,
        fontes=["F05:slide \"China - Imperativo Estratégico\"", "A01:CHINA – IMPERATIVO ESTRATÉGICO (três itens numerados)"],
        prio=["É o conceito central do módulo e a base de toda comparação com EUA e Rússia."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Três itens na ordem certa.",
              "Explica qualquer decisão chinesa, do Tibete ao Mar do Sul da China.",
              "Integra a tensão insolúvel entre abertura necessária e coesão necessária."),
        ex=["Os três itens formam um trilema: abertura gera prosperidade, prosperidade gera desigualdade, desigualdade ameaça a coesão, e a resposta à ameaça de coesão reduz a abertura.",
            "Xinjiang e Tibete são simultaneamente integridade territorial e zona tampão."],
        vuln=["🔴 Resumir o imperativo chinês a 'expandir': os três itens são de PRESERVAÇÃO — território, coesão e prosperidade.",
              "🟠 Tratar abertura ao exterior como fim em si: no slide ela é meio para a prosperidade, subordinada à coesão."],
    ),
    dict(
        id="REL-T2-M05-C004", modulo="05-china",
        assunto="Cronologia dinástica seletiva: Shang (1650-1050 a.C., primeira linha de governantes com registro escrito e evidência arqueológica, criou a primeira forma escrita do idioma), Zhou (1050-256 a.C., confucionismo e taoismo, conceito do Mandato do Céu), Qin (221-206 a.C., primeira unificação, governo burocrático centralizado, estradas, vias navegáveis, início da Grande Muralha, unificação de pesos, moedas e escrita), Han (206 a.C.-220 d.C., confucionismo como ideologia oficial, papel, bússola, Rota da Seda), Sui e Tang (618-907, apogeu, budismo, impressão em blocos de madeira e pólvora), Song (960-1279, bússola magnética para navegação de longa distância, primeiro papel-moeda oficial do mundo), Yuan (1279-1368, domínio mongol), Ming (1368-1644, restabelecimento do domínio chinês, Cidade Proibida) e Qing (1644-1911, manchus, última dinastia imperial, ocupação das zonas tampão)",
        dep=["REL-T2-M05-C003"], exam=True, rap=False, safar=True,
        fontes=["F05:slides das dinastias (Shang a Qing)",
                "A01:cronologia resumida com as conquistas territoriais por dinastia (Tang→Xinjiang, Yuan→Tibete, Qing→todas as zonas tampão)",
                "AUT:conflito CF-04 do manifesto"],
        prio=["A cronologia entra pelo que explica: unificação, ideologia de Estado, tecnologia de projeção e alcance territorial. A parte cerâmica dos slides foi cortada por não ter função avaliativa."],
        prof=(None, P_APL, C_INT),
        just=("Fora do Rápido: no tempo curto o aluno guarda Qin (unificação), Han (Rota da Seda) e Qing (última dinastia e zonas tampão), via C003 e C005.",
              "Necessária para datar o Mandato do Céu, a unificação e o alcance das zonas tampão.",
              "Integra cada dinastia à conquista territorial e à tecnologia que ela habilitou."),
        ex=["Tang foi a primeira a alcançar Xinjiang, por aliança com povos tártaros da Ásia Central; Yuan alcançou o Tibete; Qing ocupou todas as zonas tampão.",
            "Qin unificou pesos, moedas e escrita: padronização como tecnologia de integração territorial."],
        vuln=["🔴 Dizer que Zhou foi a primeira dinastia: a primeira com registro escrito e arqueológico é Shang, e foi Shang que criou a primeira forma escrita.",
              "🔴 Datar Qing até 1892: vai até 1911.",
              "🟠 Decorar a cronologia cerâmica: não tem função avaliativa e foi cortada do curso."],
    ),
    dict(
        id="REL-T2-M05-C005", modulo="05-china",
        assunto="Tianxia e o sistema sinocêntrico tributário: 'todos sob o céu' — conceito cultural que denotava o mundo geográfico ou o reino metafísico dos mortais e depois se associou à soberania política, com o centro distribuído à corte chinesa e irradiando concentricamente até os 'bárbaros' da franja; os quatro mecanismos (tornar o inimigo economicamente dependente com produtos sofisticados; doutrinação nos valores confucianos e na autoridade do Imperador, inclusive por casamento do herdeiro bárbaro com filha do Imperador; a igualdade que se torna vassalagem com o tempo; a noção de Império do Meio irradiando autoridade); e o sistema tributário (aceitação da subordinação, tributos periódicos ao detentor do Mandato Divino, adoção do calendário chinês, liberdade de comércio, reconhecimento de posição inferior com pouca violência empregada, e a obrigação do Imperador de manter a harmonia sob os Céus)",
        dep=["REL-T2-M05-C004"], exam=True, rap=True, safar=True,
        fontes=["F05:slides \"Tianxia\" (quatro slides)", "F05:slide \"Sistema sinocêntrico (tributário)\"",
                "F05:citação de Sun Tzu (\"levar tudo sob o céu intacto\")", "A01:TIANXIA e o exemplo do casamento dinástico"],
        prio=["É o contraponto conceitual direto ao Destino Manifesto e a base da expressão 'Mandato Divino' usada pelo professor."],
        prof=(R_ANC, P_T3, C_T3),
        just=("O que é e como funcionava, em quatro mecanismos.",
              "É a lente para ler a projeção chinesa contemporânea sem anacronismo.",
              "Integra Sun Tzu, dependência econômica e soft power como mecanismos de ordem hierárquica com pouca violência."),
        ex=["Sun Tzu: 'Seu objetivo deve ser levar tudo sob o céu intacto. Assim, suas tropas não estão desgastadas e seus ganhos serão completos.' — conquistar sem destruir o que se quer conquistar.",
            "O sistema tributário é hierárquico e de baixa violência: reconhece-se posição inferior, envia-se tributo, adota-se o calendário, e o comércio segue livre."],
        vuln=["🔴 Ler o sistema tributário como império territorial: era ordem hierárquica com baixa violência empregada.",
              "🟠 Traduzir Tianxia como 'império' — é 'todos sob o céu', e o Imperador tem o DEVER de manter a harmonia.",
              "🟡 Usar 'Mandato do Céu' e 'Mandato Divino' como conceitos distintos: no corpus são o mesmo."],
    ),
    dict(
        id="REL-T2-M05-C006", modulo="05-china",
        assunto="Século das Humilhações: I Guerra do Ópio e o Tratado de Nanquim, com Hong Kong entregue; II Guerra do Ópio (1856-1860), Tratado de Tianjin e Convenção de Pequim — abertura das portas chinesas aos estrangeiros, aceitação de diplomatas estrangeiros, permissão a missionários cristãos e legalização do ópio; locais com extraterritorialidade; e as revoltas fracassadas (Taiping e Boxers)",
        dep=["REL-T2-M05-C005", "REL-T2-M05-C002"], exam=True, rap=True, safar=True,
        fontes=["F05:slide \"China - Século das Humilhações\"", "A01:extraterritorialidade em Xangai; Boxers contra Reino Unido, França e Alemanha",
                "C05:mecanismo do desequilíbrio comercial (chá, prata, ópio), casus belli de 1839 e a memória nacional herdada pelo PCC"],
        prio=["É a memória estratégica que o professor usa para explicar a legitimidade do PCC e a leitura chinesa da pressão externa."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Duas guerras, três tratados, uma consequência.",
              "É o que explica por que a China lê exigência externa como humilhação.",
              "Integra o mecanismo comercial completo e a herança de legitimidade do PCC."),
        ex=["Mecanismo: obsessão britânica pelo chá → déficit pago em prata → ópio do norte da Índia como forma de recuperar a prata → tentativa chinesa de coibir → confisco de 20 mil caixas em 1839 → casus belli.",
            "O PCC herdou a memória nacional da I Guerra do Ópio; 'rejuvenescimento nacional' de Xi Jinping fala a esse sentimento e dá ao partido mais legitimidade que o marxismo."],
        vuln=["🔴 Reduzir as Guerras do Ópio a uma questão de droga: o mecanismo é de balança comercial e de pagamentos.",
              "🟠 Achar que o Tratado de Nanquim beneficiou só a Grã-Bretanha: França, Alemanha, EUA e Rússia exigiram tratamento semelhante, e Rússia e Japão conquistaram território."],
    ),
    dict(
        id="REL-T2-M05-C007", modulo="05-china",
        assunto="República, guerra civil e maoísmo: fim do império, warlords, Kuomintang × PCC, invasão japonesa e II Guerra, vitória do PCC em 1949; apoio inicial da URSS, coletivização, conquista de Xinjiang e Tibete (restabelecimento das zonas tampão), Grande Salto para a Frente (1958-1962) e seu fracasso, Grande Cisma (1960), Guerra China-Índia (1962, Arunachal Pradesh), estímulo a revoluções socialistas e Revolução Cultural (1966-1976) para abolir influências capitalistas, além da trégua com os EUA para antagonizar a URSS",
        dep=["REL-T2-M05-C006"], exam=True, rap=True, safar=True,
        fontes=["F05:slides \"China - Guerra Civil\", \"China - Maoísmo\" (dois slides), mapa dos senhores da guerra (1925)",
                "A01:mecanismo do Grande Salto (realocação de agricultores para siderurgia, manutenção da exportação agrícola, fome), razões do Grande Cisma (debate sobre difusão do comunismo), visita de Nixon em 1972 precedida por Kissinger em 1971, reconhecimento formal em 1979, entrada da RPC no CSNU em 1971"],
        prio=["Contém o caso mais rico de pragmatismo realista do corpus: dois Estados comunistas se dividem e a terceira potência explora a fenda."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Marcos e o motivo de cada um.",
              "É a sequência que explica a aproximação com os EUA e o assento no CSNU.",
              "Integra o mecanismo da fome, a lógica do cisma e a barganha triangular."),
        ex=["Grande Salto: realocar agricultores para a produção de aço reduziu a produção agrícola, mas a exportação agrícola foi mantida — resultado, fome com dezenas de milhões de mortos.",
            "A RPC entrou no CSNU em 1971 no contexto da aproximação com os EUA e do isolamento diplomático da República da China.",
            "A China reconhece o atrito de 1962 com a Índia não como guerra, mas como 'expedição punitiva'."],
        vuln=["🔴 Ler o Grande Cisma como divergência pessoal: era debate sobre difundir o comunismo (posição chinesa) ou consolidá-lo no próprio país (posição soviética), somado às concessões da URSS ao Ocidente.",
              "🟠 Datar a trégua com os EUA em 1949-1950: ela vem depois do cisma, com Kissinger em 1971 e Nixon em 1972.",
              "🟡 Confundir reconhecimento formal (1979) com reatamento de relações (1972)."],
    ),
    dict(
        id="REL-T2-M05-C008", modulo="05-china",
        assunto="Deng Xiaoping e a abertura controlada: pragmatismo econômico com recapitalização progressiva, acertos prévios com a diáspora chinesa, flexibilização agrícola e zonas econômicas especiais (ZEE); resultados — crescimento econômico sustentado, diminuição das tensões externas, fortalecimento do PCC (exemplo do Massacre da Praça da Paz Celestial, 1989) e resolução dos litígios territoriais, com exceção de Índia e Japão",
        dep=["REL-T2-M05-C007", "REL-T2-M05-C003"], exam=True, rap=True, safar=True,
        fontes=["F05:slides \"China Deng Xiao Ping\", \"China - ZEE\", \"Resultados\"",
                "A01:zonas econômicas especiais com incentivos fiscais atraindo capital estrangeiro; alerta para não confundir com zona econômica exclusiva; inflação e descontentamento antes de 1989"],
        prio=["É a demonstração viva do imperativo: abrir para prosperar sem perder a coesão. E contém a homonímia ZEE, que é pegadinha perfeita."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Quatro medidas e quatro resultados.",
              "Mostra o imperativo chinês funcionando na prática.",
              "Integra abertura, fortalecimento do partido e o custo político de 1989."),
        ex=["As ZEE chinesas são áreas com características capitalistas e incentivos fiscais para indústrias e empresas, atraindo capital estrangeiro.",
            "O fortalecimento do PCC aparece no slide como RESULTADO da abertura, não como obstáculo a ela."],
        vuln=["🔴 Confundir ZEE (zona econômica especial, chinesa, de política industrial) com ZEE (zona econômica exclusiva, da CNUDM, de direito do mar). O resumo do professor alerta expressamente para isso.",
              "🟠 Tratar 1989 como interrupção da abertura: o slide o apresenta dentro do resultado 'fortalecimento do PCC'.",
              "🟡 Dizer que todos os litígios foram resolvidos: Índia e Japão são exceção expressa."],
    ),
    dict(
        id="REL-T2-M05-C009", modulo="05-china",
        assunto="China pós-Deng e China recente: reafirmação do papel chinês no mundo, revisionismo 'soft', entrada na OMC, participação crescente nas missões de paz da ONU e aumento de influência na Ásia, África, Europa e América Latina; reestruturação econômica e vigor tecnológico, impacto dos custos trabalhistas, questão demográfica, Taiwan e litígios (Aksai Chin, Arunachal Pradesh, platô de Doklam, ilhas Diaoyu/Senkaku, Mar do Sul da China), assertividade militar e centralização política do PCC com destaque de Xi Jinping, no poder desde 2012 e o mais importante desde Mao",
        dep=["REL-T2-M05-C008"], exam=True, rap=True, safar=True,
        fontes=["F05:slides \"China Pós-Deng\" e \"China recente\"", "F05:mapas dos litígios (fronteira leste com a Índia, Doklam, Diaoyu/Senkaku, nine-dash line)",
                "A01:modelo de plataformas de exportação, deslocamento de empresas para Vietnã, Camboja e Laos, política do filho único de 1979 a 2015 e liberação de até três filhos em 2021",
                "AUT:conflito CF-04 (Doklam é com o Butão)"],
        prio=["Concentra os litígios nominais e os três vetores contemporâneos: tecnologia, demografia e assertividade."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Litígios nominais e três vetores.",
              "Permite situar qualquer notícia recente no quadro do imperativo.",
              "Integra o modelo de plataformas de exportação, o ciclo de custos trabalhistas e a armadilha demográfica."),
        ex=["Modelo de plataformas de exportação: China, Japão e os tigres asiáticos cresceram exportando; o que muda no tempo é o nível tecnológico, a complexidade produtiva e o grau de intervenção estatal.",
            "Com o progresso técnico os salários subiram, encareceram o custo trabalhista e empresas migraram para Vietnã, Camboja e Laos.",
            "Política do filho único de 1979 a 2015, abolida em 2015 e, em 2021, permissão de até três filhos por casal — a consequência é população economicamente ativa menor e custos previdenciários maiores."],
        vuln=["🔴 Situar o platô de Doklam como litígio com Bangladesh: é com o BUTÃO (o mapa do deck rotula Bhutan). O resumo do Aspirante erra esse ponto.",
              "🟠 Tratar o revisionismo chinês como ruptura declarada: o slide o qualifica como 'soft'.",
              "🟡 Confundir Aksai Chin (setor ocidental) com Arunachal Pradesh (setor oriental)."],
    ),
    dict(
        id="REL-T2-M05-C010", modulo="05-china",
        assunto="Taiwan: província considerada rebelde, para onde o Kuomintang de Chiang Kai-shek fugiu em 1949; a Resolução 2758 da Assembleia Geral da ONU (25/10/1971) e a disputa interpretativa sobre ela — para Pequim resolveu em definitivo a representação de toda a China e confirmou o princípio de Uma Só China; para os EUA e Taiwan tratou apenas da representação na ONU, sem determinar soberania territorial; distinção entre o PRINCÍPIO de Uma Só China (RPC) e a POLÍTICA de Uma Só China (EUA, com Taiwan Relations Act, Três Comunicados e Seis Garantias); ambiguidade estratégica; participação seletiva na OMC (2002) e na APEC como Chinese Taipei; escudo de silício dos semicondutores; e 12 parceiros diplomáticos formais em 2026",
        dep=["REL-T2-M05-C009", "REL-T2-M05-C003"], exam=True, rap=True, safar=True,
        fontes=["F05:slide \"China recente\" (Questão Taiwan)", "F05:mapa do Estreito de Taiwan com distâncias",
                "C08:integral", "A01:Taiwan como província rebelde desde 1949; RPC no CSNU em 1971 e isolamento da ROC"],
        prio=["É o litígio que liga integridade territorial (imperativo 1), Primeira Cadeia de Ilhas e rivalidade com os EUA — e tem uma distinção conceitual que produz pegadinha perfeita."],
        prof=(R_ANC, P_T3, C_T3),
        just=("A distinção princípio × política, em uma linha cada.",
              "Permite responder qualquer questão sobre o estreito sem simplificar.",
              "Integra reconhecimento, representação multilateral, ambiguidade estratégica e cadeia de semicondutores."),
        ex=["A Resolução 2758 'restaurou' os direitos da RPC e retirou os delegados de Chiang Kai-shek; suas consequências jurídicas permanecem disputadas — não se deve resumi-la a um ato que 'declarou Taiwan parte da China'.",
            "Ambiguidade estratégica: os EUA apoiam a capacidade de autodefesa taiwanesa sem definir de antemão como responderiam a um conflito militar.",
            "Escudo de silício: a liderança global em semicondutores (TSMC) é simultaneamente vulnerabilidade e proteção."],
        vuln=["🔴 Confundir o PRINCÍPIO de Uma Só China (RPC: Taiwan é parte inalienável e a RPC é o único governo legítimo) com a POLÍTICA de Uma Só China (EUA: reconhecem a RPC, não apoiam a independência, mantêm laços não oficiais).",
              "🔴 Afirmar que a Resolução 2758 decidiu a soberania territorial: ela tratou de representação, e a leitura é disputada.",
              "🟠 Dizer que Taiwan está isolada: ela participa da OMC e da APEC como Chinese Taipei."],
    ),
    dict(
        id="REL-T2-M05-C011", modulo="05-china",
        assunto="Mar do Sul da China e a nine-dash line: reivindicações sobrepostas de Filipinas, Vietnã, Malásia, Brunei e Indonésia sob a CNUDM contra a linha de nove traços reivindicada por China e Taiwan; Ilhas Paracel, Ilhas Spratly, Scarborough Shoal e a província de Hainan",
        dep=["REL-T2-M05-C009"], exam=True, rap=True, safar=True,
        fontes=["F05:mapa \"Mar do Sul da China\" (reivindicações de ZEE e nine-dash line)", "F05:slide \"Mar do Sul da China - A2/AD\"",
                "A01:militarização de ilhas artificiais (Spratly) e presença naval chinesa"],
        prio=["É o espaço onde o imperativo chinês colide diretamente com a CNUDM e com os aliados dos EUA."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Nomes dos arquipélagos e a natureza da disputa.",
              "É o cenário mais provável de qualquer questão aplicada sobre a China.",
              "Integra direito do mar, ilha artificial e negação de área."),
        ex=["A tensão é entre um título histórico (linha de nove traços) e um título convencional (ZEE medida das linhas de base, sob a CNUDM).",
            "Ilha artificial não gera os mesmos direitos que ilha — ponto que a própria P1 cobrou em caso com distâncias."],
        vuln=["🔴 Supor que ilha artificial gera mar territorial e ZEE.",
              "🟠 Atribuir a nine-dash line só à RPC: o mapa do deck a registra como reivindicação de China e Taiwan."],
    ),
    dict(
        id="REL-T2-M05-C012", modulo="05-china",
        assunto="A2/AD chinês por cadeias de ilhas: antiacesso (A2) é impedir a entrada do inimigo em determinada região estratégica, com mísseis balísticos de longo alcance e submarinos em locais estratégicos; negação de área (AD) é dificultar as ações do inimigo já dentro da região, com mísseis antinavio e interferência eletrônica; a China aplica A2 na região da Primeira Cadeia de Ilhas — das ilhas ao sul do Japão em Okinawa, passando por Taiwan e Filipinas, até o Estreito de Málaca — e AD de forma mais restrita às áreas de seu mar territorial (Spratly, Paracel, Hainan), com as mesmas ilhas servindo aos dois propósitos",
        dep=["REL-T2-M05-C011", "REL-T2-M04-C010"], exam=True, rap=True, safar=True,
        fontes=["F05:slide \"Mar do Sul da China - A2/AD\"", "F04:slide \"A2/AD - Anti-access/Area Denial\"",
                "A01:definição operacional de A2 e AD, alcance da Primeira Cadeia, ações que indicam A2 (mísseis e bases em Hainan, militarização de Spratly, presença naval)"],
        prio=["É o conceito militar mais técnico do curso e o único com distinção interna (A2 × AD) que o resumo detalha com meios distintos."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Duas siglas, dois alcances, dois conjuntos de meios.",
              "É a lente que explica a estrutura de força chinesa e a resposta americana.",
              "Integra geografia (cadeias de ilhas), meios (mísseis, submarinos, guerra eletrônica) e a doutrina de dispersão da frota americana."),
        ex=["A2 = manter o adversário FORA, com alcance longo. AD = dificultar a ação de quem já ENTROU, com alcance curto.",
            "Primeira Cadeia de Ilhas: Okinawa e ilhas ao sul do Japão, Taiwan, Filipinas e o Estreito de Málaca.",
            "Segunda Cadeia: Austrália, Guam e ilhas da Oceania. Terceira: Havaí."],
        vuln=["🔴 Trocar A2 por AD: o antiacesso é impedir a entrada; a negação de área é dificultar a ação de quem entrou.",
              "🟠 Supor que A2 e AD usam ilhas diferentes: o corpus registra que as mesmas ilhas servem aos dois.",
              "🟡 Colocar Taiwan na Segunda Cadeia."],
    ),
    dict(
        id="REL-T2-M05-C013", modulo="05-china",
        assunto="Dilema do Estreito de Málaca e a perspectiva chinesa de estar 'engaiolada': a China se vê cercada pela presença de bases americanas em países aliados (Japão, Coreia do Sul, Filipinas, Taiwan) e por meios navais e aéreos americanos; por isso busca alternativas terrestres de acesso ao mar (com apoio de Mianmar e Bangladesh) e investe na possibilidade do Canal de Kra, na Tailândia, temendo um bloqueio do Estreito de Málaca, por onde passa a maior parte de suas exportações e importações, inclusive insumos energéticos e alimentares",
        dep=["REL-T2-M05-C012", "REL-T2-M00-C013"], exam=True, rap=True, safar=True,
        fontes=["F05:slide \"Perspectiva Chinesa\" e mapa do Estreito de Málaca",
                "A01:PERSPECTIVA CHINESA (engaiolada, corredores terrestres, Canal de Kra)",
                "P05:questão 17 (Canal de Kra, precedentes de Suez e Panamá, interesses da Índia)",
                "C05:a China já não é autossuficiente — importa alimento e petróleo"],
        prio=["Foi cobrado em discursiva de 2,1 pontos na P2, com três subitens. É a vulnerabilidade estrutural mais explorada pelo professor."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Um estreito, uma vulnerabilidade, duas alternativas.",
              "É o melhor caso de chokepoint aplicado do curso.",
              "Integra Mahan, soberania de terceiros, interesses indianos e a perda de autossuficiência chinesa."),
        ex=["Resposta-padrão da P2: a iniciativa do canal busca contornar eventuais bloqueios do Estreito de Málaca por marinhas de outras nações, e aumentaria a influência chinesa no Golfo da Tailândia e na Baía de Bengala.",
            "Precedentes de Suez e Panamá: o funcionamento dos canais se deu com presença física de representantes das potências construtoras, inclusive em atividades de segurança — daí a questão sobre a soberania tailandesa.",
            "Não atenderia à Índia: aumentaria a influência chinesa em áreas onde a Índia projeta poder, como a Baía de Bengala e o Sudeste Asiático."],
        vuln=["🔴 Tratar o dilema de Málaca como problema comercial: é de segurança energética e alimentar.",
              "🟠 Esquecer que a China importa alimento e petróleo — historicamente autossuficiente, hoje não é.",
              "🟡 Responder o caso do canal sem considerar o efeito sobre a soberania do país anfitrião."],
    ),
    dict(
        id="REL-T2-M05-C014", modulo="05-china",
        assunto="Belt and Road (Um Cinturão, Uma Rota): Cinturão Econômico da Rota da Seda por terra e Rota da Seda Marítima do Século XXI, ligando o extremo do Leste Asiático à África Oriental e à Europa Central por rodovias, ferrovias, rotas oceânicas e portos; financiada majoritariamente com capital chinês (AIIB, China Development Bank, Bank of China, outros bancos estatais, Silk Road Fund); projeção de influência econômica e política, com países endividados junto a bancos chineses, mesmo a juros baixos, em relação de dependência; e a crítica indiana ao corredor China-Paquistão que atravessa a Caxemira ocupada",
        dep=["REL-T2-M05-C013"], exam=True, rap=True, safar=True,
        fontes=["F05:slide \"Investimentos no Exterior e One Belt, One Road\" e infográfico",
                "F05:link atualizado sobre o envolvimento da China na BRI em 2026",
                "A01:BRI como corredor econômico transcontinental por terra e mar, e a relação de dependência gerada"],
        prio=["É o instrumento econômico central da projeção chinesa e o que o Brasil e a América Latina encontram na prática."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Dois ramos, um financiador, um efeito.",
              "É o instrumento a nomear em qualquer resposta sobre projeção chinesa.",
              "Integra infraestrutura, endividamento, influência e a reação indiana e americana."),
        ex=["Dois ramos: cinturão terrestre (Xian–Ásia Central–Europa) e rota marítima (Fuzhou–Málaca–Índico–Mar Vermelho–Mediterrâneo).",
            "A Índia chamou o projeto de 'empresa colonial, deixando dívida e comunidades destruídas em seu rastro' e boicotou a cúpula.",
            "O Panamá aderiu em 2017 e saiu em 2025 sob pressão americana — a BRI é onde a competição EUA-China toca o hemisfério."],
        vuln=["🔴 Tratar a BRI como projeto só de infraestrutura: o efeito é de dependência e influência política.",
              "🟠 Esquecer o ramo marítimo: 'Um Cinturão' é terrestre, 'Uma Rota' é marítima."],
    ),
    dict(
        id="REL-T2-M05-C015", modulo="05-china",
        assunto="Modernização naval chinesa como evidência de estratégia: entre 2005 e 2020 o Congresso dos EUA registrou 49 novas corvetas, 35 naves de patrulha costeira com mísseis, 2 porta-aviões, 11 destróieres, 6 fragatas, 1 cruzador e 17 embarcações para ataque anfíbio; e a marinha chinesa passou a ter mais navios que a americana (332 contra 291, incluindo submarinos, segundo dado de 2020) — sem que isso signifique superioridade de tonelagem, alcance ou experiência",
        dep=["REL-T2-M05-C012", "REL-T2-M04-C011"], exam=True, rap=False, safar=True,
        fontes=["F05:slides \"Marinha Chinesa\" e \"A marinha chinesa possui agora mais navios que os EUA\"",
                "F05:citação do relatório do Departamento de Defesa dos EUA, 2024"],
        prio=["É o dado que mais produz conclusão apressada: mais navios não é mais poder naval."],
        prof=(None, P_T3, C_T3),
        just=("Fora do Rápido: no tempo curto vale o conceito (A2/AD), não a contagem.",
              "Necessário para recusar a conclusão apressada de superioridade naval.",
              "Integra contagem de cascos, composição de frota, alcance e rede de bases."),
        ex=["A composição revela a doutrina: corvetas e patrulhas com mísseis servem a A2/AD regional, não a projeção global.",
            "Comparar 332 contra 291 sem considerar tonelagem, porta-aviões, bases no exterior e experiência operacional é comparar números, não poder."],
        vuln=["🔴 Concluir superioridade naval chinesa a partir da contagem de cascos.",
              "🟠 Ignorar que a supremacia americana é potencializada por 9 marinhas aliadas entre as 12 seguintes."],
    ),
    dict(
        id="REL-T2-M05-C016", modulo="05-china",
        assunto="Rivalidade e interdependência EUA-China: a competição contemporânea reencena a lógica das Guerras do Ópio — uma potência ocidental insatisfeita quer redefinir os termos da relação econômica e a China está entre ser fraca demais para resistir e consciente demais do passado para ceder; a China não quer mais jogar pelas regras, quer participar de fazê-las; e a novidade histórica é que nunca houve, ao mesmo tempo, uma China poderosa e uns Estados Unidos poderosos",
        dep=["REL-T2-M05-C006", "REL-T2-M05-C014", "REL-T2-M04-C012"], exam=True, rap=True, safar=True,
        fontes=["C05:seções \"A New Chapter\" e \"Where History Diverges\"", "C06:seção final (competição incomparável; nunca houve China e EUA poderosos ao mesmo tempo)",
                "A01:guerra tarifária e bipolaridade EUA-China", "F04:slide \"Cenários — Forças-motrizes\""],
        prio=["É o conceito que fecha os módulos 04 e 05 e o mais provável em questão de integração entre módulos."],
        prof=(R_ANC, P_T3, C_T3),
        just=("A analogia e o seu limite.",
              "É a moldura de qualquer resposta sobre a competição sistêmica.",
              "Integra interdependência, memória histórica, legitimidade interna e limites da analogia."),
        ex=["Limite da analogia: a dinastia Qing era usurpadora estrangeira e perdia o controle; o PCC é han, jovem em termos dinásticos e não demonstra perder o controle.",
            "Interdependência é arma de dois gumes: fechar-se pode gerar revolução interna, integrar-se nos termos alheios pode gerar desilusão com um governo repressivo e incapaz de defender interesses.",
            "Aceitar as exigências de Washington seria visto na China como versão moderna dos tratados desiguais."],
        vuln=["🔴 Levar a analogia do ópio longe demais: há três diferenças estruturais registradas na fonte.",
              "🟠 Tratar a interdependência como garantia de paz — ela é também instrumento de coerção mútua."],
    ),

    # ───────── M06 — Política Externa Brasileira: aplicação e integração ─────────
    # A numeração começa em C015 porque C001–C014 foram emitidos para o módulo de
    # Rússia, retirado do escopo. Nenhum ID é reutilizado.
    dict(
        id="REL-T2-M06-C015", modulo="06-peb-aplicacao-e-integracao",
        assunto="Imperativo estratégico brasileiro reconstruído a partir do corpus: assegurar soberania sobre o território e as Águas Jurisdicionais Brasileiras; manter o entorno sul-americano estável e sem coalizão hostil; garantir o uso do mar de que a economia depende; e ampliar a inserção decisória sem alinhamento automático — com a particularidade de que, ao contrário de EUA, China e demais grandes potências, os objetivos brasileiros são declarados sem hierarquia entre si",
        dep=["REL-T2-M01-C001", "REL-T2-M02-C004", "REL-T2-M03-C002", "REL-T2-M00-C004"],
        exam=True, rap=True, safar=True,
        fontes=["F01:slides \"Dilemas básicos de uma Política Externa\" e \"PEB - Dilemas futuros\"",
                "F02:slide \"Objetivos Nacionais de Defesa\"",
                "F03:slides \"Política Naval\" (fundamento, entorno estratégico e resultados)",
                "AUT:inferência pedagógica — o corpus não enuncia um 'imperativo estratégico brasileiro' em slide próprio; ele é reconstruído dos objetivos, do fundamento da Política Naval e dos dilemas futuros"],
        prio=["A Unidade 2 ensina a ler EUA e China pelo imperativo estratégico; sem o equivalente brasileiro, o aluno não consegue comparar nem responder ao trabalho de T2, que pede a análise de uma nação."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Os quatro itens e a observação de que não há hierarquia declarada.",
              "Permite aplicar ao Brasil a mesma matriz usada para EUA e China.",
              "Integra PND, Política Naval e princípios constitucionais, e expõe a tensão com a crítica sobre Grande Estratégia."),
        ex=["Comparação de estrutura: o imperativo americano é sequência de quatro degraus; o chinês é trilema de três itens; o brasileiro é lista de objetivos sem ordem de prioridade declarada.",
            "É essa ausência de hierarquia que a crítica a partir de Alsina Jr. explora: ter documentos não é ter Grande Estratégia."],
        vuln=["🔴 Apresentar o imperativo brasileiro como se estivesse enunciado em slide: ele é reconstrução declarada.",
              "🟠 Copiar a estrutura americana ou chinesa para o Brasil sem notar a diferença de natureza."],
    ),
    dict(
        id="REL-T2-M06-C016", modulo="06-peb-aplicacao-e-integracao",
        assunto="Alinhamento automático posto à prova: o Acordo Militar de 1952 e a tentativa de obter contrapartidas pela participação na Guerra da Coreia, cujo resultado frustrou a expectativa brasileira; e o contraste com a aliança não-escrita da era Rio Branco, em que a convergência era pontual, negociada e proveitosa para os dois lados",
        dep=["REL-T2-M01-C006", "REL-T2-M01-C009"], exam=True, rap=True, safar=True,
        fontes=["F01:slides \"PEB - República Velha (1889~1930)\" e \"PEB - Pós II GM (1946~1960)\"",
                "F01:Estudo Dirigido 1 da Aula 13 (\"O alinhamento automático com a maior potência sempre apresentou resultados positivos? Exemplifique.\")",
                "F01:Estudo Dirigido 4 da Aula 13 (aliança não-escrita)"],
        prio=["É o Estudo Dirigido 1 do deck, e o professor pede exemplo — resposta sem caso concreto não pontua."],
        prof=(R_ANC, P_APL, C_INT),
        just=("Um caso a favor e um caso contra, com o mecanismo de cada um.",
              "Treina a resposta ao Estudo Dirigido com evidência histórica.",
              "Integra escassez do ativo, urgência e capacidade de barganha como variáveis do alinhamento."),
        ex=["A favor: a aliança não-escrita funcionou porque havia convergência de interesse e o Brasil detinha ativo então escasso.",
            "Contra: em 1952 a contrapartida esperada não veio na medida pretendida — alinhamento não gera crédito automático."],
        vuln=["🔴 Responder 'sim' ou 'não' sem exemplificar: o enunciado exige exemplo.",
              "🟠 Tratar a aliança não-escrita como alinhamento automático: ela era pontual e negociada."],
    ),
    dict(
        id="REL-T2-M06-C017", modulo="06-peb-aplicacao-e-integracao",
        assunto="Integração da América do Sul por duas razões distintas: a razão institucional, ancorada no art. 4º da Constituição e no seu parágrafo único, que determina buscar a integração latino-americana; e a razão pragmática, de estabilizar o entorno, eliminar fontes de atrito com os vizinhos menores e ampliar poder de negociação — conforme a Declaração do Iguaçu, que registra a 'urgente necessidade de que a América Latina reforce seu poder de negociação com o resto do mundo'",
        dep=["REL-T2-M01-C012", "REL-T2-M01-C022"], exam=True, rap=True, safar=True,
        fontes=["F01:slide \"PEB - Constituição de 1988\" (art. 4º e parágrafo único)",
                "F01:Estudo Dirigido 2 da Aula 13 (\"Dê uma razão institucional e outra de política pragmática\")",
                "C01:seção \"Do Mercosul à Unasul\", item 8 da Declaração do Iguaçu"],
        prio=["O Estudo Dirigido pede explicitamente DUAS razões de naturezas diferentes; entregar só uma é perder metade."],
        prof=(R_ANC, P_APL, C_INT),
        just=("As duas razões, com a fonte de cada uma.",
              "Treina a separação entre fundamento normativo e cálculo de interesse.",
              "Integra Constituição, Mercosul, Unasul e a lógica de poder de negociação."),
        ex=["Institucional: o parágrafo único do art. 4º determina buscar a integração econômica, política, social e cultural da América Latina.",
            "Pragmática: Uruguai e Paraguai têm peso econômico reduzido no Mercosul, mas elevado valor geopolítico, porque eliminam fontes de atrito entre Brasil e Argentina."],
        vuln=["🔴 Dar duas razões da mesma natureza.",
              "🟠 Citar o art. 4º sem identificar que a determinação está no PARÁGRAFO ÚNICO."],
    ),
    dict(
        id="REL-T2-M06-C018", modulo="06-peb-aplicacao-e-integracao",
        assunto="ZOPACAS e CPLP como instrumentos do entorno estratégico: a Zona de Paz e Cooperação do Atlântico Sul, de 1986, cujo conteúdo envolve afastar bases ofensivas e evitar a presença de armas nucleares na região, e a Comunidade dos Países de Língua Portuguesa, de 1996, que dá densidade institucional à direção africana; ambas correspondem a dois dos quatro itens do entorno estratégico da Política Naval e são, ao mesmo tempo, pressuposto da PND",
        dep=["REL-T2-M01-C013", "REL-T2-M03-C003", "REL-T2-M02-C005"], exam=True, rap=True, safar=True,
        fontes=["F01:slide \"PEB - Governos pós-1985\" (Sarney, ZOPACAS 1986; FHC, CPLP 1996)",
                "F01:Estudo Dirigido 5 da Aula 13 (\"Por que a ZOPACAS e a CPLP são importantes para o entorno estratégico brasileiro? E para a Marinha?\")",
                "F02:slide \"Alguns pressupostos da PND\"", "F03:slide \"Entorno Estratégico\""],
        prio=["É o Estudo Dirigido que atravessa três módulos do curso e tem parte da resposta em cada um."],
        prof=(R_ANC, P_APL, C_INT),
        just=("Datas, conteúdo e a ligação com o entorno estratégico.",
              "Responde as duas metades da pergunta: para o país e para a Marinha.",
              "Integra política externa, pressuposto de defesa e missão naval em uma só cadeia."),
        ex=["Para a Marinha: um Atlântico Sul sem bases ofensivas e sem armas nucleares reduz a ameaça no espaço onde estão as AJB e por onde passa mais de 95% do comércio exterior.",
            "ZOPACAS é pressuposto da PND, não Objetivo Nacional de Defesa — a distinção continua valendo aqui."],
        vuln=["🔴 Responder só a primeira metade da pergunta e esquecer 'e para a Marinha?'.",
              "🟠 Reclassificar a ZOPACAS como objetivo, e não como pressuposto."],
    ),
    dict(
        id="REL-T2-M06-C019", modulo="06-peb-aplicacao-e-integracao",
        assunto="Herança de Rio Branco em vigor: não-intervenção, abordagem basicamente pacífica para a solução de controvérsias, uso do direito e da negociação como instrumentos preferenciais e fronteiras estabilizadas — heranças que reaparecem, um século depois, como princípios do art. 4º da Constituição e como o duplo fundamento da Política Naval, que exige enfrentamento de antagonismos 'de forma soberana, de acordo com os princípios e fundamentos constitucionais e as normas do Direito Internacional'",
        dep=["REL-T2-M01-C007", "REL-T2-M01-C012", "REL-T2-M03-C002"], exam=True, rap=True, safar=True,
        fontes=["F01:slide \"Principais heranças do Barão do Rio Branco\"",
                "F01:Estudo Dirigido 3 da Aula 13 (\"Por que a herança dos feitos do Barão do Rio Branco é tão importante ainda hoje?\")",
                "F03:slide \"Política Naval\" (fundamento)"],
        prio=["O Estudo Dirigido pergunta por que a herança importa HOJE: a resposta forte mostra a herança convertida em norma vigente."],
        prof=(R_ANC, P_APL, C_INT),
        just=("A lista das heranças e a razão de ainda valerem.",
              "Converte herança histórica em fundamento normativo atual.",
              "Integra Rio Branco, art. 4º e o fundamento da Política Naval numa só cadeia de continuidade."),
        ex=["Fronteiras estabilizadas por via diplomática explicam por que o Brasil é o único grande país sul-americano sem litígio territorial aberto com vizinhos.",
            "A continuidade é normativa, não apenas cultural: os princípios viraram texto constitucional e, depois, fundamento de documento de defesa."],
        vuln=["🟠 Responder pela biografia do Barão em vez do efeito permanente das heranças.",
              "🟡 Tratar 'abordagem pacífica' como pacifismo: o mesmo corpus sustenta dissuasão e fortalecimento do Poder Naval."],
    ),
    dict(
        id="REL-T2-M06-C020", modulo="06-peb-aplicacao-e-integracao",
        assunto="O Brasil entre potência regional e ator global: a leitura de que o país transita da condição de potência regional para a de ator global, especialmente na diplomacia comercial e nas negociações financeiras, e a particularidade de estar, ao contrário de China e Índia, situado no hemisfério sul, longe dos principais polos de poder mundial — situação com desvantagens e com oportunidades inéditas",
        dep=["REL-T2-M01-C015", "REL-T2-M01-C018"], exam=True, rap=True, safar=True,
        fontes=["C01:abertura do capítulo 21 (unidade e diversidade da América Latina; o Brasil como ator global)",
                "F01:slide \"PEB - Dilemas futuros\""],
        prio=["É a moldura que o professor usa para os dilemas futuros e o ponto de partida de qualquer prospecção sobre o Brasil."],
        prof=(R_ANC, P_T3, C_T3),
        just=("A transição declarada e a particularidade geográfica.",
              "Serve de premissa às respostas prospectivas exigidas no trabalho de T2.",
              "Integra distância dos polos de poder, diplomacia comercial e margem de autonomia."),
        ex=["A contraposição chavista entre América Latina e Estados Unidos não faz sentido para o México, ligado ao Nafta, nem para o Brasil, que busca se reposicionar como ator global.",
            "Distância dos polos é desvantagem logística e vantagem de baixa exposição a rivalidade militar direta."],
        vuln=["🟠 Tratar 'ator global' como capacidade militar global: a fonte fala de diplomacia comercial e negociações financeiras.",
              "🟡 Homogeneizar a América Latina: a fonte insiste em unidade E diversidade."],
    ),
    dict(
        id="REL-T2-M06-C021", modulo="06-peb-aplicacao-e-integracao",
        assunto="Limites institucionais do entorno: o Mercosul tem estrutura intergovernamental, com órgãos formados por representantes dos Estados que agem apenas por consenso (Protocolo de Ouro Preto, 1994) e cláusula democrática (Protocolo de Ushuaia, 1998); a entrada da Venezuela, concluída em 2012, expande o bloco para além do Cone Sul, mas lhe retira funcionalidade comercial e política ao torná-lo dependente de consensos; e a Unasul opera com secretariado permanente em Quito e reuniões anuais de chefes de Estado",
        dep=["REL-T2-M01-C022", "REL-T2-M06-C017"], exam=True, rap=True, safar=True,
        fontes=["C01:seção \"Do Mercosul à Unasul\" (Ouro Preto, Ushuaia, adesão venezuelana, IIRSA, Unasul)"],
        prio=["Explica por que a integração avança devagar: a regra de decisão é o limite, não a falta de vontade declarada."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Consenso, cláusula democrática e o efeito da adesão venezuelana.",
              "Permite avaliar criticamente propostas de integração.",
              "Integra desenho institucional, regra de decisão e capacidade de ação coletiva."),
        ex=["Órgãos intergovernamentais por consenso: qualquer membro pode travar a decisão, o que protege soberania e reduz velocidade.",
            "IIRSA definiu eixos de integração física por rodovias, hidrovias e ferrovias — integração de infraestrutura, não de soberania."],
        vuln=["🔴 Descrever o Mercosul como bloco supranacional: ele é intergovernamental e decide por consenso.",
              "🟠 Apresentar a adesão venezuelana apenas como ganho de escala."],
    ),
    dict(
        id="REL-T2-M06-C022", modulo="06-peb-aplicacao-e-integracao",
        assunto="Aplicação da matriz de dez passos ao Brasil e roteiro para o formato de trabalho: ator, objetivo, condicionantes, vulnerabilidades, recursos, instrumentos, cálculo estratégico, lente teórica, contraponto e conclusão, preenchidos com o material dos módulos 01 a 03 e com os fatores facilitadores e dificultadores brasileiros — geografia e bacias internacionais, ausência de ameaça estatal próxima, dependência do mar, orçamento e continuidade estratégica",
        dep=["REL-T2-M00-C003", "REL-T2-M06-C015", "REL-T2-M03-C020"], exam=True, rap=True, safar=True,
        fontes=["F01:Estudo Dirigido 6 da Aula 13 (aplicar um quadrante de cenário ao Brasil, mencionando impactos)",
                "P06:itens ponderados do trabalho de T2 de 2025 (objetivos e desafios geoceanopolíticos, fatores facilitadores e dificultadores, situação atual e perspectivas)",
                "AUT:inferência pedagógica — o preenchimento da matriz para o Brasil é autoria, a partir de conceitos ensinados nos módulos 01 a 03"],
        prio=["É o item de maior peso do único instrumento de T2 documentado, e é a forma mais provável de a PEB ser cobrada por aplicação."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Os dez passos preenchidos para o Brasil, em versão enxuta.",
              "Treina a produção da análise completa exigida pelo trabalho.",
              "Integra os módulos 01, 02 e 03 num único produto avaliável."),
        ex=["Vulnerabilidade: 95% do petróleo, mais de 95% do comércio exterior e 90% do PIB ligados ao litoral e ao mar.",
            "Contraponto: princípios constitucionais de não-intervenção e solução pacífica limitam instrumentos coercitivos que outros atores usam."],
        vuln=["🔴 Descrever o Brasil sem preencher os dez passos: descrição não é análise.",
              "🟠 Omitir o contraponto — a matriz exige leitura concorrente."],
    ),
    dict(
        id="REL-T2-M06-C023", modulo="06-peb-aplicacao-e-integracao",
        assunto="Discursiva de PEB em seis movimentos, com o padrão de correção do corpus: tese, conceito, evidência, nexo causal, nuance ou contraponto e conclusão, sabendo que as provas antigas corrigem por elementos exigidos e registram a crítica na forma 'faltou mencionar X', com crédito parcial",
        dep=["REL-T2-M00-C008", "REL-T2-M01-C017"], exam=True, rap=True, safar=True,
        fontes=["P01:espelho de pontos da P1 de 2024", "P02:correção da SOPA com a crítica por elementos",
                "P05:gabarito da P2 de 2024, com blocos discursivos subdivididos"],
        prio=["Mais da metade da nota das provas escritas do corpus está em discursiva, e o critério de correção é conhecido."],
        prof=(R_ANC, P_APL, C_INT),
        just=("Os seis movimentos e o padrão de correção.",
              "Treina a produção da resposta que o corretor pontua.",
              "Integra tipologia da autonomia, princípios e casos históricos numa resposta única."),
        ex=["O movimento mais esquecido é o nexo causal — e é o que separa resposta satisfatória de resposta de nível MB.",
            "Cada subitem de um bloco discursivo subdividido exige um elemento nomeado: contar os subitens antes de escrever é método, não formalidade."],
        vuln=["🟠 Escrever um bloco único sem separar tese, evidência e nexo.",
              "🟡 Responder pela intuição sem citar o instrumento (tratado, princípio, documento) que sustenta a tese."],
    ),
]
