# -*- coding: utf-8 -*-
"""Matriz canônica — Módulos 03 e 04."""

from conceitos_m00_m02 import R_ANC, P_APL, C_INT, C_T3, P_T3

CONCEITOS = [
    # ───── M03 — Política Marítima, Política Naval, PEM 2040, Economia Azul ─────
    dict(
        id="REL-T2-M03-C001", modulo="03-politica-maritima-naval-e-economia-azul",
        assunto="Política Marítima Nacional (PMN): reeditada pelo Decreto nº 12.481, de 02 de junho de 2025, depois de anos de defasagem em relação à PND e à END e do trabalho do Grupo de Trabalho Interministerial instituído pela Marinha em 2021",
        dep=["REL-T2-M02-C002"], exam=True, rap=True, safar=True,
        fontes=["F03:slide \"Política Marítima Nacional\" (Decreto 12.481, de 02 jun 2025)",
                "A01:PMN defasada desde 1984/1994 e GTI de 2021", "AUT:conflito CF-02 do manifesto"],
        prio=["Único documento do módulo com data recente e conflito documentado entre slide e resumo — o professor atualizou o slide."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Uma data e um mecanismo.",
              "Permite explicar por que a PMN estava fora de passo e o que mudou.",
              "Integra o mecanismo completo: defasagem → GTI 2021 → estudos comparados → decreto de 2025."),
        ex=["O GTI realizou estudos comparativos com políticas marítimas de outros países, alinhando-as aos interesses estratégicos do Brasil."],
        vuln=["🔴 Responder que a PMN 'está defasada': estava. O slide registra a reedição em 2025.",
              "🟠 Confundir PMN (política marítima, interministerial, do Estado) com Política Naval (da Marinha)."],
    ),
    dict(
        id="REL-T2-M03-C002", modulo="03-politica-maritima-naval-e-economia-azul",
        assunto="Política Naval — fundamento: para proteger seu povo e seu patrimônio e ter respaldo para defender os interesses nacionais, o Brasil deve estar preparado para enfrentar ameaças que ponham em risco seus objetivos, e o eventual enfrentamento desses antagonismos deve ocorrer de forma soberana, conforme os princípios e fundamentos constitucionais e as normas do Direito Internacional",
        dep=["REL-T2-M03-C001", "REL-T2-M01-C012"], exam=True, rap=True, safar=True,
        fontes=["F03:slide \"Política Naval\" (parágrafo de abertura)"],
        prio=["É o único texto do corpus que amarra explicitamente uso da força, Constituição e Direito Internacional."],
        prof=(R_ANC, P_T3, C_T3),
        just=("A cláusula de soberania e legalidade em uma frase.",
              "Fornece a moldura normativa de qualquer resposta sobre emprego do Poder Naval.",
              "Integra com o art. 4º da CF/88 e com a CNUDM."),
        ex=["'De forma soberana, de acordo com os princípios constitucionais e as normas do Direito Internacional' é o que distingue dissuasão legítima de projeção revisionista."],
        vuln=["🟠 Ler a Política Naval como autorização genérica ao uso da força.",
              "🟡 Esquecer a dupla amarra: Constituição E Direito Internacional."],
    ),
    dict(
        id="REL-T2-M03-C003", modulo="03-politica-maritima-naval-e-economia-azul",
        assunto="Entorno estratégico brasileiro: América do Sul, Atlântico Sul, países da costa ocidental africana e Antártica",
        dep=["REL-T2-M03-C002", "REL-T2-M01-C013"], exam=True, rap=True, safar=True,
        fontes=["F03:slide \"Política Naval\" (entorno estratégico)", "A01:entorno = América do Sul + Atlântico Sul + Antártica + costa ocidental da África",
                "C02:espaço oceanopolítico proposto por Barbosa Jr."],
        prio=["Definição fechada de quatro itens; é o recorte espacial de todo o módulo e reaparece no PEM 2040."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Quatro itens — âncora de memória obrigatória.",
              "Delimita onde o Brasil tem interesse declarado e por quê.",
              "Compara com o espaço oceanopolítico mais amplo proposto por Barbosa Jr. e explica a diferença."),
        ex=["ZOPACAS e CPLP são os instrumentos institucionais que dão densidade ao entorno na costa ocidental africana.",
            "Barbosa Jr. propõe um espaço oceanopolítico brasileiro ainda mais amplo: Atlântico Norte até 18° N, Caribe, costa oeste da América do Sul, Antártica e costas oeste e leste da África até Moçambique."],
        vuln=["🔴 Omitir a Antártica ou a costa ocidental africana.",
              "🟠 Confundir entorno estratégico (quatro itens, Política Naval) com espaço oceanopolítico (proposta acadêmica de Barbosa Jr., mais amplo)."],
    ),
    dict(
        id="REL-T2-M03-C004", modulo="03-politica-maritima-naval-e-economia-azul",
        assunto="Premissas da Política Naval sobre o sistema internacional: prioridade ao relacionamento com detentores de maiores capacidades tecnológicas; busca de maior representatividade em decisões e em fóruns regionais, inter-regionais e globais; necessidade de alertar a sociedade sobre as ameaças aos interesses nacionais; vocação marítima respaldada pelo extenso litoral, pela magnitude do comércio marítimo e pela importância estratégica e econômica do Atlântico Sul",
        dep=["REL-T2-M03-C003"], exam=True, rap=True, safar=True,
        fontes=["F03:slides \"Política Naval\" (três slides de premissas)"],
        prio=["Liga diretamente a Política Naval à política externa (representatividade) e à Mentalidade Marítima (alertar a sociedade)."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Quatro premissas curtas.",
              "Permite justificar parcerias tecnológicas e a reivindicação de voz em fóruns.",
              "Integra com PROSUB (parceria com a França), CSNU e Mentalidade Marítima."),
        ex=["A prioridade a parceiros tecnologicamente capazes é o que explica o PROSUB com a França, uma relação entre Estados.",
            "'Alertar a sociedade' é a premissa que se converte no programa Mentalidade Marítima."],
        vuln=["🟠 Ler a prioridade tecnológica como alinhamento político.",
              "🟡 Tratar a vocação marítima como afirmação cultural: o slide a respalda em litoral, comércio e valor estratégico do Atlântico Sul."],
    ),
    dict(
        id="REL-T2-M03-C005", modulo="03-politica-maritima-naval-e-economia-azul",
        assunto="Antagonismos que respaldam o fortalecimento do Poder Naval: intensificação de disputas por áreas marítimas, fontes de água doce, alimentos, recursos minerais, biodiversidade e energia; tendência de aumento da demanda por ajuda humanitária e operações de paz; possibilidade de emprego das Forças Armadas para assegurar interesses do Estado e a integridade física e psicológica de nacionais brasileiros",
        dep=["REL-T2-M03-C004"], exam=True, rap=True, safar=True,
        fontes=["F03:slide \"Política Naval\" (intensificação de disputas)",
                "F03:Estudo Dirigido (\"Correlacione a crescente rivalidade interestatal por recursos naturais com as funções do Poder Marítimo\")",
                "P01:questão 15 (exaustão de recursos minerais e combate pelo mar)"],
        prio=["Estudo Dirigido explícito e discursiva já cobrada na P1 cruzando exaustão de recursos com combate pelo mar."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Lista de recursos em disputa.",
              "É a premissa de toda projeção futura sobre conflito marítimo.",
              "Integra com exaustão de recursos minerais, combate pelo mar e a reivindicação de espaços marítimos."),
        ex=["Escassez projetada de minerais críticos aumenta o valor do leito e do subsolo marinhos e, com isso, a disputa por plataforma continental estendida.",
            "A demanda por operações de paz é o que liga o Poder Naval ao apoio à política externa."],
        vuln=["🟠 Listar recursos sem dizer qual mecanismo liga escassez a conflito marítimo.",
              "🟡 Esquecer água doce e alimentos: o slide os inclui expressamente."],
    ),
    dict(
        id="REL-T2-M03-C006", modulo="03-politica-maritima-naval-e-economia-azul",
        assunto="Resultados para a sociedade na Política Naval: contribuir para a Defesa da Pátria, prover a Segurança Marítima, contribuir para a garantia dos poderes constitucionais e da lei e da ordem, cooperar com o desenvolvimento nacional e apoiar a política externa; processos (modernizar a Força Naval, obter a capacidade operacional plena, desenvolver a capacidade cibernética, aprimorar as inteligências estratégica e operacional, ampliar a consciência situacional marítima, aprimorar a gestão de pessoas) e perspectiva institucional (gestão orçamentária, financeira e administrativa)",
        dep=["REL-T2-M03-C002"], exam=True, rap=False, safar=True,
        fontes=["F03:slide \"Política Naval — Resultados para a sociedade / Processos / Institucional\"",
                "A01:missão da MB inclui apoio à política externa"],
        prio=["É o mapa estratégico da Marinha, paralelo ao Mapa Estratégico Setorial do MD — a comparação é cobrança provável."],
        prof=(None, P_T3, C_T3),
        just=("Fora do Rápido: no tempo curto o aluno guarda a missão e os cinco resultados via C002 e C011.",
              "Necessário para comparar o mapa da Marinha com o mapa do Ministério da Defesa.",
              "Integra as três camadas e mostra a simetria com o PESD."),
        ex=["'Apoiar a política externa' aparece tanto na missão da MB quanto no PESD e no Mapa Estratégico Setorial: é o ponto em que defesa e diplomacia se encontram nos três documentos.",
            "Ampliar a consciência situacional marítima nas áreas de interesse da MB é a formulação institucional do que o SisGAAz executa."],
        vuln=["🟠 Confundir o Mapa Estratégico Setorial (MD, quatro perspectivas) com o mapa da Política Naval (MB, três camadas).",
              "🟡 Tratar 'Segurança Marítima' como sinônimo de Defesa da Pátria: são resultados distintos na mesma lista."],
    ),
    dict(
        id="REL-T2-M03-C007", modulo="03-politica-maritima-naval-e-economia-azul",
        assunto="Poder Marítimo e Poder Naval: o Poder Marítimo é o conjunto e COMPREENDE o Poder Naval; seus elementos são Poder Naval, Marinha Mercante, indústria naval, indústria bélica, pessoal, pesquisa e tecnologia, recursos do mar e infraestrutura marítima e hidroviária",
        dep=["REL-T2-M03-C002", "REL-T2-M00-C013"], exam=True, rap=True, safar=True,
        fontes=["F03:slide \"Elementos do Poder Marítimo\" (slide gráfico; texto não extraído)",
                "A01:lista dos elementos e a distinção entre Poder Marítimo e Poder Naval",
                "AUT:lacuna I-04 do manifesto"],
        prio=["A distinção é a base conceitual do módulo; a lista veio do resumo porque o slide é gráfico — procedência declarada."],
        prof=(R_ANC, P_T3, C_T3),
        just=("A relação de contenção (marítimo ⊃ naval) e os oito elementos.",
              "Resolve qualquer questão que troque um termo pelo outro.",
              "Integra com Mahan (Marinha de Guerra + Marinha Mercante) e com os fatores condicionantes."),
        ex=["O Poder Naval é o braço militar operacionalizado pela Marinha; o Poder Marítimo inclui ainda a Marinha Mercante e os demais recursos e capacidades para a soberania e a garantia de interesses nacionais sobre o mar.",
            "A exigência de Mahan — Marinha de Guerra forte integrada a Marinha Mercante forte — é exatamente a lógica do Poder Marítimo."],
        vuln=["🔴 Usar Poder Naval e Poder Marítimo como sinônimos: o naval é subconjunto do marítimo.",
              "🟠 Esquecer os elementos civis (Marinha Mercante, indústria naval, infraestrutura hidroviária) na hora de listar."],
    ),
    dict(
        id="REL-T2-M03-C008", modulo="03-politica-maritima-naval-e-economia-azul",
        assunto="Funções do Poder Marítimo: intercomunicação, defesa marítima e ribeirinha, pesquisa e explotação (exploração e aproveitamento de recursos)",
        dep=["REL-T2-M03-C007"], exam=True, rap=True, safar=True,
        fontes=["F03:slide \"Funções do Poder Marítimo\"", "A01:explotação como exploração e aproveitamento de recursos; defesa das AJB",
                "F03:Estudo Dirigido (\"Correlacione a defesa ribeirinha com o conceito de AJB\")",
                "F03:Estudo Dirigido (\"Correlacione a crescente rivalidade interestatal por recursos naturais com as funções do Poder Marítimo\")"],
        prio=["DOIS Estudos Dirigidos apontam para este conceito: é a cobrança mais anunciada do módulo."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Quatro funções — âncora curta e muito cobrável.",
              "É o que responde às duas correlações pedidas pelo professor.",
              "Integra explotação com disputa por recursos e defesa ribeirinha com a parte interior das AJB."),
        ex=["A defesa ribeirinha alcança as águas interiores, que integram as AJB por definição: é a função que cobre a parte não marítima da jurisdição.",
            "A rivalidade por recursos pressiona diretamente a função de explotação e, por consequência, a de defesa marítima."],
        vuln=["🔴 Confundir explotação (aproveitar economicamente) com exploração (pesquisar, conhecer).",
              "🟠 Esquecer a intercomunicação, que é a função ligada ao transporte e às linhas de comunicação marítimas."],
    ),
    dict(
        id="REL-T2-M03-C009", modulo="03-politica-maritima-naval-e-economia-azul",
        assunto="Fatores condicionantes do Poder Marítimo: mentalidade marítima, capacidade de financiamento, necessidade de desenvolvimento sustentável, capacidade de mobilização e capacidade tecnológica e industrial",
        dep=["REL-T2-M03-C007"], exam=True, rap=True, safar=True,
        fontes=["F03:slide \"Fatores Condicionantes do Poder Marítimo\"", "A01:lista dos condicionantes"],
        prio=["São os 'fatores facilitadores/dificultadores' do trabalho de T2 aplicados ao caso brasileiro."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Cinco condicionantes.",
              "Vira checklist para a parte do trabalho que pede facilitadores e dificultadores.",
              "Integra cada condicionante a um programa e a um gargalo real."),
        ex=["Capacidade de financiamento é o condicionante que explica por que o cronograma do PROSUB se estende até 2038.",
            "Desenvolvimento sustentável entra como condicionante, e não como restrição externa — é o que liga o Poder Marítimo à Economia Azul."],
        vuln=["🟠 Confundir fatores condicionantes (cinco) com elementos (oito) e com funções (quatro) do Poder Marítimo.",
              "🟡 Deixar de fora o desenvolvimento sustentável, que o slide lista expressamente."],
    ),
    dict(
        id="REL-T2-M03-C010", modulo="03-politica-maritima-naval-e-economia-azul",
        assunto="Ameaças do PEM 2040: à soberania nacional, pirataria, pesca ilegal, acessos ilegais a conhecimentos (fauna, flora, biopirataria), crime organizado e conflitos urbanos, terrorismo, ameaças cibernéticas, questões ambientais, desastres naturais e pandemias, e disputa por recursos naturais",
        dep=["REL-T2-M03-C009", "REL-T2-M02-C004"], exam=True, rap=True, safar=True,
        fontes=["F03:slide \"PEM 2040 - Ameaças\"",
                "F03:Estudo Dirigido (\"Qual das ameaças contidas no PEM 2040 é mais difícil de combater, em termos operacionais? Por quê?\")"],
        prio=["Estudo Dirigido pede JULGAMENTO fundamentado sobre a lista — formato de discursiva com resposta aberta e defensável."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Lista de ameaças — âncora de memória.",
              "É o insumo da discursiva de julgamento que o professor anuncia.",
              "Compara com a lista da PND e discute o critério de dificuldade operacional."),
        ex=["A lista do PEM 2040 é mais ampla e mais 'não-estatal' que a da PND (táticas convencionais e irregulares, conflitos urbanos, cibernético, ADM).",
            "Critérios de dificuldade operacional: dispersão espacial, ausência de assinatura identificável, sobreposição com atividade lícita e limites jurídicos de atuação."],
        vuln=["🔴 Trocar a lista do PEM 2040 pela lista de novas ameaças da PND.",
              "🟠 Responder 'a mais difícil é X' sem apresentar critério operacional — a pergunta pede o 'por quê'."],
    ),
    dict(
        id="REL-T2-M03-C011", modulo="03-politica-maritima-naval-e-economia-azul",
        assunto="Conceito Estratégico Marítimo-Naval do PEM 2040: Combate no Mar ≠ Combate pelo Mar; Diplomacia Naval; Defesa Proativa e Defesa Reativa, compondo a Defesa Marítima de Amplo Espectro",
        dep=["REL-T2-M03-C008", "REL-T2-M00-C013"], exam=True, rap=True, safar=True,
        fontes=["F03:slide \"PEM 2040 - Conceito Estratégico Marítimo-Naval\"",
                "A01:combate no mar (batalha naval tradicional) × combate pelo mar (foco estratégico e geopolítico, soberania e controle por meio dos espaços aéreo, cibernético, espacial, marítimo e subaquático)",
                "P03:questão 4 (asserção e razão sobre Combate pelo Mar)", "P01:questão 15"],
        prio=["Cobrado em asserção e razão na SOPA T1 e em discursiva na P1. É o conceito mais armadilhado do módulo."],
        prof=(R_ANC, P_T3, C_T3),
        just=("A distinção em uma linha cada.",
              "Resolve a asserção e razão que o professor já usou.",
              "Integra com multidomínio, com Corbett e com o erro de supor superação total de Mahan."),
        ex=["Combate no Mar: batalhas navais tradicionais com navios, submarinos e aeronaves, num espaço marítimo, para vencer a batalha.",
            "Combate pelo Mar: foco estratégico e geopolítico, soberania e controle do mar por meio dos espaços aéreo, cibernético, espacial, marítimo e subaquático."],
        vuln=["🔴 Concluir que o Combate pelo Mar representa a vitória total de Corbett sobre Mahan e que Mahan 'não é mais considerado'. As duas afirmativas da SOPA T1 eram verdadeiras, mas a segunda NÃO era explicação da primeira — e a parte sobre Mahan é falsa.",
              "🟠 Tratar Defesa Proativa e Reativa como alternativas excludentes: juntas compõem a Defesa Marítima de Amplo Espectro."],
    ),
    dict(
        id="REL-T2-M03-C012", modulo="03-politica-maritima-naval-e-economia-azul",
        assunto="Programas Estratégicos da Marinha: Pessoal, Programa Nuclear da Marinha, Construção do Núcleo do Poder Naval, Obtenção da Capacidade Operacional Plena, SisGAAz, Ampliação da Capacidade de Apoio Logístico para os Meios Operativos e Mentalidade Marítima",
        dep=["REL-T2-M03-C009"], exam=True, rap=True, safar=True,
        fontes=["F03:slide \"Programas Estratégicos\"", "A01:PNM dividido em protótipo de reator e domínio do ciclo do combustível nuclear",
                "F03:Estudo Dirigido (\"Correlacione o conceito de Amazônia Azul com alguns dos Programas Estratégicos da Marinha\")"],
        prio=["Sete programas; Estudo Dirigido explícito pedindo correlação com Amazônia Azul."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Sete programas — âncora de memória de alto retorno.",
              "Cada programa é um instrumento nomeável em qualquer resposta.",
              "Integra cada programa à capacidade que constrói e ao objetivo que serve."),
        ex=["O PNM tem duas frentes: protótipo de reator do submarino de propulsão nuclear e domínio da tecnologia do ciclo do combustível nuclear.",
            "Mentalidade Marítima é programa estratégico, não campanha de comunicação avulsa."],
        vuln=["🔴 Esquecer que Pessoal e Mentalidade Marítima são programas estratégicos, tanto quanto os de material.",
              "🟠 Confundir o PNM (programa) com o setor nuclear (responsabilidade setorial da Marinha na END)."],
    ),
    dict(
        id="REL-T2-M03-C013", modulo="03-politica-maritima-naval-e-economia-azul",
        assunto="Construção do Núcleo do Poder Naval: PROSUB, Programa de Obtenção das Fragatas Classe Tamandaré (PCT), PROHIDRO (meios hidroceanográficos), PROADSUMUS e OCOP",
        dep=["REL-T2-M03-C012"], exam=True, rap=True, safar=True,
        fontes=["F03:slide \"Construção do Núcleo do Poder Naval\"",
                "F03:Estudo Dirigido (\"Por que o PROHIDRO é importante em termos de Política Nacional de Defesa?\")"],
        prio=["Estudo Dirigido pede justificativa do PROHIDRO em termos de PND: exige a cadeia hidrografia → jurisdição → soberania."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Cinco siglas do núcleo.",
              "Permite nomear instrumentos concretos no trabalho e nas discursivas.",
              "Integra o PROHIDRO ao levantamento da plataforma continental e, por aí, à própria definição de AJB."),
        ex=["Hidrografia e oceanografia produzem o dado que sustenta o pleito de plataforma continental estendida — sem levantamento não há jurisdição reconhecida.",
            "O PROHIDRO serve simultaneamente à segurança da navegação, à pesquisa e à afirmação de direitos."],
        vuln=["🟠 Justificar o PROHIDRO apenas pela segurança da navegação, ignorando a ligação com jurisdição e soberania.",
              "🟡 Confundir PCT (fragatas) com PROSUB (submarinos)."],
    ),
    dict(
        id="REL-T2-M03-C014", modulo="03-politica-maritima-naval-e-economia-azul",
        assunto="PROSUB: criado em 2008, parceria entre Brasil e França (relação entre Estados), com objetivo de produzir quatro submarinos convencionais (Riachuelo, Humaitá, Tonelero e Angostura) e o primeiro submarino brasileiro com propulsão nuclear (Álvaro Alberto, previsto para 2038), além do complexo de infraestrutura industrial e de apoio em Itaguaí (estaleiros, Base Naval e UFEM)",
        dep=["REL-T2-M03-C013", "REL-T2-M02-C010"], exam=True, rap=True, safar=True,
        fontes=["F03:slides \"PROSUB\" (dois slides)", "A01:PROSUB como parceria de 2008 com a França"],
        prio=["É o programa mais citável e o exemplo canônico de conversão de parceria externa em capacidade e indústria."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Datas, nomes e o que é o programa.",
              "Instrumento a citar em qualquer resposta sobre autonomia tecnológica.",
              "Integra parceria entre Estados, transferência de tecnologia, BID e dissuasão."),
        ex=["A parceria é 'relação entre Estados', e não contrato comercial comum — o que a torna instrumento de política externa.",
            "O complexo de Itaguaí é BID materializada: estaleiros, Base Naval e Unidade de Fabricação de Estruturas Metálicas."],
        vuln=["🔴 Dizer que o PROSUB produz submarino com armamento nuclear: é PROPULSÃO nuclear.",
              "🟠 Contar cinco submarinos convencionais: são quatro convencionais mais um de propulsão nuclear."],
    ),
    dict(
        id="REL-T2-M03-C015", modulo="03-politica-maritima-naval-e-economia-azul",
        assunto="Programa Fragata Classe Tamandaré: executado pela Emgepron com a SPE Águas Azuis (Thyssenkrupp Marine Systems, Embraer Defesa & Segurança e Atech), com quatro embarcações da primeira fase construídas no Estaleiro Brasil Sul, em Itajaí — Tamandaré (F200) incorporada à frota em abr/2026, Jerônimo de Albuquerque (F201) lançada ao mar em 2025 e em integração e testes, Cunha Moreira (F202) lançada ao mar em jun/2026 e Mariz e Barros (F203) com construção iniciada em jan/2026",
        dep=["REL-T2-M03-C013"], exam=True, rap=False, safar=True,
        fontes=["F03:slides \"Programa Fragata Classe Tamandaré\" (dois slides)"],
        prio=["É o único ponto do corpus com cronograma atualizado até 2026 — indício de que o professor acompanha o programa."],
        prof=(None, P_APL, C_INT),
        just=("Fora do Rápido: o nome do programa basta no tempo curto (coberto por C013).",
              "O arranjo industrial é o exemplo concreto de BID em funcionamento.",
              "Integra arranjo societário, nacionalização e cronograma como evidência de capacidade industrial."),
        ex=["O arranjo Emgepron + SPE com parceiro estrangeiro e empresas nacionais é o modelo de transferência de tecnologia da BID.",
            "Quatro cascos em estágios diferentes ao mesmo tempo é indicador de continuidade de programa, não de evento isolado."],
        vuln=["🟠 Atribuir a construção a estaleiro do Rio de Janeiro: as fragatas são construídas em Itajaí (SC); Itaguaí (RJ) é do PROSUB.",
              "🟡 Tratar 'lançada ao mar' como 'incorporada à frota': são etapas distintas."],
    ),
    dict(
        id="REL-T2-M03-C016", modulo="03-politica-maritima-naval-e-economia-azul",
        assunto="SisGAAz: monitorar e controlar de forma integrada as águas jurisdicionais brasileiras e as áreas internacionais de responsabilidade para operações de Socorro e Salvamento (SAR), a fim de agilizar o ciclo decisório e assegurar capacidade de pronta resposta a qualquer ameaça, emergência, agressão ou ilegalidade; integra AIS, LRIT, VTS, radar, satélite, SIMMAP e SIR",
        dep=["REL-T2-M03-C012", "REL-T2-M02-C008", "REL-T2-M02-C009"], exam=True, rap=True, safar=True,
        fontes=["F03:slide \"SisGAAz\"", "F03:slide com os sistemas integrados (AIS, LRIT, VTS, SIMMAP, SIR)",
                "A01:SisGAAz e a lógica de pronta-resposta; relação com o monitoramento do mar"],
        prio=["É a ponte operacional entre AJB, tarefas básicas do Poder Naval e Amazônia Azul — pedida por Estudo Dirigido."],
        prof=(R_ANC, P_T3, C_T3),
        just=("O que é e para que serve, em uma frase.",
              "É o instrumento a citar em qualquer resposta sobre consciência situacional.",
              "Integra o alcance para além das AJB (áreas SAR internacionais) e a cadeia dado → decisão → resposta."),
        ex=["O objetivo declarado é 'agilizar o ciclo decisório': o valor do sistema está na velocidade da decisão, não no volume de dados.",
            "O alcance inclui áreas internacionais de responsabilidade SAR, que estão FORA das AJB."],
        vuln=["🔴 Restringir o SisGAAz às AJB: ele cobre também áreas internacionais de responsabilidade SAR.",
              "🟠 Tratá-lo como sistema de vigilância apenas, ignorando socorro e salvamento."],
    ),
    dict(
        id="REL-T2-M03-C017", modulo="03-politica-maritima-naval-e-economia-azul",
        assunto="Ampliação da capacidade de apoio logístico: em atendimento à END, o País deve estabelecer nas proximidades da foz do rio Amazonas um complexo naval de uso múltiplo, que ampliará a capacidade de negação do uso do mar, de controle de áreas marítimas e de projeção de poder, com ênfase nas operações e ações de guerra naval no Atlântico Sul, prioridade para o litoral norte e nordeste, e garantindo a defesa em profundidade da foz do rio Amazonas",
        dep=["REL-T2-M03-C012", "REL-T2-M02-C009"], exam=True, rap=True, safar=True,
        fontes=["F03:slide \"Ampliação da Capacidade de Apoio Logístico para os Meios Operativos\""],
        prio=["Único ponto do corpus em que três das quatro tarefas básicas do Poder Naval aparecem juntas, ligadas a uma decisão geográfica."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Onde, por quê e o que amplia.",
              "É o melhor exemplo de decisão de infraestrutura justificada por tarefa básica.",
              "Integra geografia (foz do Amazonas), tarefas básicas, entorno estratégico e proteção e integração da Amazônia."),
        ex=["A escolha da foz do Amazonas conecta defesa marítima, Amazônia Azul e o pressuposto da PND de proteção e integração da Amazônia brasileira.",
            "'Defesa em profundidade' significa impor custo ao adversário em camadas sucessivas antes de ele alcançar o objetivo."],
        vuln=["🟠 Ler o complexo como obra logística apenas: o slide o liga expressamente a negação, controle e projeção.",
              "🟡 Deslocar a prioridade para o litoral sul: o slide prioriza norte e nordeste."],
    ),
    dict(
        id="REL-T2-M03-C018", modulo="03-politica-maritima-naval-e-economia-azul",
        assunto="Mentalidade Marítima: programa que atua em três níveis de inserção — comunicação estratégica para avivar a consciência coletiva de que o Brasil começou pelo mar e com ele deve buscar sua realização plena; atuação junto a atores governamentais para promover pensamento estratégico marítimo autóctone e políticas públicas assertivas; e foco no principal elemento e núcleo maduro do Poder Marítimo, os homens e mulheres do mar",
        dep=["REL-T2-M03-C009", "REL-T2-M03-C012"], exam=True, rap=True, safar=True,
        fontes=["F03:slide \"Mentalidade Marítima\"",
                "F03:Estudo Dirigido (\"Por que a Mentalidade Marítima é um conceito tão importante para a Marinha?\")",
                "C02:formação de recursos humanos e difusão em nível escolar; programas análogos na França e no Chile"],
        prio=["Estudo Dirigido explícito e conceito que aparece duas vezes na aula (condicionante e programa)."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Três níveis e a razão do programa.",
              "Responde diretamente ao Estudo Dirigido.",
              "Integra com o argumento de More sobre formação de pessoal e difusão escolar, e com o condicionante de financiamento."),
        ex=["O mecanismo causal: sem mentalidade marítima, não há apoio social; sem apoio social, não há orçamento; sem orçamento, o condicionante de financiamento inviabiliza os programas.",
            "More propõe difusão nos ensinos fundamental e médio, citando França e Chile como referências."],
        vuln=["🟠 Reduzir Mentalidade Marítima a divulgação institucional: ela é condição de viabilidade orçamentária e política.",
              "🟡 Esquecer o terceiro nível (os homens e mulheres do mar como núcleo maduro do Poder Marítimo)."],
    ),
    dict(
        id="REL-T2-M03-C019", modulo="03-politica-maritima-naval-e-economia-azul",
        assunto="Amazônia Azul: designação do oceano do Brasil que dá dimensão pública às AJB e articula riqueza, jurisdição e responsabilidade de defesa",
        dep=["REL-T2-M02-C008", "REL-T2-M03-C016"], exam=True, rap=True, safar=True,
        fontes=["F03:slide \"SisGAAz\" (Sistema de Gerenciamento da Amazônia Azul)",
                "F02:Estudo Dirigido (\"Correlacione alguma das tarefas básicas do Poder Naval com o conceito de Amazônia Azul\")",
                "C02:introdução (a Marinha propôs o termo Amazônia Azul para ilustrar as riquezas do oceano do Brasil)",
                "A01:AJB como Amazônia Azul brasileira"],
        prio=["Aparece em Estudo Dirigido de DOIS módulos (Aulas 14 e 15). É o conceito-ponte do curso na parte brasileira."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Um termo que carrega AJB, riqueza e dever de defesa.",
              "É o vocabulário obrigatório das duas correlações pedidas pelo professor.",
              "Integra jurisdição (AJB), economia (Economia Azul), monitoramento (SisGAAz) e tarefas básicas."),
        ex=["Amazônia Azul é o nome público; AJB é o conceito jurídico. O primeiro comunica, o segundo delimita.",
            "A correlação mais direta: controle de área marítima só é possível sobre um espaço monitorado, e o SisGAAz é o Sistema de Gerenciamento da Amazônia Azul."],
        vuln=["🔴 Usar Amazônia Azul como se fosse definição jurídica: a definição é a de AJB.",
              "🟠 Responder a correlação sem escolher UMA tarefa básica e explicar o nexo."],
    ),
    dict(
        id="REL-T2-M03-C020", modulo="03-politica-maritima-naval-e-economia-azul",
        assunto="Economia Azul e os números do mar brasileiro: do mar vêm cerca de 95% do petróleo, 80% do gás natural e 45% do pescado produzidos no País, e por rotas marítimas escoam mais de 95% do comércio exterior; nos cerca de 8.500 km de faixa litorânea concentram-se 80% da população, 90% do PIB e os principais destinos turísticos; o conceito traz reflexões sobre a contribuição dos oceanos à economia e sobre a necessidade de garantir a sustentabilidade ambiental e ecológica dos espaços marítimos, para que futuras gerações também usufruam os recursos",
        dep=["REL-T2-M03-C019", "REL-T2-M03-C008"], exam=True, rap=True, safar=True,
        fontes=["F03:slides \"Economia Azul\" (três slides)",
                "F03:Estudo Dirigido (\"o conceito de Economia Azul é fundamental para as atribuições da Marinha? Por quê?\")",
                "A01:números da Economia Azul"],
        prio=["Os cinco percentuais são o dado mais cobrável do módulo e sustentam qualquer argumento sobre prioridade do mar."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Cinco números que ganham qualquer discussão.",
              "Converte dado em argumento: dependência mede vulnerabilidade.",
              "Integra a tensão entre explotação e sustentabilidade e o dever intergeracional."),
        ex=["O mecanismo: 95% do comércio exterior pelo mar significa que interromper o tráfego marítimo é interromper a economia nacional.",
            "A tensão declarada: a mesma dinâmica que instrumentaliza o uso dos recursos vivos e não vivos provoca crescente preocupação com a saúde dos oceanos."],
        vuln=["🔴 Trocar os percentuais entre si (95% petróleo, 80% gás, 45% pescado, mais de 95% do comércio exterior).",
              "🟠 Apresentar Economia Azul como sinônimo de exploração econômica: o conceito é inseparável da sustentabilidade."],
    ),
    dict(
        id="REL-T2-M03-C021", modulo="03-politica-maritima-naval-e-economia-azul",
        assunto="Oceanopolítica aplicada ao Brasil: o oceano no ciclo vital do Estado; fronteira integral de Martinez Busch (linha permanente onde se choca o interesse oposto dos Estados — há tantas fronteiras quantos interesses, e quanto mais desenvolvido o Estado, mais fronteiras e mais poder exigido para mantê-las); o Mar Presencial chileno como tese que desafia o limite das 200 MN; o deslocamento dos conflitos do plano terrestre (land-based) para o oceânico (sea-based); assimetria de conhecimento técnico-científico como fonte de conflito",
        dep=["REL-T2-M00-C012", "REL-T2-M03-C020"], exam=True, rap=False, safar=True,
        fontes=["C02:seções 2, 3, 3.1, 3.2 e 3.3", "C02:princípios gerais de Busch",
                "P01:questão 4 (correlação Geopolítica × Oceanopolítica)"],
        prio=["Leitura complementar autorizada da linha oceanopolítica; sustenta o termo 'geoceanopolítico' do trabalho de T2."],
        prof=(None, P_T3, C_T3),
        just=("Fora do Rápido: a distinção operacional já está em C012.",
              "Fornece a moldura teórica para objetivos geoceanopolíticos.",
              "Integra fronteira integral, Mar Presencial, extensão da plataforma e a redução da Área como espaço comum da humanidade."),
        ex=["Quando um Estado costeiro amplia a plataforma continental além das 200 MN, diminui a Área — espaço comum da humanidade que rende royalties inclusive a Estados sem litoral. Isso é potencialmente gerador de conflito.",
            "O restabelecimento da Quarta Frota dos EUA para o Caribe e a América do Sul e Central, em 2008, é lido por More como sinal do valor atribuído à mobilização de meios navais."],
        vuln=["🟠 Tratar a fronteira integral como linha geográfica: ela é definida por interesse, não por coordenada.",
              "🟡 Supor que ampliar a plataforma continental não afeta terceiros — reduz a Área e o benefício comum."],
    ),

    # ─────────────────────── M04 — Estados Unidos ────────────────────────
    dict(
        id="REL-T2-M04-C001", modulo="04-estados-unidos",
        assunto="Formação geográfica dos EUA: treze colônias ao leste, planícies centrais férteis com os rios Mississippi e Missouri, Montes Apalaches entre as colônias e as planícies, Montanhas Rochosas entre as planícies e o Pacífico, e o sistema de rios, canais e eclusas que liga o Mississippi aos Grandes Lagos (pelo rio Illinois) e ao São Lourenço, com escoamento pelo porto de Nova Orleans no Golfo do México",
        dep=["REL-T2-M00-C003"], exam=True, rap=True, safar=True,
        fontes=["F04:slides \"EUA (fonte: GPF)\" (mapas; texto não extraído)", "F04:mapa \"Estados Unidos: expansão territorial\"",
                "A01:seção ESTADOS UNIDOS (leitura dos mapas), AUT:lacuna I-04"],
        prio=["Sem a geografia não se explica por que a compra da Louisiana foi decisiva nem por que a expansão foi para oeste."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Três elementos de relevo e uma via fluvial.",
              "Transforma geografia em explicação de decisão política.",
              "Integra relevo, hidrografia, porto e mercado interno."),
        ex=["Planície + rio navegável = produção escoável: é o que torna a Louisiana o alvo prioritário, e não um território qualquer.",
            "A conexão Mississippi–Illinois–Grandes Lagos–São Lourenço dá ao interior duas saídas para o mar."],
        vuln=["🟠 Tratar a expansão como ideologia pura: o relevo e os rios explicam a direção e a velocidade.",
              "🟡 Situar os Apalaches entre as planícies e o Pacífico — ali estão as Rochosas."],
    ),
    dict(
        id="REL-T2-M04-C002", modulo="04-estados-unidos",
        assunto="Expansão territorial dos EUA por compra, tratado e guerra: Louisiana comprada da França (1803, 15 milhões de dólares), tratados com o Reino Unido (1818, 1842, 1846), Flórida comprada da Espanha (1819, 5 milhões), Texas tomado do México (1845, dando início à guerra), terras obtidas com a vitória sobre o México (1848), compra do México (1853, 10 milhões), Alasca comprado da Rússia (1867, 7 milhões) e Havaí anexado após disputa com o Japão (1898)",
        dep=["REL-T2-M04-C001"], exam=True, rap=True, safar=True,
        fontes=["F04:mapa \"Estados Unidos: expansão territorial\" (legenda com datas e valores)",
                "A01:Corolário Polk, Tratado de Guadalupe-Hidalgo, Oregon por tratado", "C01:Corolário Polk"],
        prio=["A legenda do mapa é a fonte mais densa de dados nominais do módulo, e os instrumentos usados (compra, tratado, guerra) são a lição."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Datas e instrumentos em bloco.",
              "Ensina que a expansão combinou três instrumentos, não um só.",
              "Integra com Destino Manifesto, Corolário Polk e a tese da fronteira."),
        ex=["Oregon veio por tratado com o Reino Unido; o sudoeste veio por guerra com o México (Tratado de Guadalupe-Hidalgo).",
            "Corolário Polk: uso de diplomacia E de meios militares para a expansão efetiva do território."],
        vuln=["🔴 Dizer que a expansão foi apenas militar ou apenas por compra: foi pelos três instrumentos.",
              "🟠 Confundir Corolário Polk (1845, expansão) com Corolário Roosevelt (1904, poder de polícia internacional)."],
    ),
    dict(
        id="REL-T2-M04-C003", modulo="04-estados-unidos",
        assunto="Destino Manifesto e American way of life: noção de que as ideias e conceitos do experimento político norte-americano seriam universais e deveriam ser disseminados; até então só havia república em pequenos territórios, e os EUA foram a primeira com grande extensão; o liberalismo como pedra de toque da política externa, especialmente depois da ascensão ao status de potência hegemônica; e a dificuldade — mas não a impossibilidade — de incorporar críticas e novos estilos por ser um 'mundo em si'",
        dep=["REL-T2-M04-C002"], exam=True, rap=True, safar=True,
        fontes=["F04:slide \"EUA - Destino Manifesto (embasamento)\"", "A01:Destino Manifesto e American way of life como soft power",
                "C03:tese da fronteira de Turner e o westering"],
        prio=["É o conceito identitário que o professor contrapõe ao Mandato Divino chinês; a P1 registra 'questões possíveis: relacionar destino manifesto com american way of life; relacionar destino manifesto com doutrina monroe'."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Definição e a razão de ser.",
              "É a variável ideacional que explica a forma da hegemonia americana.",
              "Integra com construtivismo, com soft power e com a tese da fronteira de Turner."),
        ex=["American way of life: expressão cultural, econômica e social do soft power americano, surgida em meados dos anos 1940, representando capitalismo, democracia e liberalismo.",
            "Turner: com o fechamento da fronteira interna, a lógica expansionista se desloca do espaço continental para o marítimo e externo — é a ponte para Mahan."],
        vuln=["🔴 Ler Destino Manifesto como sinônimo de Doutrina Monroe: um é embasamento ideacional, a outra é instrumento de política externa.",
              "🟠 Tratar o Destino Manifesto como retórica vazia: ele opera como variável construtivista, moldando o que se considera interesse legítimo."],
    ),
    dict(
        id="REL-T2-M04-C004", modulo="04-estados-unidos",
        assunto="Doutrina Monroe (1823) e seus corolários: 'a América para os americanos'; declaração unilateral, não pacto negociado nem tratado; dupla natureza simultaneamente anticolonial e hegemonista; aquisição de territórios, aviso aos europeus sobre esfera de influência, guerras com Grã-Bretanha e México, consolidação de fronteiras e áreas próximas; Corolário Polk (1845) e Corolário Roosevelt (1904, poder de polícia internacional, Big Stick, Caribe como 'lago americano')",
        dep=["REL-T2-M04-C003"], exam=True, rap=True, safar=True,
        fontes=["F04:slide \"EUA - Expansão, Doutrina Monroe\"", "C01:p. 344-346 (dupla natureza, Polk, Roosevelt, Big Stick)",
                "C03:texto da mensagem de 1823 e do Corolário de 1904", "A01:Santa Aliança como razão da doutrina"],
        prio=["Conceito mais integrador do módulo: liga século XIX, Guerra Fria e conjuntura de 2025-2026."],
        prof=(R_ANC, P_T3, C_T3),
        just=("A fórmula, a data e as duas naturezas.",
              "É a lente com que se lê qualquer intervenção hemisférica.",
              "Integra Santa Aliança, hegemonia britânica nos mares, corolários e releituras contemporâneas."),
        ex=["Magnoli: na prática, a independência das antigas colônias espanholas era assegurada pela hegemonia britânica nos mares; a declaração de 1823 indicava a ambição, não a capacidade.",
            "Corolário Roosevelt: 'irregularidades crônicas... podem exigir intervenção por alguma nação civilizada, e no Hemisfério Ocidental... o exercício de um poder de polícia internacional'.",
            "Kissinger: manter o poder militar de outros continentes fora do Hemisfério Ocidental sempre foi princípio sagrado da política externa americana."],
        vuln=["🔴 Chamar a Doutrina Monroe de tratado ou pacto: é declaração UNILATERAL.",
              "🔴 Ler a doutrina só como anticolonial: sua força e permanência vêm da dupla natureza, anticolonial E hegemonista.",
              "🟠 Atribuir o 'lago americano' a Monroe: ele resulta do Corolário Roosevelt e da abertura do Canal do Panamá."],
    ),
    dict(
        id="REL-T2-M04-C005", modulo="04-estados-unidos",
        assunto="Guerra Civil americana (1861-1865) e suas consequências estratégicas: estabelecimento de um modelo hegemônico industrial-financeiro com a vitória do Norte sobre o Sul, ampliação do mercado interno, fortalecimento do mercado financeiro e inovações industriais",
        dep=["REL-T2-M04-C002"], exam=True, rap=True, safar=True,
        fontes=["F04:slide \"EUA - Guerra Civil\"", "A01:vitória do modelo econômico-financeiro do Norte"],
        prio=["Explica como os EUA passaram de território extenso a potência econômica, condição de toda a projeção posterior."],
        prof=(R_ANC, P_APL, C_INT),
        just=("Quatro consequências em uma linha.",
              "Fornece o elo entre expansão territorial e capacidade de projeção.",
              "Integra com Mahan: só uma economia industrial-financeira sustenta esquadra oceânica."),
        ex=["Norte industrializado com mão de obra assalariada × Sul latifundiário com mão de obra escrava: a vitória define o modelo econômico do país.",
            "Sem mercado interno ampliado e mercado financeiro forte não haveria Grande Esquadra Branca nem Canal do Panamá."],
        vuln=["🟠 Tratar a Guerra Civil como episódio interno sem consequência internacional.",
              "🟡 Esquecer que ela é pré-requisito material da virada marítima de 1890-1914."],
    ),
    dict(
        id="REL-T2-M04-C006", modulo="04-estados-unidos",
        assunto="Virada marítima e expansão geopolítica: Mahan, a Grande Esquadra Branca, o Canal do Panamá e as intervenções na América Latina; Spykman e a importância do domínio sobre a América Latina para ter presença na Rimland",
        dep=["REL-T2-M04-C005", "REL-T2-M00-C013", "REL-T2-M00-C014"], exam=True, rap=True, safar=True,
        fontes=["F04:slide \"Expansão geopolítica\"", "C03:Mahan 1890, Guerra Hispano-Americana de 1898, Roosevelt e o canal",
                "A01:Mahan (pontos de estrangulamento, bases navais, linhas de comunicação, interligação das marinhas leste-oeste) e Spykman (consolidar as Américas antes de conter a potência euroasiática)"],
        prio=["É o núcleo teórico do módulo e a lente mais provável de instrumentalização no trabalho de T2."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Dois autores e quatro instrumentos.",
              "É a lente que explica a estrutura de bases e alianças dos EUA.",
              "Integra o mecanismo Turner → Mahan → Roosevelt → canal → mare nostrum."),
        ex=["A secessão do Panamá em 1903 foi estimulada e garantida com navios de guerra depois da recusa colombiana; dias depois vinha a posse do canal.",
            "Após a inauguração em 1914, o Caribe se transformou em espécie de mare nostrum dos EUA — primeira condição de grandeza de um império marítimo emergente."],
        vuln=["🔴 Inverter a ordem de Spykman: primeiro consolidar as Américas, DEPOIS conter a potência eurasiática.",
              "🟠 Tratar o Canal do Panamá como obra de engenharia: é instrumento de bioceanidade e de projeção."],
    ),
    dict(
        id="REL-T2-M04-C007", modulo="04-estados-unidos",
        assunto="Construção da hegemonia: potência econômica já no início do século XX, consolidação no pós-II Guerra, Guerra Fria e a expectativa pós-Guerra Fria de um longo ciclo de paz global; o liberalismo como forma de política externa materializado em GATT (1947) e OMC, ONU, FMI e Banco Mundial (Bretton Woods, 1944) com o BIRD financiando a reconstrução da Europa e do Japão",
        dep=["REL-T2-M04-C006"], exam=True, rap=True, safar=True,
        fontes=["F04:slide \"Hegemonia Mundial\"", "A01:liberalismo como forma de política externa (comércio, multilateralismo, instituições financeiras)",
                "F04:slide \"2. Liberais\""],
        prio=["É o exemplo canônico da ambivalência institucional: instituições como cooperação e como instrumento de hegemonia."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Quatro marcos e três famílias de instituições.",
              "É o material da clínica sobre instituições.",
              "Integra a leitura liberal e a leitura realista do MESMO conjunto institucional."),
        ex=["Leitura liberal: GATT/OMC reduzem incerteza e ampliam ganhos mútuos. Leitura realista: elas codificam regras favoráveis a quem as escreveu.",
            "O BIRD financiou a reconstrução da Europa e do Japão com juros baixos e assistência técnica — cooperação que também produziu alinhamento."],
        vuln=["🔴 Classificar como liberal qualquer política que crie instituição: a criação pode servir a imperativo realista.",
              "🟠 Datar Bretton Woods em 1947 (é 1944) ou o GATT em 1944 (é 1947)."],
    ),
    dict(
        id="REL-T2-M04-C008", modulo="04-estados-unidos",
        assunto="Declínio absoluto × declínio relativo: os EUA passaram de 27% do PIB mundial em 1945 para cerca de 20% hoje, o que caracteriza declínio RELATIVO; permanecem com supremacia militar (a Marinha equivale às 12 maiores marinhas seguintes, das quais 9 são aliadas), supremacia financeira (o dólar como moeda-padrão), liderança em inovação tecnológica e capital humano (complexo industrial-militar-acadêmico, política da tripla hélice) e mercado de trabalho flexível que acelera a superação de crises",
        dep=["REL-T2-M04-C007"], exam=True, rap=True, safar=True,
        fontes=["F04:slide \"Declínio?\"", "A01:declínio relativo, tripla hélice, revolução industrial 4.0",
                "C03:considerações finais (hegemonia em declínio, coerção em vez de consenso)"],
        prio=["É a distinção conceitual mais cobrável do módulo e a que produz alternativas parcialmente verdadeiras."],
        prof=(R_ANC, P_T3, C_T3),
        just=("A distinção e os cinco indicadores de força.",
              "Permite recusar tanto o diagnóstico de colapso quanto o de invulnerabilidade.",
              "Integra a leitura de declínio com a mudança de método (coerção em vez de consenso) proposta pelo artigo de 2026."),
        ex=["O dado de 27% → 20% mede perda de participação relativa em um mundo que cresceu, não redução absoluta de poder.",
            "Das 12 maiores marinhas seguintes, 9 são aliadas: a aliança multiplica o poder relativo e é ela que o declínio ameaçaria primeiro."],
        vuln=["🔴 Concluir declínio absoluto a partir da queda de participação no PIB mundial.",
              "🔴 Esquecer a cláusula das alianças: a supremacia naval americana é potencializada por 9 marinhas aliadas entre as 12 seguintes.",
              "🟠 Tratar o status do dólar como garantido: o próprio slide traz um ponto de interrogação."],
    ),
    dict(
        id="REL-T2-M04-C009", modulo="04-estados-unidos",
        assunto="Imperativo estratégico dos EUA em quatro degraus: hegemonia na América do Norte; depois América do Sul e Caribe; domínio dos oceanos que banham a costa leste e a costa oeste, vistos como instrumento de projeção de poder e de livre comércio; e, estrategicamente, evitar o surgimento de uma potência hegemônica na Eurásia",
        dep=["REL-T2-M04-C008", "REL-T2-M00-C004", "REL-T2-M00-C014"], exam=True, rap=True, safar=True,
        fontes=["F04:slide \"EUA - Imperativo Estratégico\"", "A01:IMPERATIVO ESTRATÉGICO DOS EUA (quatro itens numerados)",
                "P03:questão 10 (asserção e razão sobre Spykman e o pré-requisito sul-americano)"],
        prio=["É o conceito central do módulo, já cobrado em asserção e razão, e a chave da comparação com a China e com o Brasil."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Quatro degraus na ordem certa.",
              "É o que explica por que a América do Sul importa e por que a Eurásia é a preocupação final.",
              "Integra com Spykman, com a Doutrina Monroe e com os cenários asiáticos."),
        ex=["A ordem é hierárquica e sequencial: sem retaguarda hemisférica segura não há projeção global sustentável.",
            "Historicamente os EUA sempre buscaram evitar que uma potência ascendesse à condição de superpotência eurasiática: Alemanha nas duas guerras, URSS na Guerra Fria, China hoje."],
        vuln=["🔴 Marcar 'a afirmativa 2 é a explicação COMPLETA' quando o controle da América do Sul e do Caribe é apenas UM dos quatro degraus.",
              "🟠 Tratar os oceanos apenas como barreira defensiva: o slide os apresenta como instrumento de projeção e de livre comércio."],
    ),
    dict(
        id="REL-T2-M04-C010", modulo="04-estados-unidos",
        assunto="Âmbito multidomínio e A2/AD na perspectiva americana: operações multidomínio como prioridade das Forças Armadas dos EUA para o século XXI, e o antiacesso/negação de área (A2/AD) como o problema a resolver; interoperabilidade interna (entre forças de um país) e externa (entre forças de países diferentes)",
        dep=["REL-T2-M04-C009"], exam=True, rap=True, safar=True,
        fontes=["F04:slide \"Âmbito multidomínio\"", "F04:slide \"Prioridades para a Defesa no Século XXI – FFAA EUA / A2/AD\"",
                "P03:questão 5 (asserção e razão sobre interoperabilidade e multidomínio)",
                "C06:analogia entre espaço sideral e oceano", "P06:item 5 do trabalho (operações de interoperabilidade externa)"],
        prio=["A SOPA T1 cobrou interoperabilidade e multidomínio em asserção e razão, e o trabalho de T2 exige três operações de interoperabilidade externa."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Duas definições e a distinção interna/externa.",
              "É o vocabulário da parte do trabalho que pede operações concretas.",
              "Integra com o A2/AD chinês, com a astropolítica e com a analogia do espaço como novo oceano."),
        ex=["Raramente uma batalha será ganha com o uso de apenas uma força ou, em conflito de maior escala, sem alianças táticas ou estratégicas.",
            "Bartosiak: só grandes potências navegam no espaço; países sem essa capacidade se parecem com países sem litoral — e, sem árbitro, quem tem acesso pode negá-lo aos outros."],
        vuln=["🔴 Trocar interoperabilidade interna por externa.",
              "🟠 Tratar multidomínio como somatório de forças em vez de integração entre domínios (terrestre, marítimo, aéreo, cibernético, espacial)."],
    ),
    dict(
        id="REL-T2-M04-C011", modulo="04-estados-unidos",
        assunto="Estrutura de força naval dos EUA como indicador de estratégia: meta de 355 navios (2016) e de 381 navios (2023); a principal alteração recente é a incorporação de embarcações autônomas, com metas de força somando centenas de vetores não tripulados; e a discussão sobre porta-aviões leves e a redução proporcional de grandes combatentes de superfície",
        dep=["REL-T2-M04-C010"], exam=True, rap=True, safar=True,
        fontes=["F04:slide \"Previsão sobre a dimensão da Marinha dos EUA (segundo o Congresso dos EUA)\" e tabelas",
                "C04:sumário executivo (metas de 321 a 404 navios tripulados e 45 a 204 grandes veículos não tripulados)"],
        prio=["O slide traz as tabelas completas; a mudança de composição (menos navios grandes, mais pequenos e não tripulados) é uma inferência de doutrina, não um detalhe."],
        prof=(R_ANC, P_APL, C_INT),
        just=("No Rápido em versão mínima: as duas metas, a incorporação de vetores autônomos e a inferência de dispersão contra A2/AD — exigido pelo simulado final, que é o mesmo instrumento nas três modalidades.",
              "A composição da frota é evidência material do imperativo estratégico.",
              "Integra estrutura de força, A2/AD e restrição orçamentária."),
        ex=["A nova arquitetura prevê menor proporção de navios grandes, maior proporção de pequenos e um terceiro elemento de grandes veículos não tripulados.",
            "Mais plataformas pequenas e autônomas é resposta doutrinária ao A2/AD: dispersar para sobreviver a mísseis de longo alcance."],
        vuln=["🟠 Decorar números sem extrair a doutrina: o que se cobra é o que a composição revela.",
              "🟡 Tratar a meta de 355 navios como número atual da frota."],
    ),
    dict(
        id="REL-T2-M04-C012", modulo="04-estados-unidos",
        assunto="Mandato Divino × Destino Manifesto e a questão da 'Doutrina Monroe chinesa': se os EUA sairiam da Ásia como o Reino Unido saiu da América Latina no século XIX; o papel do Japão e da Índia; e por que a analogia é imperfeita — em 1823 o centro econômico do mundo era a Europa e afastar potências europeias era mais fácil; hoje a Ásia é a região mais dinâmica do planeta e, por isso, é difícil fazer os EUA saírem",
        dep=["REL-T2-M04-C009", "REL-T2-M04-C003"], exam=True, rap=True, safar=True,
        fontes=["F04:slide \"Cenários para o Leste Asiático\"", "F04:slide \"Mandato Divino X Destino Manifesto\"",
                "A01:análise da assimetria entre 1823 e hoje; 'nunca na história da Ásia, China, Índia e Japão foram potências ao mesmo tempo'"],
        prio=["É a pergunta-problema com que o professor fecha a Aula 16 e a ponte direta para o módulo de China."],
        prof=(R_ANC, P_T3, C_T3),
        just=("A analogia e o motivo de ela falhar.",
              "Treina o raciocínio contrafactual que o professor usa.",
              "Integra as três variáveis: dinamismo regional, simultaneidade de potências asiáticas e legitimidade do PCC."),
        ex=["A alternativa discutida: os EUA recuam para a Segunda Cadeia (Austrália, Guam, ilhas da Oceania) e a China ocupa a Primeira Cadeia.",
            "Três problemas dessa alternativa: o que garante que a China pararia na Primeira Cadeia; se parar, o PCC perde legitimidade no seu projeto; e a Revolução Industrial 4.0 e o envelhecimento populacional mudam as contas."],
        vuln=["🔴 Aceitar a analogia com a retirada britânica da América Latina sem a ressalva do dinamismo econômico asiático.",
              "🟠 Esquecer que o problema não é só de capacidade americana, mas de legitimidade interna chinesa."],
    ),
    dict(
        id="REL-T2-M04-C013", modulo="04-estados-unidos",
        assunto="Cenários para o Leste e Sudeste Asiáticos: duas forças-motrizes (nível de expansão da economia chinesa e capacidade dos EUA de forjar e manter um arco de alianças para conter a China) geram quatro cenários — Cria Cuervos (China desacelera, arco forte, aliados asiáticos deixam de ver necessidade da presença ostensiva americana e desenvolvem políticas nacionalistas contrárias aos interesses dos EUA), Concerto Asiático (arco forte com China forte, EUA como potência externa num equilíbrio delicado e instável), Casa sem Dono (China desacelera e presidente isolacionista retira tropas, potências asiáticas se engalfinham pela hegemonia) e Império do Meio II (EUA perdem capacidade de influir e a China estabelece nova ordem sinocêntrica, com países recalcitrantes: Japão, Índia e Rússia)",
        dep=["REL-T2-M04-C012"], exam=True, rap=True, safar=True,
        fontes=["F04:slides \"Cenários para o Leste e Sudeste Asiáticos\" (matriz e quatro descrições)",
                "F04:slide \"Cenários — Forças-motrizes\"", "A01:leitura dos quadrantes e a analogia do Afeganistão",
                "AUT:incerteza I-02 do manifesto"],
        prio=["É o exercício de cenários mais elaborado do corpus e o formato exato que o trabalho de T2 pede na parte prospectiva."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Quatro nomes e o eixo de cada um.",
              "Modelo de construção de cenário por forças-motrizes.",
              "Integra a analogia do Afeganistão, a instabilidade do Concerto e a recalcitrância no Império do Meio II."),
        ex=["Cria Cuervos: no Afeganistão dos anos 1980, com a URSS em declínio no lugar da China e os combatentes muçulmanos no lugar do arco, os financiados pelos EUA depois fundaram a Al-Qaeda e atacaram os EUA. 'Cría cuervos y te sacarán los ojos'.",
            "Casa sem Dono: não existe vácuo de poder — alguém buscará a hegemonia.",
            "Concerto Asiático: como o Concerto Europeu do século XIX, é equilíbrio instável; os países tendem a se armar e um incidente pode gerar guerra."],
        vuln=["🔴 Supor que o cenário com arco forte é sempre favorável aos EUA: em Cria Cuervos o arco forte com China fraca volta-se contra eles.",
              "🟠 Tratar Casa sem Dono como vácuo de poder — o próprio raciocínio nega que vácuo exista.",
              "🟡 Confundir Concerto Asiático (equilíbrio com potência externa) com Império do Meio II (ordem sinocêntrica)."],
    ),
    dict(
        id="REL-T2-M04-C014", modulo="04-estados-unidos",
        assunto="Conjuntura: releitura contemporânea da Doutrina Monroe no hemisfério — a Estratégia de Segurança Nacional de 2025 trata o Hemisfério Ocidental como prioritário e institui o que se descreve como 'corolário Trump', negando acesso territorial a competidores não-hemisféricos; a expressão 'Doutrina Donroe' surge na imprensa em 08/01/2025 e é adotada pelo próprio presidente; pressão sobre o Canal do Panamá e a concessão portuária de Balboa e Cristóbal (CK Hutchison); a Groenlândia e o Ártico como segundo foco; a invasão da Venezuela em janeiro de 2026; e a disputa por terras raras, das quais o Brasil detém a segunda reserva mundial (23%)",
        dep=["REL-T2-M04-C004", "REL-T2-M04-C008"], exam=True, rap=True, safar=True,
        fontes=["C03:seção \"(Des)Territorializações em disputa na Doutrina Donroe\" e considerações finais",
                "C07:o Conselho da Paz e a expansão para a Venezuela, a Groenlândia e o Irã"],
        prio=["É a caixa de conjuntura que reativa Monroe e liga diretamente o módulo 04 ao interesse brasileiro."],
        prof=("âncora — o fato e o conceito que ele ilumina", P_T3, C_T3),
        just=("Um fato recente que reacende um conceito de 1823.",
              "Treina a leitura de acontecimento por conceito, com data de corte.",
              "Integra território, chokepoint, mineral crítico e a crítica de que coerção substitui consenso."),
        ex=["O Panamá foi, em 2017, o primeiro país da América Latina e do Caribe a aderir à iniciativa chinesa Um Cinturão, Uma Rota, e saiu em 2025 sob pressão americana.",
            "Terras raras e minerais críticos ligam 'soberania mineral' a 'supremacia digital' — e colocam o Brasil, com 23% das reservas mundiais, na conta.",
            "Data de corte desta caixa: as informações foram verificadas nas fontes autorizadas C03 (aceita em 10/04/2026) e C07 (23/01/2026)."],
        vuln=["🔴 Tratar a interpretação do artigo (imperialismo e colonialidade do poder) como descrição neutra: é leitura declarada, e há leituras concorrentes.",
              "🟠 Usar o exemplo atual sem nomear o conceito que ele ilumina — exemplo sem conceito não pontua.",
              "🟡 Esquecer de datar a informação."],
    ),
    dict(
        id="REL-T2-M04-C015", modulo="04-estados-unidos",
        assunto="Conjuntura e clínica institucional: o Conselho da Paz instituído em janeiro de 2026, com origem na Resolução 2803 do Conselho de Segurança da ONU e depois desvinculado dela na própria carta; presidência permanente, mandatos renováveis a critério do presidente, financiamento 'voluntário' com associação permanente para quem aportar um bilhão de dólares, e um conselho executivo nomeado; a maior parte da Europa, a Rússia, a China e os Estados africanos ficaram fora",
        dep=["REL-T2-M04-C007", "REL-T2-M00-C006"], exam=True, rap=True, safar=True,
        fontes=["C07:integral"],
        prio=["É o melhor caso contemporâneo de instituição lida simultaneamente como cooperação e como instrumento de poder."],
        prof=("âncora — o desenho institucional e o teste que decide entre as duas leituras", P_T3, C_T3),
        just=("No Rápido em versão mínima: o desenho do arranjo e o teste 'a regra restringe quem a criou?' — exigido pelo simulado final, que é o mesmo instrumento nas três modalidades.",
              "Fornece um segundo caso ambíguo, contemporâneo e datado.",
              "Integra desenho institucional, assimetria de voto e financiamento como fonte de influência."),
        ex=["Leitura institucional: um órgão de construção da paz mais ágil que a ONU, criado a partir de uma resolução do próprio Conselho de Segurança. Leitura de poder: um arranjo em que todas as decisões emanam do presidente e a influência acompanha o aporte financeiro.",
            "Data de corte: 23/01/2026, conforme a fonte."],
        vuln=["🟠 Escolher uma das duas leituras sem dizer qual evidência do desenho institucional a sustenta.",
              "🟡 Tratar a fonte europeia como neutra: é análise com posição declarada."],
    ),
]
