# -*- coding: utf-8 -*-
"""Matriz canônica — Módulo 99 (revisão final e comparações globais)."""

from conceitos_m00_m02 import R_ANC, P_APL, C_INT, C_T3, P_T3

CONCEITOS = [
    dict(
        id="REL-T2-M99-C001", modulo="99-revisao-final",
        assunto="Comparação global de objetivos estratégicos: Brasil (soberania, integridade territorial, autonomia tecnológica, coesão, projeção e inserção decisória), EUA (hegemonia hemisférica em quatro degraus, culminando em evitar hegemon eurasiático), China (integridade territorial, contenção da desigualdade interna, abertura sem desagregação) e Rússia (manter o centro Europa-Urais com tampões, garantir o Cazaquistão, tentar acesso aos mares)",
        dep=["REL-T2-M02-C006", "REL-T2-M04-C009", "REL-T2-M05-C003", "REL-T2-M06-C003"],
        exam=True, rap=True, safar=True,
        fontes=["F02:slides \"Objetivos Nacionais de Defesa\"", "F04:slide \"EUA - Imperativo Estratégico\"",
                "F05:slide \"China - Imperativo Estratégico\"", "F06:slide \"Imperativos Estratégicos\"",
                "P06:item 2 do trabalho de T2"],
        prio=["É a questão de integração mais provável: os quatro imperativos lado a lado."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Um quadro de quatro colunas resolve qualquer questão comparativa.",
              "Permite responder 'compare X e Y' sem improvisar.",
              "Integra a diferença de natureza: preservação, expansão e recuperação."),
        ex=["Natureza dos imperativos: China e Brasil são predominantemente de PRESERVAÇÃO; EUA, de MANUTENÇÃO de hegemonia; Rússia, de RECUPERAÇÃO de posição perdida.",
            "Só os EUA têm um imperativo cujo objeto está fora do próprio hemisfério (evitar hegemon na Eurásia)."],
        vuln=["🔴 Tratar todos os imperativos como 'expansionistas': três dos quatro são de preservação ou recuperação.",
              "🟠 Comparar sem nomear o critério de comparação."],
    ),
    dict(
        id="REL-T2-M99-C002", modulo="99-revisao-final",
        assunto="Comparação global de condicionantes geográficos: Brasil (litoral de cerca de 8.500 km, bacias internacionais, fronteira com 10 vizinhos, sem ameaça estatal próxima), EUA (bioceanidade, planícies centrais com rios navegáveis, vizinhos fracos, dois oceanos como fosso e como via), China (isoieta de 300 mm separando litoral rico de interior pobre, zonas tampão de altitude e aridez, litoral fechado por cadeias de ilhas) e Rússia (planície europeia aberta, centro Europa-Urais, mares congelados ou dependentes de estreitos de terceiros)",
        dep=["REL-T2-M99-C001", "REL-T2-M04-C001", "REL-T2-M05-C001", "REL-T2-M06-C004"],
        exam=True, rap=True, safar=True,
        fontes=["F03:slides \"Economia Azul\"", "F04:mapas de formação geográfica", "F05:mapas de isoieta e topografia",
                "F06:mapas de formação territorial", "A01:leitura dos mapas dos três países"],
        prio=["A geografia é a variável que o professor usa para explicar comportamento — comparar as quatro é comparar as causas."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Quatro geografias em quatro linhas.",
              "Explica por que atores diferentes fazem escolhas diferentes com meios semelhantes.",
              "Integra relevo, clima, hidrografia, vizinhança e acesso ao mar."),
        ex=["Brasil e EUA têm acesso oceânico livre; China tem acesso obstruído por cadeias de ilhas; Rússia tem acesso obstruído por gelo e por estreitos alheios.",
            "Brasil é o único dos quatro sem rival estatal próximo de peso comparável — e essa é a condição que Alsina Jr. considera geradora de cultura excessivamente pacífica."],
        vuln=["🟠 Confundir extensão de litoral com acesso ao oceano: a Rússia tem muito litoral e pouco acesso.",
              "🟡 Tratar vizinhança fraca como vantagem apenas: ela reduz o incentivo ao investimento em defesa."],
    ),
    dict(
        id="REL-T2-M99-C003", modulo="99-revisao-final",
        assunto="Comparação global de vulnerabilidades: Brasil (baixa prontidão, orçamento, cultura de defesa pouco consolidada, dependência do mar para 95% do comércio exterior), EUA (declínio relativo de participação econômica, dependência de alianças, A2/AD adversário, fragilidade do consenso interno), China (Estreito de Málaca, dependência de alimento e petróleo importados, demografia, custos trabalhistas, desigualdade litoral-interior) e Rússia (demografia, dependência de petróleo e gás, frota e indústria naval defasadas, perda de tampões)",
        dep=["REL-T2-M99-C002", "REL-T2-M02-C013", "REL-T2-M04-C008", "REL-T2-M05-C013", "REL-T2-M06-C013"],
        exam=True, rap=True, safar=True,
        fontes=["F01:slide \"Pontos para Debate (Alsina Jr.)\"", "F03:slides \"Economia Azul\"", "F04:slide \"Declínio?\"",
                "F05:slide \"China recente\"", "F06:slides \"Desafios para a Rússia\"", "C05:perda da autossuficiência chinesa", "C10:restrições materiais russas"],
        prio=["O trabalho de T2 exige fatores dificultadores; a vulnerabilidade é o passo 4 da matriz de cenários."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Uma vulnerabilidade dominante por ator.",
              "É o insumo direto da parte de dificultadores do trabalho.",
              "Integra vulnerabilidade material, demográfica, institucional e de percepção."),
        ex=["Duas vulnerabilidades demográficas (China e Rússia), duas de dependência de renda concentrada (Rússia em hidrocarbonetos, Brasil em commodities e comércio marítimo).",
            "A vulnerabilidade brasileira mais citada no corpus é interna e institucional, não externa."],
        vuln=["🔴 Listar vulnerabilidades sem dizer o que cada uma ameaça: vulnerabilidade é sempre relativa a um objetivo.",
              "🟠 Tratar vulnerabilidade como fraqueza geral em vez de ponto de pressão específico."],
    ),
    dict(
        id="REL-T2-M99-C004", modulo="99-revisao-final",
        assunto="Comparação global da relação com o mar e dos instrumentos de projeção: Brasil (Amazônia Azul, AJB, tarefas básicas do Poder Naval, PROSUB, SisGAAz, complexo naval da foz do Amazonas, ZOPACAS, CPLP), EUA (Marinha global com alcance planetário, rede de bases, canais, alianças, meta de 355/381 navios com vetores não tripulados), China (A2/AD por cadeias de ilhas, ilhas artificiais, Belt and Road com ramo marítimo, corredores terrestres alternativos, canal de Kra) e Rússia (doutrina marítima de 2022, Rota Marítima do Norte, Ártico, frota defasada e dependência de estreitos alheios)",
        dep=["REL-T2-M99-C003", "REL-T2-M03-C009", "REL-T2-M04-C011", "REL-T2-M05-C012", "REL-T2-M06-C013"],
        exam=True, rap=True, safar=True,
        fontes=["F03:slides de programas estratégicos", "F04:slides de estrutura de força naval", "F05:slides de A2/AD e BRI",
                "C10:doutrina marítima russa de 2022", "P06:itens 4 e 5 do trabalho de T2"],
        prio=["É a comparação oceanopolítica que o termo 'geoceanopolítico' do trabalho exige."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Um instrumento marítimo dominante por ator.",
              "É o quadro que responde qualquer comparação naval.",
              "Integra a natureza do instrumento: jurisdição, projeção global, negação regional e compensação."),
        ex=["Natureza dos instrumentos: o Brasil investe em JURISDIÇÃO e monitoramento; os EUA, em PROJEÇÃO global; a China, em NEGAÇÃO regional; a Rússia, em COMPENSAÇÃO de um acesso deficiente.",
            "Só os EUA têm rede de bases suficiente para operar longe; a própria fonte russa identifica a falta de bases externas como ameaça principal às suas atividades marítimas."],
        vuln=["🔴 Comparar marinhas por número de navios em vez de por tarefa que conseguem cumprir.",
              "🟠 Tratar A2/AD como projeção de poder: é negação, o oposto funcional."],
    ),
    dict(
        id="REL-T2-M99-C005", modulo="99-revisao-final",
        assunto="Comparação global do papel das alianças e da relação com instituições: Brasil (não-intervenção, solução pacífica, multilateralismo, reivindicação de assento no CSNU, Mercosul intergovernamental por consenso, ZOPACAS, CPLP), EUA (alianças formais com 9 das 12 maiores marinhas seguintes, OTAN, AUKUS, arquitetura de Bretton Woods e, na conjuntura, arranjos paralelos à ONU), China (participação crescente em missões de paz e na OMC, revisionismo 'soft', vontade de participar de fazer as regras) e Rússia (multipolaridade como esferas de influência, BRICS, União Eurasiática, CEI, ultimatos à OTAN)",
        dep=["REL-T2-M99-C004", "REL-T2-M01-C012", "REL-T2-M04-C007", "REL-T2-M05-C016", "REL-T2-M06-C012"],
        exam=True, rap=True, safar=True,
        fontes=["F01:slide \"PEB - Constituição de 1988\"", "F04:slide \"Hegemonia Mundial\"", "F05:slide \"China Pós-Deng\"",
                "C11:multipolaridade como esferas de influência", "C07:arranjo institucional paralelo", "P06:item 4 do trabalho"],
        prio=["É a comparação que obriga a usar a ambivalência institucional aprendida no Módulo 00."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Uma postura institucional por ator.",
              "É o quadro que responde 'como cada ator usa instituições'.",
              "Integra a ambivalência: a mesma instituição como cooperação e como instrumento."),
        ex=["Três posturas distintas diante da mesma ordem: o Brasil quer ENTRAR no núcleo decisório; a China quer PARTICIPAR de fazer as regras; a Rússia quer SUBSTITUIR a ordem por esferas de influência.",
            "Os EUA construíram a ordem e, na conjuntura de 2026, aparecem criando arranjo paralelo a ela — o que é matéria de interpretação disputada."],
        vuln=["🔴 Classificar como 'liberal' todo ator que participa de instituições.",
              "🟠 Tratar reformismo (Brasil, China) e revisionismo de substituição (leitura crítica da Rússia) como a mesma coisa."],
    ),
    dict(
        id="REL-T2-M99-C006", modulo="99-revisao-final",
        assunto="Comparação global da tensão entre economia e segurança: Brasil (dependência do mar para exportação × baixo investimento em defesa), EUA (dependência de cadeias globais × decoupling e tarifas), China (abertura necessária à prosperidade × risco de desagregação interna e de bloqueio de Málaca) e Rússia (receita de hidrocarbonetos × sanções e perda de mercados)",
        dep=["REL-T2-M99-C005", "REL-T2-M03-C020", "REL-T2-M05-C003", "REL-T2-M06-C010"],
        exam=True, rap=True, safar=True,
        fontes=["F03:slides \"Economia Azul\"", "F05:slide \"China - Imperativo Estratégico\"", "F06:slide \"Desafios para a Rússia\"",
                "C05:limites do alinhamento econômico EUA-China", "P05:questão 18c (segurança sobrepondo-se ao comércio)"],
        prio=["A P2 cobrou exatamente essa tensão no caso australiano, e a resposta-padrão conclui que segurança se sobrepõe a comércio."],
        prof=(R_ANC, P_T3, C_T3),
        just=("Uma tensão por ator, na mesma forma.",
              "É o esqueleto de qualquer questão sobre parceiro comercial × aliado de segurança.",
              "Integra o critério de arbitragem observado no corpus."),
        ex=["Caso-padrão: a Austrália proibiu ZTE e Huawei no 5G apesar de a China ser seu maior parceiro comercial — a geopolítica de uma ilha a leva a se aliar à maior potência naval, e os interesses de segurança se sobrepõem aos comerciais.",
            "Regra derivada: quando a dependência econômica e a dependência de segurança apontam para atores diferentes, o vetor de segurança tende a prevalecer nas decisões estruturais."],
        vuln=["🔴 Concluir que o maior parceiro comercial determina o alinhamento estratégico.",
              "🟠 Tratar a regra como lei: ela é tendência observada, com contraexemplos possíveis."],
    ),
    dict(
        id="REL-T2-M99-C007", modulo="99-revisao-final",
        assunto="Comparação global da lógica teórica predominante e os limites da comparação: qual lente explica melhor cada ator, e por que a comparação entre Brasil, EUA, China e Rússia tem limites — escalas de poder muito distintas, posições no sistema distintas, qualidade e acesso a fontes desiguais, e o risco de projetar a categoria de um ator sobre outro",
        dep=["REL-T2-M99-C006", "REL-T2-M00-C005", "REL-T2-M00-C006", "REL-T2-M00-C007", "REL-T2-M00-C009"],
        exam=True, rap=True, safar=True,
        fontes=["F04:slides das três teorias", "AUT:limites declarados da comparação", "P06:item 3 do trabalho de T2 (instrumentalização de um teórico)"],
        prio=["O último passo da matriz de cenários é a arbitragem entre leituras; o limite da comparação é o que separa resposta MB de resposta satisfatória."],
        prof=(R_ANC, P_T3, C_T3),
        just=("A lente dominante por ator e a ressalva.",
              "É o fechamento argumentativo de qualquer comparação.",
              "Integra a arbitragem entre lentes e a declaração explícita dos limites."),
        ex=["O mesmo ator admite leituras distintas conforme o aspecto: os EUA de Bretton Woods pedem lente liberal; os EUA da Doutrina Monroe reativada pedem lente realista; o Destino Manifesto pede lente construtivista.",
            "Limite explícito: comparar o Brasil aos outros três iguala atores de escalas incomparáveis — a comparação serve para isolar variáveis, não para ranquear."],
        vuln=["🔴 Atribuir uma lente fixa a um país: a lente depende do aspecto destacado.",
              "🟠 Concluir comparação sem declarar o seu limite — é o elemento que a correção por elementos cobra."],
    ),
    dict(
        id="REL-T2-M99-C008", modulo="99-revisao-final",
        assunto="Protocolo de véspera e de prova: ordem de recuperação das âncoras (listas fechadas primeiro), roteiro de dez passos da matriz, seis movimentos da discursiva, regras antiformato para comando invertido e asserção e razão, e o roteiro de sete itens caso a T2 seja trabalho em grupo",
        dep=["REL-T2-M99-C007", "REL-T2-M00-C010", "REL-T2-M00-C016"], exam=True, rap=True, safar=True,
        fontes=["AUT:perfil-cobranca.json", "P06:estrutura e pesos do trabalho de 2025", "P02:padrão de correção por elementos"],
        prio=["É o que o aluno usa nas últimas horas; converte todo o curso em procedimento executável."],
        prof=(R_ANC, P_APL, C_INT),
        just=("É a própria função do modo Rápido.",
              "Fecha o estudo com procedimento, não com conteúdo novo.",
              "Integra os dois formatos possíveis de avaliação."),
        ex=["Ordem de recuperação: listas fechadas (art. 4º, objetivos de defesa, capacidades, tarefas básicas, funções e elementos do Poder Marítimo, imperativos dos quatro atores) antes de qualquer releitura de texto corrido."],
        vuln=["🟠 Gastar a véspera relendo teoria em vez de recuperar listas fechadas e treinar formato."],
    ),
]
