# -*- coding: utf-8 -*-
"""Metadados dos módulos da família rel-t2, por modalidade."""

FAMILIA = "rel-t2"
FAMILIA_TITULO = "Relações Internacionais — T2"

# tempo em minutos por (modulo, modalidade)
TEMPOS = {
    "00-metodo-e-matriz-de-cenarios": {"rapido": 8, "pra-safar": 20, "completo": 32},
    "01-politica-externa-brasileira": {"rapido": 12, "pra-safar": 45, "completo": 70},
    "02-pnd-end-e-pesd": {"rapido": 10, "pra-safar": 30, "completo": 48},
    "03-politica-maritima-naval-e-economia-azul": {"rapido": 12, "pra-safar": 40, "completo": 58},
    "04-estados-unidos": {"rapido": 20, "pra-safar": 55, "completo": 88},
    "05-china": {"rapido": 16, "pra-safar": 55, "completo": 88},
    "06-peb-aplicacao-e-integracao": {"rapido": 12, "pra-safar": 40, "completo": 62},
    "99-revisao-final": {"rapido": 8, "pra-safar": 25, "completo": 42},
}

MODULOS = [
    dict(
        ordem=0, slug="00-metodo-e-matriz-de-cenarios",
        titulo="Método: matriz de cenários, lentes teóricas e discursiva",
        subtitulo="Escopo, hierarquia das fontes, dez passos de análise e seis movimentos de resposta",
        prioridade="máxima",
        objetivo="Delimitar o escopo da T2 e aplicar a matriz de dez passos, as três lentes teóricas e os seis movimentos da resposta discursiva a um cenário inédito.",
        palavrasChave=["escopo", "matriz de cenários", "imperativo estratégico", "realismo", "liberalismo",
                       "construtivismo", "caso ambíguo", "discursiva"],
        aula="13 a 17 (transversal)",
    ),
    dict(
        ordem=1, slug="01-politica-externa-brasileira",
        titulo="Política Externa Brasileira",
        subtitulo="Interesses, meios e princípios — da Colônia à tipologia da autonomia",
        prioridade="máxima",
        objetivo="Explicar a política externa brasileira pela relação entre interesses, meios de ação e princípios, classificando qualquer governo na tipologia da autonomia com evidência histórica.",
        palavrasChave=["interesses e meios", "Rio Branco", "aliança não-escrita", "PEI", "pragmatismo responsável",
                       "art. 4º da CF/88", "autonomia pela participação", "autonomia pela diversificação", "Mercosul"],
        aula="13",
    ),
    dict(
        ordem=2, slug="02-pnd-end-e-pesd",
        titulo="PND, END e PESD",
        subtitulo="Grande Estratégia, objetivos, capacidades, Poder Naval e AJB",
        prioridade="máxima",
        objetivo="Percorrer a cadeia objetivo → estratégia → capacidade → ação nos dois sentidos, usando os objetivos da PND, as capacidades da END, as tarefas básicas do Poder Naval e a definição de AJB.",
        palavrasChave=["Grande Estratégia", "PND", "END", "PESD", "capacidades nacionais de defesa",
                       "tarefas básicas do Poder Naval", "AJB", "setores estratégicos", "ZOPACAS"],
        aula="14",
    ),
    dict(
        ordem=3, slug="03-politica-maritima-naval-e-economia-azul",
        titulo="Política Marítima, Política Naval, PEM 2040 e Economia Azul",
        subtitulo="Entorno estratégico, Poder Marítimo, programas e o mar como base da economia",
        prioridade="máxima",
        objetivo="Distinguir Poder Marítimo de Poder Naval e ligar entorno estratégico, funções e condicionantes, programas estratégicos e Economia Azul a objetivos e vulnerabilidades concretos do Brasil.",
        palavrasChave=["Política Marítima Nacional", "Política Naval", "entorno estratégico", "Poder Marítimo",
                       "PEM 2040", "combate pelo mar", "PROSUB", "SisGAAz", "Amazônia Azul", "Economia Azul"],
        aula="15",
    ),
    dict(
        ordem=4, slug="04-estados-unidos",
        titulo="Estados Unidos",
        subtitulo="Da fronteira interna ao imperativo eurasiático, e os cenários asiáticos",
        prioridade="máxima",
        objetivo="Explicar a hegemonia norte-americana pela cadeia geografia → expansão → virada marítima → instituições, distinguir declínio relativo de absoluto e operar os quatro cenários do Leste Asiático.",
        palavrasChave=["Destino Manifesto", "Doutrina Monroe", "Corolário Roosevelt", "Mahan", "Spykman",
                       "declínio relativo", "imperativo estratégico", "multidomínio", "cenários asiáticos"],
        aula="16",
    ),
    dict(
        ordem=5, slug="05-china",
        titulo="China",
        subtitulo="Dupla tensão, Tianxia, humilhações e a projeção contemporânea",
        prioridade="máxima",
        objetivo="Explicar as decisões chinesas pelos três imperativos estratégicos, pela dupla tensão litoral-interior e pela memória das humilhações, aplicando A2/AD, Taiwan, Málaca e Belt and Road a cenários inéditos.",
        palavrasChave=["dupla tensão histórica", "Tianxia", "Século das Humilhações", "Deng Xiaoping", "Taiwan",
                       "Resolução 2758", "A2/AD", "Primeira Cadeia de Ilhas", "Estreito de Málaca", "Belt and Road"],
        aula="17",
    ),
    dict(
        ordem=6, slug="06-peb-aplicacao-e-integracao",
        titulo="Política Externa Brasileira — aplicação e integração",
        subtitulo="Imperativo brasileiro, os seis Estudos Dirigidos da Aula 13 e a análise do Brasil pela matriz",
        prioridade="máxima",
        objetivo="Reconstruir o imperativo estratégico brasileiro a partir do corpus, responder aos seis Estudos Dirigidos da Aula 13 com evidência e aplicar a matriz de dez passos ao próprio Brasil, no formato que o trabalho de T2 exige.",
        palavrasChave=["imperativo brasileiro", "alinhamento automático", "integração sul-americana", "art. 4º",
                       "ZOPACAS", "CPLP", "Rio Branco", "Mercosul intergovernamental", "ator global",
                       "matriz de dez passos", "discursiva em seis movimentos"],
        aula="13 (aplicação) + integração com 14 e 15",
    ),
    dict(
        ordem=99, slug="99-revisao-final",
        titulo="Revisão final",
        subtitulo="Matriz comparativa Brasil–EUA–China, erros frequentes e véspera",
        prioridade="máxima",
        objetivo="Comparar Brasil, Estados Unidos e China em objetivos, geografia, vulnerabilidades, mar, alianças, instituições e lógica teórica, declarando os limites da comparação, e executar o protocolo de véspera.",
        palavrasChave=["matriz comparativa", "limites da comparação", "erros frequentes", "véspera", "protocolo de prova"],
        aula="13 a 17 (síntese)",
    ),
]

MODULOS_POR_SLUG = {m["slug"]: m for m in MODULOS}

# ─────────────────────────── checklists ──────────────────────────────────
# Itens de autoavaliação por módulo. Formulados como desempenho verificável.
CHECKLISTS = {
    "00-metodo-e-matriz-de-cenarios": [
        "Digo de cabeça quais são as seis aulas internas do escopo e por que os arquivos têm nome deslocado.",
        "Aplico os dez passos da matriz de cenários a um caso que nunca vi, sem consultar a lista.",
        "Defino imperativo estratégico com as palavras do professor e digo por que ele pode mudar.",
        "Distingo realismo, liberalismo e construtivismo pelo imperativo central de cada um.",
        "Construo as duas leituras do Brexit e escolho uma, dizendo qual evidência do enunciado a sustenta.",
        "Escrevo uma resposta em seis movimentos, com nexo causal explícito e um contraponto.",
        "Reconheço comando invertido e asserção e razão e sei o que checar primeiro em cada um.",
    ],
    "01-politica-externa-brasileira": [
        "Explico o dilema interesses × meios mediados por princípios e aplico a um governo qualquer.",
        "Respondo, com dois exemplos opostos, se o alinhamento automático sempre deu resultado ao Brasil.",
        "Digo as três heranças de Rio Branco e as localizo no art. 4º da CF/88.",
        "Recito os dez incisos do art. 4º e o parágrafo único.",
        "Classifico Castello, Geisel, FHC, Lula e Dilma na tipologia da autonomia, sem errar a exceção.",
        "Digo o que é comum e o que é diferente entre FHC e Lula, incluindo a posição sobre o Conselho de Segurança.",
        "Dou uma razão institucional e uma razão pragmática para a integração latino-americana.",
        "Distingo hispano-americanismo de pan-americanismo e digo por que o Brasil ficou fora do primeiro.",
    ],
    "02-pnd-end-e-pesd": [
        "Defino Grande Estratégia com a formulação de Feaver e digo por que ela tem influência realista.",
        "Digo quem define objetivo, quem orienta medida e quem comunica: PND, END e Livro Branco.",
        "Sei a diferença entre as aprovações do Congresso (2005, 2012, 2018) e a versão em vigor (nov/2025).",
        "Listo os cinco pressupostos da PND e os oito Objetivos Nacionais de Defesa.",
        "Listo as nove Capacidades Nacionais de Defesa e correlaciono uma delas com o conceito de multimodal.",
        "Reproduzo a definição de AJB, inclusive a cláusula 'em algum grau' e a extensão da plataforma.",
        "Listo as quatro tarefas básicas do Poder Naval e correlaciono uma com a Amazônia Azul.",
        "Digo qual Força responde por cada setor estratégico e correlaciono o PESD com a Escola Naval.",
        "Apresento a crítica de Alsina Jr. como contraponto, nomeando as ameaças internas.",
    ],
    "03-politica-maritima-naval-e-economia-azul": [
        "Digo a situação atual da Política Marítima Nacional e o mecanismo que levou ao decreto de 2025.",
        "Listo os quatro itens do entorno estratégico brasileiro.",
        "Distingo Poder Marítimo de Poder Naval e listo os oito elementos do primeiro.",
        "Listo as quatro funções e os cinco fatores condicionantes do Poder Marítimo.",
        "Distingo Combate no Mar de Combate pelo Mar e recuso a afirmação de que Mahan foi superado.",
        "Listo os sete programas estratégicos e correlaciono dois deles com a Amazônia Azul.",
        "Explico o PROSUB sem confundir propulsão nuclear com armamento nuclear.",
        "Digo o objetivo do SisGAAz, inclusive o alcance para áreas SAR internacionais.",
        "Recito os cinco percentuais da Economia Azul e os uso como argumento de vulnerabilidade.",
        "Julgo qual ameaça do PEM 2040 é operacionalmente mais difícil, com critério explícito.",
    ],
    "04-estados-unidos": [
        "Explico a expansão americana pelos três instrumentos e pela geografia das planícies e rios.",
        "Distingo Destino Manifesto, American way of life, Doutrina Monroe e Corolário Roosevelt.",
        "Digo por que a Doutrina Monroe é declaração unilateral de dupla natureza.",
        "Explico a cadeia fronteira fechada → Mahan → Roosevelt → canal → mare nostrum.",
        "Argumento que o declínio é relativo, com os cinco indicadores de força e a cláusula das alianças.",
        "Recito os quatro degraus do imperativo estratégico americano, na ordem.",
        "Distingo interoperabilidade interna de externa e explico multidomínio e A2/AD.",
        "Nomeio os quatro cenários asiáticos, digo o eixo de cada um e explico Cria Cuervos pela analogia do Afeganistão.",
        "Uso a conjuntura de 2025-2026 nomeando o conceito que ela ilumina e a data de corte.",
    ],
    "05-china": [
        "Explico a dupla tensão histórica em quatro passos, terminando na autarcização.",
        "Recito os três imperativos estratégicos chineses e mostro por que formam um trilema.",
        "Digo qual foi a primeira dinastia com registro escrito e qual unificou o país.",
        "Explico Tianxia e o sistema tributário como ordem hierárquica de baixa violência.",
        "Explico o Século das Humilhações pelo mecanismo comercial, não só pelo ópio.",
        "Digo por que o Grande Cisma ocorreu e como os EUA o exploraram.",
        "Não confundo zona econômica especial com zona econômica exclusiva.",
        "Distingo princípio de Uma Só China de política de Uma Só China e explico a Resolução 2758.",
        "Distingo A2 de AD e digo o alcance da Primeira Cadeia de Ilhas.",
        "Explico o dilema de Málaca, as duas alternativas chinesas e o interesse indiano contrário.",
        "Recuso a conclusão de superioridade naval chinesa a partir da contagem de cascos.",
    ],
    "06-peb-aplicacao-e-integracao": [
        "Enuncio os quatro itens do imperativo estratégico brasileiro e digo que são reconstrução, não slide.",
        "Explico por que o imperativo brasileiro não tem hierarquia declarada, ao contrário do americano e do chinês.",
        "Respondo ao Estudo Dirigido 1 com um caso a favor e um contra o alinhamento automático.",
        "Dou uma razão institucional e uma pragmática para a integração sul-americana, sem repetir a natureza.",
        "Explico por que ZOPACAS e CPLP importam ao entorno estratégico E à Marinha.",
        "Converto as heranças de Rio Branco em norma vigente: art. 4º e fundamento da Política Naval.",
        "Distingo potência regional de ator global na formulação da fonte, sem inflar para capacidade militar.",
        "Explico o efeito da regra de consenso do Mercosul e o da adesão venezuelana de 2012.",
        "Preencho os dez passos da matriz para o Brasil, com vulnerabilidade, instrumentos e contraponto.",
        "Escrevo uma discursiva de PEB nos seis movimentos, sem omitir o nexo causal.",
    ],
    "99-revisao-final": [
        "Preencho de memória a matriz comparativa dos quatro atores nas sete linhas.",
        "Digo a natureza do imperativo de cada ator: preservação, manutenção ou recuperação.",
        "Digo qual instrumento marítimo domina em cada ator e qual tarefa ele cumpre.",
        "Declaro pelo menos dois limites da comparação entre os quatro atores.",
        "Executo o protocolo de véspera na ordem certa, começando pelas listas fechadas.",
        "Escrevo uma resposta em seis movimentos em até dez minutos.",
        "Monto o roteiro de sete itens do trabalho em grupo, caso a T2 tenha esse formato.",
    ],
}

# ─────────────────────────── fontes por módulo ───────────────────────────
FONTES = [
    dict(
        titulo="Aula interna 13 — Política Externa Brasileira (arquivo AULA 12.pdf)",
        tipo="slide",
        descricao="Fonte material do Módulo 01. Atenção ao deslocamento: o arquivo se chama AULA 12 e contém a Aula 13 seguida da Aula 14. Bibliografia obrigatória indicada no próprio deck: MAGNOLI (2013, 340-355).",
        topicos=["00-metodo-e-matriz-de-cenarios", "01-politica-externa-brasileira", "99-revisao-final"],
    ),
    dict(
        titulo="Aula interna 14 — PND, END e PESD (arquivo AULA 13.pdf, versão de nov/2025)",
        tipo="slide",
        descricao="Fonte material do Módulo 02, em versão autônoma e atualizada. Divergência registrada: este deck cita a versão da PND/END de 18/11/2025 (Decreto 12.725), enquanto o deck combinado ainda cita 2016/2018. Prevalece este.",
        topicos=["02-pnd-end-e-pesd", "99-revisao-final"],
    ),
    dict(
        titulo="Aula interna 15 — Política Marítima, Política Naval, PEM 2040 e Economia Azul (arquivo AULA 14.pdf)",
        tipo="slide",
        descricao="Fonte material do Módulo 03. O slide 'Elementos do Poder Marítimo' é um diagrama sem texto extraível; a lista dos oito elementos foi recuperada do resumo de Aspirante e está marcada como tal no curso.",
        topicos=["03-politica-maritima-naval-e-economia-azul", "99-revisao-final"],
    ),
    dict(
        titulo="Aula interna 16 — EUA (arquivo AULA 15.pdf)",
        tipo="slide",
        descricao="Fonte material do Módulo 04 e única fonte primária que define, em slides próprios, o conceito de imperativo estratégico e as três lentes teóricas — por isso sustenta também o Módulo 00. Bibliografia obrigatória: MAGNOLI (2013, 133-140; 226-239), não fornecida ao corpus.",
        topicos=["00-metodo-e-matriz-de-cenarios", "04-estados-unidos", "99-revisao-final"],
    ),
    dict(
        titulo="Aula interna 17 — China (arquivo AULA 16.pdf)",
        tipo="slide",
        descricao="Fonte material do Módulo 05. Bibliografia obrigatória: MAGNOLI (2013, 244-260), correspondente ao cap. 18 na edição em PDF (p. 265-282), não fornecida ao corpus.",
        topicos=["05-china", "99-revisao-final"],
    ),
    dict(
        titulo="MAGNOLI, Demétrio — capítulo 21, 'O Brasil e a América Latina' (p. 340-355)",
        tipo="livro",
        descricao="Bibliografia obrigatória da Aula 13, fornecida ao corpus e lida integralmente. Aprofunda bolivarianismo e pan-americanismo, corolários Polk e Roosevelt, Sistema Interamericano, invenção da América Latina, Cepal, Travassos e Golbery, Mercosul, Unasul e IIRSA — e sustenta o módulo de aplicação de PEB.",
        topicos=["01-politica-externa-brasileira", "04-estados-unidos", "06-peb-aplicacao-e-integracao"],
    ),
    dict(
        titulo="MORE, Rodrigo Fernandes — 'Reflexões sobre a formação de um pensamento oceanopolítico brasileiro'",
        tipo="livro",
        descricao="Leitura complementar autorizada. Aprofunda oceanopolítica, Barbosa Jr., Martinez Busch, fronteira integral, Mar Presencial, CNUDM como Constituição do Mar, Lei 8.617/1993, LEPLAC e PNRM.",
        topicos=["00-metodo-e-matriz-de-cenarios", "03-politica-maritima-naval-e-economia-azul"],
    ),
    dict(
        titulo="HAESBAERT & SANTA BÁRBARA — 'Da Doutrina Monroe à Doutrina Donroe' (GEOgraphia, 2026)",
        tipo="livro",
        descricao="Leitura complementar autorizada, com posição crítica declarada (imperialismo e colonialidade do poder). Usada como interpretação identificada, não como descrição neutra. Aprofunda Monroe, Corolário Roosevelt, tese da fronteira de Turner, mediterrâneo americano, chokepoints e terras raras.",
        topicos=["04-estados-unidos"],
    ),
    dict(
        titulo="CRS RL32665 — 'Navy Force Structure and Shipbuilding Plans'",
        tipo="observacao",
        descricao="Relatório do Congresso dos EUA citado pelo próprio slide da Aula 16. Consultado parcialmente (sumário executivo e metas de nível de força); as tabelas de que o curso precisa já estão transcritas no deck.",
        topicos=["04-estados-unidos"],
    ),
    dict(
        titulo="Geopolitical Futures — 'The Third Opium War'",
        tipo="observacao",
        descricao="Leitura complementar autorizada. Fornece o mecanismo causal do Século das Humilhações (chá, prata, ópio, cobre) e a explicação de por que a China deixou de ser autossuficiente.",
        topicos=["05-china"],
    ),
    dict(
        titulo="BARTOSIAK, Jacek — 'The Politics of Space'",
        tipo="observacao",
        descricao="Autor citado na bibliografia de aprofundamento da Aula 16. Sustenta a analogia entre espaço sideral e oceano e o argumento de que nunca houve, ao mesmo tempo, uma China poderosa e uns EUA poderosos.",
        topicos=["04-estados-unidos", "05-china"],
    ),
    dict(
        titulo="IDEG — 'Taiwan e as Nações Unidas: a política de Uma Só China'",
        tipo="observacao",
        descricao="Leitura complementar autorizada. Fonte da distinção entre princípio e política de Uma Só China, da disputa interpretativa sobre a Resolução 2758, da ambiguidade estratégica e do escudo de silício.",
        topicos=["05-china"],
    ),
    dict(
        titulo="LOVATT, Hugh (ECFR) — 'O Conselho da Paz de Trump se torna global'",
        tipo="observacao",
        descricao="Caixa de conjuntura, verificada em 23/01/2026. Análise de think tank europeu com posição declarada. Usada como caso-clínica da ambiguidade institucional.",
        topicos=["00-metodo-e-matriz-de-cenarios", "04-estados-unidos"],
    ),
    dict(
        titulo="Perfil de cobrança da família rel-t2 (perfil-cobranca.json)",
        tipo="prova",
        descricao="Formato e peso inferidos de P1 REL 2024, gabarito da P2 REL 2024, SOPA REL T1 2024 (dois exemplares), correção da SOPA da P1 e critérios do trabalho de T2 de 2025. Nenhuma questão antiga foi copiada ou parafraseada. Incerteza declarada: não há prova ESCRITA de T2 no corpus.",
        topicos=["00-metodo-e-matriz-de-cenarios", "99-revisao-final"],
    ),
    dict(
        titulo="Resumo de Aspirante 'REL - T2.pdf' (nível 3 da hierarquia)",
        tipo="resumo",
        descricao="Recupera explicações orais ausentes dos slides: Grande Estratégia de Feaver, crítica de Alsina Jr., Milani e Nery, elementos do Poder Marítimo, leitura dos eixos da matriz de cenários, mecanismo do A2/AD e o alerta ZEE × ZEE. A seção EUROPA foi integralmente ignorada. Nunca prevalece sobre o slide.",
        topicos=["01-politica-externa-brasileira", "02-pnd-end-e-pesd",
                 "03-politica-maritima-naval-e-economia-azul", "04-estados-unidos", "05-china", "06-peb-aplicacao-e-integracao"],
    ),
    dict(
        titulo="Manifesto de fontes, conflitos e lacunas (fontes-manifesto.json)",
        tipo="observacao",
        descricao="Inventário deduplicado com o mapeamento arquivo → aula interna, os quatro conflitos entre fontes e as incertezas e lacunas declaradas, incluindo a ausência dos capítulos de Magnoli sobre EUA e China e a saída da Rússia do escopo.",
        topicos=["00-metodo-e-matriz-de-cenarios", "99-revisao-final"],
    ),
]
